"""
s5lib.py -- CHARGE LANE library, written from scratch for the S5-CHARGE lane of
"Where Atoms Come From".  python3.9 + numpy only (no scipy/sympy/mpmath used).

CONVENTIONS PUBLISHED HERE (custody: nothing enters a governing clause without a pointer)

  * A carrier is a finite oriented regular CW complex of dim <= 2, given by
        vertices  V  (list of names)
        edges     E  (list of (src_index, tgt_index))
        faces     F  (list of dict {edge_index: signed multiplicity})
    d1 is V x E with d1[v,e] = +1 if v = tgt(e), -1 if v = src(e), 0 else
       (a vertex that is both src and tgt of a loop edge gets 0; no such edge is used).
    d2 is E x F with d2[e,f] = the signed multiplicity of e in the boundary chain of f.
    d1 @ d2 = 0 is asserted on every carrier.

  * A designated loop is a signed edge chain (dict edge_index -> int).  Its VERTEX SUPPORT
    is { v : v is an endpoint of some edge appearing in the chain with nonzero coefficient }.
    (This is W-01's operator convention: (M_gamma s)(v) = W(gamma) s(v) for v ON gamma.)

  * CHARGE.  q_v is an integer attached to the FIBRE at v.  U(1) acts on L_v by z -> z^{q_v},
    so the holonomy W(gamma) acts on L_v as W(gamma)^{q_v}.  Hence the EXPONENT VECTOR
        E_v = q_v * (a_v, b_v)  in  Z^2 ,     a_v = [v on gamma_F], b_v = [v on gamma_C].
    Unit charge (q_v = 1 for all v) recovers S4's four corners of the unit square.

  * FORMATION FUNCTIONAL.  With u = conj(W_F) = e^{-i f}, v = W_C = e^{i c},
        Z_k = sum_v p_v u^{k m_v} v^{k n_v} = sum_v p_v exp( i k ( -m_v f + n_v c ) ).
    theta := (theta_u, theta_v) = (-f, c) is the coordinate used throughout.

  * lambda_A = log|Z_1|            (schedule A, uniform clock k_n = 1)
    lambda_B = lim (1/N) sum_{n<=N} log|Z_n|   (schedule B, canonical clock k_n = n)

  * RELATION LATTICE  L = { (m,n) in Z^2 : u^m v^n = 1 } = { (m,n) : -m f + n c = 0 mod 2pi }.
  * DIFFERENCE LATTICE Delta(S) = subgroup of Z^2 generated by { E_x - E_y : x,y in supp(p) }.
  * FORMATION GROUP    G = phi(Delta) = Delta / (Delta ^ L)   where phi(m,n) = u^m v^n.

  * SEEDS: every random draw in this lane uses numpy.random.default_rng(SEED) with SEED
    printed at the call site.  No global/implicit seeding anywhere.
"""

import numpy as np
from fractions import Fraction
from itertools import product

TWO_PI = 2.0 * np.pi

# --------------------------------------------------------------------------------------
# 1.  CW COMPLEX
# --------------------------------------------------------------------------------------

class CW:
    def __init__(self, name, nV, edges, faces):
        self.name = name
        self.nV = nV
        self.edges = list(edges)                 # [(s,t), ...]
        self.faces = [dict(f) for f in faces]    # [{e: mult}, ...]
        self.nE = len(self.edges)
        self.nF = len(self.faces)
        self.d1 = np.zeros((self.nV, self.nE), dtype=np.int64)
        for e, (s, t) in enumerate(self.edges):
            self.d1[s, e] -= 1
            self.d1[t, e] += 1
        self.d2 = np.zeros((self.nE, self.nF), dtype=np.int64)
        for f, ch in enumerate(self.faces):
            for e, m in ch.items():
                self.d2[e, f] += m
        assert np.all(self.d1 @ self.d2 == 0), f"{name}: d1 d2 != 0"

    # ranks over Q via numpy SVD-based matrix_rank on float copies (no torsion in this corpus)
    def betti(self):
        r1 = np.linalg.matrix_rank(self.d1.astype(float)) if self.nE else 0
        r2 = np.linalg.matrix_rank(self.d2.astype(float)) if self.nF else 0
        b0 = self.nV - r1
        b1 = (self.nE - r1) - r2
        b2 = self.nF - r2
        chi = self.nV - self.nE + self.nF
        assert chi == b0 - b1 + b2, f"{self.name}: chi mismatch"
        return dict(V=self.nV, E=self.nE, F=self.nF, chi=chi, b0=b0, b1=b1, b2=b2,
                    rank_d1=r1, rank_d2=r2,
                    gauge_params=self.nV - b0,
                    invariants=self.nE - (self.nV - b0),
                    curvature=r2, flat=b1)

    def chain_vec(self, chain):
        v = np.zeros(self.nE, dtype=np.int64)
        for e, m in chain.items():
            v[e] += m
        return v

    def is_cycle(self, chain):
        return np.all(self.d1 @ self.chain_vec(chain) == 0)

    def bounds(self, chain):
        """Is the chain in the image of d2 over Q?"""
        if self.nF == 0:
            return False
        b = self.chain_vec(chain).astype(float)
        A = self.d2.astype(float)
        r = np.linalg.matrix_rank(A)
        rA = np.linalg.matrix_rank(np.column_stack([A, b]))
        return r == rA

    def vertex_support(self, chain):
        vs = set()
        for e, m in chain.items():
            if m != 0:
                s, t = self.edges[e]
                vs.add(s); vs.add(t)
        return vs

    def classes(self, gF, gC):
        """returns a_v, b_v arrays in {0,1}"""
        sF = self.vertex_support(gF)
        sC = self.vertex_support(gC) if gC is not None else set()
        a = np.array([1 if v in sF else 0 for v in range(self.nV)], dtype=np.int64)
        b = np.array([1 if v in sC else 0 for v in range(self.nV)], dtype=np.int64)
        return a, b


# --------------------------------------------------------------------------------------
# 2.  EXPONENT DATA
# --------------------------------------------------------------------------------------

def exponents_from_charge(a, b, q):
    """E_v = q_v * (a_v, b_v)."""
    q = np.asarray(q, dtype=np.int64)
    return np.stack([q * a, q * b], axis=1)          # shape (V,2)

def support_exponents(E, p, tol=0.0):
    keep = np.asarray(p) > tol
    return np.asarray(E)[keep], np.asarray(p)[keep]

# ---- integer lattice utilities (exact, integer arithmetic only) ----

def _igcd(a, b):
    a, b = abs(int(a)), abs(int(b))
    while b:
        a, b = b, a % b
    return a

def hnf2(vectors):
    """Hermite normal form (row style) of the subgroup of Z^2 generated by `vectors`.
    Returns a tuple of 0,1 or 2 basis rows in a canonical form -> usable as a dict key."""
    rows = [tuple(int(x) for x in v) for v in vectors if any(int(x) != 0 for x in v)]
    if not rows:
        return ()
    # column-echelon by repeated gcd on first coordinate
    A = [list(r) for r in rows]
    # reduce first column
    while True:
        nz = [r for r in A if r[0] != 0]
        if len(nz) <= 1:
            break
        nz.sort(key=lambda r: abs(r[0]))
        piv = nz[0]
        changed = False
        for r in A:
            if r is piv or r[0] == 0:
                continue
            k = r[0] // piv[0]
            r[0] -= k * piv[0]
            r[1] -= k * piv[1]
            changed = True
        if not changed:
            break
    piv = None
    for r in A:
        if r[0] != 0:
            piv = r
            break
    rest = [r for r in A if r[0] == 0 and r[1] != 0]
    g = 0
    for r in rest:
        g = _igcd(g, r[1])
    basis = []
    if piv is not None:
        if piv[0] < 0:
            piv = [-piv[0], -piv[1]]
        if g:
            piv = [piv[0], piv[1] % g]
        basis.append(tuple(piv))
    if g:
        basis.append((0, g))
    return tuple(basis)

def lattice_rank(vectors):
    return len(hnf2(vectors))

def lattice_index(vectors):
    """|Z^2 : Lambda| if rank 2, else None."""
    B = hnf2(vectors)
    if len(B) != 2:
        return None
    return abs(B[0][0] * B[1][1] - B[0][1] * B[1][0])

def difference_lattice(Esup):
    """Delta(S), as an HNF basis tuple."""
    E = np.asarray(Esup)
    if len(E) == 0:
        return ()
    diffs = [E[i] - E[0] for i in range(1, len(E))]
    return hnf2(diffs)

def unimodular_completion(d):
    """Given a primitive (m,n), return M in GL2(Z) with M @ d = (1,0)^T."""
    m, n = int(d[0]), int(d[1])
    g = _igcd(m, n)
    assert g == 1, "not primitive"
    # extended euclid: x*m + y*n = 1
    old_r, r = m, n
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r != 0:
        qq = old_r // r
        old_r, r = r, old_r - qq * r
        old_s, s = s, old_s - qq * s
        old_t, t = t, old_t - qq * t
    x, y = old_s, old_t          # x*m + y*n = gcd = +-1
    if old_r < 0:
        x, y, old_r = -x, -y, -old_r
    M = np.array([[x, y], [-n, m]], dtype=np.int64)
    assert abs(int(round(np.linalg.det(M.astype(float))))) == 1
    assert tuple(M @ np.array([m, n])) == (1, 0)
    return M

def primitive(d):
    g = _igcd(d[0], d[1])
    return (d[0] // g, d[1] // g), g


# --------------------------------------------------------------------------------------
# 3.  THE FORMATION FUNCTIONAL
# --------------------------------------------------------------------------------------

def Z_of_k(k, E, p, f, c):
    """closed form.  k may be an array."""
    E = np.asarray(E); p = np.asarray(p, dtype=float)
    th = np.array([-f, c], dtype=float)
    ph = E @ th                                    # (V,)
    k = np.atleast_1d(np.asarray(k, dtype=float))
    return (np.exp(1j * np.outer(k, ph)) * p).sum(axis=1)

def Z_of_k_matrix(k, a, b, q, p_or_s, f, c):
    """direct matrix action on C^V, no closed form used.
    p_or_s : a complex section s (arbitrary phases) -- p_v = |s_v|^2, must be normalised."""
    s = np.asarray(p_or_s, dtype=complex)
    WF = np.exp(1j * f); WC = np.exp(1j * c)
    q = np.asarray(q, dtype=np.int64)
    MF = np.diag(WF ** (q * np.asarray(a)))
    MC = np.diag(WC ** (q * np.asarray(b)))
    x = np.linalg.matrix_power(MF, int(k)) @ s
    y = np.linalg.matrix_power(MC, int(k)) @ s
    return np.vdot(x, y)

def lambda_A(E, p, f, c):
    return float(np.log(np.abs(Z_of_k(1, E, p, f, c))[0]))

def lambda_B_direct(E, p, f, c, N=2_000_000, chunk=200_000):
    """(1/N) sum_{n=1}^N log|Z_n|.  Phases accumulated by exact integer n times float theta."""
    E = np.asarray(E); p = np.asarray(p, dtype=float)
    th = np.array([-f, c], dtype=float)
    ph = E @ th
    tot = 0.0
    n0 = 1
    while n0 <= N:
        n1 = min(N, n0 + chunk - 1)
        ns = np.arange(n0, n1 + 1, dtype=np.float64)
        Zs = (np.exp(1j * np.outer(ns, ph)) * p).sum(axis=1)
        tot += np.log(np.abs(Zs)).sum()
        n0 = n1 + 1
    return tot / N


# --------------------------------------------------------------------------------------
# 4.  MAHLER MEASURES  (all from scratch; Jensen via numpy.roots)
# --------------------------------------------------------------------------------------

def mahler1(coef_by_exp):
    """m(P) for P(z) = sum coef z^exp, exponents integers (may be negative:
    multiplying by z^k does not change m).  Exact up to numpy.roots."""
    items = [(int(e), complex(cv)) for e, cv in coef_by_exp.items() if abs(cv) > 0]
    if not items:
        return -np.inf
    emin = min(e for e, _ in items)
    emax = max(e for e, _ in items)
    deg = emax - emin
    co = np.zeros(deg + 1, dtype=complex)
    for e, cv in items:
        co[e - emin] += cv
    co = co[::-1]                                     # numpy.roots wants highest first
    while len(co) > 1 and abs(co[0]) == 0:
        co = co[1:]
    if len(co) == 1:
        return float(np.log(abs(co[0])))
    r = np.roots(co)
    return float(np.log(abs(co[0])) + np.sum(np.log(np.maximum(1.0, np.abs(r)))))

def mahler2(coef_by_exp2, Nx=4096):
    """m(P) for P(x,y) = sum coef x^m y^n.  EXACT (Jensen) in y, midpoint quadrature in x
    with Nx nodes.  Nx is published at every call site."""
    items = [((int(m), int(n)), complex(cv)) for (m, n), cv in coef_by_exp2.items() if abs(cv) > 0]
    ts = (np.arange(Nx) + 0.5) / Nx
    xs = np.exp(2j * np.pi * ts)
    tot = 0.0
    ny = sorted(set(n for (m, n), _ in items))
    for x in xs:
        d = {}
        for (m, n), cv in items:
            d[n] = d.get(n, 0j) + cv * (x ** m)
        tot += mahler1(d)
    return tot / Nx

def mahler_generic(Esup, psup, Nx=4096):
    """m of the weight polynomial, i.e. lambda_B at a GENERIC (rank L = 0) connection.
    Reduces exactly to a 1-variable Mahler measure when rank Delta <= 1."""
    E = np.asarray(Esup); p = np.asarray(psup, dtype=float)
    E = E - E[0]                                       # translation: |Z| unchanged
    B = difference_lattice(E)
    if len(B) == 0:
        return 0.0
    if len(B) == 1:
        d, _ = primitive(B[0])
        M = unimodular_completion(d)
        F = (M @ E.T).T                                # second coordinate must vanish
        assert np.all(F[:, 1] == 0), F
        dd = {}
        for i in range(len(p)):
            dd[int(F[i, 0])] = dd.get(int(F[i, 0]), 0.0) + p[i]
        return mahler1(dd)
    dd = {}
    for i in range(len(p)):
        key = (int(E[i, 0]), int(E[i, 1]))
        dd[key] = dd.get(key, 0.0) + p[i]
    return mahler2(dd, Nx=Nx)

def lambda_B_exact(Esup, psup, L_basis, Nx=4096):
    """lambda_B = int_{L^perp} log|Z| dHaar, for an arbitrary exponent configuration and an
    arbitrary relation lattice L (given by an HNF basis tuple, () for rank 0).
      rank L = 0 : full torus  -> mahler_generic
      rank L = 1 : L = e*<d>, d primitive -> mean of e one-variable Mahler measures
      rank L = 2 : finite group -> exact finite average
    """
    E = np.asarray(Esup) - np.asarray(Esup)[0]
    p = np.asarray(psup, dtype=float)
    if len(L_basis) == 0:
        return mahler_generic(E, p, Nx=Nx)
    if len(L_basis) == 1:
        d, e = primitive(L_basis[0])
        M = unimodular_completion(d)                  # M d = (1,0)
        # characters of Z^2 restricted to L^perp:  L = e*Z*d.  In the M-basis, exponent
        # vector alpha = (M^{-T}) ... we instead push the EXPONENTS through (M^{-1})^T = ?
        # Cleanest: use the pairing <E, x>.  Substitute x = M^T y  =>  <E, M^T y> = <M E, y>.
        # M^T is a measure preserving automorphism of T^2 and maps the annihilator of e*<d>
        # to { y : e*y_1 = 0 } = mu_e x U(1).
        Fv = (M @ E.T).T
        tot = 0.0
        for j in range(e):
            zeta = np.exp(2j * np.pi * j / e)
            dd = {}
            for i in range(len(p)):
                key = int(Fv[i, 1])
                dd[key] = dd.get(key, 0j) + p[i] * zeta ** int(Fv[i, 0])
            tot += mahler1(dd)
        return tot / e
    # rank 2 : the quotient Z^2/L is finite; H = its dual, a finite group.  Enumerate.
    B = np.array(L_basis, dtype=np.int64)
    idx = abs(int(B[0, 0] * B[1, 1] - B[0, 1] * B[1, 0]))
    # enumerate H = { (s,t) in (1/idx)Z^2 mod 1 : <(m,n),(s,t)> in Z for all (m,n) in L }
    pts = []
    D = idx
    for s in range(D):
        for t in range(D):
            ok = all((B[r, 0] * s + B[r, 1] * t) % D == 0 for r in range(2))
            if ok:
                pts.append((s / D, t / D))
    assert len(pts) == D, (len(pts), D)
    tot = 0.0
    for (s, t) in pts:
        ph = 2 * np.pi * (E[:, 0] * s + E[:, 1] * t)
        tot += float(np.log(abs((p * np.exp(1j * ph)).sum())))
    return tot / len(pts)

def relation_lattice(f, c, max_den=None, exact_pair=None):
    """L for a connection.  If exact_pair = (Fraction pf, Fraction pc) is given with
    f = 2 pi pf, c = 2 pi pc, L is computed EXACTLY in integer arithmetic.
    Otherwise returns () (treated as generic)."""
    if exact_pair is None:
        return ()
    pf, pc = exact_pair
    # L = { (m,n) : -m pf + n pc  in  Z }
    den = np.lcm(pf.denominator, pc.denominator)
    A = int(-pf * den), int(pc * den)                 # -m A0 ... : condition m*A0 + n*A1 = 0 mod den
    sols = []
    # the set { (m,n) : m*A0 + n*A1 = 0 mod den } is a finite-index sublattice of Z^2
    for m in range(den):
        for n in range(den):
            if (m * A[0] + n * A[1]) % den == 0:
                sols.append((m, n))
    sols += [(den, 0), (0, den)]
    return hnf2(sols)
