#!/usr/bin/env python3
"""
LANE O-4 -- "admissible" in clause (iv).

ABSTRACT PART.  No lattice, no gauge group, no topology.  Everything here is stated
in terms of (H, {L_k}, R) only -- the record level's own data.

CANDIDATE DEFINITIONS TESTED
  DEF-A  (proposed)  U is admissible for (H,{L_k})  iff  U is unitary and [U,H] = 0.
  DEF-B  (the framework's own parenthetical, CORE_FRAMEWORK O4 row:
          "generated by the theory's own operators")
          U admissible iff U lies in the *-algebra generated by {H, L_k}.
  DEF-C  (the trivial reading)   U admissible iff U is unitary.
  DEF-E  (the tempting one)      U admissible iff U is not supported in a small region.
          -- rejected on criterion (3) by inspection, no numerics needed.

WHAT IS PROVED / MEASURED HERE
  1. BALANCE LEMMA.  Under DEF-A, clause (iv) holds  <=>  Tr(P_E R) = 0 for every
     eigenprojector P_E of H.  Necessity is a two-line proof; sufficiency is a
     construction.  Both are checked numerically with random data.
  2. DEF-B makes clause (iv) VACUOUS -- no record can ever satisfy it.  (Proof is
     one line from clause (ii); confirmed numerically on random words.)
  3. DEF-C is strictly weaker than DEF-A: an explicit 6-dimensional witness passing
     (i),(ii),(iii) and DEF-C's (iv) but failing DEF-A's (iv).

SELF-CHECKS: every section prints PASS/FAIL against an independently known answer.
POSITIVE CONTROLS: every reported zero is accompanied by a construction that would
have produced a nonzero if one existed.
"""

import numpy as np

np.random.seed(20260818)
np.set_printoptions(precision=4, suppress=True)

FAILURES = []


def check(name, condition, detail=""):
    tag = "PASS" if condition else "FAIL"
    if not condition:
        FAILURES.append(name)
    print(f"   [{tag}] {name}   {detail}")


def hr(title):
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def rand_unitary(n):
    z = (np.random.randn(n, n) + 1j * np.random.randn(n, n)) / np.sqrt(2)
    q, r = np.linalg.qr(z)
    return q * (np.diag(r) / np.abs(np.diag(r)))


def comm(A, B):
    return A @ B - B @ A


def nrm(A):
    return np.linalg.norm(A)


# ----------------------------------------------------------------------------
hr("SECTION 0 -- SANITY OF THE MACHINERY (known answers)")

X = np.array([[0, 1], [1, 0]], dtype=complex)
Z = np.array([[1, 0], [0, -1]], dtype=complex)
check("XZ anticommutes", nrm(X @ Z + Z @ X) < 1e-12, f"||{{X,Z}}|| = {nrm(X@Z+Z@X):.2e}")
check("X flips Z", nrm(X.conj().T @ Z @ X + Z) < 1e-12,
      f"||X^dag Z X + Z|| = {nrm(X.conj().T@Z@X+Z):.2e}")
check("Z does NOT flip Z (control)", nrm(Z.conj().T @ Z @ Z + Z) > 1.0,
      f"||Z^dag Z Z + Z|| = {nrm(Z.conj().T@Z@Z+Z):.3f}")


# ----------------------------------------------------------------------------
hr("SECTION 1 -- THE BALANCE LEMMA  (DEF-A: admissible == [U,H] = 0)")

print("""
LEMMA (necessity).  Let [H,R]=0, R=R^dag, R^2=I.  Let U be unitary with [U,H]=0 and
U^dag R U = -R.  Since [U,H]=0, U commutes with every spectral projector P_E of H, so
   Tr(P_E R) = Tr(P_E U^dag R U) = Tr(U P_E U^dag R) = Tr(P_E R),
while U^dag R U = -R gives Tr(P_E U^dag R U) = -Tr(P_E R).  Hence Tr(P_E R) = 0.

LEMMA (sufficiency).  If Tr(P_E R) = 0 for every E, then inside each eigenspace of H
the +1 and -1 eigenspaces of R|_E have equal dimension, so a unitary swapping them
exists inside that block; the direct sum U over blocks satisfies [U,H]=0 and
U^dag R U = -R.

=> Under DEF-A, clause (iv) is EXACTLY the statement: at every energy, the record's
   two values are equally available.  ("The bit costs no energy.")
""")


def build_HR(mults, energies, plus_counts, basis_rotate=True):
    """H with given eigenvalue multiplicities; R block-diagonal, plus_counts[i] of
    its eigenvalues equal to +1 inside block i.  Optionally conjugate everything by a
    random unitary so no result is an artefact of the eigenbasis."""
    n = sum(mults)
    Hd = np.zeros(n)
    Rd = np.zeros(n)
    o = 0
    for m, e, p in zip(mults, energies, plus_counts):
        Hd[o:o + m] = e
        Rd[o:o + p] = 1.0
        Rd[o + p:o + m] = -1.0
        o += m
    H = np.diag(Hd).astype(complex)
    R = np.diag(Rd).astype(complex)
    if basis_rotate:
        V = rand_unitary(n)
        # rotate only WITHIN blocks so that [H,R]=0 survives and R is not diagonal
        W = np.zeros((n, n), dtype=complex)
        o = 0
        for m in mults:
            W[o:o + m, o:o + m] = rand_unitary(m)
            o += m
        H = W.conj().T @ H @ W
        R = W.conj().T @ R @ W
        H = V.conj().T @ H @ V
        R = V.conj().T @ R @ V
    return H, R


def spectral_projectors(H, tol=1e-8):
    w, v = np.linalg.eigh(H)
    projs = []
    i = 0
    while i < len(w):
        j = i
        while j + 1 < len(w) and abs(w[j + 1] - w[i]) < tol:
            j += 1
        V = v[:, i:j + 1]
        projs.append((w[i], V @ V.conj().T))
        i = j + 1
    return projs


def build_admissible_flipper(H, R, tol=1e-8):
    """Construct U with [U,H]=0 and U^dag R U = -R, or return None if the balance
    obstruction forbids it."""
    n = H.shape[0]
    U = np.zeros((n, n), dtype=complex)
    for _, P in spectral_projectors(H, tol):
        # eigenbasis of the block
        wP, vP = np.linalg.eigh(P)
        cols = vP[:, wP > 0.5]                      # orthonormal basis of the block
        Rb = cols.conj().T @ R @ cols               # R restricted to the block
        wR, vR = np.linalg.eigh(Rb)
        plus = vR[:, wR > 0]
        minus = vR[:, wR < 0]
        if plus.shape[1] != minus.shape[1]:
            return None
        Ub = plus @ minus.conj().T + minus @ plus.conj().T   # swaps +1 <-> -1
        U += cols @ Ub @ cols.conj().T
    return U


print("--- 1a. BALANCED cases: the construction must succeed ---")
cases = [
    ([2], [0.0], [1]),
    ([4, 2], [0.0, 1.7], [2, 1]),
    ([6, 4, 2], [-1.0, 0.3, 2.5], [3, 2, 1]),
    ([8], [0.0], [4]),
]
for mults, en, pc in cases:
    H, R = build_HR(mults, en, pc)
    U = build_admissible_flipper(H, R)
    ok = U is not None
    if ok:
        e1 = nrm(comm(U, H))
        e2 = nrm(U.conj().T @ R @ U + R)
        e3 = nrm(U.conj().T @ U - np.eye(H.shape[0]))
        check(f"mults={mults} balanced: admissible flipper built",
              ok and e1 < 1e-9 and e2 < 1e-9 and e3 < 1e-9,
              f"||[U,H]||={e1:.2e}  ||U^dag R U + R||={e2:.2e}  ||U^dag U - I||={e3:.2e}")
    else:
        check(f"mults={mults} balanced: admissible flipper built", False, "construction returned None")

print("\n--- 1b. UNBALANCED cases: clause (iv) must FAIL under DEF-A ---")
print("     positive control alongside: the SAME R is flippable by a general unitary")
print("     (DEF-C), so the zero below is not a zero of the search machinery.")
unbal = [
    ([3], [0.0], [2]),                 # block trace 1
    ([4, 4], [0.0, 1.0], [3, 1]),      # traces +2 and -2, total trace 0
    ([6, 2], [0.0, 1.0], [4, 0]),      # traces +2 and -2, total trace 0
]
for mults, en, pc in unbal:
    H, R = build_HR(mults, en, pc)
    n = H.shape[0]
    traces = [(e, np.real(np.trace(P @ R))) for e, P in spectral_projectors(H)]
    obstruction = max(abs(t) for _, t in traces)
    # rigorous lower bound: ||U^dag R U + R||_F >= 2|Tr(P_E R)| / sqrt(dim E)
    dims = {round(e, 6): int(round(np.real(np.trace(P)))) for e, P in spectral_projectors(H)}
    bound = max(2 * abs(t) / np.sqrt(dims[round(e, 6)]) for e, t in traces)
    # numerical search over admissible unitaries (block-diagonal in H's eigenspaces)
    best = np.inf
    projs = spectral_projectors(H)
    blocks = []
    for _, P in projs:
        wP, vP = np.linalg.eigh(P)
        blocks.append(vP[:, wP > 0.5])
    for _ in range(4000):
        U = np.zeros((n, n), dtype=complex)
        for cols in blocks:
            U += cols @ rand_unitary(cols.shape[1]) @ cols.conj().T
        best = min(best, nrm(U.conj().T @ R @ U + R))
    Uc = build_admissible_flipper(H, R)
    # POSITIVE CONTROL: a general (DEF-C) unitary flipping R, exists iff Tr R = 0
    wR, vR = np.linalg.eigh(R)
    plus, minus = vR[:, wR > 0], vR[:, wR < 0]
    globally_balanced = (plus.shape[1] == minus.shape[1])
    check(f"mults={mults} unbalanced: construction refuses", Uc is None,
          f"max_E |Tr(P_E R)| = {obstruction:.3f}  (total Tr R = {np.real(np.trace(R)):+.1f})")
    check(f"mults={mults} unbalanced: 4000-sample search never reaches -R",
          best > 0.5 * bound,
          f"best ||U^dag R U + R|| = {best:.4f}   proved lower bound = {bound:.4f}")
    if globally_balanced:
        Ug = plus @ minus.conj().T + minus @ plus.conj().T
        ctrl = nrm(Ug.conj().T @ R @ Ug + R)
        check(f"mults={mults} POSITIVE CONTROL: a DEF-C unitary DOES flip it",
              ctrl < 1e-9, f"||U^dag R U + R|| = {ctrl:.2e}  <-- nonzero WOULD have registered")
    else:
        print(f"   [N/A ] mults={mults} POSITIVE CONTROL not applicable: Tr R = "
              f"{np.real(np.trace(R)):+.1f} != 0, so NO unitary at all flips R under any "
              f"definition.  This case tests the global obstruction only.")

print("\n--- 1c. necessity direction, checked directly on the balanced cases ---")
for mults, en, pc in cases:
    H, R = build_HR(mults, en, pc)
    U = build_admissible_flipper(H, R)
    traces = [abs(np.real(np.trace(P @ R))) for _, P in spectral_projectors(H)]
    check(f"mults={mults}: [U,H]=0 flipper exists => all Tr(P_E R) = 0",
          max(traces) < 1e-9, f"max_E |Tr(P_E R)| = {max(traces):.2e}")


# ----------------------------------------------------------------------------
hr("SECTION 2 -- DEF-B IS VACUOUS  ('generated by the theory's own operators')")

print("""
CLAIM.  If "admissible" means "lies in the *-algebra generated by {H, L_k}", then NO
record can satisfy clause (iv), for any (H,{L_k}) whatever.

PROOF (one line, and it is the framework's own P-2).  Clause (ii) says [H,R]=0 and
[L_k,R]=0.  The set of operators commuting with R is an algebra closed under sums,
products and adjoints, and it contains every generator; hence it contains the whole
generated algebra.  So every DEF-B-admissible U has [U,R]=0, and U^dag R U = +R != -R
(R != 0).  Clause (iv) is unsatisfiable.  QED

=> DEF-B is REJECTED: it fails criterion (1) outright.  It does not merely restrict
   clause (iv); it empties it, and with it the whole definition of "record".
""")

for trial in range(3):
    n = 8
    V = rand_unitary(n)
    Rd = np.diag([1, 1, 1, 1, -1, -1, -1, -1]).astype(complex)
    R = V.conj().T @ Rd @ V
    # build H and L_k commuting with R: block-diagonal in R's eigenbasis
    def block_op(hermitian=True):
        A = np.zeros((n, n), dtype=complex)
        for sl in (slice(0, 4), slice(4, 8)):
            M = np.random.randn(4, 4) + 1j * np.random.randn(4, 4)
            if hermitian:
                M = M + M.conj().T
            A[sl, sl] = M
        return V.conj().T @ A @ V
    H = block_op(True)
    Ls = [block_op(False) for _ in range(3)]
    check(f"trial {trial}: clause (ii) holds by construction",
          max(nrm(comm(H, R)), max(nrm(comm(L, R)) for L in Ls)) < 1e-9,
          f"max commutator = {max(nrm(comm(H,R)), max(nrm(comm(L,R)) for L in Ls)):.2e}")
    gens = [H] + Ls + [L.conj().T for L in Ls]
    worst = 0.0
    for _ in range(400):
        W = np.eye(n, dtype=complex)
        for _ in range(np.random.randint(1, 7)):
            W = W @ gens[np.random.randint(len(gens))]
        worst = max(worst, nrm(comm(W, R)) / max(nrm(W), 1e-30))
    check(f"trial {trial}: 400 random words of the algebra all commute with R",
          worst < 1e-9, f"max relative ||[W,R]|| = {worst:.2e}")
    # POSITIVE CONTROL: add ONE non-generator that anticommutes with R
    wR, vR = np.linalg.eigh(R)
    plus, minus = vR[:, wR > 0], vR[:, wR < 0]
    F = plus @ minus.conj().T + minus @ plus.conj().T
    check(f"trial {trial}: POSITIVE CONTROL, an outside operator does NOT commute",
          nrm(comm(F, R)) > 1.0,
          f"||[F,R]|| = {nrm(comm(F,R)):.3f}  <-- the test can see a flipper")


# ----------------------------------------------------------------------------
hr("SECTION 3 -- DEF-C IS STRICTLY WEAKER THAN DEF-A  (the 6-dimensional witness)")

print("""
WITNESS.  H = diag(0,0,0, 1,1,1).  R = diag(+1,+1,-1 | -1,-1,+1).
  (i)   R = R^dag, R^2 = I.
  (ii)  [H,R] = 0; jumps taken block-diagonal so [L_k,R] = 0.
  (iii) R is NOT constant on the E=0 eigenspace  ->  non-trivial, and R is not f(H).
  (iv)  under DEF-C (any unitary): Tr R = 0, so a flipper exists.
        under DEF-A ([U,H]=0):    Tr(P_0 R) = +1 != 0, so NO flipper exists.
""")

Hw = np.diag([0., 0., 0., 1., 1., 1.]).astype(complex)
Rw = np.diag([1., 1., -1., -1., -1., 1.]).astype(complex)
check("witness (i) bit", nrm(Rw - Rw.conj().T) < 1e-12 and nrm(Rw @ Rw - np.eye(6)) < 1e-12)
check("witness (ii) [H,R]=0", nrm(comm(Hw, Rw)) < 1e-12, f"{nrm(comm(Hw,Rw)):.2e}")
P0 = np.diag([1., 1., 1., 0., 0., 0.]).astype(complex)
P1 = np.eye(6) - P0
r0 = P0 @ Rw @ P0
check("witness (iii) R non-constant on E=0",
      nrm(r0 - (np.trace(r0) / 3) * P0) > 1e-6,
      f"deviation from scalar on E=0 : {nrm(r0 - (np.trace(r0)/3)*P0):.4f}")
check("witness: R is not a function of H",
      nrm(r0 - (np.trace(r0) / 3) * P0) > 1e-6)
wR, vR = np.linalg.eigh(Rw)
plus, minus = vR[:, wR > 0], vR[:, wR < 0]
Ug = plus @ minus.conj().T + minus @ plus.conj().T
check("witness (iv) under DEF-C: a general unitary flips R",
      nrm(Ug.conj().T @ Rw @ Ug + Rw) < 1e-12 and nrm(Ug.conj().T @ Ug - np.eye(6)) < 1e-12,
      f"||U^dag R U + R|| = {nrm(Ug.conj().T@Rw@Ug+Rw):.2e}")
check("witness: that DEF-C unitary does NOT commute with H (it moves energy)",
      nrm(comm(Ug, Hw)) > 1.0, f"||[U,H]|| = {nrm(comm(Ug,Hw)):.3f}")
print(f"     Tr(P_0 R) = {np.real(np.trace(P0@Rw)):+.1f}   Tr(P_1 R) = {np.real(np.trace(P1@Rw)):+.1f}"
      f"   Tr R = {np.real(np.trace(Rw)):+.1f}")
check("witness (iv) under DEF-A: FORBIDDEN by the balance lemma",
      abs(np.real(np.trace(P0 @ Rw))) > 0.5,
      f"|Tr(P_0 R)| = {abs(np.real(np.trace(P0@Rw))):.1f} != 0")
best = np.inf
for _ in range(20000):
    U = np.zeros((6, 6), dtype=complex)
    U[:3, :3] = rand_unitary(3)
    U[3:, 3:] = rand_unitary(3)
    best = min(best, nrm(U.conj().T @ Rw @ U + Rw))
check("witness: 20000-sample search over admissible U never reaches -R",
      best > 1.0, f"best ||U^dag R U + R|| = {best:.4f}   (proved bound 2|Tr P_0 R|/sqrt(3) = {2/np.sqrt(3):.4f})")

print("""
READING.  DEF-C would certify this R as a record.  Its "write" operation necessarily
carries the system between energy shells: the bit is not available at fixed energy,
which is precisely what clause (iii) was written to demand of the record itself.
DEF-A refuses it.  The two definitions are therefore NOT equivalent, and clause (iv)
under DEF-A carries content that DEF-C throws away.
""")

# ----------------------------------------------------------------------------
hr("SECTION 4 -- DOES DEF-A MAKE CLAUSE (iv) TRIVIAL?  (criterion 2, abstract half)")

print("""
Under DEF-A, clause (iv) is equivalent to the per-eigenspace balance condition.  If
that condition were implied by clauses (i)-(iii) it would be trivial.  It is not:
the Section-3 witness satisfies (i),(ii),(iii) and fails (iv).  So (iv) is an
INDEPENDENT clause under DEF-A.
""")
check("(i)-(iii) do NOT imply (iv) under DEF-A", abs(np.real(np.trace(P0 @ Rw))) > 0.5,
      "Section-3 witness passes (i),(ii),(iii) and fails (iv)")

frac_num = 0
TRIALS = 2000
for _ in range(TRIALS):
    U = rand_unitary(6)
    if nrm(comm(U, Hw)) < 1e-6:
        frac_num += 1
check("a random unitary is almost never admissible under DEF-A", frac_num == 0,
      f"{frac_num}/{TRIALS} random unitaries commute with H  (DEF-C would give {TRIALS}/{TRIALS})")

# ----------------------------------------------------------------------------
hr("SUMMARY -- ABSTRACT PART")
if FAILURES:
    print(f"*** {len(FAILURES)} SELF-CHECK FAILURES: {FAILURES}")
else:
    print("ALL SELF-CHECKS PASSED.")
print("""
  DEF-B  REJECTED -- makes clause (iv) unsatisfiable for every record (criterion 1).
  DEF-C  REJECTED -- admits a 6-dim object whose write moves it between energy shells;
                     and it is the trivial reading (criterion 2).
  DEF-A  SURVIVES the abstract tests.  Clause (iv) becomes:
         "at every energy, the record's two values are equally available."
""")
