"""O-5 COMMON.  The carriers.  Everything downstream imports from here.

TOPOLOGICAL CARRIER -- the toric code the program uses: 2x2 periodic square lattice, Z2, one qubit
per edge, 8 edges, dim 2^8 = 256.  H = -sum_v A_v - sum_p B_p.

SYMMETRY CARRIER -- the SAME 256-dimensional Hilbert space, a different H:
    H_sym = -sum_{l=1..7} X_l .
Qubit 0 does not appear in H_sym, so every level is exactly 2-fold degenerate.  That degeneracy is
supplied by a symmetry (the group generated by X_0, Z_0 acts trivially on H_sym) and it is
LOCALLY DISTINGUISHABLE -- which is what makes it split at FIRST order.  Same Hilbert space, same
perturbation operator, same norms: the only difference between the two runs is H.

This is deliberately the honest contrast the program measured in W-60/W-61 -- symmetry degeneracy
dies linearly, topological degeneracy dies at order d -- rebuilt so both sides live in one space.
"""
import numpy as np

NQ = 8
DIM = 1 << NQ

# ---- edge indexing on the 2x2 torus -------------------------------------------------------------
# h(i,j) = horizontal edge from vertex (i,j) to (i+1,j)   -> index      (j%2)*2 + (i%2)   in 0..3
# v(i,j) = vertical   edge from vertex (i,j) to (i,j+1)   -> index  4 + (j%2)*2 + (i%2)   in 4..7
def h(i, j): return (j % 2) * 2 + (i % 2)
def v(i, j): return 4 + (j % 2) * 2 + (i % 2)

STARS = [[h(i, j), h(i - 1, j), v(i, j), v(i, j - 1)] for j in range(2) for i in range(2)]
PLAQS = [[h(i, j), v(i + 1, j), h(i, j + 1), v(i, j)] for j in range(2) for i in range(2)]

# logical operators, computed by hand and VERIFIED in o5_a_carrier.py
Z_A_SUP = [h(0, 0), h(1, 0)]          # dual cycle  -> Z-type logical    = THE RECORD
X_A_SUP = [h(0, 0), h(0, 1)]          # direct cycle-> X-type logical    = THE WRITER (anticommutes)
Z_B_SUP = [v(0, 0), v(0, 1)]
X_B_SUP = [v(0, 0), v(1, 0)]

_BITS = np.arange(DIM)


def mask_of(S):
    m = 0
    for k in S:
        m |= (1 << k)
    return m


def Zop(S):
    """product of Pauli Z over the qubit set S  (diagonal)"""
    m = mask_of(S)
    par = np.array([bin(s & m).count('1') & 1 for s in range(DIM)])
    return np.diag(np.where(par == 0, 1.0, -1.0)).astype(complex)


def Xop(S):
    """product of Pauli X over the qubit set S  (permutation)"""
    m = mask_of(S)
    M = np.zeros((DIM, DIM), complex)
    M[_BITS ^ m, _BITS] = 1.0
    return M


def Yop(k):
    return 1j * Xop([k]) @ Zop([k])


def toric_H():
    H = -sum(Xop(s) for s in STARS) - sum(Zop(p) for p in PLAQS)
    return (H + H.conj().T) / 2


def sym_H():
    H = -sum(Xop([l]) for l in range(1, NQ))
    return (H + H.conj().T) / 2


def local_perturbation(seed, nq=NQ):
    """a random LOCAL perturbation: one-qubit Paulis only, unit operator norm.
    Operators on distinct qubits have ||sum|| = sum||.||, so the normalisation is exact."""
    rng = np.random.default_rng(seed)
    V = np.zeros((DIM, DIM), complex)
    for l in range(nq):
        c = rng.normal(size=3)
        V = V + c[0] * Xop([l]) + c[1] * Yop(l) + c[2] * Zop([l])
    V = (V + V.conj().T) / 2
    return V / np.linalg.norm(V, 2)


def cluster(H, g, ):
    """lowest g eigenvalues/vectors, the cluster width, and the gap to the rest"""
    e, U = np.linalg.eigh(H)
    width = e[g - 1] - e[0]
    gap = e[g] - e[g - 1] if g < len(e) else float('nan')
    return e, U, width, gap


def dressed_record(H, R0, g):
    """THE DRESSED RECORD.  R0 is the exact record of the unperturbed H.  On the lowest g-level
    cluster of the perturbed H, take M = P R0 P in the cluster basis and set R_c = sign(M).
    Returns (R_c, cluster Hamiltonian Hc, min|eig M|, ||[Hc,R_c]||).
    The full-space extension of R_c can be chosen to be a function of H outside the cluster, which
    commutes with H exactly, so ||[Hc,R_c]|| IS the achievable tolerance for this record."""
    e, U = np.linalg.eigh(H)
    Uc = U[:, :g]
    M = Uc.conj().T @ R0 @ Uc
    M = (M + M.conj().T) / 2
    w, Q = np.linalg.eigh(M)
    Rc = Q @ np.diag(np.sign(w)) @ Q.conj().T
    Hc = np.diag(e[:g]).astype(complex)
    tol = np.linalg.norm(Hc @ Rc - Rc @ Hc, 2)
    return Rc, Hc, float(np.min(np.abs(w))), float(tol)
