"""LEG A -- rebuild COR-F's edge tick T from S3_THE_CROSSING_AUDIT_V001.md:160-215 and
   check every structural claim about it.  Blind: no registrar code read."""
import numpy as np, sys
sys.path.insert(0, '.')
from wcore import *

np.set_printoptions(precision=6, suppress=False, linewidth=140)
print("LEG A -- THE TWO CONVENTIONS AS OPERATORS.  double precision (float64) throughout.\n")

# ---- A.0  reproduce COR-F's OWN sealed exhibit, at its own numbers -----------------
print("A.0  COR-F's exhibit reproduced at its own parameters a4,a5,a6 = 0.7, 1.3, -0.4")
car = Carrier('K1(COR-F)', 5, [0,1,2], [0,3,4], [0.4,0.5,0.6], [0.7,1.3,-0.4])
T = car.T('C')
print("   || T*T - I ||            = %.2e        (COR-F prints 0.00e+00)" % np.linalg.norm(T.conj().T@T - np.eye(5)))
print("   T diagonal?                %s" % (np.linalg.norm(T - np.diag(np.diag(T))) < 1e-14))
T3 = np.linalg.matrix_power(T, 3)
WC = np.exp(1j*(0.7+1.3-0.4))
print("   T^3 = diag             = %s" % np.array2string(np.diag(T3), precision=6))
print("   W_C                    = %.6f %+.6fj      (COR-F: -0.029200 +0.999574j)" % (WC.real, WC.imag))
print("   ||T^3 - diag(WC,1,1,WC,WC)|| = %.2e" % np.linalg.norm(T3 - np.diag([WC,1,1,WC,WC])))
rho = np.diag([0.40,0.15,0.15,0.15,0.15]).astype(complex)
print("   diag( T rho T* )       = %s   (COR-F: [0.15 0.15 0.15 0.40 0.15])" % np.array2string(np.real(np.diag(T@rho@T.conj().T)), precision=2))
print("   diag( rho )            = %s\n" % np.array2string(np.real(np.diag(rho)), precision=2))

# ---- A.1  T is unitary, T^L = M_gamma, over many random connections ---------------
print("A.1  T unitary and T^L = M_gamma, 2000 random connections on K1, seed 20260817")
rng = np.random.default_rng(20260817)
e_u = e_F = e_C = 0.0
for _ in range(2000):
    pf = rng.uniform(-np.pi, np.pi, 3); pc = rng.uniform(-np.pi, np.pi, 3)
    k = Carrier('K1', 5, [0,1,2], [0,3,4], pf, pc)
    for w in ('F','C'):
        A = k.T(w)
        e_u = max(e_u, np.linalg.norm(A.conj().T@A - np.eye(5)))
        d = np.linalg.norm(np.linalg.matrix_power(A,3) - k.M(w))
        if w=='F': e_F = max(e_F, d)
        else:      e_C = max(e_C, d)
print("   max ||T*T - I||        = %.2e" % e_u)
print("   max ||T_F^3 - M_F||    = %.2e" % e_F)
print("   max ||T_C^3 - M_C||    = %.2e" % e_C)

# ---- A.2  gauge behaviour, S1:59-63 -----------------------------------------------
print("\nA.2  gauge covariance of T and gauge INVARIANCE of M   (S1 sec.4: a_e -> a_e + th_v - th_u)")
worstT = worstM = 0.0
for _ in range(2000):
    pf = rng.uniform(-np.pi, np.pi, 3); pc = rng.uniform(-np.pi, np.pi, 3)
    k = Carrier('K1', 5, [0,1,2], [0,3,4], pf, pc)
    th = rng.uniform(0, 2*np.pi, 5); g = np.exp(1j*th)
    # gauge-transformed connection: each traversal step u->v picks up th_v - th_u
    def shift(loop, ph):
        return np.array([ph[j] + th[loop[(j+1)%len(loop)]] - th[loop[j]] for j in range(len(loop))])
    kg = Carrier('K1g', 5, [0,1,2], [0,3,4], shift([0,1,2],pf), shift([0,3,4],pc))
    G = np.diag(g)
    for w in ('F','C'):
        worstT = max(worstT, np.linalg.norm(kg.T(w) - G@k.T(w)@np.linalg.inv(G)))
        worstM = max(worstM, np.linalg.norm(kg.M(w) - k.M(w)))
print("   max || T[a^g] - g T[a] g^-1 ||   = %.2e   -> T is gauge-COVARIANT" % worstT)
print("   max || M[a^g] - M[a] ||          = %.2e   -> M is gauge-INVARIANT (entries unmoved)" % worstM)

# ---- A.3  THE STRUCTURAL FACT THE WHOLE QUESTION TURNS ON -------------------------
print("\nA.3  *** M IS NOT AN ALTERNATIVE TO T.  M = T^L, EXACTLY. ***")
k = K1(1.0, np.sqrt(2.0))
for w,L in (('F',3),('C',3)):
    print("   || M_%s - T_%s^%d ||  = %.2e" % (w,w,L, np.linalg.norm(k.M(w) - np.linalg.matrix_power(k.T(w),L))))
print("   => the two 'conventions' are generated by ONE operator.  What differs between them")
print("      is WHICH POWERS of it the branch comparison is evaluated at, i.e. THE CLOCK.")

# ---- A.4  diagonality of T^n as a function of n ------------------------------------
print("\nA.4  when is T_gamma^n diagonal, and when is its diagonal CLASS-CONSTANT?")
for w in ('F','C'):
    row = []
    for n in range(1, 13):
        A = np.linalg.matrix_power(k.T(w), n)
        diagq = np.linalg.norm(A - np.diag(np.diag(A))) < 1e-12
        d = np.diag(A)
        cc = True
        for cl, idx in k.classes().items():
            if len(idx) > 1 and np.ptp(np.abs(d[idx]-d[idx[0]])) > 1e-12: cc = False
            if len(idx) > 1 and np.max(np.abs(d[idx]-d[idx[0]])) > 1e-12: cc = False
        row.append('D' if (diagq and cc) else ('d' if diagq else '.'))
    print("   T_%s^n, n=1..12 :  %s     (D = diagonal AND class-constant)" % (w, ' '.join(row)))
print("   K1: both loops L=3, so both are D exactly on 3Z.")
