"""
k1_typecheck.py -- LANE W21-K, BLOCK 1.

TWO JOBS, IN THIS ORDER:

  (A) VALIDATE THE INSTRUMENT.  The restricted-algebra entropy S(rho|_A) is the only
      quantity this lane produces.  It is cross-checked against THREE independent code
      paths that share no line with it: ordinary partial-trace von Neumann entropy
      (A = a tensor factor), Shannon entropy of a joint projective measurement
      (A abelian), and an explicit measure-then-partial-trace construction (A with a
      non-trivial centre).  If these disagree the lane is void.

  (B) SETTLE THE TYPE QUESTION CONSTRUCTIVELY, NOT BY CITATION.  For each candidate
      region algebra: exhibit the Artin-Wedderburn decomposition, exhibit a MINIMAL
      PROJECTION (a type-III algebra has none), and exhibit a faithful trace.  Then
      exhibit the one thing that *is* ambiguous finitely: the trace is unique only up
      to an independent positive scale on each central block, and rescaling shifts the
      entropy by a state-dependent amount sum_alpha p_alpha log c_alpha -- which is the
      finite shadow, and a WEAK one, of "entropy up to an additive constant".

  CONTROL DISCIPLINE: everything in (B) is a THEOREM (Artin-Wedderburn) being exhibited,
  not a measurement.  It could not have come out otherwise.  It is reported as a
  certificate, never as evidence for a hypothesis.
"""
import numpy as np
import itertools
from klib import (PauliAlgebra, Z2Gauge, pauli_matrix, pauli_expect, pack, unpack,
                  rref_basis, span_elements, gauge_invariant_subspace, sympl_perp, in_span)


def in_span_helper(e, basis):
    return in_span(e, basis)

np.set_printoptions(precision=9, suppress=True)
def line(c="="): print(c * 100)


# ---------------------------------------------------------------- independent paths
def vn_entropy(rho):
    w = np.linalg.eigvalsh((rho + rho.conj().T) / 2)
    w = np.clip(w.real, 0, None)
    return float(-sum(x * np.log2(x) for x in w if x > 1e-14))


def partial_trace_keep(psi, n, keep):
    """Independent path #1: reshape + transpose partial trace.
    CONVENTION NOTE (a real bug caught here, recorded not fixed quietly): in klib a Pauli
    on qubit q touches BIT q of the basis-state integer, i.e. tensor position n-1-q under
    numpy's reshape([2]*n).  This map is applied here so the two paths speak of the same
    qubits."""
    keep = sorted(keep)
    pos = [n - 1 - q for q in keep]
    rest = [i for i in range(n) if i not in pos]
    t = psi.reshape([2] * n)
    t = np.transpose(t, pos + rest).reshape(1 << len(keep), 1 << len(rest))
    return t @ t.conj().T


def shannon_of_commuting(psi, gens, n):
    """Independent path #2: joint projective measurement of commuting Hermitian Paulis."""
    d = 1 << n
    probs = []
    for signs in itertools.product([1, -1], repeat=len(gens)):
        P = np.eye(d, dtype=complex)
        for s, (x, z) in zip(signs, gens):
            P = P @ (np.eye(d, dtype=complex) + s * pauli_matrix(x, z, n)) / 2
        probs.append(float(np.real(np.vdot(psi, P @ psi))))
    return float(-sum(p * np.log2(p) for p in probs if p > 1e-14)), probs


def measure_then_ptrace(psi, n, central_gens, keep_qubits):
    """Independent path #3: for A = (full algebra on `keep_qubits`) tensor (abelian
    algebra generated by `central_gens`), the entropy is H(p) + sum p S(rho_keep|outcome)."""
    d = 1 << n
    tot = 0.0
    ps = []
    for signs in itertools.product([1, -1], repeat=len(central_gens)):
        P = np.eye(d, dtype=complex)
        for s, (x, z) in zip(signs, central_gens):
            P = P @ (np.eye(d, dtype=complex) + s * pauli_matrix(x, z, n)) / 2
        v = P @ psi
        p = float(np.real(np.vdot(v, v)))
        ps.append(p)
        if p > 1e-14:
            v = v / np.sqrt(p)
            rho = partial_trace_keep(v, n, keep_qubits)
            tot += p * vn_entropy(rho)
    tot += -sum(p * np.log2(p) for p in ps if p > 1e-14)
    return tot, ps


# ---------------------------------------------------------------- A. VALIDATION
line()
print("BLOCK 1A -- INSTRUMENT VALIDATION.  Three independent code paths.")
line()

rng = np.random.default_rng(20260817)
n = 5
d = 1 << n
psi = rng.normal(size=d) + 1j * rng.normal(size=d)
psi /= np.linalg.norm(psi)
print(f"random pure state on n={n} qubits, seed 20260817, ||psi||={np.linalg.norm(psi):.12f}")

# --- check 1: A = full algebra on qubits {0,1}
bas = []
for q in (0, 1):
    bas.append(pack((1 << q, 0), n)); bas.append(pack((0, 1 << q), n))
A1 = PauliAlgebra(bas, n, "M_4 on qubits {0,1}")
s_alg = A1.entropy(psi)
s_pt = vn_entropy(partial_trace_keep(psi, n, [0, 1]))
print(f"  {A1.describe()}")
print(f"  CHECK1  S_alg = {s_alg:.12f}   S_partialtrace = {s_pt:.12f}   diff = {abs(s_alg-s_pt):.3e}")
assert abs(s_alg - s_pt) < 1e-9

# --- check 2: A abelian, generated by 3 commuting Paulis
gens2 = [(0b00001, 0), (0b00110, 0), (0, 0b01000)]
A2 = PauliAlgebra([pack(g, n) for g in gens2], n, "abelian alg{X0, X1X2, Z3}")
s_alg2 = A2.entropy(psi)
s_sh, probs = shannon_of_commuting(psi, gens2, n)
print(f"  {A2.describe()}")
print(f"  CHECK2  S_alg = {s_alg2:.12f}   S_shannon = {s_sh:.12f}   diff = {abs(s_alg2-s_sh):.3e}")
assert abs(s_alg2 - s_sh) < 1e-9

# --- check 3: A = M_2(qubit 0) (x) abelian{X_2, Z_3}  -- non-trivial centre
gens3c = [(0b00100, 0), (0, 0b01000)]
bas3 = [pack((1, 0), n), pack((0, 1), n)] + [pack(g, n) for g in gens3c]
A3 = PauliAlgebra(bas3, n, "M_2(q0) (x) abelian{X2,Z3}")
s_alg3 = A3.entropy(psi)
s_mp, ps3 = measure_then_ptrace(psi, n, gens3c, [0])
print(f"  {A3.describe()}")
print(f"  CHECK3  S_alg = {s_alg3:.12f}   S_measure+ptrace = {s_mp:.12f}   diff = {abs(s_alg3-s_mp):.3e}")
assert abs(s_alg3 - s_mp) < 1e-9

# --- check 4: A = B(H) on a pure state must give 0
A4 = PauliAlgebra([pack((1 << q, 0), n) for q in range(n)] + [pack((0, 1 << q), n) for q in range(n)], n, "B(H)")
print(f"  {A4.describe()}")
print(f"  CHECK4  S_alg(B(H), pure state) = {A4.entropy(psi):.12f}  (must be 0)")
assert abs(A4.entropy(psi)) < 1e-9
print("\n>>> INSTRUMENT VALIDATED, 4/4.  Every number below uses this one routine.")


# ---------------------------------------------------------------- B. TYPE CERTIFICATE
line()
print("BLOCK 1B -- THE TYPE CERTIFICATE.  Z_2 gauge theory, carrier 'ladder3'.")
line()

# ladder3: u0 u1 u2 / w0 w1 w2
edges = [(0, 1), (1, 2), (3, 4), (4, 5), (0, 3), (1, 4), (2, 5)]
G = Z2Gauge(6, edges, "ladder3")
print(f"carrier {G.name}: V={G.V} L={G.L} cycle_dim={G.cycle_dim} "
      f"physical dim = 2^{G.L-G.V+1} = {2**(G.L-G.V+1)}   ambient d = {1<<G.n}")
print(f"edges (link index -> endpoints): {list(enumerate(G.edges))}")
print(f"independent Wilson loops (link masks): {[bin(c) for c in G.cycles]}")

psi_g, physdim, e0 = G.ground_state(0.5)
print(f"ground state at g^2=0.50: physical sector dim = {physdim}, E0 = {e0:.9f}, "
      f"max Gauss residual = {G.gauss_residual(psi_g):.3e}")

internal, boundary, external = G.region([0, 1, 3, 4])
print(f"\nregion A = vertices (u0,u1,w0,w1) = {[0,1,3,4]}")
print(f"  internal links {internal}   boundary links {boundary}   external links {external}")

n = G.n
# electric-centre algebra of A: X on every link touching A, plus Wilson loops inside A
inside_cycles = [c for c in G.cycles if (c & ~sum(1 << l for l in internal)) == 0]
A_el_basis = [pack(G.X(l), n) for l in internal + boundary] + [pack(G.W(c), n) for c in inside_cycles]
A_el = PauliAlgebra(A_el_basis, n, "A_electric(A)")

# extended-Hilbert-space algebra: the FULL matrix algebra on A's links (boundary -> A)
A_ext_basis = []
for l in internal + boundary:
    A_ext_basis += [pack((1 << l, 0), n), pack((0, 1 << l), n)]
A_ext = PauliAlgebra(A_ext_basis, n, "A_extended(A), boundary links -> A")

# complement's minimal algebra, and its commutant = the magnetic-centre choice for A
int_b, bnd_b, ext_b = G.region([2, 5])
inside_cycles_b = [c for c in G.cycles if (c & ~sum(1 << l for l in int_b)) == 0]
A_el_B_basis = [pack(G.X(l), n) for l in int_b + bnd_b] + [pack(G.W(c), n) for c in inside_cycles_b]
A_el_B = PauliAlgebra(A_el_B_basis, n, "A_electric(Abar)")
GI = gauge_invariant_subspace(G)
from klib import intersect
A_mag = PauliAlgebra(intersect(sympl_perp(A_el_B.basis, n), GI, n), n,
                     "A_magnetic(A) = commutant of A_electric(Abar) INSIDE the gauge-invariant algebra")

for A in (A_el, A_mag, A_ext):
    line("-")
    print(A.describe())
    nb, k, m = A.nblocks, A.k, A.mult
    print(f"  ARTIN-WEDDERBURN:  A  ~=  (+)_{{i=1}}^{{{nb}}} M_{{{2**k}}} ,  each acting with "
          f"multiplicity {m} on C^{1<<n}")
    print(f"  dimension check: {nb} * {2**k}^2 = {nb*(2**k)**2}  vs dim_C(A) = {A.dim}  "
          f"-> {'MATCH' if nb*(2**k)**2 == A.dim else 'MISMATCH'}")
    assert nb * (2 ** k) ** 2 == A.dim
    print(f"  TYPE: I_{{{2**k}}} on every block. Finite type I. Not II, not III. (Artin-Wedderburn; "
          f"exhibited, not assumed.)")

    # --- minimal projection certificate: type III has NO minimal (indeed no finite) projections
    # build one: fix all central signs +, then a maximal commuting set inside one block
    d = 1 << n
    P = np.eye(d, dtype=complex)
    for cb in A.centre_basis:
        v = unpack(cb, n)
        P = P @ (np.eye(d, dtype=complex) + pauli_matrix(v[0], v[1], n)) / 2
    # greedily add block generators that commute with what we have
    chosen = []
    cur_basis = list(A.centre_basis)
    from klib import sympl as _s
    for e in span_elements(A.basis):
        if e == 0 or len(chosen) >= k:
            continue
        ve = unpack(e, n)
        if any(_s(ve, unpack(c, n)) for c in chosen):
            continue
        if in_span_helper(e, cur_basis):
            continue
        chosen.append(e)
        cur_basis = rref_basis(cur_basis + [e])
        P = P @ (np.eye(d, dtype=complex) + pauli_matrix(ve[0], ve[1], n)) / 2
    rk = int(round(np.real(np.trace(P))))
    idem = np.linalg.norm(P @ P - P)
    print(f"  MINIMAL PROJECTION exhibited: ambient rank {rk} (predicted m = {m}), "
          f"||P^2-P|| = {idem:.2e}  -> {'MINIMAL' if rk == m else 'NOT MINIMAL'}")

    # --- trace certificate
    els = [pauli_matrix(*unpack(e, n), n) for e in span_elements(A.basis)[:16]]
    worst = 0.0
    for a in els[:8]:
        for b in els[:8]:
            worst = max(worst, abs(np.trace(a @ b) - np.trace(b @ a)))
    print(f"  FAITHFUL TRACE exhibited: tr = ambient Tr restricted to A; "
          f"max |Tr(ab)-Tr(ba)| over 64 pairs = {worst:.2e}")


# ---------------------------------------------------------------- the ONE finite residue
line()
print("BLOCK 1C -- THE ONLY THING THE TRACE LEAVES OPEN FINITELY, AND ITS SIZE.")
line()
print("""A finite direct sum (+)_alpha M_{n_alpha} admits a trace, but NOT a unique one: any
c_alpha > 0 per block gives another trace tr_c = sum_alpha c_alpha Tr_alpha.  The entropy
computed against tr_c differs from the entropy against the ambient trace by
    Delta S = sum_alpha p_alpha log2 c_alpha
which is STATE DEPENDENT whenever there is more than one block with weight.  In type II_infinity
the corresponding freedom is a SINGLE overall scale, so the shift is a genuine constant.
Finitely the freedom is per-block, and the shift is NOT a constant -- it is a Shannon-weighted
average.  These are different animals and the finite one is strictly worse behaved.""")
pd = A_el.central_distribution(psi_g)
print(f"\n  A_electric(A): {A_el.nblocks} central sectors, p_chi =")
tot = 0.0
for signs, p in pd:
    if abs(p) > 1e-12:
        print(f"     signs {signs}  p = {p:+.9f}")
    tot += p
print(f"     sum p = {tot:.12f}")
nz = [p for _, p in pd if p > 1e-12]
print(f"  number of OCCUPIED central sectors = {len(nz)} of {A_el.nblocks}")
if len(nz) > 1:
    print("  -> more than one block carries weight, so the per-block trace freedom moves the")
    print("     entropy by a STATE-DEPENDENT amount.  This is not the type-II additive constant.")
else:
    print("  -> only one block carries weight, so the per-block freedom degenerates to a single")
    print("     scale here and the shift IS a constant.  Recorded as a carrier-specific accident.")

line()
print("END BLOCK 1")
