"""
k3_crossed.py -- LANE W21-K, BLOCK 3.

The brief's question (3): "Is there any finite construction in which adjoining a degree of
freedom (a clock, an observer, a modular generator) changes what is well-defined?  Or is that
content purely type-theoretic?"

THE ANSWER HAS A THEOREM UNDER IT AND THE THEOREM IS OLDER THAN THE PROGRAM.  Skolem-Noether:
every automorphism of a finite-dimensional central simple algebra is INNER.  The entire content
of the crossed-product construction is that in a type III_1 factor the modular automorphism
group is OUTER -- it is not implemented by any unitary IN the algebra -- so adjoining it
enlarges the algebra.  Finitely that is impossible.  This block exhibits the collapse rather
than asserting it:

  3A  modular flow is inner: Delta^{it} a Delta^{-it} = rho_A^{it} a rho_A^{-it}, and
      rho_A^{it} lies IN A.  Measured as a norm, at several t.
  3B  the crossed product by that flow is A (x) C[G] -- the clock DECOUPLES.  Measured as
      a dimension count and as an explicit untwisting unitary.
  3C  therefore the entropy after adjoining the clock is S(A) + H(clock), additively, and
      NOTHING that was undefined becomes defined, because nothing was undefined.
  3D  the one finite construction that DOES change what is well-defined, exhibited for
      contrast: imposing a CONSTRAINT.  A constraint is not a crossed product.
"""
import numpy as np
import itertools
from klib import (PauliAlgebra, Z2Gauge, pauli_matrix, pack, unpack, rref_basis,
                  span_elements, gauge_invariant_subspace, sympl_perp, intersect)

np.set_printoptions(precision=9, suppress=True)
def line(c="="): print(c * 100)

rng = np.random.default_rng(21)


def randunitary(d):
    z = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))
    q, r = np.linalg.qr(z)
    return q * (np.diag(r) / abs(np.diag(r)))


def span_dim(mats, tol=1e-9):
    """Dimension of the complex linear span of a list of matrices."""
    M = np.array([m.reshape(-1) for m in mats])
    return int(np.linalg.matrix_rank(M, tol=tol))


def algebra_closure(gens, d, tol=1e-8, maxit=40):
    """Linear span of the *-algebra generated by gens (with identity).
    Incremental Gram-Schmidt on flattened matrices -- O(dim^2) not O(dim^4)."""
    onb = []                                   # orthonormal flattened basis
    basis = []

    def add(m):
        v = m.reshape(-1).astype(complex)
        for b in onb:
            v = v - np.vdot(b, v) * b
        nv = np.linalg.norm(v)
        if nv > tol * max(1.0, np.linalg.norm(m)):
            onb.append(v / nv); basis.append(m); return True
        return False

    add(np.eye(d, dtype=complex))
    for g in gens:
        add(g); add(g.conj().T)
    frontier = list(basis)
    it = 0
    while frontier and it < maxit:
        it += 1
        nxt = []
        for a in frontier:
            for g in gens:
                for m in (a @ g, g @ a, a @ g.conj().T, g.conj().T @ a):
                    if add(m):
                        nxt.append(m)
        frontier = nxt
    return basis


# ============================================================ 3A
line()
print("BLOCK 3A -- MODULAR FLOW IN FINITE DIMENSIONS IS INNER.")
print("DECLARED FIRST: THIS IS A THEOREM EXHIBIT, NOT A MEASUREMENT.  IT COULD NOT HAVE FAILED.")
line()
print("""In finite dimensions Delta = rho_A (x) rho_{A'}^{-1}, the two factors commute, and the
adjoint action on A involves only the first.  So Ad(Delta^{it})|_A = Ad(rho_A^{it})|_A is TRUE BY
CONSTRUCTION and the residual below is a code check, nothing more.  The content is the theorem
underneath it (Skolem-Noether: every automorphism of a finite-dimensional central simple algebra
is inner), and the program's own rule -- 'could not have failed' voids a control, never a theorem
-- is what lets this stand as the premise of 3B.  Stated plainly so it is not read as evidence.""")
psi = rng.normal(size=16) + 1j * rng.normal(size=16)
psi /= np.linalg.norm(psi)
print(f"\nH = C^16 = C^4 (x) C^4 ;  A = M_4 (x) 1 ;  A' = 1 (x) M_4 ; random pure Omega, seed 21.")
t = psi.reshape(4, 4)
rhoA = t @ t.conj().T
rhoB = t.conj().T @ t
eA = np.linalg.eigvalsh(rhoA).real
eB = np.linalg.eigvalsh(rhoB).real
print(f"  rho_A eigenvalues  = {np.round(eA,9)}")
print(f"  rho_A' eigenvalues = {np.round(eB,9)}")
print(f"  Omega is CYCLIC AND SEPARATING: min eig(rho_A) = {eA.min():.3e} > 0, "
      f"min eig(rho_A') = {eB.min():.3e} > 0")

def mpow(M, s):
    w, V = np.linalg.eigh((M + M.conj().T) / 2)
    w = np.clip(w.real, 1e-300, None)
    return V @ np.diag(w.astype(complex) ** s) @ V.conj().T

for tt in (0.3, 1.0, 2.5):
    Dit = np.kron(mpow(rhoA, 1j * tt), mpow(rhoB, -1j * tt))
    uA = mpow(rhoA, 1j * tt)
    UA = np.kron(uA, np.eye(4))
    worst = 0.0
    for _ in range(6):
        a = np.kron(randunitary(4), np.eye(4))
        worst = max(worst, np.linalg.norm(Dit @ a @ Dit.conj().T - UA @ a @ UA.conj().T))
    print(f"  t = {tt:4.1f}:  max_a || Delta^it a Delta^-it - rho_A^it a rho_A^-it || = {worst:.3e}"
          f"   [FORCED]   rho_A^it unitary in A: ||u u* - 1|| = "
          f"{np.linalg.norm(uA @ uA.conj().T - np.eye(4)):.1e}")


# ============================================================ 3B
line()
print("BLOCK 3B -- THE CROSSED PRODUCT COLLAPSES.  A x|_sigma Z_N  ==  A (x) C^N.")
line()
N = 4
u = mpow(rhoA, 1j * 1.0)                      # unitary in A implementing sigma_1
print(f"clock: Z_{N}.  action alpha_k = Ad(u^k) with u = rho_A^i in A (inner, by 3A).")

# crossed product on C^4 (x) C^N : pi(a) block-diagonal, lambda = shift
def blockdiag(blocks):
    D = sum(b.shape[0] for b in blocks)
    M = np.zeros((D, D), dtype=complex)
    o = 0
    for b in blocks:
        M[o:o+b.shape[0], o:o+b.shape[1]] = b; o += b.shape[0]
    return M

upow = [np.linalg.matrix_power(u, k) for k in range(N)]
uinv = [np.linalg.inv(x) for x in upow]

def pi(a):
    return blockdiag([uinv[k] @ a @ upow[k] for k in range(N)])

lam = np.zeros((4 * N, 4 * N), dtype=complex)
for k in range(N):
    lam[4 * ((k + 1) % N):4 * ((k + 1) % N) + 4, 4 * k:4 * k + 4] = np.eye(4)

gens = [pi(randunitary(4)) for _ in range(6)] + [lam]
bas = algebra_closure(gens, 4 * N)
print(f"  dim_C ( A x|_sigma Z_{N} ) measured by explicit closure = {len(bas)}")
print(f"  dim_C ( A ) * N = 16 * {N} = {16*N}      "
      f"{'MATCH -> the crossed product is A (x) C^N' if len(bas)==16*N else 'MISMATCH'}")
print(f"  dim_C ( M_{4*N} ) = {(4*N)**2}  -- the crossed product is far smaller than the full")
print(f"     algebra on the enlarged space; it added a CLASSICAL label, not a quantum sector.")

V = blockdiag(upow)
resid = 0.0
for _ in range(6):
    a = randunitary(4)
    resid = max(resid, np.linalg.norm(V @ pi(a) @ V.conj().T - blockdiag([a] * N)))
shifted = V @ lam @ V.conj().T
tgt = np.zeros_like(shifted)
for k in range(N):
    tgt[4 * ((k + 1) % N):4 * ((k + 1) % N) + 4, 4 * k:4 * k + 4] = u
print(f"  EXPLICIT UNTWISTING UNITARY V = diag(u^0,...,u^{N-1}) IN A (x) 1:")
print(f"     max_a || V pi(a) V*  -  a (x) 1 || = {resid:.3e}")
print(f"     || V lambda V*  -  u (x) shift ||  = {np.linalg.norm(shifted-tgt):.3e}   and u is IN A,")
print(f"     so V (A x| Z_N) V* = A (x) C[Z_N].  The clock factorises off.  EXACT.")


# ============================================================ 3C
line()
print("BLOCK 3C -- WHAT THE CLOCK DOES TO THE ENTROPY: IT ADDS ITS OWN AND NOTHING ELSE.")
line()
for pclock in ([1.0, 0, 0, 0], [0.5, 0.5, 0, 0], [0.25] * 4, [0.4, 0.3, 0.2, 0.1]):
    p = np.array(pclock)
    Hc = float(-sum(x * np.log2(x) for x in p if x > 0))
    Sa = float(-sum(x * np.log2(x) for x in np.linalg.eigvalsh(rhoA).real if x > 1e-14))
    # state on A (x) C^N : rho_A (x) diag(p)
    ev = np.kron(np.linalg.eigvalsh(rhoA).real, p)
    Stot = float(-sum(x * np.log2(x) for x in ev if x > 1e-14))
    print(f"  clock distribution {np.round(p,3)}:  S(A) = {Sa:.9f}   H(clock) = {Hc:.9f}   "
          f"S(A x| Z_N) = {Stot:.9f}   S - (S_A + H) = {Stot-Sa-Hc:+.1e}")
print(""">>> ADDITIVE, EXACTLY, EVERY TIME.  Nothing became well-defined that was not already
    well-defined, because in finite dimensions nothing was ill-defined.  In type III_1 the same
    construction is not additive and not a tensor product: it manufactures a trace where there
    was none.  THAT step has no finite shadow.  Question (3) is answered NO for clocks,
    observers and modular generators alike.""")


# ============================================================ 3D
line()
print("BLOCK 3D -- THE CONTRAST.  THE ONE FINITE MOVE THAT DOES CHANGE WHAT IS WELL-DEFINED")
print("IS A CONSTRAINT, AND A CONSTRAINT IS NOT A CROSSED PRODUCT.")
line()
edges = [(0, 1), (1, 2), (3, 4), (4, 5), (0, 3), (1, 4), (2, 5)]
G = Z2Gauge(6, edges, "ladder3")
n = G.L
psi_g, physdim, e0 = G.ground_state(0.5)
print(f"carrier ladder3, ground state at g^2 = 0.50, Gauss residual {G.gauss_residual(psi_g):.1e}")

lnk = 4
A_free = PauliAlgebra([pack((1 << lnk, 0), n), pack((0, 1 << lnk), n)], n, f"M_2 on link {lnk}, UNCONSTRAINED")
GI = gauge_invariant_subspace(G)
A_con = PauliAlgebra(intersect([pack((1 << lnk, 0), n), pack((0, 1 << lnk), n)], GI, n), n,
                     f"gauge-invariant part of link {lnk}")
print(f"  BEFORE the constraint: {A_free.describe()}")
print(f"     -> a FACTOR (trivial centre). Entropy = ordinary von Neumann entropy: "
      f"{A_free.entropy(psi_g):.9f} bits")
print(f"  AFTER  the constraint: {A_con.describe()}")
print(f"     -> an algebra WITH A CENTRE. Entropy = classical + quantum split: "
      f"{A_con.entropy(psi_g):.9f} bits")
print("""
  The constraint changed the algebra, hence the centre, hence what the word 'entropy of this
  region' even denotes.  That is a real finite change in what is well-defined -- and it is the
  Gauss law, which this theory already has.  It is NOT the crossed-product mechanism, it does
  not require an observer, and it produces a centre rather than a trace.  Anyone importing the
  type-II story as a model for 'adding gravity fixes the ambiguity' is importing a mechanism
  whose finite analogue is a constraint we already imposed on line one.""")

line()
print("END BLOCK 3")
