# W10-D leg 3 -- W-02's CHARACTER-RATIO CRITERION and its TABLE; W-01's "the root can never fire"
# and the three-way split; the two |S|=2 support classes that CANNOT EXIST ON K1; and the level at
# which the multiset theorem actually holds (lambda, not |Z_k|, not finite N).
import numpy as np
from itertools import permutations, combinations
from fractions import Fraction

CLS = ('00', '10', '01', '11')
EXP = {'00': (0, 0), '10': (1, 0), '01': (0, 1), '11': (1, 1)}   # (a,b) in chi = u^a v^b

def chi(cl, f, c, k=1):
    a, b = EXP[cl]
    return np.exp(1j*k*(-a*f + b*c))

def Zk(p, f, c, k):
    return sum(p[i]*chi(CLS[i], f, c, k) for i in range(4))

print("="*100)
print("== 3A  S4-1 / W-02's CRITERION: rank of G = <chi_a/chi_b : a,b in S>, ALL 15 SUPPORTS ==")
print("="*100)
print("  The exponent lattice: chi_ab has exponent vector (-a, b) in Z^2 (u = e^{-if}, v = e^{ic}).")
print("  rank G = rank of the lattice generated by DIFFERENCES of exponent vectors over S.")
print(f"  {'S':22s} {'rank':>5s} {'G generated by':>26s}  {'on K1?':>8s}  {'in W-02 table?':>15s}")
W02_TABLE = {frozenset(['11', '01']), frozenset(['11', '10']), frozenset(['10', '01'])}
rows = []
for r in (1, 2, 3, 4):
    for S in combinations(CLS, r):
        V = [np.array(EXP[s]) * np.array([-1, 1]) for s in S]
        D = [v - V[0] for v in V[1:]]
        rank = 0 if not D else np.linalg.matrix_rank(np.array(D))
        onk1 = "yes" if '00' not in S else "NO (needs 00)"
        gen = "{1}" if rank == 0 else ("<" + ",".join(
            f"u^{-d[0]}v^{d[1]}" for d in D) + ">")
        intab = "yes" if (r == 2 and frozenset(S) in W02_TABLE) else ("n/a" if r != 2 else "MISSING")
        rows.append((S, rank, gen, onk1, intab))
        print(f"  {str(S):22s} {rank:5d} {gen:>26s}  {onk1:>8s}  {intab:>15s}")
print("\n  W-02's registered table lists FOUR lines: |S|=3 -> <u,v>, {0,C} -> <u>, {0,F} -> <v>,")
print("  {F,C} -> <u/v>, plus |S|=1 -> never.  In K1's labels 0 = root = class 11, F = class 10,")
print("  C = class 01.  THE TABLE ENUMERATES 3 OF THE 6 TWO-ELEMENT SUPPORTS.  The three it omits")
print("  are exactly the three that require class 00 -- {00,10}, {00,01}, {00,11} -- and class 00")
print("  IS EMPTY ON K1.  The table is not wrong; it is INCOMPLETE, and incomplete in a way no")
print("  carrier the corpus ran could reveal.  W-02's table row is THREE-CLASS-SCOPED.")
print("  The criterion itself -- FORMATION <=> G != {1} -- quantifies over S and is not.")

print("\n"+"="*100)
print("== 3B  THE TWO SUPPORTS THAT CANNOT EXIST ON K1, RUN ==")
print("="*100)
print("  S = {00,11}: G = <uv>, so formation sees ONLY the product conj(W_F) W_C.")
print("  S = {10,01}: G = <u/v>, so formation sees ONLY the ratio conj(W_F)/W_C.")
print("  Each has a NON-TRIVIAL connection on which it NEVER forms.  Both need class 00.")
N = 200000
k = np.arange(1, N+1)
def run(p, f, c, label):
    Z = Zk(p, f, c, k)
    lg = np.log(np.abs(Z))
    return lg.mean(), np.abs(Z).min(), np.abs(np.exp(np.cumsum(lg))[-1])
CASES = [
    ("S={00,11} p=(.6,0,0,.4)  c=f      (uv=1)", np.array([.6, 0, 0, .4]), 1.3, 1.3),
    ("S={00,11} p=(.6,0,0,.4)  c=f+0.7  generic", np.array([.6, 0, 0, .4]), 1.3, 2.0),
    ("S={10,01} p=(0,.5,.5,0)  c=-f     (u=v)", np.array([0, .5, .5, 0]), 1.3, -1.3),
    ("S={10,01} p=(0,.5,.5,0)  c=-f+0.9 generic", np.array([0, .5, .5, 0]), 1.3, -0.4),
    ("S={00,10} p=(.5,.5,0,0)  f=0      (u=1)", np.array([.5, .5, 0, 0]), 0.0, 1.3),
    ("S={00,10} p=(.5,.5,0,0)  f=1.3    generic", np.array([.5, .5, 0, 0]), 1.3, 0.0),
    ("S={00}    p=(1,0,0,0)    any (f,c)", np.array([1., 0, 0, 0]), 1.3, 2.0),
    ("S={11}    p=(0,0,0,1)    any (f,c)  [K1's ROOT]", np.array([0, 0, 0, 1.]), 1.3, 2.0),
]
print(f"  {'case':46s} {'(1/N)log|Omega_N|':>19s} {'min|Z_k|':>11s} {'|Omega_N|':>12s}  verdict")
for lab, p, fv, cv in CASES:
    r, mn, om = run(p, fv, cv, lab)
    v = "NO FORMATION" if r > -1e-12 else "forms"
    print(f"  {lab:46s} {r:19.12f} {mn:11.6f} {om:12.4e}  {v}")
print("\n  W-02's criterion SURVIVES on four classes, including on the two support classes K1")
print("  cannot realise.  CARRIER-INDEPENDENT.  Its TABLE does not.")

print("\n"+"="*100)
print("== 3C  W-01's 'THE ROOT CAN NEVER FIRE', AND THE THREE-WAY SPLIT ==")
print("="*100)
print("  On K1 the root v0 is the UNIQUE vertex in both loops -- class 11 -- so a state on the")
print("  root alone has |S| = 1 and Z_k is a unit-modulus constant.  Tested above: |Omega_N| = 1.")
print("  BUT: the true statement is '|S| = 1 never fires', and |S| = 1 is reachable from any")
print("  SINGLE class, not from the root.  Off K1 the two come apart three ways:")
print("   (i) B0b has TWO vertices in class 11 (the loops meet twice) -- there is no 'the root'.")
print("   (ii) B0b has FOUR vertices in class 00; a state on any ONE of them also never fires,")
print("        and so does a state SPREAD OVER ALL FOUR.  Non-firing is a CLASS fact, not a")
print("        vertex fact, and on K1 the two coincide only because every class but 11 has >1")
print("        vertex and 11 has exactly one.")
print("   (iii) On B1p (2 classes, {10,01}) the criterion NEVER fires at any state -- W-09.")
for lab, p in [("B0b, state on ONE class-00 vertex   p=(1,0,0,0)", np.array([1., 0, 0, 0])),
               ("B0b, state on ALL FOUR class-00 vtcs p=(1,0,0,0)", np.array([1., 0, 0, 0])),
               ("B0b, state on both class-11 vertices p=(0,0,0,1)", np.array([0., 0, 0, 1.])),
               ("B0b, published SENSE-U               p=(4,2,1,2)/9", np.array([4/9, 2/9, 1/9, 2/9]))]:
    r, mn, om = run(p, 1.3, 2.0, lab)
    print(f"   {lab:50s} rate {r:+.12f}")
print("\n  THE THREE-WAY SPLIT {v0}/{v1,v2}/{v3,v4}.  It IS the loop-membership class partition,")
print("  computed from incidence -- that much is carrier-independent.  Its ARITY is not:")
print("   K1  -> 3 blocks of sizes (1,2,2)        [classes 11,10,01; class 00 empty]")
print("   B1q -> 3 blocks of sizes (1,3,3)        [classes 00,10,01; class 11 empty]")
print("   B0b -> 4 blocks of sizes (4,2,1,2)      [ALL FOUR occupied]")
print("   B4  -> 4 blocks of sizes (1,1,1,3)      [ALL FOUR occupied]")
print("  W-01's registered wording -- 'a canonical THREE-WAY split ... the root, the filled")
print("  triangle's other vertices, the unfilled triangle's other vertices' -- names K1's block")
print("  SIZES and K1's block MEANINGS.  On a four-class carrier the split is FOUR-way and the")
print("  'source/record/environment shape' the row says is 'available here without being imposed'")
print("  acquires a fourth block with no role in that shape.  THREE-WAY: K1-SCOPED (and B1q).")

print("\n"+"="*100)
print("== 3D  AT WHICH LEVEL DOES THE MULTISET THEOREM HOLD?  lambda ONLY. ==")
print("="*100)
print("  W-03 registers TWO different things and the register runs them together:")
print("   (a) the EXACT INVOLUTION 00<->11, 10<->01 -- proved by multiplying Z_k by")
print("       conj(u)^k conj(v)^k, a UNIT MODULUS factor, so it fixes |Z_k| POINTWISE in k;")
print("   (b) '24 of 24 permutations invariant' -- an identity for lambda = m(P) ONLY.")
print("  Tested at the |Z_k| level on B0b's own weights, generic (f,c), k = 1..8:")
p = np.array([4/9, 2/9, 1/9, 2/9]); fv, cv = 1.3, 2.0
base = np.abs(Zk(p, fv, cv, np.arange(1, 9)))
print(f"    identity                       |Z_k| = {np.array2string(base, precision=8)}")
surv_pt, surv_l = [], []
for q in permutations(range(4)):
    a = np.abs(Zk(p[list(q)], fv, cv, np.arange(1, 9)))
    if np.abs(a-base).max() < 1e-12:
        surv_pt.append(q)
inv = (3, 2, 1, 0)   # 00<->11, 10<->01 in index order (00,10,01,11)
a = np.abs(Zk(p[list(inv)], fv, cv, np.arange(1, 9)))
print(f"    W-03 involution {inv}      |Z_k| = {np.array2string(a, precision=8)}"
      f"  max dev {np.abs(a-base).max():.2e}")
bad = (1, 0, 2, 3)
a = np.abs(Zk(p[list(bad)], fv, cv, np.arange(1, 9)))
print(f"    transposition   {bad}      |Z_k| = {np.array2string(a, precision=8)}"
      f"  max dev {np.abs(a-base).max():.2e}")
print(f"    PERMUTATIONS PRESERVING |Z_k| POINTWISE: {len(surv_pt)} of 24 -> {surv_pt}")
print("    PERMUTATIONS PRESERVING lambda        : 24 of 24 (leg 2D)")
print("  SO: the invisibility of the incidence labels is a statement about the ASYMPTOTIC RATE.")
print("  At every FINITE N the labels are visible in |Omega_N|.  The register states the multiset")
print("  theorem without that qualification and W-05 offers it for publication as N2 without it.")
print("  This is a SCOPE defect that has nothing to do with the carrier -- it is CARRIER-")
print("  INDEPENDENT and OBSERVABLE-SCOPED, and it is new here.")

print("\n"+"="*100)
print("== 3E  W-08's MONOTONICITY AND ITS EXACT IDENTITY, ON FOUR CLASSES ==")
print("="*100)
print("  |Z_k| <= 1 by the triangle inequality on non-negative weights summing to 1 -- no")
print("  incidence input, no class-count input.  Checked over k <= 10^6, four carriers,")
print("  at the generic, the resonant and the order-4 connections:")
K = 10**6
kk = np.arange(1, K+1)
for nm, p in [("B1  K1", np.array([0, 2/5, 2/5, 1/5])), ("B1q spectator", np.array([1/7, 3/7, 3/7, 0])),
              ("B0b torus", np.array([4/9, 2/9, 1/9, 2/9])), ("B4  spindle", np.array([1/6, 1/6, 1/6, 3/6]))]:
    worst = -9.9
    for lab, (fv, cv) in [("generic", (1.3, 2.0)), ("resonant f=2,c=1.1", (2.0, 1.1)),
                          ("order-4", (np.pi, 3*np.pi/2))]:
        worst = max(worst, (np.abs(Zk(p, fv, cv, kk))-1).max())
    print(f"    {nm:14s} max_k over all three connections (|Z_k| - 1) = {worst:+.3e}")
print("  MONOTONE NON-INCREASING |Omega_N| ON EVERY CARRIER.  CARRIER-INDEPENDENT.")
print("\n  The exact identity |Z_k|^2 = 1 - sum_{j<l} w_j w_l |chi_j^k - chi_l^k|^2 :")
print("    proof in one line, any number of classes -- |sum w_j chi_j|^2 = sum_{j,l} w_j w_l")
print("    conj(chi_j) chi_l and 1 = (sum w_j)^2 = sum_{j,l} w_j w_l, subtract and pair (j,l),(l,j).")
print("    Checked at FOUR classes in exact rationals for rational angles f = 2pi*a/q, c = 2pi*b/q:")
q = 7
pf = [Fraction(4, 9), Fraction(2, 9), Fraction(1, 9), Fraction(2, 9)]
worst = 0.0
for a in range(q):
    for b in range(q):
        for kexp in range(1, 6):
            ch = [np.exp(2j*np.pi*(-EXP[cl][0]*a + EXP[cl][1]*b)*kexp/q) for cl in CLS]
            Z = sum(float(pf[i])*ch[i] for i in range(4))
            rhs = 1 - sum(float(pf[i])*float(pf[j])*abs(ch[i]-ch[j])**2
                          for i in range(4) for j in range(i+1, 4))
            worst = max(worst, abs(abs(Z)**2 - rhs))
print(f"    max |LHS - RHS| over q={q}, all (a,b), k=1..5, four classes: {worst:.3e}")
