# FT-1 — THE SHAM TARGET, applied to the corpus's one live finding.
#
# W-19's finding: the disagreement between the EXTENDED algebra and the GAUGE-INVARIANT algebra on
# the system region is ~1 bit in the magnetic phase and ~0 in the electric phase -- "the coupling
# indexes whether the boundary data is determined."
#
# THE FITTING RISK: maybe ANY two inequivalent subalgebras disagree differently in the two phases,
# because the two phases have different entanglement structure. Then "boundary" does no work and
# the finding restates "the phases differ".
#
# THE SHAM: run the IDENTICAL pipeline on subalgebra pairs with NO boundary interpretation.
# If they show the same phase-indexed swing, the word "boundary" is narration.
import numpy as np, itertools
rng=np.random.default_rng(20260826)
# small Z_2 gauge carrier: theta graph with 2 extra links -> V=4, L=6, enough for a phase crossover
E=[(0,1),(0,1),(1,2),(2,3),(3,0),(1,3)]
V=4; L=len(E)
I2=np.eye(2); Xp=np.array([[0,1],[1,0]],dtype=complex); Zp=np.diag([1,-1]).astype(complex)
def kr(ops):
    M=np.array([[1]],dtype=complex)
    for o in ops: M=np.kron(M,o)
    return M
X=[kr([Xp if j==i else I2 for j in range(L)]) for i in range(L)]
Z=[kr([Zp if j==i else I2 for j in range(L)]) for i in range(L)]
def gauss(v):
    M=np.eye(2**L,dtype=complex)
    for i,(a,b) in enumerate(E):
        if a==v or b==v: M=M@Z[i]
    return M
P=np.eye(2**L,dtype=complex)
for v in range(V): P=P@((np.eye(2**L)+gauss(v))/2)
dphys=int(round(np.trace(P).real))
# independent cycles -> plaquette (Wilson) operators, built from X on the cycle's links
cycles=[[0,1],[2,3,4,5],[0,2,5,4]]
def wilson(c):
    M=np.eye(2**L,dtype=complex)
    for i in c: M=M@X[i]
    return M
W=[wilson(c) for c in cycles]
print(f"  carrier V={V} L={L}; physical dim {dphys} of {2**L}; {len(cycles)} independent cycles")

def ground(g2):
    H=-(1.0/g2)*sum(W)-g2*sum(Z)                       # magnetic + electric, coupling g^2
    Hp=H+1e6*(np.eye(2**L)-P)
    w,v=np.linalg.eigh(Hp); psi=v[:,0]
    return np.outer(psi,psi.conj())
def red(rho,keep):
    d=[2]*L; r=rho.reshape(d+d); tr=[i for i in range(L) if i not in keep]
    for k,i in enumerate(sorted(tr,reverse=True)): r=np.trace(r,axis1=i,axis2=i+L-k)
    m=2**len(keep); return r.reshape(m,m)
def S(r):
    w=np.linalg.eigvalsh(r); return float(-sum(x*np.log2(x) for x in w if x>1e-12))
def dephase(r,Aops):
    """restrict a state to the abelian subalgebra generated by Aops: keep only its diagonal there"""
    out=np.zeros_like(r)
    ev=[np.linalg.eigh(a)[1] for a in Aops]
    Ubasis=ev[0]
    proj=[np.outer(Ubasis[:,k],Ubasis[:,k].conj()) for k in range(r.shape[0])]
    for p in proj: out+=p@r@p
    return out
def disagreement(rho,region,sub):
    """EXT entropy of the region minus entropy after restricting to the named subalgebra"""
    rr=red(rho,region)
    return abs(S(rr)-S(dephase(rr,[sub])))

REG=[0]                                                # system region: one link
# DEFECT RECORDED, NOT PATCHED OUT: the first run of this script labelled X as "the gauge-invariant
# choice". With Gauss = product of Z over incident links it is Z that commutes with the constraint,
# so the labels were SWAPPED and the printed table read backwards. The invariance is now CHECKED
# rather than asserted, below, so the label cannot be wrong again.
Xr=np.array([[0,1],[1,0]],dtype=complex)
Zr=np.diag([1,-1]).astype(complex)
def is_gauge_inv(op1):
    """lift a single-link operator to the full space and test it against every Gauss operator"""
    full=kr([op1 if j==REG[0] else I2 for j in range(L)])
    return max(np.linalg.norm(full@gauss(v)-gauss(v)@full) for v in range(V))
print(f"\n  GAUGE-INVARIANCE CHECK ON THE SINGLE-LINK CHOICES (max commutator norm):")
print(f"    X on the link : {is_gauge_inv(Xr):.3e}   {'GAUGE-INVARIANT' if is_gauge_inv(Xr)<1e-9 else 'NOT gauge-invariant'}")
print(f"    Z on the link : {is_gauge_inv(Zr):.3e}   {'GAUGE-INVARIANT' if is_gauge_inv(Zr)<1e-9 else 'NOT gauge-invariant'}")
def rand_herm():
    A=rng.normal(size=(2,2))+1j*rng.normal(size=(2,2)); A=A+A.conj().T
    return A

print("\n== THE FINDING, AND THREE SHAMS, THROUGH ONE PIPELINE ==")
print(f"  {'g^2':>7}{'Z on link':>14}{'X on link':>14}{'random #1':>14}{'random #2':>14}")
shams=[Xr, rand_herm(), rand_herm()]
rows=[]
for g2 in (0.10,0.30,0.70,1.50,3.00):
    rho=ground(g2)
    a=disagreement(rho,REG,Zr); b=[disagreement(rho,REG,s) for s in shams]
    rows.append((g2,a,b))
    print(f"  {g2:>7.2f}{a:>14.6f}{b[0]:>14.6f}{b[1]:>14.6f}{b[2]:>14.6f}")
sw=lambda col:max(col)-min(col)
bnd=[r[1] for r in rows]; s0=[r[2][0] for r in rows]; s1=[r[2][1] for r in rows]; s2=[r[2][2] for r in rows]
print(f"\n  SWING ACROSS THE COUPLING   Z(gauge-inv) {sw(bnd):.6f} | X {sw(s0):.6f}"
      f" | random1 {sw(s1):.6f} | random2 {sw(s2):.6f}")
print("\n  READ IT HONESTLY:")
print("   if the shams swing comparably, 'boundary' does no work and W-19's finding restates")
print("   'the two phases differ'. If only the gauge-invariant choice swings, the word earns its place.")
