"""ADVERSARIAL CHECK V4 -- IS THE LANE'S NULL A MEASUREMENT OR A THEOREM?

The lane reports the null as an empirical sweep over five relation definitions and n = 4..20.
But its own step 2D shows only (a) and (c) are gauge-invariant, and (c) is the identity.  If
the symplectic group acts TRANSITIVELY on ordered pairs of distinct non-zero logical classes
with a given symplectic product, then ANY gauge-invariant, basis-covariant pairwise relation
between two stabiliser records is a FUNCTION OF ONE BIT -- on ANY stabiliser carrier, not
just [[n,n-2,2]].  A one-bit relation can never carry a metric geometry.

CHECK BY BRUTE ORBIT COMPUTATION over F_2^{2k}: generate Sp(2k,F2) by random transvections,
compute the orbits on ordered pairs (u,v) of distinct non-zero vectors, and count how many
orbits there are.  If the orbit count equals 2 (one for <u,v>=0, one for <u,v>=1), the claim
holds.  CONTROL IN THE SAME TABLE: the orbit count under the group generated by PERMUTATION
matrices only, which is NOT the full symplectic group and must give MORE than 2 orbits --
otherwise the test is trivially satisfied by anything and discriminates nothing.
"""
import sys, itertools
sys.path.insert(0, "/Users/bgm/MB Work/where-atoms-come-from/LANE_SCALE_B_METRIC")
import numpy as np

OUT = []
def P(*a):
    s = " ".join(str(x) for x in a); print(s, flush=True); OUT.append(s)

def spform(u, v, k):
    return int(sum(u[i] * v[k + i] + u[k + i] * v[i] for i in range(k)) % 2)

def transvection(a, k):
    """T_a(x) = x + <x,a> a   -- a symplectic transvection, as a 2k x 2k F2 matrix"""
    m = 2 * k
    M = np.eye(m, dtype=int)
    for j in range(m):
        e = np.zeros(m, dtype=int); e[j] = 1
        M[:, j] = (e + spform(e, a, k) * np.array(a)) % 2
    return M

def orbits(gens, k):
    m = 2 * k
    vecs = [v for v in itertools.product([0, 1], repeat=m) if any(v)]
    idx = {v: i for i, v in enumerate(vecs)}
    pairs = [(u, v) for u in vecs for v in vecs if u != v]
    pidx = {p: i for i, p in enumerate(pairs)}
    parent = list(range(len(pairs)))
    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]; x = parent[x]
        return x
    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb: parent[ra] = rb
    for g in gens:
        for p in pairs:
            u2 = tuple((g @ np.array(p[0])) % 2)
            v2 = tuple((g @ np.array(p[1])) % 2)
            if u2 == v2 or not any(u2) or not any(v2): continue
            union(pidx[p], pidx[(u2, v2)])
    reps = {}
    for p in pairs:
        reps.setdefault(find(pidx[p]), []).append(p)
    return reps

P("=" * 108)
P("V4  ORBITS OF Sp(2k,F2) ON ORDERED PAIRS OF DISTINCT NON-ZERO LOGICAL CLASSES.")
P("    CONTROL IN THE SAME TABLE: the same orbit count under a PERMUTATION-only subgroup,")
P("    which is a proper subgroup and must give MORE orbits or the test discriminates nothing.")
P("=" * 108)
P("")
P("  %-4s %-8s %-10s | %-14s %-22s | %-14s" %
  ("k", "#classes", "#pairs", "Sp orbits", "symplectic values seen", "PERM-only orbits"))
P("  " + "-" * 100)
rng = np.random.default_rng(11)
for k in [1, 2, 3]:
    m = 2 * k
    gens = []
    for _ in range(60):
        a = tuple(int(x) for x in rng.integers(0, 2, m))
        if not any(a): continue
        gens.append(transvection(a, k))
    reps = orbits(gens, k)
    vals = set()
    for r, ps in reps.items():
        vals.add(tuple(sorted(set(spform(u, v, k) for u, v in ps))))
    # permutation-only control
    pgens = []
    for _ in range(60):
        perm = rng.permutation(m)
        Mp = np.zeros((m, m), dtype=int)
        for j in range(m): Mp[perm[j], j] = 1
        pgens.append(Mp)
    preps = orbits(pgens, k)
    nvec = 2 ** m - 1
    P("  %-4d %-8d %-10d | %-14d %-22s | %-14d" %
      (k, nvec, nvec * (nvec - 1), len(reps), str(sorted(vals)), len(preps)))
P("")
P("  READ, filled from the numbers above:")
P("  If the Sp-orbit column reads 2 while the PERM-only control reads more, then every")
P("  gauge-invariant, basis-covariant pairwise relation between two stabiliser records is")
P("  constant on each of exactly 2 orbits, i.e. a FUNCTION OF THE ANTICOMMUTATION BIT ALONE.")

open("/Users/bgm/MB Work/where-atoms-come-from/LANE_SCALE_B_METRIC/VERIFY/V4_gauge_invariant_relations_are_one_bit.txt",
     "w").write("\n".join(OUT) + "\n")
