# W-07 leg A — rebuild K1 from S1's own bytes; validate before attacking anything.
# Lineage note: corpus authored by Claude Fable 5 (git trailers, 9/9 commits). This lane is Opus 5.
import numpy as np, itertools
np.set_printoptions(precision=6, suppress=True)

# S1 sec1 / LANE_G PUBLISHED_CONVENTIONS
EDGES = [(0,1),(1,2),(2,0),(0,3),(3,4),(4,0)]   # e1..e6
V, E = 5, 6
d1 = np.zeros((V,E))
for j,(s,t) in enumerate(EDGES):
    d1[t,j] += 1; d1[s,j] -= 1
d2 = np.array([[1],[1],[1],[0],[0],[0]], float)  # F attached along e1+e2+e3

print("== VALIDATE against S1 sec2 ==")
print("d1@d2 =", (d1@d2).ravel())
r1, r2 = np.linalg.matrix_rank(d1), np.linalg.matrix_rank(d2)
chi = V - E + 1
b1 = 1 - chi          # b0=1, b2=0
print(f"V={V} E={E} F=1  chi={chi}  rank d1={r1}  rank d2={r2}  b1={b1}")
assert (d1@d2==0).all() and chi==0 and r1==4 and r2==1 and b1==1

# S1 sec6 worked instance
a_pub = np.array([np.pi/3]*3 + [np.pi/2]*3)
def hol(a):
    WF = np.exp(1j*(a[0]+a[1]+a[2]))
    WC = np.exp(1j*(a[3]+a[4]+a[5]))
    return WF, WC
WF, WC = hol(a_pub)
print(f"S1 sec6:  W_F={WF:.12f}   W_C={WC:.12f}")
assert abs(WF-(-1))<1e-12 and abs(WC-(-1j))<1e-12
print("S1 sec6 reproduced exactly.\n")

print("== LEG A — the ORDER of S1's published connection in U(1) ==")
# The gauge-invariant content of the connection is the pair (W_F, W_C) in U(1)^2 (S1 sec4).
# Question nobody in the record asked: what is the ORDER of the subgroup it generates?
def order(z, cap=10**6):
    w = z
    for k in range(1, cap+1):
        if abs(w-1) < 1e-12: return k
        w *= z
    return None
print(f"  ord(W_F) = ord(-1)  = {order(WF)}")
print(f"  ord(W_C) = ord(-i)  = {order(WC)}")
# subgroup of U(1) generated by both
gen = set()
for i in range(1,9):
    for j in range(1,9):
        gen.add(round(np.angle(WF**i * WC**j)/(np.pi/4)) % 8)
print(f"  <W_F, W_C> as a subgroup of U(1): order {len(gen)}  (elements at multiples of pi/4: {sorted(gen)})")
print(f"  <W_F,W_C> = <-i> = Z_4 :  {abs(WF - WC**2) < 1e-12}   (W_F == W_C^2)")
print()
print("  ==> S1's PUBLISHED CONNECTION IS OF FINITE ORDER 4.")
print("      Its orbit in T^2 is 4 points, not a dense line and not even a subtorus.")
