"""T-20: RECORD-LEVEL HOLONOMY, on three records, with every operator COMPUTED.

Criterion H-9 (the principal): gravity emerging from Gamma looks like a stable, path-dependent
mismatch among records --  H_ABCD = (G_AB G_BD)(G_AC G_CD)^-1, with H = I flat.

Transport between records = the record's own admissible writer (C-13). Two chains between the same
endpoints then differ exactly when the writers fail to commute, so the question is whether THE
HOLONOMY GROUP GENERATED BY THE WRITERS IS ABELIAN."""
import sys, itertools, numpy as np
sys.path.insert(0,'/Users/bgm/MB Work/where-atoms-come-from/model')
from record_model import RecordModel, symplectic_logicals, xz_to_matrix
def say(*a): print(*a); sys.stdout.flush()
def s2xz(s,n): return [1 if c in 'XY' else 0 for c in s]+[1 if c in 'ZY' else 0 for c in s]
say("="*100); say("T-20   RECORD-LEVEL HOLONOMY -- DOES TRANSPORT AROUND A RECORD LOOP CLOSE?"); say("="*100)
CAR=[("[[8,3,2]]  three records", 8, ['XXXXXXXX','ZZZZZZZZ','ZZZZIIII','ZZIIZZII','ZIZIZIZI']),
     ("[[4,2,2]]  two records",   4, ['XXXX','ZZZZ'])]
for nm,n,gens in CAR:
    S=[s2xz(g,n) for g in gens]
    pairs=symplectic_logicals(S,n)
    Sm=[xz_to_matrix(v,n) for v in S]; H=-sum(Sm); N=2**n
    Zs=[xz_to_matrix(a,n) for a,b in pairs]; Xs=[xz_to_matrix(b,n) for a,b in pairs]
    ok=all(np.linalg.norm(A@H-H@A)<1e-9 for A in Zs+Xs) and \
       all(np.linalg.norm(Zs[i]@Xs[i]+Xs[i]@Zs[i])<1e-9 for i in range(len(pairs)))
    say(f"\n  {nm}   dim {N}   records {len(pairs)}   operators verified: {ok}")
    if not ok: say("    VERIFICATION FAILED -- not reporting"); continue
    if len(pairs)<3:
        say("    fewer than three records: PATH COMPARISON IS NOT POSSIBLE here, by the criterion's")
        say("    own terms. Two records give relation, not a loop. Reported, not measured.")
        continue
    # HOLONOMY IS A CLOSED LOOP. v1 compared chains with DIFFERENT endpoints -- A->B against
    # A->C -- which are simply two different operators, and it reported 12 spurious CURVED while
    # the writer commutators were all zero. The output contradicted itself and the enumeration was
    # the error. The genuine object is the loop A->B->A^-1->B^-1, the group commutator.
    say(f"    {'closed loop':<22}{'||H - I||':>13}{'verdict':>10}")
    Ident=np.eye(N); tot=curved=0; worst=0.0; lbl='ABC'
    for (i,j) in itertools.combinations(range(3),2):
        Hol = Xs[i] @ Xs[j] @ np.linalg.inv(Xs[i]) @ np.linalg.inv(Xs[j])
        dev=float(np.linalg.norm(Hol-Ident)); tot+=1; curved += dev>1e-9; worst=max(worst,dev)
        say(f"    {lbl[i]+'->'+lbl[j]+'->'+lbl[i]+'->'+lbl[j]:<22}{dev:>13.3e}"
            f"{('CURVED' if dev>1e-9 else 'FLAT'):>10}")
    # and the three-record loop the criterion actually names: A -> {B,C} -> D, two chains, same ends
    Hol3 = (Xs[0]@Xs[1]) @ np.linalg.inv(Xs[1]@Xs[0])
    d3=float(np.linalg.norm(Hol3-Ident))
    say(f"    {'A->B->D vs A->C->D':<22}{d3:>13.3e}{('CURVED' if d3>1e-9 else 'FLAT'):>10}")
    say(f"    {tot} closed loops;  close exactly: {tot-curved};  fail to close: {curved};  worst {worst:.3e}")
    # the holonomy group
    say(f"    writer commutators ||[X_i,X_j]||: "
        f"{max(np.linalg.norm(Xs[i]@Xs[j]-Xs[j]@Xs[i]) for i in range(3) for j in range(3)):.3e}")
    say(f"    -> the holonomy group generated by the writers is "
        f"{'ABELIAN' if max(np.linalg.norm(Xs[i]@Xs[j]-Xs[j]@Xs[i]) for i in range(3) for j in range(3))<1e-9 else 'NON-ABELIAN'}")
say("")
say("="*100)
say("  READ: every loop closes exactly. Our records are logical operators of an ABELIAN stabiliser")
say("  code and their writers commute, so transport is path-INDEPENDENT and the record geometry is")
say("  FLAT. This is a NULL for the criterion, and it is informative: curvature needs transport whose")
say("  composition depends on order in a way no relabelling removes -- a NON-ABELIAN connection.")
