# core_w20r.py -- LANE W20_R_LEDGER.  THE MACHINERY.  No arm is defined in this file.
#
# CONVENTIONS INHERITED VERBATIM FROM W-19 / LANE_W20_PRE (pin_carrier.py header):
#   Z_2 on each link.  Z|j> = (-1)^j |j>,  X|j> = |j+1 mod 2>.
#   G_v = prod_{l incident to v} X_l.   PHYSICAL sector: G_v = eta_v, eta_v in {+1,-1}.
#   W_z = prod_{l in z} Z_l for z in the GF(2) cycle space.
#   H = -(1/g2) sum_{p in PLAQ} W_p - g2 sum_l X_l.
#
# WHAT THIS FILE PROVIDES, AND WHY EACH PIECE IS FORCED RATHER THAN CHOSEN:
#
# 1. THE EFFECTIVE OPERATOR SPACE.  A gauge-invariant Pauli string is O(a,b) = i^{|a&b|} X^a Z^b
#    with b in Z_1 (cycle space).  Proof: Z^b G_v Z^b = (-1)^{<b,star(v)>} G_v, so Z^b preserves
#    the sector iff b annihilates every star, iff b in ker(d) = Z_1.  X^a always commutes with G_v.
#    ON THE PHYSICAL SECTOR two strings are the SAME OPERATOR up to sign iff b = b' and
#    a + a' in B^1 (the cocycle space), because X^{delta A} = prod_{v in A} eta_v is a SCALAR.
#    So the effective label space is (GF(2)^L / B^1) x Z_1 = GF(2)^5 x GF(2)^5 -- exactly 2^10 =
#    32^2 operators, i.e. all of B(H_phys).  Verified in the run.
#
# 2. THE SYMPLECTIC FORM.  omega((a,b),(a',b')) = |a&b'| + |a'&b| mod 2.  It DESCENDS to the
#    quotient because <delta A, b> = 0 for every b in Z_1 (mutual annihilators).  Asserted in code.
#
# 3. ALGEBRAIC ENTROPY.  For a *-subalgebra A spanned by Pauli strings whose effective label set
#    is a GF(2) subspace W:  let R = radical of omega|_W (dim r) and let W/R be symplectic of
#    dim 2s.  Then A = (+)_{k=1..2^r} M_{2^s}, dim A = 2^{r+2s}, max entropy r+s bits.
#    The 2^r minimal central projections are P_k = prod_j (I + s_j g_j)/2 over a Hermitian basis
#    g_1..g_r of R.  p_k = <psi|P_k|psi>.  Inside block k the algebra is the full s-qubit Pauli
#    algebra generated by Hermitian lifts x_1,z_1,...,x_s,z_s of a symplectic basis; the map
#    O_{ab} = i^{a.b} x^a z^b  |-->  sigma_{ab} = i^{a.b} X^a Z^b  is a group isomorphism because
#    the relations (squares = I, commutation form) are identical.  Hence
#         rho_k = 2^{-s} sum_{ab} c_{ab} sigma_{ab},   c_{ab} = <psi|O_{ab} P_k|psi> / p_k
#    and  S(rho|A) = H({p_k}) + sum_k p_k S(rho_k).   Reduces to Shannon when s = 0 and to the
#    ordinary von Neumann entropy when r = 0 and A = B(H).  ALL OF THIS IS VERIFIED NUMERICALLY
#    in the run (rho_k Hermitian, PSD, trace 1; S(B(H)) = 0 on a pure state).
#
# 4. THE MUTUAL INFORMATION.  I(A:B) = S(rho|A) + S(rho|B) - S(rho|A v B) with A v B the algebra
#    generated by both, i.e. label space W_A + W_B (GF(2) SUM, not the algebra of the union link
#    set: JOIN != UNION, and the gap is printed where it occurs).
#
# NOTHING IN THIS FILE KNOWS ABOUT ANY ARM, ANY COUPLING VALUE, OR ANY SECTOR.

import numpy as np, itertools, math

# ------------------------------------------------------------------ THE CARRIER (byte-identical)
V_N = 8
EDGES = [(0, 7), (0, 1), (0, 2), (1, 2), (1, 3), (2, 3),
         (3, 4), (4, 5), (4, 6), (5, 6), (5, 7), (6, 7)]
L = len(EDGES)

STAR = [0] * V_N
for _i, (_a, _b) in enumerate(EDGES):
    STAR[_a] |= 1 << _i
    STAR[_b] |= 1 << _i


def pop(m):
    return bin(m).count("1")


def bits(m, n=L):
    return [i for i in range(n) if m >> i & 1]


def dpartial(mask):
    r = 0
    for i in bits(mask):
        a, b = EDGES[i]
        r ^= (1 << a) ^ (1 << b)
    return r


CYC = [m for m in range(1 << L) if dpartial(m) == 0]          # 32 cycles
CYCSET = set(CYC)


# ------------------------------------------------------------------ GF(2)
def gf2_rref(vs):
    """Return {pivot: vector} in reduced row echelon form."""
    b = {}
    for v in vs:
        x = v
        for p in sorted(b, reverse=True):
            if x >> p & 1:
                x ^= b[p]
        if x:
            p = x.bit_length() - 1
            for q in list(b):
                if b[q] >> p & 1:
                    b[q] ^= x
            b[p] = x
    return b


def gf2_red(x, basis):
    """Canonical representative of x modulo span(basis).  LINEAR."""
    for p in sorted(basis, reverse=True):
        if x >> p & 1:
            x ^= basis[p]
    return x


def gf2_span(basis_vals):
    out = {0}
    for b in basis_vals:
        out |= {x ^ b for x in out}
    return sorted(out)


COCYC_BASIS = gf2_rref(STAR)                                  # B^1, dim 7
COCYC = set(gf2_span(list(COCYC_BASIS.values())))             # 128 elements


# ------------------------------------------------------------------ string labels
# label = a | (b << L)   in 2L = 24 bits
def mk(a, b):
    return a | (b << L)


def sa(v):
    return v & ((1 << L) - 1)


def sb(v):
    return v >> L


def omega(u, v):
    return (pop(sa(u) & sb(v)) + pop(sa(v) & sb(u))) & 1


# N = the SCALAR subspace on the physical sector: (delta A, 0).  Empty for the unconstrained space.
N_PHYS = gf2_rref([mk(m, 0) for m in STAR])
N_FREE = {}


def symplectic_decompose(vecs):
    """vecs: GF(2) vectors already reduced mod N.  Returns (radical_basis, [(x,z), ...])."""
    B = gf2_rref([v for v in vecs if v])
    rem = list(B.values())
    pairs = []
    while True:
        found = None
        for i in range(len(rem)):
            for j in range(i + 1, len(rem)):
                if omega(rem[i], rem[j]):
                    found = (i, j)
                    break
            if found:
                break
        if not found:
            break
        i, j = found
        x, z = rem[i], rem[j]
        rest = [w for k, w in enumerate(rem) if k not in (i, j)]
        rest = [w ^ (x if omega(w, z) else 0) ^ (z if omega(w, x) else 0) for w in rest]
        rest = [w for w in rest if w]
        rem = list(gf2_rref(rest).values())
        pairs.append((x, z))
    return rem, pairs


# ------------------------------------------------------------------ BACKENDS
class PhysSector:
    """The 32-dimensional physical sector for a given charge pattern eta.

    Basis |psi_c> = 128^{-1/2} sum_A eta^A |c + delta A>, one per coset of B^1.
    G_v |psi_c> = eta_v |psi_c>  (checked in the run).
    """
    name = "PHYS"

    def __init__(self, eta):
        assert len(eta) == V_N
        assert int(np.prod(eta)) == 1, "prod eta must be +1 (delta V = 0)"
        self.eta = list(eta)
        # the 128 (cut mask -> scalar) pairs
        cut_sign = {}
        for A in range(1 << V_N):
            m = 0
            s = 1
            for v in range(V_N):
                if A >> v & 1:
                    m ^= STAR[v]
                    s *= eta[v]
            if m in cut_sign:
                assert cut_sign[m] == s, "inconsistent eta -- prod eta != +1"
            cut_sign[m] = s
        assert len(cut_sign) == 128
        self.cut_sign = cut_sign
        orb = [-1] * (1 << L)
        sgn = [0] * (1 << L)
        reps = []
        for c in range(1 << L):
            if orb[c] >= 0:
                continue
            k = len(reps)
            reps.append(c)
            for m, s in cut_sign.items():
                orb[c ^ m] = k
                sgn[c ^ m] = s
        self.orb = np.array(orb, dtype=np.int64)
        self.sgn = np.array(sgn, dtype=np.float64)
        self.reps = np.array(reps, dtype=np.int64)
        self.dim = len(reps)
        assert self.dim == 32
        # X^a action cache: perm[i] = orb[rep_i ^ a], ph[i] = sgn[rep_i ^ a]
        self._xc = {}
        self._zc = {}

    def xperm(self, a):
        if a not in self._xc:
            t = self.reps ^ a
            self._xc[a] = (self.orb[t], self.sgn[t])
        return self._xc[a]

    def zsign(self, b):
        if b not in self._zc:
            self._zc[b] = np.array([1.0 - 2.0 * (pop(b & int(c)) & 1) for c in self.reps])
        return self._zc[b]

    def apply(self, v, a, b):
        """Apply the HERMITIAN string O(a,b) = i^{|a&b|} X^a Z^b to vector v."""
        w = v * self.zsign(b)
        if a:
            perm, ph = self.xperm(a)
            out = np.zeros_like(w)
            np.add.at(out, perm, ph * w)
            w = out
        m = pop(a & b) & 3
        if m:
            w = w * (1j ** m)
        return w


class FreeSpace:
    """The unconstrained 2^12 = 4096 link Hilbert space.  NO Gauss projection."""
    name = "FREE"

    def __init__(self):
        self.dim = 1 << L
        self.idx = np.arange(1 << L, dtype=np.int64)
        self._zc = {}

    def zsign(self, b):
        if b not in self._zc:
            pc = np.array([1.0 - 2.0 * (pop(b & int(c)) & 1) for c in range(1 << L)])
            self._zc[b] = pc
        return self._zc[b]

    def apply(self, v, a, b):
        w = v * self.zsign(b)
        if a:
            w = w[self.idx ^ a]
        m = pop(a & b) & 3
        if m:
            w = w * (1j ** m)
        return w


# ------------------------------------------------------------------ entropies
def vn_entropy(rho):
    w = np.linalg.eigvalsh((rho + rho.conj().T) / 2)
    w = np.clip(w.real, 0.0, None)
    w = w[w > 1e-13]
    if w.size == 0:
        return 0.0
    return float(-(w * np.log2(w)).sum())


def shannon(ps):
    p = np.array([x for x in ps if x > 1e-13])
    if p.size == 0:
        return 0.0
    return float(-(p * np.log2(p)).sum())


_PAULI_CACHE = {}


def pauli_sigma(s, al, be):
    """sigma_{al,be} = i^{al.be} X^al Z^be on s abstract qubits."""
    key = (s, al, be)
    if key in _PAULI_CACHE:
        return _PAULI_CACHE[key]
    X = np.array([[0, 1], [1, 0]], dtype=complex)
    Z = np.array([[1, 0], [0, -1]], dtype=complex)
    I = np.eye(2, dtype=complex)
    M = np.array([[1.0 + 0j]])
    for j in range(s):
        f = I
        if al >> j & 1:
            f = f @ X
        if be >> j & 1:
            f = f @ Z
        M = np.kron(M, f)
    M = M * (1j ** (pop(al & be) & 3))
    _PAULI_CACHE[key] = M
    return M


class Algebra:
    """A *-subalgebra of B(H) spanned by gauge-invariant Pauli strings."""

    def __init__(self, backend, gens, Nb, label=""):
        self.backend = backend
        self.label = label
        self.Nb = Nb
        red = [gf2_red(g, Nb) for g in gens]
        # sanity: omega must descend
        for p, nv in Nb.items():
            for g in red:
                assert omega(nv, g) == 0, "omega does not descend -- a non-cycle b slipped in"
        self.W = gf2_rref([v for v in red if v])
        self.n = len(self.W)
        rad, pairs = symplectic_decompose(list(self.W.values()))
        self.rad = rad
        self.pairs = pairs
        self.r = len(rad)
        self.s = len(pairs)
        assert self.r + 2 * self.s == self.n, (self.r, self.s, self.n)
        self.dim = 1 << self.n
        self.maxent = self.r + self.s

    def entropy(self, psi, tol=1e-11, want_detail=False):
        be = self.backend
        # build the 2^r branch vectors  P_k|psi>  by a binary tree over the radical generators
        branches = [(0, psi)]
        for g in self.rad:
            a, b = sa(g), sb(g)
            nb = []
            for (k, v) in branches:
                gv = be.apply(v, a, b)
                nb.append((k << 1, 0.5 * (v + gv)))
                nb.append(((k << 1) | 1, 0.5 * (v - gv)))
            branches = nb
        ps = []
        Ss = []
        detail = []
        for (k, phi) in branches:
            p = float(np.vdot(phi, phi).real)
            if p <= tol:
                ps.append(0.0)
                continue
            ps.append(p)
            if self.s == 0:
                Ss.append((p, 0.0))
                detail.append((k, p, None))
                continue
            d = 1 << self.s
            rho = np.zeros((d, d), dtype=complex)
            for al in range(d):
                for bt in range(d):
                    w = phi
                    for j in range(self.s):
                        if bt >> j & 1:
                            zg = self.pairs[j][1]
                            w = be.apply(w, sa(zg), sb(zg))
                    for j in range(self.s):
                        if al >> j & 1:
                            xg = self.pairs[j][0]
                            w = be.apply(w, sa(xg), sb(xg))
                    ph = 1j ** (pop(al & bt) & 3)
                    c = complex(np.vdot(phi, w)) * ph / p
                    rho = rho + c * pauli_sigma(self.s, al, bt)
            rho = rho / d
            tr = complex(np.trace(rho))
            ev = np.linalg.eigvalsh((rho + rho.conj().T) / 2).real
            assert abs(tr - 1.0) < 1e-8, ("block trace", tr, self.label)
            assert ev.min() > -1e-8, ("block not PSD", ev.min(), self.label)
            assert np.linalg.norm(rho - rho.conj().T) < 1e-8, ("block not Hermitian", self.label)
            Ss.append((p, vn_entropy(rho)))
            detail.append((k, p, ev))
        S = shannon(ps) + sum(p * s for (p, s) in Ss)
        if want_detail:
            return S, ps, detail
        return S


def join(A, B):
    return Algebra(A.backend, list(A.W.values()) + list(B.W.values()), A.Nb,
                   label="(%s v %s)" % (A.label, B.label))


def MI(psi, A, B, AB=None):
    if AB is None:
        AB = join(A, B)
    return A.entropy(psi) + B.entropy(psi) - AB.entropy(psi), AB


# ------------------------------------------------------------------ algebra builders
def cycles_inside(T):
    return [z for z in CYC if z and (z & ~T) == 0]


def alg_links(backend, T, Nb, label):
    """The gauge-invariant Pauli algebra supported on link set T:
       X^a for a subset of T ; Z^z for z a CYCLE inside T."""
    gens = [mk(1 << l, 0) for l in bits(T)]
    zb = gf2_rref(cycles_inside(T))
    gens += [mk(0, z) for z in zb.values()]
    return Algebra(backend, gens, Nb, label)


def D_int(T):
    """GF(2) dim of {delta A : delta A subset of T}.  Gauss constraints acting INSIDE T alone.
    NOT the pre-registration's D(F) -- kept because it is the right number for A_T's own radical."""
    return len(gf2_rref([m for m in COCYC if m and (m & ~T) == 0]))


def D_forced(S_T, F_T):
    """THE PRE-REGISTRATION'S VACUITY NUMBER, verbatim:
         D(F) = GF(2) dim of { delta A' & S : delta A' subset of S u F }.
    It counts the bits of S's ELECTRIC content that the Gauss law forces F to know, for EVERY
    state, coupling, sector and history.  D(F) bits of I(A_S : A_F) CANNOT FAIL to be present."""
    U = S_T | F_T
    return len(gf2_rref([(m & S_T) for m in COCYC if m and (m & ~U) == 0]))


# ------------------------------------------------------------------ Hamiltonian
PLAQ = [0b1110, 0b111000, 0b1110000000, 0b111000000000,
        (1 << 0) | (1 << 1) | (1 << 4) | (1 << 6) | (1 << 7) | (1 << 10)]
# = [1,2,3] , [3,4,5] , [7,8,9] , [9,10,11] , [0,1,4,6,7,10]
for _p in PLAQ:
    assert dpartial(_p) == 0, "a plaquette is not a cycle"


def H_matrix(backend, g2, plaq=None):
    """Dense H in the backend basis.  Only used for the 32-dim sector."""
    plaq = PLAQ if plaq is None else plaq
    d = backend.dim
    H = np.zeros((d, d), dtype=complex)
    for i in range(d):
        e = np.zeros(d, dtype=complex)
        e[i] = 1.0
        col = np.zeros(d, dtype=complex)
        for p in plaq:
            col -= (1.0 / g2) * backend.apply(e, 0, p)
        for l in range(L):
            col -= g2 * backend.apply(e, 1 << l, 0)
        H[:, i] = col
    assert np.linalg.norm(H - H.conj().T) < 1e-10
    return (H + H.conj().T) / 2


def H_matvec(backend, g2, v, plaq=None):
    plaq = PLAQ if plaq is None else plaq
    out = np.zeros_like(v)
    for p in plaq:
        out -= (1.0 / g2) * backend.apply(v, 0, p)
    for l in range(L):
        out -= g2 * backend.apply(v, 1 << l, 0)
    return out


def lanczos_ground(backend, g2, plaq=None, m=200, seed=7, restarts=3):
    """Ground state of H on a backend too big for eigh.  Returns (E0, psi)."""
    rng = np.random.default_rng(seed)
    v = rng.normal(size=backend.dim) + 0j
    v /= np.linalg.norm(v)
    E0 = None
    for _ in range(restarts):
        Q = [v]
        al, bt = [], []
        for j in range(m):
            w = H_matvec(backend, g2, Q[-1], plaq)
            a = complex(np.vdot(Q[-1], w)).real
            al.append(a)
            w = w - a * Q[-1]
            if j > 0:
                w = w - bt[-1] * Q[-2]
            for q in Q:                                  # full reorthogonalisation
                w = w - np.vdot(q, w) * q
            b = float(np.linalg.norm(w))
            if b < 1e-12:
                break
            bt.append(b)
            Q.append(w / b)
        T = np.diag(al) + np.diag(bt[:len(al) - 1], 1) + np.diag(bt[:len(al) - 1], -1)
        ev, evec = np.linalg.eigh(T)
        E0 = ev[0]
        v = sum(evec[i, 0] * Q[i] for i in range(len(al)))
        v = v / np.linalg.norm(v)
    return E0, v
