#!/usr/bin/env python3
# LANE W08 / M3 — REFUTER 2 — LENS: SCOPE.
# script 3: TWO THINGS THAT BREAK ON A SPECTATOR CARRIER AND THAT THE LANE DID NOT REPORT.
#
# (A) THE FORMATION CRITERION'S ENUMERATION.  The register's W-02 row carries the corrected
#     criterion as a FIVE-ROW TABLE over K1's support classes.  On a carrier with a spectator
#     vertex the support lattice has 15 non-empty classes, and one of the new never-forming
#     families -- support {spectator, shared}, W_C = W_F -- is DISJOINT from all four families
#     COR-B exhibits.  COR-B's "four exhibited families of non-trivial connections never form"
#     is a K1 count.
#
# (B) THE DOUBLE-DEGENERACY LOCUS.  M3-F5/F6 locate the state half of the Omega_N = 0 pathology
#     at "exactly three points of the simplex, the vertices of the medial triangle", one of which
#     is K1's published state.  With a spectator vertex the same locus is a ONE-PARAMETER FAMILY:
#     P factors as (a+bx)(c+dy) on the codim-1 surface p00 p11 = p10 p01, and the zero set is a
#     whole CIRCLE on the two arcs {p00=p10, p01=p11} and {p00=p01, p10=p11}.  On every state of
#     the first arc, K1's OWN PUBLISHED CONNECTION (f = pi) gives Omega_N = 0 for all N >= 1.
#
# PRECISION: (A) and (B) are decided in EXACT arithmetic -- Fraction weights and integer
# character exponents.  Floats appear only in the reported |Z_k| magnitudes, and every claimed
# EXACT ZERO is established by integer/rational identity, never by a float comparison.  (The lane
# self-flagged three separate float-standing-in-for-an-exact-zero defects; this script avoids the
# class by construction.)
import numpy as np
from fractions import Fraction as Fr
from itertools import combinations

L = []
def out(s=""):
    print(s); L.append(s)

out("=" * 100)
out("R2-3  THE FORMATION FAMILIES AND THE DEGENERACY LOCUS, ON A CARRIER WITH A SPECTATOR VERTEX")
out("=" * 100)
out("numpy %s ; EXACT rational/integer arithmetic for every zero and every group; doubles only"
    % np.__version__)
out("for reported magnitudes.")
out()

# ==================================================================== (A) formation families
out("(A) THE SUPPORT LATTICE.  Characters, as integer exponent vectors (i,j) meaning u^i v^j:")
out("      class 00 (spectator, in NEITHER loop) -> chi = 1     = u^0 v^0")
out("      class 10 (face only)                  -> chi = u     = u^1 v^0")
out("      class 01 (cycle only)                 -> chi = v     = u^0 v^1")
out("      class 11 (shared, K1's root)          -> chi = uv    = u^1 v^1")
out("    G = closed subgroup generated by { chi_a/chi_b : a,b in S }  (S3 audit sec4.4).")
out("    G = {1}  iff  ALL characters on the support coincide  iff  no formation, ever.")
out()
CH = {"00": (0, 0), "10": (1, 0), "01": (0, 1), "11": (1, 1)}
NAMES = ["00", "10", "01", "11"]


def lattice_of(S):
    """Integer lattice of exponent DIFFERENCES over the support; returned as a reduced basis."""
    base = CH[S[0]]
    rows = [(CH[a][0] - base[0], CH[a][1] - base[1]) for a in S[1:]]
    rows = [r for r in rows if r != (0, 0)]
    return rows


def trivial_condition(S):
    rows = lattice_of(S)
    if not rows:
        return "G = {1} ALWAYS  (|S| = 1)"
    conds = []
    for (i, j) in rows:
        t = []
        if i:
            t.append(("u" if i == 1 else "u^%d" % i))
        if j:
            t.append(("v" if j == 1 else "v^%d" % j))
        conds.append("*".join(t) + " = 1")
    return "G = {1} iff  " + "  and  ".join(sorted(set(conds)))


out("    ALL 15 NON-EMPTY SUPPORTS ON A FOUR-CLASS CARRIER (K1S).  Rows marked [K1] are the five")
out("    the register's W-02 row lists; rows marked [NEW] cannot occur on K1 (they need class 00).")
K1_CLASSES = {"10", "01", "11"}
new_families = []
for r in range(1, 5):
    for S in combinations(NAMES, r):
        S = list(S)
        onK1 = set(S) <= K1_CLASSES
        tag = "[K1]" if onK1 else "[NEW]"
        cond = trivial_condition(S)
        out("      %-4s S = %-18s  %s" % (tag, "{" + ",".join(S) + "}", cond))
        if not onK1 and len(S) > 1:
            new_families.append((tuple(S), cond))
out()
out("    THE NEVER-FORMING SET, AS CURVES IN THE (f,c) TORUS  (u = e^{-if}, v = e^{ic}):")
out("      on K1  : {f = 0} u {c = 0} u {c = -f}        [u=1, v=1, u=v i.e. W_F W_C = 1]")
out("               plus the three one-point supports.   -> COR-B's 'four exhibited families'")
out("      on K1S : the same three curves, PLUS {c = f}  [uv = 1, support {00,11}]")
out("               plus the four one-point supports.")
out("    {c = f} IS DISJOINT FROM ALL THREE K1 CURVES away from the origin: at f = c = 1 rad,")
out("    W_F = e^{i} != 1, W_C = e^{i} != 1, W_F W_C = e^{2i} != 1.  A NON-TRIVIAL CURVATURE AND")
out("    A NON-TRIVIAL FLAT HOLONOMY, AND NOTHING EVER FORMS.")
out()

# ---- realise it on K1S, with the literal matrix action, and check |Z_k| = 1 exactly in structure
out("    REALISED ON K1S.  Ready state supported on {v5 (class 00), v0 (class 11)}:")
out("      |s_{v5}|^2 = 1/2, |s_{v0}|^2 = 1/2, all other vertices 0.  Connection f = c = 1 rad.")
cls_K1S = [(1, 1), (1, 0), (1, 0), (0, 1), (0, 1), (0, 0)]
s = np.zeros(6, dtype=complex)
s[0] = np.sqrt(0.5)
s[5] = np.sqrt(0.5)
f = c = 1.0
WF, WC = np.exp(1j * f), np.exp(1j * c)
mags = []
for k in range(1, 21):
    a = s.copy()
    b = s.copy()
    for v, (inF, inC) in enumerate(cls_K1S):
        if inF:
            a[v] *= WF ** k
        if inC:
            b[v] *= WC ** k
    mags.append(abs(np.vdot(a, b)))
out("      literal 6x6 matrix action, k = 1..20:  min |Z_k| = %.15f , max |Z_k| = %.15f"
    % (min(mags), max(mags)))
out("      EXACT REASON (not a float observation): Z_k = p00 + p11 (uv)^k and uv = e^{i(c-f)} = 1")
out("      identically when c = f, so Z_k = p00 + p11 = 1 for EVERY k and |Omega_N| = 1 for all N.")
out("      m(P) MEANWHILE = m(1/2 + (1/2) xy) = log(1/2) = %.12f < 0, which would predict"
    % np.log(0.5))
out("      exponential decay.  N1's 'lambda = m(P)' is a FULL-TORUS statement; the orbit here is")
out("      the single point (u,v) with uv = 1 and never leaves the subtorus {xy = 1}, on which")
out("      |P| == 1.  Same failure mode as the ERRATUM AGAINST W-02 (subtorus vs full torus), on")
out("      a family of connections that DOES NOT EXIST ON K1.")
out()
out("    *** SCOPE CORRECTION TO THE REGISTER, not to this lane's own findings: the W-02 row's")
out("    *** five-row support table and COR-B's 'four families' are K1 enumerations presented as")
out("    *** the corrected criterion.  The criterion (G != {1}) generalises verbatim; its")
out("    *** enumeration does not.  M3-F10 answers the silent-use question with 'W-03's multiset")
out("    *** theorem is safe / N1's polynomial is safe' and does not look at W-02's table.")
out()

# ==================================================================== (B) degeneracy locus
out("(B) THE ONE-DIMENSIONAL-ZERO-SET LOCUS.  M3-F5: 'The 1-dimensional zero set occurs at exactly")
out("    three points of the simplex, the vertices of the medial triangle.'  TRUE AT THREE CLASSES.")
out("    AT FOUR CLASSES IT IS A CURVE.  Derivation:")
out("      Newton polygon of p00 + p10 x + p01 y + p11 xy is the UNIT SQUARE = [0,1]x{0} + {0}x[0,1],")
out("      so P factors iff it factors as (a + b x)(c + d y), iff p00 p11 = p10 p01.")
out("      A factor a + b x vanishes somewhere on |x| = 1 iff |a| = |b|.  Hence the zero set of P")
out("      contains a CIRCLE iff  (p00 = p10 and p01 = p11)  or  (p00 = p01 and p10 = p11).")
out("      Each is a ONE-PARAMETER family in the 3-simplex; the two arcs meet at (1/4,1/4,1/4,1/4).")
out("      At p00 = 0 the first forces p10 = 0 and the second forces p10 = p11 with p10 = 0 -- i.e.")
out("      exactly the two-class balanced corners.  M3-F5's 'three points' is the p00 = 0 shadow")
out("      of a curve.  Codimension is 2 in BOTH cases, so this is a change of SHAPE, not of size.")
out()
out("    EXACT CHECK, rational weights, no floats.  Arc 1: p = (a,a,b,b) with 2a+2b = 1.")
out("    Take the connection f = pi (K1's OWN published curvature, S1 sec6) so u = -1 EXACTLY,")
out("    and ANY c.  Then Z_k = (1 + u^k)(a + b v^k) and for every ODD k the first factor is")
out("    EXACTLY 0, so Omega_N = 0 for every N >= 1 -- the M3-F6 pathology, on a whole arc.")
hdr = "      %-22s %-14s %-16s %-22s" % ("state (p00,p10,p01,p11)", "m(P) exact", "Z_1 (exact)", "Omega_N, N>=1")
out(hdr)
for num in (1, 2, 3, 4, 5):
    a = Fr(num, 20)
    b = Fr(1, 2) - a
    if b < 0:
        continue
    p = (a, a, b, b)
    # u = -1 exactly.  Z_1 = p00 + p10*(-1) + p01*v + p11*(-1)*v = (a-a) + v(b-b) = 0 EXACTLY,
    # for EVERY v.  This is an identity in the integers, not a float evaluation.
    Z1_is_zero = (p[0] - p[1] == 0) and (p[2] - p[3] == 0)
    mp = np.log(float(max(a, b))) if max(a, b) > 0 else float("-inf")
    out("      %-22s %-14.9f %-16s %-22s"
        % (str(tuple(str(x) for x in p)), mp, "0 (exactly)" if Z1_is_zero else "nonzero",
           "0 for all N >= 1" if Z1_is_zero else "-"))
out("      (m(P) = m((1+x)(a+by)) = m(1+x) + m(a+by) = 0 + log max(a,b), an EXACT closed form.)")
out("      Every row: m(P) finite and negative, actual per-cell rate -infinity.  On K1 this")
out("      mismatch happens at ONE state; on K1S it happens on a CONTINUUM, at the same connection.")
out()

# a strict control: move OFF the arc and the exact zero disappears
out("    CONTROL (one variable moves: the state leaves the arc, connection held at f = pi):")
for p in [(Fr(1, 4), Fr(1, 4), Fr(1, 4), Fr(1, 4)),
          (Fr(1, 4), Fr(1, 5), Fr(1, 4), Fr(3, 10)),
          (Fr(3, 10), Fr(1, 5), Fr(1, 4), Fr(1, 4)),
          (Fr(2, 5), Fr(1, 10), Fr(1, 5), Fr(3, 10))]:
    onarc = (p[0] == p[1] and p[2] == p[3]) or (p[0] == p[2] and p[1] == p[3])
    # with u = -1 exactly:  Z_k(odd) = (p00-p10) + v^k (p01-p11)   -- exact rational coefficients
    A = p[0] - p[1]
    B = p[2] - p[3]
    # odd k:  Z_k = A + v^k B  with A,B EXACT rationals.  Three exact regimes:
    if A == 0 and B == 0:
        verdict = "Z_k == 0 for EVERY c  (the whole circle of connections)"
    elif abs(A) == abs(B):
        verdict = "Z_k = 0 only for isolated c  (needs v^k = -A/B)"
    else:
        verdict = "|Z_k| >= %s > 0 for EVERY c  (no zero at all)" % abs(abs(A) - abs(B))
    out("      p = %-38s on an arc? %-5s  %s"
        % (str(tuple(str(x) for x in p)), onarc, verdict))
out("      => the exact zero at odd k is a property of the ARC, not of f = pi alone.  The two")
out("         halves of the degeneracy are still a PAIR (M3-F7's C7 survives); what changes is")
out("         that the state half is now a curve rather than an isolated point.")
out()
out("DONE.")
open("r2_3_formation_families_and_degeneracy.OUT.txt", "w").write("\n".join(L) + "\n")
