"""
b3 -- THE GAUGE PROBLEM.  THIS IS THE ACTUAL RESIDUE.

In a gauge theory the physical algebra does not factorise into system and environment, so "I(S:F)"
is not defined until a BOUNDARY ALGEBRA is chosen.  This file enumerates the choices on the carrier,
computes I(S:F) under EACH, and asks whether the answer depends on the choice.

THE CHOICES, each a subalgebra assigned to a link region R, listed from largest to smallest.
  C1 EXT   extended Hilbert space (Buividovich-Polikarpov; Donnelly).  A_R = the FULL matrix algebra
           on the links of R.  Gauge invariance is imposed on the STATE, never on the cut.
  C5 MAG   magnetic centre (Casini-Huerta-Rosabal).  The Gauss law is DROPPED at the boundary
           vertices of R, so boundary holonomies enter A_R.
  C3 FULL  the full gauge-invariant region algebra: every gauge-invariant Pauli SUPPORTED in R.
  C2 ELEC  electric centre: only the gauge-invariant electric operators X_l, l in R.  Abelian.
  C6 DRESS dressed / Wilson-line choice (Donnelly-Freidel): electric operators in R together with
           gauge-invariant holonomies closed through a FIXED reference link.

DIFF THE ARMS: every choice is one line -- a different GENERATOR LIST fed to the SAME
algebra-entropy function.  The generator lists are printed below so the diff is on the page.
C1's numbers are computed by the reduced-density-matrix route instead, which b0 test [3] verified
agrees with the algebra route to 1e-8 (the algebra route costs 4^k and is unusable at k = 8).

ISOLATION LEDGER
  held fixed : carrier, state, system region, fragment list, delta.
  moved      : THE ALGEBRA CHOICE, and nothing else.
  KNOWN COLLAPSES, recorded rather than hidden:  on theta_L every vertex is a boundary vertex of
  every proper region, so C5 MAG returns the SAME generator list as C1 EXT there -- those two arms
  are NOT independent on theta and are marked (=C1).  The wheel and fan carriers, which have
  interior vertices, are run precisely to break that degeneracy.
"""
import numpy as np, itertools
from lib_b import *

np.set_printoptions(precision=6, suppress=True)
DELTA = 0.1
REF = None      # dressing reference link, set per carrier


def gens_for(choice, car, R):
    if choice == "C1_EXT":   return gens_EXT(car, R)
    if choice == "C5_MAG":   return gens_MAG(car, R)
    if choice == "C3_FULL":  return gens_FULL(car, R)
    if choice == "C2_ELEC":  return gens_ELEC(car, R)
    if choice == "C6_DRESS": return gens_DRESS(car, R, REF)
    raise KeyError(choice)

ORDER = ["C1_EXT", "C5_MAG", "C3_FULL", "C2_ELEC", "C6_DRESS"]

def show_gens(car, R, tag):
    print(f"  generator lists for R = {R}   ({tag})")
    for ch in ORDER:
        g = gens_for(ch, car, R)
        pairs, cen = algebra_structure(g)
        print(f"     {ch:<9} {[sp_str(a, car['L']) for a in g]}"
              f"   -> algebra = 2^{len(cen)} blocks of M_2^{len(pairs)}")

def I_choice(psi, E, car, ch, S, F):
    if ch == "C1_EXT":
        return mi_ext(psi, car["L"], S, F)
    v, _ = mutual_information(E, gens_for(ch, car, S), gens_for(ch, car, F))
    return v

def H_choice(psi, E, car, ch, S):
    if ch == "C1_EXT":
        return vn_entropy(reduce_links(psi, car["L"], S))
    v, _ = algebra_entropy(E, gens_for(ch, car, S))
    return v


# =====================================================================================
print("=" * 108)
print("b3  THE GAUGE PROBLEM:  DOES THE RECORD VERDICT DEPEND ON THE BOUNDARY ALGEBRA?")
print("=" * 108)

# -------------------------------------------------------------------------------------
print("\n" + "=" * 108)
print("PART A  --  A THEOREM THAT FIXES WHAT ANY GAUGE-INVARIANT REGION ALGEBRA CAN CONTAIN")
print("=" * 108)
print("""
  A Pauli P_{x,z} commutes with the Gauss operator G_v = prod_{l ~ v} X_l  iff  z . G_v = 0 mod 2.
  The x-part is unconstrained.  Restricting to Paulis SUPPORTED IN R, the admissible z-vectors are
  exactly the GF(2) nullspace of the incidence matrix of the subgraph spanned by R -- that is, the
  CYCLE SPACE of R.  Hence:

     THEOREM (magnetic content = cycle space).  The gauge-invariant Pauli algebra supported on a
     link set R is generated by { X_l : l in R } together with the Wilson loops of the cycles
     of R.  It is ABELIAN -- purely electric -- if and only if R contains no cycle.

     COROLLARY.  If the system region is a single link, or any forest, then NO gauge-invariant
     magnetic (holonomy) observable is localised in it, whatever the carrier.  A holonomy record
     requires the system region to contain a closed loop, hence at least girth(G) links.

  INDEPENDENT CHECK: the algebra's z-dimension (from gf2_nullspace over Pauli strings) versus the
  cyclomatic number |R| - |V(R)| + components(R) computed by union-find on the graph.""")
bad = 0; tot = 0
for car in [theta(4), theta(6), fan(3), fan(4), wheel(4), wheel(5)]:
    L = car["L"]
    for r in range(1, min(L, 6) + 1):
        for R in itertools.combinations(range(L), r):
            R = list(R)
            zdim = len([g for g in gens_FULL(car, R) if g.x == 0])
            cyc = cyclomatic(car, R)
            tot += 1
            if zdim != cyc: bad += 1
print(f"  checked {tot} link subsets over 6 carriers:  mismatches = {bad}")
print("  smallest region with magnetic content, per carrier (= girth):")
for car in [theta(6), fan(3), wheel(4), wheel(5)]:
    g = min((len(R) for r in range(1, car["L"] + 1)
             for R in itertools.combinations(range(car["L"]), r) if cyclomatic(car, list(R)) > 0),
            default=None)
    print(f"     {car['name']:<10} girth = {g}")

# -------------------------------------------------------------------------------------
print("\n" + "=" * 108)
print("PART A2  --  ONE OF THE FIVE CHOICES IS NOT INDEPENDENT.  RECORDED, NOT HIDDEN.")
print("=" * 108)
print("""
  CLAIM.  On PHYSICAL states, C5 MAG and C1 EXT give the same entropy for every region R.
  PROOF.  C5 keeps exactly the Gauss operators supported INSIDE R and drops the rest, so
  A_R^MAG is the commutant, inside B(H_R), of the interior Gauss operators {G_v}.  A physical
  state has rho_R supported in the joint +1 eigenspace H_+ of those same G_v (they act only on R).
  Compressing, P_+ B(H_R) P_+ = P_+ A_R^MAG P_+ = B(H_+), and rho_R lives there, so the two
  algebras assign it the same state and the same entropy.  QED.
  CONSEQUENCE: the published choice list, evaluated on gauge-invariant states, has FEWER
  independent members than it appears to.  C5 is reported below but carries no independent weight.
  CONTROL (this could have failed): the same comparison on UNPROJECTED random states must differ.""")
diffs_phys = []; diffs_unphys = []
for car in [fan(3), fan(4), wheel(4), wheel(5), theta(6)]:
    Lc = car["L"]
    rng = np.random.default_rng(31337)
    for sd in range(3):
        psi = haar_physical(car, 1000 + sd)
        v = rng.normal(size=1 << Lc) + 1j * rng.normal(size=1 << Lc); v /= np.linalg.norm(v)
        Ep = pauli_table(psi, Lc); Eu = pauli_table(v, Lc)
        for r in (1, 2, 3):
            for R in list(itertools.combinations(range(Lc), r))[:6]:
                R = list(R)
                a, _ = algebra_entropy(Ep, gens_MAG(car, R)); b, _ = algebra_entropy(Ep, gens_EXT(car, R))
                diffs_phys.append(abs(a - b))
                a2, _ = algebra_entropy(Eu, gens_MAG(car, R)); b2, _ = algebra_entropy(Eu, gens_EXT(car, R))
                diffs_unphys.append(abs(a2 - b2))
print(f"  max |S_MAG - S_EXT| over {len(diffs_phys)} (carrier, physical state, region) triples "
      f"= {max(diffs_phys):.3e}")
print(f"  max |S_MAG - S_EXT| over {len(diffs_unphys)} UNPROJECTED states, same regions "
      f"= {max(diffs_unphys):.6f}   (nonzero: the control separates)")

print("\n" + "=" * 108)
print("PART B  --  theta_8, SYSTEM = ONE LINK.  FIVE CHOICES, SAME STATE, SAME CUT.")
print("=" * 108)
L = 8; car = theta(L); REF = 7
S = [0]; ENVF = [[e] for e in range(1, L - 1)]     # link 7 reserved as the dressing reference
print(f"carrier {car['name']}  edges={car['edges']}  gauss={car['gauss']}  dim H_phys={phys_dim(car)}")
print(f"S = {S}   fragments = {ENVF}   dressing reference link = {REF}")
print()
show_gens(car, [0], "the system region")
show_gens(car, [1], "a one-link fragment")

def elec_ghz(car):
    L = car["L"]; popc = popc_table(1 << L)
    a = np.ones(1 << L, dtype=complex); b = ((-1.0) ** popc[np.arange(1 << L)]).astype(complex)
    return project_physical(a / np.linalg.norm(a) + b / np.linalg.norm(b), car)

STATES = [("BRD_M  magnetic GHZ (|0^L>+|1^L>)/sqrt2", sym_basis_state(car, 0)),
          ("BRD_E  electric GHZ (|+^L>+|-^L>)/sqrt2", elec_ghz(car)),
          ("GS     ground state, g^2 = 0.30", ground_state(car, 0.30)[0]),
          ("GS     ground state, g^2 = 1.00", ground_state(car, 1.00)[0]),
          ("HAAR   Haar-random physical, seed 55", haar_physical(car, 55))]

for nm, psi in STATES:
    E = pauli_table(psi, L)
    print(f"\n{nm}")
    print(f"   {'choice':<10}{'H_A(S)':>9}   I(S:F) for |F| = 1..{len(ENVF)}"
          f"{'':>10}{'Rdelta':>8}{'plateau?':>10}")
    for ch in ORDER:
        HS = H_choice(psi, E, car, ch, S)
        curve = [I_choice(psi, E, car, ch, S, sum(ENVF[:m], [])) for m in range(1, len(ENVF) + 1)]
        singles = [I_choice(psi, E, car, ch, S, f) for f in ENVF]
        R = int(sum(1 for v in singles if v >= (1 - DELTA) * HS - 1e-9))
        plat = curve[:-1]
        flat = (HS > 1e-9) and all(abs(v - HS) <= DELTA * HS for v in plat) and len(plat) >= 4
        tag = ch + (" (=C1)" if ch == "C5_MAG" else "")
        print(f"   {tag:<10}{HS:9.5f}   {' '.join('%8.5f' % v for v in curve)}"
              f"{R:8d}{('YES' if flat else 'no'):>10}")

print("""
  READING.  For the MAGNETIC GHZ -- which is the g^2 -> 0 ground state of the theory, i.e. the state
  the dynamics actually produces in the strong-plaquette regime -- the extended-Hilbert-space choice
  reports a perfect redundancy plateau with R_delta = 6, and EVERY gauge-invariant choice reports
  I(S:F) = 0 for every fragment.  The verdict is not merely shifted; it is INVERTED by the choice.
  For the ELECTRIC GHZ the choices agree.  So choice-dependence is itself state-dependent, and the
  states on which it bites are exactly the ones whose record is magnetic.""")

# -------------------------------------------------------------------------------------
print("\n" + "=" * 108)
print("PART C  --  theta_10, SYSTEM = A PLAQUETTE (2 links).  NOW A_S HAS MAGNETIC CONTENT.")
print("=" * 108)
L = 10; car = theta(L); REF = None
S = [0, 1]; FR = [[2, 3], [4, 5], [6, 7], [8, 9]]
print(f"carrier {car['name']}  S = {S} (contains the cycle 0-1)   fragments = {FR}")
show_gens_order = ["C1_EXT", "C3_FULL", "C2_ELEC"]
for R, tag in [([0, 1], "system = one plaquette"), ([2, 3], "fragment = one plaquette")]:
    print(f"  generator lists for R = {R}   ({tag})")
    for ch in show_gens_order:
        g = gens_for(ch, car, R); pairs, cen = algebra_structure(g)
        print(f"     {ch:<9} {[sp_str(a, L) for a in g]}  -> 2^{len(cen)} blocks of M_2^{len(pairs)}")

def wilson_broadcast(car):
    """all four plaquette holonomies W_{2k,2k+1} perfectly correlated: a GHZ in the WILSON loops.
       branch A: every link z = 0 ;  branch B: z = 1 on links 1,3,5,7,9 -- so every W = -1."""
    L = car["L"]
    a = sym_basis_state(car, 0)
    b = sym_basis_state(car, sum(1 << i for i in range(1, L, 2)))
    return project_physical((a + b) / np.linalg.norm(a + b), car)

STATES_C = [("BRD_W  Wilson-loop GHZ: all 5 plaquette holonomies perfectly correlated",
             wilson_broadcast(car)),
            ("BRD_M  magnetic GHZ (all W = +1, deterministic)", sym_basis_state(car, 0)),
            ("HAAR   Haar-random physical, seed 66", haar_physical(car, 66))]
for nm, psi in STATES_C:
    E = pauli_table(psi, L, "direct")
    print(f"\n{nm}")
    print(f"   {'choice':<10}{'H_A(S)':>9}   I(S:F) for 1,2,3,4 fragments{'':>6}{'Rdelta':>8}")
    for ch in show_gens_order:
        HS = H_choice(psi, E, car, ch, S)
        curve = [I_choice(psi, E, car, ch, S, sum(FR[:m], [])) for m in range(1, len(FR) + 1)]
        singles = [I_choice(psi, E, car, ch, S, f) for f in FR]
        R = int(sum(1 for v in singles if v >= (1 - DELTA) * HS - 1e-9))
        print(f"   {ch:<10}{HS:9.5f}   {' '.join('%8.5f' % v for v in curve)}{R:8d}")

print("""
  READING.  With the system region enlarged to contain a cycle, the FULL gauge-invariant algebra
  acquires the Wilson loop W_01, and on the Wilson-loop-GHZ state it reports a nonzero, FLAT
  I(S:F) = 1.000000 across every fragment count -- where the electric choice still reports zero.
  THE CHOICE-DEPENDENCE IS REDUCED BY ENLARGING THE REGION UNTIL IT CONTAINS A LOOP.  But note
  R_delta = 0 for C3_FULL anyway, and that is a SEPARATE DEFECT, isolated next.""")

print("\n" + "=" * 108)
print("PART C2  --  A GAUGE-SPECIFIC DEFECT OF R_delta, AND THE REPAIR")
print("=" * 108)
print("""
  In BRD_W above, C3_FULL reports I(S:F_k) = 1.000000 for every fragment while H_A(S) = 2.000000,
  so R_delta = 0 by the standard rule I >= (1-delta) H(S) -- even though ONE FULL BIT, the Wilson
  loop W_01, is perfectly and redundantly recorded in every fragment.  The reason is structural:
  A_S^FULL = alg{X_0, X_1, W_01} carries TWO bits, one magnetic (W_01) and one electric
  (the centre X_0 X_1), and THE ELECTRIC BIT IS NOT RECORDABLE -- Gauss's law ties it to the rest
  of the graph.  R_delta demands the WHOLE system algebra be reproduced and therefore returns zero
  on a state that plainly has a record.
  THE REPAIR: evaluate R_delta relative to a declared POINTER SUBALGEBRA rather than all of A_S.
  Below, A_S is replaced by alg{W_01} alone; nothing else in the computation changes.""")
car = theta(10); L = 10
S = [0, 1]; FR = [[2, 3], [4, 5], [6, 7], [8, 9]]
POINTER = [SP(0, 0b11)]                                     # W_01 = Z_0 Z_1, the system holonomy
for nm, psi in STATES_C:
    E = pauli_table(psi, L, "direct")
    HW, _ = algebra_entropy(E, POINTER)
    singles = [mutual_information(E, POINTER, gens_FULL(car, f))[0] for f in FR]
    cum = [mutual_information(E, POINTER, gens_FULL(car, sum(FR[:m], [])))[0]
           for m in range(1, len(FR) + 1)]
    R = int(sum(1 for v in singles if v >= (1 - DELTA) * HW - 1e-9))
    print(f"   {nm[:45]:<46} H(W_01) = {HW:.5f}   I(W_01 : F) = "
          f"{' '.join('%8.5f' % v for v in cum)}   Rdelta = {R}")
print("""   => with the pointer subalgebra declared, the Wilson-loop-GHZ state returns R_delta = 4 of 4
      and a flat curve.  The magnetic-GHZ row is the b1 trap again and is WEIGHTLESS: H(W_01) = 0
      there (the holonomy is deterministic), so "R_delta = 4" is the empty condition 0 >= 0.
      THE CRITERION NEEDS A DECLARED POINTER OBSERVABLE; in a gauge theory it cannot be
      read off the system region, because the region algebra always carries unrecordable electric
      charge alongside the recordable holonomy.""")

# -------------------------------------------------------------------------------------
print("\n" + "=" * 108)
print("PART D  --  fan_4 and wheel_4: carriers WITH INTERIOR VERTICES.  C5 MAG has a DIFFERENT")
print("=" * 108)
for car, S, FR in [(fan(4), [1, 2], [[3, 4], [5, 6], [7, 8]]),
                   (wheel(4), [0, 4], [[1, 5], [2, 6], [3, 7]])]:
    L = car["L"]; REF = None
    print(f"\ncarrier {car['name']}  L={L}  edges={car['edges']}  dim H_phys={phys_dim(car)}")
    print(f"S = {S}  fragments = {FR}   cyclomatic(S) = {cyclomatic(car, S)}")
    for R in [S, FR[0]]:
        print(f"  generator lists for R = {R}")
        for ch in ["C1_EXT", "C5_MAG", "C3_FULL", "C2_ELEC"]:
            g = gens_for(ch, car, R); pairs, cen = algebra_structure(g)
            print(f"     {ch:<9} {[sp_str(a, L) for a in g]}  -> 2^{len(cen)} blocks of M_2^{len(pairs)}")
    for nm, psi in [("g^2=0.30 ground state", ground_state(car, 0.30)[0]),
                    ("g^2=1.00 ground state", ground_state(car, 1.00)[0]),
                    ("Haar physical seed 77", haar_physical(car, 77))]:
        E = pauli_table(psi, L, "direct")
        print(f"   {nm}")
        for ch in ["C1_EXT", "C5_MAG", "C3_FULL", "C2_ELEC"]:
            HS = H_choice(psi, E, car, ch, S)
            curve = [I_choice(psi, E, car, ch, S, sum(FR[:m], [])) for m in range(1, len(FR) + 1)]
            print(f"      {ch:<9} H_A(S)={HS:8.5f}   I = {' '.join('%8.5f' % v for v in curve)}")

print("""
  READING.  On fan_4 the region {1,2} has an INTERIOR vertex, so C5 MAG is a strictly smaller
  algebra than C1 EXT -- 2^1 blocks of M_2 against M_4 -- yet it returns the SAME number to every
  printed digit, exactly as PART A2 proves it must for physical states.  The genuine spread across
  choices on one state and one cut is C1=C5 versus C3 versus C2, and on fan_4 at g^2 = 0.30 it is
  0.95496 versus 0.00000 versus 0.00000 for the first fragment: the full width of the answer.""")
