"""
LANE W19-B  --  SHARED LIBRARY.  Z_N (here N=2) pure lattice gauge theory on a finite graph.
Everything downstream (b1..b4) imports this and CHANGES EXACTLY ONE THING per arm.

CONVENTIONS, stated once so the arms can be diffed:
  * a link l carries a qubit; the full "extended" Hilbert space is H_ext = (C^2)^{tensor L}.
  * a Pauli string is (x,z) in F_2^L x F_2^L packed as two python ints;  P_{x,z} = i^{|x&z|} X^x Z^z
    is HERMITIAN.  A signed Pauli SP is c * P_{x,z}.
  * Gauss operator at vertex v is the pure-X string G_v = prod_{l incident to v} X_l.
    A Pauli P_{x,z} COMMUTES with G_v  <=>  z . x_{G_v} = 0 mod 2.   (x plays no role: G_v is pure X.)
    => "gauge invariant" is a LINEAR condition on the z-part only.  Used everywhere below.
  * PHYSICAL sector = joint +1 eigenspace of the independent G_v.
  * Hamiltonian  H = -(1/g2) * sum_plaquettes (W_p + W_p^dag) - g2 * sum_links X_l .
    For Z_2, W_p = W_p^dag is a Z-string, so W+W^dag = 2 W_p and the 2 is absorbed into 1/g2.

ALGEBRA ENTROPY.  For a *-subalgebra A of B(H_ext) generated by signed Paulis:
    A  ~=  direct-sum over 2^c central blocks of  M_{2^k},
  found by symplectic Gram-Schmidt over F_2 (c = dim of the radical, k = # hyperbolic pairs).
  S_A(rho) := H({p_s}) + sum_s p_s S(sigma_s)  with p_s = Tr(rho P_s), sigma_s the block state.
  This reduces to the ordinary reduced-density-matrix entropy when A is a full matrix algebra on
  a set of links (checked in b0_selftest).
  I_A(A:B) := S_A + S_B - S_{A join B},  A join B generated by the UNION of the generator lists.
"""
import numpy as np, itertools

# ---------------------------------------------------------------- bit helpers
def pc(n):
    return bin(n).count("1")

_POPC_CACHE = {}
def popc_table(D):
    if D not in _POPC_CACHE:
        _POPC_CACHE[D] = np.array([bin(i).count("1") for i in range(D)], dtype=np.int64)
    return _POPC_CACHE[D]

# ---------------------------------------------------------------- signed Paulis
class SP:
    __slots__ = ("x", "z", "c")
    def __init__(self, x, z, c=1.0 + 0j):
        self.x = int(x); self.z = int(z); self.c = complex(c)
    def __repr__(self):
        return f"SP(x={self.x},z={self.z},c={self.c:.3g})"

def sp_str(a, L):
    s = ""
    for l in range(L):
        b = ((a.x >> l) & 1, (a.z >> l) & 1)
        s += {(0,0):"I",(1,0):"X",(0,1):"Z",(1,1):"Y"}[b]
    sign = "+" if abs(a.c - 1) < 1e-9 else ("-" if abs(a.c + 1) < 1e-9 else f"({a.c:.2g})")
    return sign + s

def spmul(a, b):
    x = a.x ^ b.x; z = a.z ^ b.z
    ph = (1j) ** ((pc(a.x & a.z) + pc(b.x & b.z) - pc(x & z)) % 4) * ((-1) ** (pc(a.z & b.x)))
    return SP(x, z, a.c * b.c * ph)

def anticomm(a, b):
    return (pc(a.x & b.z) + pc(a.z & b.x)) % 2

def hermitize(a):
    # a signed Pauli c*P is Hermitian iff c is real; multiplying by i fixes a pure-imaginary c
    if abs(a.c.imag) > 1e-9:
        return SP(a.x, a.z, a.c * 1j)
    return SP(a.x, a.z, complex(a.c.real, 0.0))

# ---------------------------------------------------------------- GF(2) linear algebra on packed ints
def gf2_independent(vecs):
    """Return (indices of an independent subset, reduced basis) for packed-int vectors."""
    basis = []; piv = []; keep = []
    for i, v in enumerate(vecs):
        w = v
        for p, b in zip(piv, basis):
            if (w >> p) & 1:
                w ^= b
        if w:
            p = w.bit_length() - 1
            piv.append(p); basis.append(w); keep.append(i)
    return keep, basis

def gf2_nullspace(rows, n):
    """Basis (packed ints, n bits) of {v : popcount(v & r) even for every r in rows}.
       Proper RREF + back substitution.  (The first version of this routine was wrong and its own
       assert caught it while b3 was running -- kept as an assert below.)"""
    mat = [r & ((1 << n) - 1) for r in rows]
    mat = [x for x in mat if x]
    piv_cols = []
    r = 0
    for col in range(n):
        if r >= len(mat): break
        sel = next((i for i in range(r, len(mat)) if (mat[i] >> col) & 1), None)
        if sel is None: continue
        mat[r], mat[sel] = mat[sel], mat[r]
        for i in range(len(mat)):
            if i != r and ((mat[i] >> col) & 1):
                mat[i] ^= mat[r]
        piv_cols.append(col); r += 1
    free = [c for c in range(n) if c not in piv_cols]
    ns = []
    for f in free:
        v = 1 << f
        for ri, pcol in enumerate(piv_cols):
            if (mat[ri] >> f) & 1:
                v |= (1 << pcol)
        ns.append(v)
    for v in ns:
        for rr in rows:
            assert pc(v & rr & ((1 << n) - 1)) % 2 == 0, "nullspace failure"
    assert len(ns) == n - len(piv_cols)
    return ns

# ---------------------------------------------------------------- Pauli expectation table
class PauliExpect:
    """<psi| P_{x,z} |psi> on demand.  mode='table' precomputes all 4^L (O(D^3), L <= 10);
       mode='direct' evaluates one string in O(D) and memoises (the only route for L >= 11)."""
    def __init__(self, psi, L, mode=None):
        self.psi = psi; self.L = L; self.D = 1 << L
        self.popc = popc_table(self.D)
        self.idx = np.arange(self.D)
        if mode is None:
            mode = "table" if L <= 10 else "direct"
        self.mode = mode
        self.cache = {}
        if mode == "table":
            D = self.D; idx = self.idx; popc = self.popc
            A = np.empty((D, D), dtype=complex)
            for x in range(D):
                A[x] = np.conj(psi[idx ^ x]) * psi
            Sg = ((-1.0) ** popc[idx[None, :] & idx[:, None]])     # Sg[z,j]
            E0 = A @ Sg.T                                          # <X^x Z^z>
            ph = (1j) ** (popc[idx[:, None] & idx[None, :]] % 4)   # i^{|x&z|}
            self.E = E0 * ph
    def __call__(self, x, z):
        if self.mode == "table":
            return self.E[x, z]
        k = (x, z)
        if k not in self.cache:
            v = np.vdot(self.psi[self.idx ^ x], ((-1.0) ** self.popc[self.idx & z]) * self.psi)
            self.cache[k] = (1j) ** (pc(x & z) % 4) * v
        return self.cache[k]

def pauli_table(psi, L, mode=None):
    return PauliExpect(psi, L, mode)

def sp_expect(E, a):
    return a.c * E(a.x, a.z)

# ---------------------------------------------------------------- algebra structure
def algebra_structure(gens):
    """Symplectic Gram-Schmidt.  Returns (pairs, center) as lists of Hermitian SPs."""
    keep, _ = gf2_independent([(g.x << 64) | g.z for g in gens])
    rest = [hermitize(gens[i]) for i in keep]
    pairs = []; center = []
    while rest:
        a = rest.pop(0)
        j = next((i for i, b in enumerate(rest) if anticomm(a, b)), None)
        if j is None:
            center.append(a); continue
        b = rest.pop(j)
        new = []
        for g in rest:
            h = g
            if anticomm(h, b): h = hermitize(spmul(h, a))
            if anticomm(h, a): h = hermitize(spmul(h, b))
            assert not anticomm(h, a) and not anticomm(h, b)
            new.append(h)
        rest = new
        pairs.append((a, b))
    return pairs, center

def _center_products(center):
    """All 2^c products C_T (Hermitian SPs), indexed by subset bitmask."""
    c = len(center)
    out = [None] * (1 << c)
    out[0] = SP(0, 0, 1.0)
    for m in range(1, 1 << c):
        low = m & -m; j = low.bit_length() - 1
        out[m] = hermitize(spmul(out[m ^ low], center[j]))
        assert abs(out[m].c.imag) < 1e-9
    return out

def _word(pairs, al, be):
    """W_{al,be} = prod_i A_i^{al_i} * prod_i B_i^{be_i}  as a signed Pauli."""
    w = SP(0, 0, 1.0)
    for i, (a, b) in enumerate(pairs):
        if (al >> i) & 1: w = spmul(w, a)
    for i, (a, b) in enumerate(pairs):
        if (be >> i) & 1: w = spmul(w, b)
    return w

def _abstract_word(al, be, k):
    """X^al Z^be as a 2^k x 2^k matrix (matches the ordered product A^al B^be)."""
    d = 1 << k
    M = np.zeros((d, d), dtype=complex)
    popc = popc_table(d)
    cols = np.arange(d)
    M[cols ^ al, cols] = (-1.0) ** popc[cols & be]
    return M

def vn_entropy(rho, tol=1e-10):
    w = np.linalg.eigvalsh(rho)
    w = w[w > tol]
    return float(-np.sum(w * np.log2(w)))

def shannon(p, tol=1e-12):
    p = np.asarray(p, dtype=float); p = p[p > tol]
    return float(-np.sum(p * np.log2(p)))

def algebra_entropy(E, gens, want_blocks=False, kmax=9):
    """S_A(rho) for rho = |psi><psi| encoded in the Pauli expectation object E.
       Cost is 2^c * 4^k signed-Pauli products; the (s, word) sum is done as one matmul, which is
       a 2^c speedup over the obvious triple loop and is what makes k = 5 reachable."""
    if not gens:
        return (0.0, (0, 0), []) if want_blocks else (0.0, (0, 0))
    pairs, center = algebra_structure(gens)
    k = len(pairs); c = len(center)
    assert k <= kmax, f"algebra has k={k} hyperbolic pairs; 4^k words is out of reach (kmax={kmax})"
    nc = 1 << c; nk = 1 << k; nw = nk * nk
    CT = _center_products(center)
    sgn = np.array([[(-1.0) ** pc(m & s) for m in range(nc)] for s in range(nc)])
    ctv = np.array([sp_expect(E, CT[m]).real for m in range(nc)])
    ps = (sgn @ ctv) / nc
    S = shannon(ps)
    words = [SP(w.x, w.z, np.conj(w.c)) for w in
             (_word(pairs, al, be) for al in range(nk) for be in range(nk))]      # W^dagger
    M = np.empty((nc, nw), dtype=complex)
    for m in range(nc):
        Cm = CT[m]
        for wi, Wd in enumerate(words):
            M[m, wi] = sp_expect(E, spmul(Cm, Wd))
    coef = (sgn @ M) / nc                                     # coef[s, word], word = al*nk + be
    # sigma_s = 2^-k sum_{al,be} coef[s,al,be] X^al Z^be, and (X^al Z^be)[r,c] = d_{r,c^al}(-1)^{c.be},
    # so sigma_s[r,c] = 2^-k * (C @ Hd^T)[r^c, c] with Hd[c,be] = (-1)^{popcount(c & be)}.
    # This avoids materialising 4^k matrices of size 2^k (which is 4.3 GB already at k = 7).
    ar = np.arange(nk); popk = popc_table(nk)
    Hd = ((-1.0) ** popk[ar[:, None] & ar[None, :]])
    xor = ar[:, None] ^ ar[None, :]
    blocks = []
    for s in range(nc):
        if ps[s] < 1e-12:
            blocks.append((ps[s], None)); continue
        T = (coef[s] / ps[s]).reshape(nk, nk) @ Hd.T
        sig = T[xor, ar[None, :]] / nk
        assert abs(np.trace(sig) - 1) < 1e-8, f"block trace {np.trace(sig)}"
        assert np.linalg.norm(sig - sig.conj().T) < 1e-8, "block not Hermitian"
        assert np.min(np.linalg.eigvalsh(sig)) > -1e-8, "block not PSD"
        S += ps[s] * vn_entropy(sig)
        blocks.append((ps[s], sig))
    return (S, (c, k), blocks) if want_blocks else (S, (c, k))

def mutual_information(E, gA, gB):
    SA, dA = algebra_entropy(E, gA)
    SB, dB = algebra_entropy(E, gB)
    SAB, dAB = algebra_entropy(E, list(gA) + list(gB))
    return SA + SB - SAB, (SA, SB, SAB, dA, dB, dAB)

# ---------------------------------------------------------------- carriers
def _from_edges(name, edges, plaq):
    """Build a carrier from an explicit edge list.  Gauss string at vertex v = prod of incident X."""
    L = len(edges)
    nv = 1 + max(max(e) for e in edges)
    gauss = []
    for v in range(nv):
        g = 0
        for l, (a, b) in enumerate(edges):
            if a == v or b == v: g |= (1 << l)
        gauss.append(g)
    return dict(name=name, L=L, edges=edges, gauss=gauss, plaq=plaq, verts=gauss)

def theta(L):
    """2 vertices, L parallel links.  One independent Gauss operator: prod_l X_l."""
    plaq = [(1 << 0) | (1 << i) for i in range(1, L)]     # W_{0i} = Z_0 Z_i, L-1 independent cycles
    return _from_edges(f"theta_{L}", [(0, 1)] * L, plaq)

def fan(n):
    """central link e0=0 (u->v); path k uses a_k=1+2k (u->w_k) and b_k=2+2k (w_k->v).
       n triangular plaquettes W_k = Z_0 Z_{a_k} Z_{b_k}; every path has its OWN Gauss law."""
    edges = [(0, 1)]
    for k in range(n):
        edges.append((0, 2 + k)); edges.append((2 + k, 1))
    plaq = [1 | (1 << (1 + 2 * k)) | (1 << (2 + 2 * k)) for k in range(n)]
    return _from_edges(f"fan_{n}", edges, plaq)

def wheel(n):
    """hub vertex 0 plus an n-cycle on vertices 1..n.  Links: n spokes then n rim links.
       n triangular plaquettes.  Has INTERIOR vertices for regions, unlike theta."""
    edges = [(0, 1 + k) for k in range(n)] + [(1 + k, 1 + (k + 1) % n) for k in range(n)]
    plaq = [(1 << k) | (1 << ((k + 1) % n)) | (1 << (n + k)) for k in range(n)]
    return _from_edges(f"wheel_{n}", edges, plaq)

def cyclomatic(car, R):
    """|R| - |V(R)| + components(R): the dimension of the cycle space of the induced subgraph,
       computed from the GRAPH (union-find), independently of any Pauli algebra."""
    verts = set()
    for l in R: verts |= set(car["edges"][l])
    par = {v: v for v in verts}
    def find(a):
        while par[a] != a: par[a] = par[par[a]]; a = par[a]
        return a
    for l in R:
        a, b = car["edges"][l]; ra, rb = find(a), find(b)
        if ra != rb: par[ra] = rb
    comps = len({find(v) for v in verts})
    return len(R) - len(verts) + comps

def indep_gauss(car):
    keep, _ = gf2_independent(car["gauss"])
    return [car["gauss"][i] for i in keep]

def project_physical(psi, car):
    idx = np.arange(psi.shape[0])
    for g in indep_gauss(car):
        psi = 0.5 * (psi + psi[idx ^ g])
    n = np.linalg.norm(psi)
    return psi / n if n > 1e-12 else psi

def phys_dim(car):
    return (1 << car["L"]) // (1 << len(indep_gauss(car)))

# ---------------------------------------------------------------- Hamiltonian & states
def hamiltonian(car, g2):
    L = car["L"]; D = 1 << L
    idx = np.arange(D); popc = popc_table(D)
    H = np.zeros((D, D), dtype=float)
    for w in car["plaq"]:
        H[idx, idx] += -(1.0 / g2) * (-1.0) ** popc[idx & w]
    for l in range(L):
        b = 1 << l
        H[idx ^ b, idx] += -g2
    return H

def ground_state(car, g2, penalty=1e6):
    L = car["L"]; D = 1 << L
    H = hamiltonian(car, g2)
    P = np.eye(D)
    idx = np.arange(D)
    for g in indep_gauss(car):
        Pg = np.zeros((D, D)); Pg[idx, idx] += 0.5; Pg[idx ^ g, idx] += 0.5
        P = P @ Pg
    w, v = np.linalg.eigh(H + penalty * (np.eye(D) - P))
    psi = v[:, 0]
    psi = project_physical(psi, car)
    return psi, float(w[0])

def sym_basis_state(car, conf):
    """gauge-orbit-symmetrised Z-basis state of a link configuration (an int)."""
    D = 1 << car["L"]
    psi = np.zeros(D, dtype=complex); psi[conf] = 1.0
    return project_physical(psi, car)

def haar_physical(car, seed):
    rng = np.random.default_rng(seed)
    D = 1 << car["L"]
    psi = rng.normal(size=D) + 1j * rng.normal(size=D)
    return project_physical(psi, car)

# ---------------------------------------------------------------- extended-Hilbert-space reductions
def reduce_links(psi, L, keep):
    """Partial trace onto `keep`.  NOTE the index convention: state index j has link l in bit l,
       so link l is numpy AXIS (L-1-l) after reshape([2]*L).  (b0 self-test [1] caught this.)"""
    keep = sorted(keep)
    other = [i for i in range(L) if i not in keep]
    perm = [L - 1 - l for l in keep] + [L - 1 - l for l in other]
    t = psi.reshape([2] * L).transpose(perm).reshape(1 << len(keep), 1 << len(other))
    return t @ t.conj().T

def rdm_ordered(psi, L, order):
    """Reduced density matrix with the subsystem order EXACTLY as given (order[0] most significant).
       reduce_links() sorts; this one does not, which matters for the SBS product test."""
    other = [i for i in range(L) if i not in order]
    perm = [L - 1 - l for l in order] + [L - 1 - l for l in other]
    t = psi.reshape([2] * L).transpose(perm).reshape(1 << len(order), 1 << len(other))
    return t @ t.conj().T

def ptrace_blocks(rho, dims, keep):
    """Partial trace of a multipartite rho given block dims; keep = list of block indices."""
    n = len(dims)
    t = rho.reshape(list(dims) + list(dims))
    for i in sorted([i for i in range(n) if i not in keep], reverse=True):
        t = np.trace(t, axis1=i, axis2=i + len(t.shape) // 2)
    d = int(np.prod([dims[i] for i in keep]))
    return t.reshape(d, d)

def trace_norm(A):
    return float(np.sum(np.abs(np.linalg.eigvalsh(A)))) if np.allclose(A, A.conj().T) \
        else float(np.sum(np.linalg.svd(A, compute_uv=False)))

def msqrt(A):
    w, v = np.linalg.eigh(A)
    w = np.clip(w, 0, None)
    return (v * np.sqrt(w)) @ v.conj().T

def mi_ext(psi, L, A, B):
    A = sorted(A); B = sorted(B)
    return (vn_entropy(reduce_links(psi, L, A)) + vn_entropy(reduce_links(psi, L, B))
            - vn_entropy(reduce_links(psi, L, A + B)))

# ---------------------------------------------------------------- algebra CHOICES (the whole point of b3)
def gens_EXT(car, R):
    """C1  EXTENDED HILBERT SPACE: full matrix algebra on the links of R (gauge law ignored)."""
    return [SP(1 << l, 0) for l in R] + [SP(0, 1 << l) for l in R]

def gens_ELEC(car, R):
    """C2  ELECTRIC CENTRE: only the gauge-invariant electric operators X_l, l in R.  Abelian."""
    return [SP(1 << l, 0) for l in R]

def gens_FULL(car, R):
    """C3/C4  FULL GAUGE-INVARIANT REGION ALGEBRA: every gauge-invariant Pauli supported in R.
       z-part must be orthogonal (mod 2) to every Gauss x-string restricted to R."""
    Rm = 0
    for l in R: Rm |= (1 << l)
    pos = sorted(R)
    rows = []
    for g in car["gauss"]:
        gr = g & Rm
        rows.append(sum(((gr >> l) & 1) << i for i, l in enumerate(pos)))
    ns = gf2_nullspace(rows, len(pos))
    zg = [sum(((v >> i) & 1) << l for i, l in enumerate(pos)) for v in ns]
    return [SP(1 << l, 0) for l in R] + [SP(0, z) for z in zg if z]

def gens_MAG(car, R):
    """C5  MAGNETIC CENTRE: the Gauss law is DROPPED at the boundary vertices of R, so boundary
       holonomies join the algebra.  Boundary vertex = incident to a link in R and one outside."""
    Rm = 0
    for l in R: Rm |= (1 << l)
    out = ((1 << car["L"]) - 1) ^ Rm
    keepg = [g for g in car["gauss"] if not ((g & Rm) and (g & out))]
    pos = sorted(R)
    rows = []
    for g in keepg:
        gr = g & Rm
        rows.append(sum(((gr >> l) & 1) << i for i, l in enumerate(pos)))
    ns = gf2_nullspace(rows, len(pos)) if rows else [1 << i for i in range(len(pos))]
    zg = [sum(((v >> i) & 1) << l for i, l in enumerate(pos)) for v in ns]
    return [SP(1 << l, 0) for l in R] + [SP(0, z) for z in zg if z]

def gens_DRESS(car, R, ref):
    """C6  DRESSED: electric ops in R plus gauge-invariant Wilson loops that leave R and close
       through a FIXED reference link `ref` (a Wilson line to a chosen point)."""
    g = gens_ELEC(car, R)
    for l in R:
        if l == ref: continue
        z = (1 << l) | (1 << ref)
        p = SP(0, z)
        if all(not anticomm(p, SP(gv, 0)) for gv in car["gauss"]):
            g.append(p)
    return g

CHOICES = {
    "C1_EXT":   lambda car, R: gens_EXT(car, R),
    "C2_ELEC":  lambda car, R: gens_ELEC(car, R),
    "C3_FULL":  lambda car, R: gens_FULL(car, R),
    "C5_MAG":   lambda car, R: gens_MAG(car, R),
}
