#!/usr/bin/env python3
"""
REFUTER LANE (charge axis) -- part 2.  THE ATTACKS.
Conventions identical to r1_build.py (published there).  Exact integer arithmetic
wherever a rank or a group order is claimed.
"""
import numpy as np
from itertools import combinations, product
from fractions import Fraction
from math import gcd, log, pi

V = 5
a_v = np.array([1, 1, 1, 0, 0])
b_v = np.array([1, 0, 0, 1, 1])

def lattice_rank(vecs):
    vs = [v for v in vecs if v != (0, 0)]
    if not vs:
        return 0
    for i in range(len(vs)):
        for j in range(i + 1, len(vs)):
            if vs[i][0] * vs[j][1] - vs[i][1] * vs[j][0] != 0:
                return 2
    return 1

def delta_rank(points):
    pts = sorted(set(points))
    if len(pts) <= 1:
        return 0
    b = pts[0]
    return lattice_rank([(p[0] - b[0], p[1] - b[1]) for p in pts])

def span_rank(points):
    """rank of the LINEAR span of the exponent points themselves (not the differences)."""
    return lattice_rank([p for p in sorted(set(points))])

def E_points(q):
    return [(q[v] * a_v[v], q[v] * b_v[v]) for v in range(V)]

# =====================================================================================
print("=" * 96)
print("A1.  IS THE CLAIM'S SUPPORTING CHECK CAPABLE OF FAILING?   (homogeneous charge, 5/6/4)")
print("=" * 96)
print("The claim's evidence for 'S4-1 holds verbatim for homogeneous charge' is the 5/6/4")
print("enumeration re-run at q = 1,2,3,4.  Re-run here at every q in -12..12, q != 0:")
CORNERS = [(0, 0), (1, 0), (0, 1), (1, 1)]
allsame = True
for q in [x for x in range(-12, 13) if x != 0]:
    t = {0: 0, 1: 0, 2: 0}
    for r in range(1, 5):
        for sub in combinations(CORNERS, r):
            t[delta_rank([(q * m, q * n) for (m, n) in sub])] += 1
    allsame &= (t[2], t[1], t[0]) == (5, 6, 4)
print("  every q in -12..12 (q!=0) gives exactly 5 / 6 / 4 :", allsame)
print("  PROOF that it could not have done otherwise:  x -> q*x is a Q-linear ISOMORPHISM")
print("  of Q^2 for every q != 0, so Delta(q*S) = q*Delta(S) and rank is preserved for EVERY")
print("  point configuration on EVERY carrier -- not just the square.  Check on 3000 random")
print("  integer configurations, comparing rank at q=1 against rank at q=2,3,5,-7:")
rng = np.random.default_rng(70251102)
bad = 0
for _ in range(3000):
    n = int(rng.integers(1, 6))
    P = [(int(x), int(y)) for x, y in rng.integers(-6, 7, (n, 2))]
    r1 = delta_rank(P)
    for q in (2, 3, 5, -7):
        if delta_rank([(q * x, q * y) for x, y in P]) != r1:
            bad += 1
print(f"  configurations whose rank moved under homogeneous charge: {bad} of 12000")
print("  ==> THE CHECK IS VACUOUS BY IDENTITY.  It is the same defect W-03 convicted S4's")
print("      CONTROL 1 of committing (a control that varies nothing the functional reads).")

# =====================================================================================
print("\n" + "=" * 96)
print("A2.  'HOLDS VERBATIM FOR ANY HOMOGENEOUS q != 0' -- BROKEN BY EXACT ARITHMETIC.")
print("=" * 96)
print("S4-1 concludes about G = <chi_x/chi_y> <= U(1): 'rank 2', and for |S|=2 'G = <u>' etc.")
print("W-01/S2's formation criterion is a statement about G:  formation <=> G != {1}.")
print("Take the connection (f,c) = (pi,pi), K1's three classes, weights (0.4,0.3,0.3):")
for q in (1, 2, 3, 4, 6):
    f = c = pi
    Zs = []
    for k in (1, 2, 3, 5, 7):
        z = 0.4 * np.exp(1j * k * (-q * f + q * c)) + 0.3 * np.exp(1j * k * (-q * f)) \
            + 0.3 * np.exp(1j * k * (q * c))
        Zs.append(abs(z))
    # exact: characters are q-th powers of (-1); G generated by (-1)^q
    Gtriv = (q % 2 == 0)
    print(f"   q={q}:  |Z_k| for k=1,2,3,5,7 = {['%.6f'%x for x in Zs]}   "
          f"G = {'{1}' if Gtriv else '{+1,-1}'}   formation: {not Gtriv}")
print("  EXACT: u = v = e^{i pi} = -1.  chi_(1,1)=(uv)^q=1, chi_(1,0)=u^q, chi_(0,1)=v^q.")
print("  q EVEN  ->  all three characters equal 1  ->  G = {1}  ->  |Z_k| = 1 for every k,")
print("  lambda = 0 EXACTLY, NO FORMATION EVER -- while |S| = 3 and rank Delta = 2.")
print("  q ODD   ->  G = {+1,-1} != {1}, formation occurs, |Z_1| = 0.2, lambda_A = log(0.2).")
print("  ==> homogeneous charge 2 DESTROYS formation at a connection where charge 1 has it.")
print("      S4-1's conclusion and the criterion it feeds are NOT invariant under homogeneous")
print("      charge.  'Holds VERBATIM for any q != 0' is FALSE.")
print("  Same break on the |S|=2 table: S={1,u} at u = e^{2 pi i/q} gives G = <u^q> = {1},")
print("  where the table asserts G = <u> (order q).  Verified exactly:")
for q in (2, 3, 5):
    u = np.exp(2j * pi / q)
    print(f"     q={q}: u = e^(2 pi i/{q}), <u> has order {q}, but <u^q> = {{1}} "
          f"(|u^q - 1| = {abs(u**q - 1):.2e})")

# =====================================================================================
print("\n" + "=" * 96)
print("A3.  THE WALL IS NOT AT CHARGE 1 EITHER: S4-1 FAILS AT UNIT CHARGE ON THE CORPUS'S")
print("     OWN HEADLINE CONNECTION (f,c) = (2.0, 1.1).")
print("=" * 96)
print("  L = {(m,n) : -m f + n c = 0 mod 2pi}.  At f=2.0, c=1.1:  -m*2 + n*1.1 is RATIONAL,")
print("  so it lies in 2pi Z only when it is 0, i.e. -20m + 11n = 0, i.e. L = <(11,20)>.")
print("  check: -11*2.0 + 20*1.1 =", -11 * 2.0 + 20 * 1.1, " (this is the S3 audit's resonance)")
print("  Unit charge, full support: Delta = Z^2, so Delta ^ L = L, rank 1.")
print("  G = image of Z^2 under (m,n) -> e^{i(-2m + 1.1n)} = e^{0.1 i (-20m + 11n)};")
print("  gcd(20,11) = 1 so {-20m+11n : m,n in Z} = Z and G = <e^{0.1 i}> = Z, RANK 1.")
print("  S4-1 asserts rank G = 2 whenever |S| >= 3.  Here |S| = 3 and rank G = 1.")
print("  Numerical corroboration -- the orbit (u^k,v^k) fills a 1-dimensional subgroup:")
ks = np.arange(1, 200001)
th = np.mod(np.stack([-2.0 * ks, 1.1 * ks], 1), 2 * pi)
resid = np.mod(11 * th[:, 0] + 20 * th[:, 1], 2 * pi)   # should be identically 0 mod 2pi
resid = np.minimum(resid, 2 * pi - resid)
print(f"     max dist of 11*theta_u + 20*theta_v from 0 mod 2pi over k<=2e5 : {resid.max():.3e}")
print("     (a 2-dimensional orbit would have this equidistributed on [0,pi])")
print("  ==> at UNIT CHARGE, on the connection S3 and S4 actually work at, S4-1 is FALSE.")

# =====================================================================================
print("\n" + "=" * 96)
print("A4.  'FAILS THE MOMENT THE CHARGE IS INHOMOGENEOUS' -- REFUTED BY CENSUS.")
print("=" * 96)
print("  (a) the claim's own parameter space: class-constant charge (r,s,t) in {-3..3}^3")
print("      r on class (1,1), s on class (1,0), t on class (0,1).")
tot = full = failing = 0
fail_list = []
for r, s, t in product(range(-3, 4), repeat=3):
    P = [(r, r), (s, 0), (0, t)]
    tot += 1
    if len(set(P)) == 3:
        full += 1
        if delta_rank(P) <= 1:
            failing += 1
            fail_list.append((r, s, t))
print(f"      assignments: {tot};  with 3 DISTINCT exponent points: {full};")
print(f"      of those, rank Delta <= 1 (S4-1 broken): {failing}")
print(f"      the failing set: {fail_list}")
inhom = sum(1 for r, s, t in product(range(-3, 4), repeat=3) if len({r, s, t}) > 1)
print(f"      INHOMOGENEOUS assignments in the same box: {inhom} of {tot}")
print(f"      fraction of inhomogeneous assignments that break S4-1: {failing}/{inhom} "
      f"= {failing/inhom:.4f}")
print("  (b) the ACTUAL charge space of K1: per-vertex q in {-3..3}^5 (charge is a per-vertex")
print("      fibre weight -- it need not be constant on a class).")
tot5 = full5 = fail5 = 0
fails5 = []
for q in product(range(-3, 4), repeat=5):
    P = E_points(q)
    tot5 += 1
    if len(set(P)) >= 3:
        full5 += 1
        if delta_rank(P) <= 1:
            fail5 += 1
            fails5.append(q)
print(f"      assignments: {tot5};  with >=3 distinct exponent points: {full5};")
print(f"      of those, rank Delta <= 1: {fail5}   ({100*fail5/full5:.3f}% of them)")
inhom5 = sum(1 for q in product(range(-3, 4), repeat=5) if len(set(q)) > 1)
print(f"      INHOMOGENEOUS q in the box: {inhom5};  breaking S4-1: {fail5} "
      f"= {100*fail5/inhom5:.3f}% of them")
print("  ==> inhomogeneity is nowhere near sufficient.  The failure locus is a thin set.")

# =====================================================================================
print("\n" + "=" * 96)
print("A5.  WHERE THE WALL ACTUALLY IS -- THEOREM R-1, DERIVED AND THEN CHECKED EXHAUSTIVELY.")
print("=" * 96)
print("  THEOREM R-1.  On K1 with per-vertex charges q = (q0; q1,q2; q3,q4), let S be the set")
print("  of DISTINCT exponent points.  Then |S| >= 3 and rank Delta(S) <= 1 hold iff exactly")
print("  one of:")
print("     (A) AXIAL / LINEARLY degenerate:  q0 = 0, and either")
print("         (q3=q4=0, q1 != q2, q1 q2 != 0)  or  (q1=q2=0, q3 != q4, q3 q4 != 0);")
print("     (B) HARMONIC / AFFINELY degenerate:  q1 = q2 = s != 0, q3 = q4 = t != 0,")
print("         q0 != 0, and  1/q0 = 1/s + 1/t   (equivalently s t = q0 (s+t)).")
print("  PROOF SKETCH.  Points are (q0,q0),(q1,0),(q2,0),(0,q3),(0,q4).  If a line contains")
print("  two distinct nonzero points of the x-axis it IS the x-axis, forcing q0 = 0 and the")
print("  y-axis points to the origin: case (A).  Otherwise q1=q2=s, q3=q4=t and the line")
print("  through (s,0),(0,t) is x/s + y/t = 1, which contains (q0,q0) iff q0/s + q0/t = 1.")
def predicate_R1(q):
    q0, q1, q2, q3, q4 = q
    A = (q0 == 0 and ((q3 == 0 and q4 == 0 and q1 != q2 and q1 * q2 != 0) or
                      (q1 == 0 and q2 == 0 and q3 != q4 and q3 * q4 != 0)))
    B = (q1 == q2 != 0 and q3 == q4 != 0 and q0 != 0 and q1 * q3 == q0 * (q1 + q3))
    return A or B
mis = [q for q in product(range(-6, 7), repeat=5)
       if predicate_R1(q) != (len(set(E_points(q))) >= 3 and delta_rank(E_points(q)) <= 1)]
print(f"  EXHAUSTIVE CHECK over q in {{-6..6}}^5  ({13**5} assignments): mismatches = {len(mis)}")
print("  Consequences, all immediate from R-1:")
print("   * homogeneous q0=q1=q2=q3=q4=q!=0 gives case (B) condition q*q = q*2q, i.e. q=0.")
print("     So homogeneity IS sufficient for S4-1's rank clause -- but only in the rank sense,")
print("     and A2 shows the rank sense is not what S4-1 states.")
print("   * the failure locus in Z^5 has codimension >= 2 (A: 3 linear conditions;")
print("     B: 2 linear + 1 quadratic).  'Fails the moment charge is inhomogeneous' is false.")
print("   * case (A) needs a class ZEROED OUT, i.e. it is a SUPPORT collapse dressed as charge.")

# =====================================================================================
print("\n" + "=" * 96)
print("A6.  ARE THE TWO COUNTEREXAMPLES 'THE SAME PHENOMENON'?  NO -- AND ONE IS OFF-CARRIER.")
print("=" * 96)
ex1 = [(1, 1), (2, 0), (0, 2)]      # q = (1,2,2,2,2) -- the claim's exhibit
ex2 = [(1, 0), (2, 0), (3, 0)]      # the critic's exhibit, of record in W-03
for nm, P in (("(1,1),(2,0),(0,2)", ex1), ("(1,0),(2,0),(3,0)", ex2)):
    print(f"   {nm}:  rank Delta = {delta_rank(P)}   rank of the LINEAR span of E = {span_rank(P)}")
print("   They differ in the linear rank, and that decides WHAT lambda sees:")
print("     (1,0),(2,0),(3,0): every character is a power of u   -> |Z_k| depends on f ONLY.")
print("     (1,1),(2,0),(0,2): characters span rank 2, ratios rank 1 -> |Z_k| depends on f+c ONLY.")
rng2 = np.random.default_rng(70251103)
d1m = d2m = 0.0
for _ in range(2000):
    f, c = rng2.uniform(0, 2 * pi, 2)
    z1 = lambda ff, cc, P: abs(sum(w * np.exp(1j * (-m * ff + n * cc))
                                   for w, (m, n) in zip((0.4, 0.3, 0.3), P)))
    d1m = max(d1m, abs(z1(f, c, ex1) - z1(0.0, f + c, ex1)))     # depends on f+c only
    d2m = max(d2m, abs(z1(f, c, ex2) - z1(f, 0.0, ex2)))         # depends on f only
print(f"   checked, 2000 random (f,c), seed 70251103:  |Z_1|(f,c) vs |Z_1|(0,f+c) for ex1: "
      f"{d1m:.2e};   |Z_1|(f,c) vs |Z_1|(f,0) for ex2: {d2m:.2e}")
print("   In S4-1's own vocabulary ex1 'sees the PRODUCT' and ex2 'sees W_F only' -- two")
print("   DIFFERENT rows of the table S4-1 was replaced for.  Not the same phenomenon.")
print("   AND: (1,0),(2,0),(3,0) needs THREE vertices of class (1,0).  K1 has TWO.")
onaxis = [q for q in product(range(-3, 4), repeat=5)
          if sorted(set(E_points(q))) == sorted({(1, 0), (2, 0), (3, 0)})]
print(f"   per-vertex charges on K1 realising exactly {{(1,0),(2,0),(3,0)}}: {len(onaxis)}")
print("   The K1-realisable axial case always contains the ORIGIN, e.g. q=(0,1,2,0,0) ->",
      sorted(set(E_points((0, 1, 2, 0, 0)))))

# =====================================================================================
print("\n" + "=" * 96)
print("A7.  DOES lambda ACTUALLY MOVE?  THE ONE NUMBER THE CLAIM'S FAMILY IS CARRIED BY.")
print("=" * 96)
def lam_A(f, c, P, w):
    return log(abs(sum(wi * np.exp(1j * (-m * f + n * c)) for wi, (m, n) in zip(w, P))))
def lam_B_direct(P, w, N, f, c):
    ks = np.arange(1, N + 1)
    z = sum(wi * np.exp(1j * ks * (-m * f + n * c)) for wi, (m, n) in zip(w, P))
    return float(np.mean(np.log(np.abs(z))))
w = (0.4, 0.3, 0.3)
f0, c0 = 1.0, np.sqrt(2.0)        # generic (L = 0)
print(f"  generic connection (f,c) = (1.0, sqrt2), weights {w}, N = 2e6:")
print(f"     unit charge   E = {[(1,1),(1,0),(0,1)]}  lambda_B = "
      f"{lam_B_direct([(1,1),(1,0),(0,1)], w, 2000000, f0, c0):.9f}")
print(f"     q=(1,2,2,2,2) E = {ex1}  lambda_B = {lam_B_direct(ex1, w, 2000000, f0, c0):.9f}")
print(f"     q=(0,1,2,0,0) E = {sorted(set(E_points((0,1,2,0,0))))}  lambda_B = "
      f"{lam_B_direct(sorted(set(E_points((0,1,2,0,0)))), (0.4+0.3, 0.15, 0.15), 2000000, f0, c0):.9f}")
print("  and at the resonant corpus connection (2.0, 1.1), unit charge, N = 2e6:")
print(f"     lambda_B = {lam_B_direct([(1,1),(1,0),(0,1)], w, 2000000, 2.0, 1.1):.9f}")
print("     (S3 audit of record: subtorus value -0.767014993; generic torus -0.767507880)")
