"""W-57.  REDUNDANCY WITHOUT PARTIAL TRACES.

W-36, W-40 and W-43b measured "how much does a fragment of the environment know about the record"
with Holevo quantities computed through PARTIAL TRACES. A partial trace presupposes a tensor
factorisation, and IMP-2 records that a gauge theory's algebra does not have one. Those numbers were
obtained in a structure the system does not possess.

THE ALGEBRAIC QUANTITY, WHICH NEEDS NO FACTORISATION. "What a region knows" is how well the two
record sectors can be told apart BY MEASUREMENTS IN ITS OWN ALGEBRA. For states rho_+ and rho_- and a
subalgebra A,
        d_A  =  max over a in A, ||a|| <= 1, of | Tr(a rho_+) - Tr(a rho_-) |
              =  || P_A(rho_+ - rho_-) ||_1
where P_A is the Hilbert-Schmidt projection onto A -- the conditional expectation. Only the algebra
enters. No factor, no trace-out, no environment Hilbert space.

d_A = 0  means the region cannot tell the sectors apart AT ALL.
d_A = 1  means it can do so perfectly.
This is the same question W-36 asked, asked in a structure the system actually has.
"""
import itertools, numpy as np

V2=[(i,j) for j in range(3) for i in range(3)]; vid={v:k for k,v in enumerate(V2)}
E=[]
for j in range(3):
    for i in range(2): E.append((vid[(i,j)],vid[(i+1,j)]))
for j in range(2):
    for i in range(3): E.append((vid[(i,j)],vid[(i,j+1)]))
L=len(E)
hid=lambda i,j:j*2+i; vx=lambda i,j:6+j*3+i
PLQ=[[(hid(i,j),+1),(vx(i+1,j),+1),(hid(i,j+1),-1),(vx(i,j),-1)] for j in range(2) for i in range(2)]
PSUP=[set(k for k,_ in p) for p in PLQ]
st=[s for s in itertools.product(range(2),repeat=L)
    if all((sum(s[k] for k,(a,b) in enumerate(E) if a==v)
           -sum(s[k] for k,(a,b) in enumerate(E) if b==v))%2==0 for v in range(9))]
idx={s:i for i,s in enumerate(st)}; D=len(st); m=len(PLQ)
def Zop(links): return np.diag([(-1.0)**(sum(s[k] for k in links)%2) for s in st]).astype(complex)
def Move(mv):
    M=np.zeros((D,D),complex)
    for j,s in enumerate(st):
        t=list(s)
        for k,sg in mv: t[k]=(t[k]+sg)%2
        t=tuple(t)
        if t in idx: M[idx[t],j]=1.0
    return M
CENTREV=vid[(1,1)]; CUT=[k for k,(a,b) in enumerate(E) if a==CENTREV or b==CENTREV]
PERIM=[k for k in range(L) if k not in CUT]

# --- the algebra as Pauli strings on m effective qubits (exact, GF(2)) ---
def zvec(lk): return tuple(1 if lk in PSUP[p] else 0 for p in range(m))
def xvec(p):  return tuple(1 if q==p else 0 for q in range(m))
def spanF2(vs):
    basis=[]
    for v in vs:
        cur=list(v)
        for b in basis:
            piv=next((i for i,x in enumerate(b) if x),None)
            if piv is not None and cur[piv]: cur=[(x+y)%2 for x,y in zip(cur,b)]
        if any(cur): basis.append(cur)
    return basis
def elementsF2(basis):
    out=[]
    for coef in itertools.product([0,1],repeat=len(basis)):
        v=[0]*(2*m)
        for c,b in zip(coef,basis):
            if c: v=[(x+y)%2 for x,y in zip(v,b)]
        out.append(tuple(v))
    return out
XP=[Move(PLQ[p]) for p in range(m)]
def cycleZ(p):
    """Z on effective qubit p: the diagonal operator distinguishing that cycle's flux"""
    reps=[lk for lk in range(L) if zvec(lk)==xvec(p)]
    return Zop([reps[0]])
ZP=[cycleZ(p) for p in range(m)]
def pauli(v):
    O=np.eye(D,dtype=complex)
    for p in range(m):
        if v[p]:   O=O@XP[p]
    for p in range(m):
        if v[m+p]: O=O@ZP[p]
    return O
def loop_support(T):
    """support of the Wilson loop that is the product of the plaquettes in T (odd-multiplicity links)"""
    c={}
    for p in T:
        for lk in PSUP[p]: c[lk]=c.get(lk,0)+1
    return set(lk for lk,v in c.items() if v%2)
def algebra_paulis(S):
    """A(S): generated by the electric Z on links of S, and by EVERY gauge-invariant Wilson loop whose
    SUPPORT lies inside S -- not merely the full plaquettes inside S. The first version admitted only
    whole plaquettes, so A(PERIM) failed to contain the rim loop and the control returned 0."""
    Ss=set(S)
    gens=[tuple([0]*m)+zvec(lk) for lk in S]
    for r in range(1,m+1):
        for T in itertools.combinations(range(m),r):
            if loop_support(T)<=Ss:
                gens.append(tuple(1 if p in T else 0 for p in range(m))+tuple([0]*m))
    return elementsF2(spanF2(gens))

R=Move([(k,1) for k in PERIM])                        # the rim loop -- the record W-34 selected
Pp=(np.eye(D)+R)/2; Pm=(np.eye(D)-R)/2
rho_p=Pp/np.trace(Pp).real; rho_m=Pm/np.trace(Pm).real
D_=rho_p-rho_m

def distinguishability(S):
    """|| P_A(rho_+ - rho_-) ||_1 -- the trace-distance the subalgebra can actually resolve"""
    V=algebra_paulis(S)
    proj=np.zeros((D,D),complex)
    for v in V:
        P=pauli(v); n=np.real(np.vdot(P,P))
        proj+=np.vdot(P,D_)/n*P
    return float(np.sum(np.abs(np.linalg.eigvalsh((proj+proj.conj().T)/2))))/2.0   # normalised to [0,1]

print("W-57  DISTINGUISHABILITY OF THE RECORD'S SECTORS BY A REGION'S OWN ALGEBRA")
print("      record = the rim loop (the observable W-34's sieve selected)")
print("      NO PARTIAL TRACE. NO TENSOR FACTOR. Only the subalgebra enters.\n")
print(f"  {'region S (links)':>34s} {'|S|':>4s} {'dim A':>6s} {'d_A':>9s}   reading")
print("  "+"-"*76)
tests=[("one cut link [2]",[2]),
       ("two cut links [2,3]",[2,3]),
       ("all four cut links",CUT),
       ("one perimeter link [0]",[0]),
       ("two perimeter links [0,1]",[0,1]),
       ("half the perimeter",PERIM[:4]),
       ("the whole perimeter",PERIM),
       ("perimeter minus one link",PERIM[:-1]),
       ("everything",list(range(L)))]
for nm,S in tests:
    d=distinguishability(S); nA=len(algebra_paulis(S))
    rd=("cannot tell the sectors apart" if d<1e-9 else
        "resolves them perfectly" if d>1-1e-9 else "partial")
    print(f"  {nm:>34s} {len(S):4d} {nA:6d} {d:9.6f}   {rd}")
print()
print("  CONTROLS")
print(f"    an algebra CONTAINING the rim loop (S = perimeter) must resolve perfectly: "
      f"d_A = {distinguishability(PERIM):.6f}")
print("  CONTROL -- the empty region knows nothing.")
print(f"    S = {{}}: d_A = {distinguishability([]):.6f}")
