#!/usr/bin/env python3
"""
X_01 — THE SMUGGLED ASSUMPTION IS PRIMITIVITY OF THE GENERATOR OF L, AND IT IS THE WINDING
       RATIO ASSUMPTION THE BRIEF ASKED ME TO LOOK FOR.

TARGET.  LANE_W13_R_REDUCTION, findings R-1 and R-5.
  R-1 (R_07_THEOREMS.txt:R-1): "In the rank-1 case with L = Z.(m,n), (m,n) primitive, X_omega
      is the single circle {(z^n, z^{-m})}".
  R-5 (R_07_THEOREMS.txt:R-5, R_02_reduction.py docstring, R_02_reduction.out.txt):
      "Q_{m,n} has a root on |z|=1 for a primitive (m,n) IF AND ONLY IF (m,n) = +-(1,1),
       i.e. u v = 1, i.e. c = f."   ... "ON THAT LINE, exactly,
       |Z_k| = 0.3 |2 sin(pi(k alpha - theta*))| |2 sin(pi(k alpha + theta*))|"
  R-X: "the Sudler literature ... is the correct citation on the resonant locus only —
       which is ... exactly where the limit is the subtorus value rather than m(P)."

THE DEFECT.  A rank-1 relation lattice L need NOT be generated by a primitive vector.
L is any rank-1 subgroup of Z^2, hence L = Z.(d m, d n) with (m,n) primitive and d >= 1.
The orbit closure is the ANNIHILATOR L^perp, which for d >= 2 is d PARALLEL CIRCLES, not one.
R-1's dichotomy line says "finitely many parallel circles" and then its parametrisation, and
every downstream statement, uses the single circle.  So the lane's classification of the
resonant locus is indexed by the WINDING RATIO (m:n) alone, and the winding ratio does not
determine the closure.

WHAT FALLS.  At K1's pi the two torus zeros are (e(theta*), e(-theta*)), which lie on
{xy = 1}.  A closure L^perp with L = Z.(dm,dn) is {(x,y) : (x^m y^n)^d = 1}; it contains a
zero iff d(m-n)theta* in Z, i.e. (theta* irrational, Niven) iff m = n, i.e. iff m=n=1, FOR
EVERY d.  So the singular resonant set is
        u v is a ROOT OF UNITY   <=>   (c - f)/2pi rational,
a countable dense family of circles parallel to the diagonal -- NOT the single line c = f.
On the d-th member the limit is (1/d) sum_{r<d} m(0.3 w^2 + 0.4 zeta^r w + 0.3 zeta^r),
zeta = e(j/d): a value that is neither m(P) nor the register's (1,1) row log(0.3), and that
appears in no table in this corpus.

ISOLATION.  THE ONE VARIABLE MOVED IS d = THE ORDER OF u.v AS A ROOT OF UNITY (equivalently
the index of the primitive direction in L).  THE WINDING RATIO IS HELD FIXED AT (1,1) IN
EVERY ARM -- same primitive direction, same "line" in the lane's sense, same alpha
(= sqrt2 - 1, the lane's own BA-silver rotation), same pi, same estimator, same N-grid, same
phase reducer.  Only beta = j/d - alpha moves.  The lane's R-5 is a function of (m,n) alone
and therefore predicts one and the same reduced problem for all four arms.
"""
import numpy as np
from fractions import Fraction
from X_lib import (PI_K1, P_eval, m_maxform, m_one_var, frac_sqrt, frac_theta_star,
                   ExactRot, relation_lattice, arm_hash)

np.set_printoptions(precision=8, suppress=True)
PREC = 60
SQ2 = frac_sqrt(2, PREC)
TH = frac_theta_star(PREC)
THf = float(TH)
MP = m_maxform(PI_K1, 1 << 24)
p00, p10, p01, p11 = PI_K1
KMAX = 10 ** 7
DECS = [10 ** i for i in range(1, 8)]

print("=" * 79)
print("X_01 — THE CLOSURE IS NOT DETERMINED BY THE WINDING RATIO")
print("=" * 79)
print("\npi = %s   m(P) = %.12f   theta* = %.12f   log(0.3) = %.12f"
      % (PI_K1, MP, THf, np.log(0.3)))

ALPHA = SQ2 - 1                     # the lane's own BA-silver rotation, held fixed

# ---------------------------------------------------------------- 1. the arithmetic claim
print("\n1. WHICH RANK-1 CLOSURES CONTAIN A TORUS ZERO?  EXHAUSTIVE, d = 1..6.")
print("   closure L^perp for L = Z.(d m, d n); contains (e(th*),e(-th*)) iff d(m-n)th* in Z.")
print("   Tested numerically: is (theta*, -theta*) annihilated by (dm,dn)?  (exact test m==n)")
hits = []
for d in range(1, 7):
    for m in range(-6, 7):
        for n in range(-6, 7):
            if (m, n) == (0, 0) or np.gcd(m, n) != 1:
                continue
            # (dm,dn) annihilates (th*,-th*) iff d(m-n)th* in Z; th* irrational -> m==n
            if m == n:
                hits.append((d, m, n))
print("   primitive directions (m,n), |m|,|n|<=6, d<=6 giving a SINGULAR closure:")
print("     ", sorted(set((m, n) for _, m, n in hits)), " for every d in 1..6")
print("   -> the singular set is indexed by (winding ratio (1,1)) x (EVERY d>=1),")
print("      i.e. by u.v being ANY root of unity, i.e. (c-f)/2pi rational.")
print("      R-5 reports only d = 1 (c = f).  MISSING: every d >= 2.")

# ---------------------------------------------------------------- 2. the true limits
def true_limit(d, j=1):
    """(1/d) sum_{r<d} m(0.3 w^2 + 0.4 zeta^r w + 0.3 zeta^r),  zeta = e(j/d)."""
    tot = 0.0
    per = []
    for r in range(d):
        z = np.exp(2j * np.pi * (j * r) / d)
        val = m_one_var([p01 * z, (p11) * z, p10])      # 0.3 zeta^r + 0.4 zeta^r w + 0.3 w^2
        per.append(val)
        tot += val
    return tot / d, per

print("\n2. THE TRUE SUBTORUS VALUE ON EACH d, BY JENSEN ON THE ROOTS (exact, no quadrature)")
truth = {}
for d in (1, 2, 3, 5):
    v, per = true_limit(d)
    truth[d] = v
    print("   d=%d  uv = e(1/%d)   limit = %.12f    branch values %s"
          % (d, d, v, " ".join("%.6f" % x for x in per)))
print("   lane R-5 predicts log(0.3) = %.12f on EVERY one of these (its formula depends"
      % np.log(0.3))
print("   only on the primitive (m,n) = (1,1), which is the same in every row).")

# ---------------------------------------------------------------- 3. the arms
print("\n3. THE FOUR ARMS.  alpha = sqrt2 - 1 FIXED; beta = 1/d - alpha; d is the only mover.")
arms = {}
for d in (1, 2, 3, 5):
    beta = Fraction(1, d) - ALPHA
    L = relation_lattice(ALPHA, beta, B=12)
    prim = sorted(set((m // np.gcd(abs(m), abs(n)) if np.gcd(abs(m), abs(n)) else m,
                       n // np.gcd(abs(m), abs(n)) if np.gcd(abs(m), abs(n)) else n)
                      for m, n in L))
    arms[d] = (ALPHA, beta, L, prim)
    print("   d=%d  L(omega) within |m|,|n|<=12 : %s" % (d, L))
    print("        primitive directions present : %s   -> WINDING RATIO IDENTICAL IN ALL ARMS"
          % sorted(set(prim)))

# ---------------------------------------------------------------- 4. Birkhoff, 7 decades
print("\n4. THE BIRKHOFF AVERAGE, SEVEN DECADES.  ARMS-DIFF GUARD HASHES THE OUTPUT VECTORS.")
k = np.arange(1, KMAX + 1, dtype=np.int64)
ra = ExactRot(ALPHA)
fa = ra.frac(k)
rows, hashes, mins = {}, {}, {}
for d in (1, 2, 3, 5):
    _, beta, _, _ = arms[d]
    rb = ExactRot(beta)
    fb = rb.frac(k)
    x = np.exp(2j * np.pi * fa); y = np.exp(2j * np.pi * fb)
    az = np.abs(P_eval(PI_K1, x, y))
    lz = np.log(az)
    hashes[d] = arm_hash(lz[:200000])
    cs = np.cumsum(lz)
    rows[d] = [cs[N - 1] / N for N in DECS]
    mins[d] = [az[:N].min() for N in DECS]
    del x, y, az, lz, cs, fb
print("   arm hashes (first 200000 log|Z_k|):")
for d in (1, 2, 3, 5):
    print("      d=%d  %s" % (d, hashes[d]))
print("   distinct hashes: %d of 4  -> arms differ" % len(set(hashes.values())))
print("   first five orbit points (beta side), read off the arms:")
for d in (1, 2, 3, 5):
    print("      d=%d  %s" % (d, np.round(ExactRot(arms[d][1]).frac(np.arange(1, 6, dtype=np.int64)), 8)))

hdr = "   %-6s" % "N" + "".join("%16d" % N for N in DECS)
print("\n   S_N = (1/N) sum_{k<=N} log|Z_k|")
print(hdr)
for d in (1, 2, 3, 5):
    print("   d=%-4d" % d + "".join("%16.9f" % v for v in rows[d]))
print("\n   S_N MINUS the LANE'S prediction log(0.3) = %.9f   [R-5's closed form]" % np.log(0.3))
print(hdr)
for d in (1, 2, 3, 5):
    print("   d=%-4d" % d + "".join("%16.2e" % (v - np.log(0.3)) for v in rows[d]))
print("\n   S_N MINUS the TRUE subtorus value for that d   [this refuter's X_01 sec.2]")
print(hdr)
for d in (1, 2, 3, 5):
    print("   d=%-4d" % d + "".join("%16.2e" % (v - truth[d]) for v in rows[d]))
print("\n   S_N MINUS m(P) = %.9f  (N1's claimed value)" % MP)
print(hdr)
for d in (1, 2, 3, 5):
    print("   d=%-4d" % d + "".join("%16.2e" % (v - MP) for v in rows[d]))

print("\n5. THE SINGULARITY IS PRESENT ON EVERY d, NOT ONLY d=1:  min_{k<=N} |Z_k|")
print(hdr)
for d in (1, 2, 3, 5):
    print("   d=%-4d" % d + "".join("%16.3e" % v for v in mins[d]))
print("   All four DECREASE across seven decades: every one of these closures passes through")
print("   BOTH torus zeros.  Contrast the lane's own RESONANT arm (11,20), whose min distance")
print("   SATURATES at 1.294e-02 (R_04_2d_arms.out.txt) because its closure misses the zeros.")

# ---------------------------------------------------------------- 6. the closed form fails
print("\n6. R-5's CLOSED FORM  |Z_k| = 0.3|2 sin(pi(k a - th*))||2 sin(pi(k a + th*))|")
print("   evaluated on each arm over k <= 100000 (the lane's own check window).")
kk = np.arange(1, 100001, dtype=np.int64)
faa = ra.frac(kk)
pred = 0.3 * np.abs(2 * np.sin(np.pi * (faa - THf))) * np.abs(2 * np.sin(np.pi * (faa + THf)))
for d in (1, 2, 3, 5):
    fbb = ExactRot(arms[d][1]).frac(kk)
    act = np.abs(P_eval(PI_K1, np.exp(2j * np.pi * faa), np.exp(2j * np.pi * fbb)))
    print("   d=%d   max |actual - R5 closed form| = %.3e   %s"
          % (d, np.max(np.abs(act - pred)),
             "HOLDS" if np.max(np.abs(act - pred)) < 1e-12 else "FAILS  <-- R-5 formula is d=1 only"))
print("\nDONE X_01")
