"""R2 for fractons: the writer exists and is non-local -- but WHAT SHAPE is it?
For the toric code the writer is a 1-cycle (a string): weight ~ extent.
Haah's cubic code has NO string logical operators (Haah 2011).  We measure the
SHAPE of the lowest-weight logical we can find: its bounding box vs its weight."""
import sys, random, itertools
sys.path.insert(0,"/Users/bgm/MB Work/where-atoms-come-from/LANE_O78_FRACTON_NONABELIAN")
from gf2 import *
from models import *

def support_geometry(v, n, L, cell):
    pts = []
    for i in range(n):
        if ((xpart(v,n)>>i)&1) or ((zpart(v,n)>>i)&1):
            pts.append(cell(i))
    if not pts: return None
    # smallest periodic bounding box per axis
    ext = []
    for t in range(3):
        vals = sorted(set(p[t] for p in pts))
        best = L
        for s in vals:
            m = max((x - s) % L for x in vals)
            best = min(best, m+1)
        ext.append(best)
    return len(pts), sorted(ext, reverse=True)

def probe(name, gens, n, L, cell, trials=3000, seed=3):
    _, pivS = rank_gf2(gens)
    N = normaliser_basis(gens, n)
    rng = random.Random(seed)
    best = None; bestv = None
    for _ in range(trials):
        v = 0
        for b in N:
            if rng.getrandbits(1): v ^= b
        if v == 0 or in_span(pivS, v): continue
        w = pweight(v,n); improved = True
        while improved:
            improved = False
            for b in N:
                v2 = v ^ b
                if v2 == 0 or in_span(pivS, v2): continue
                w2 = pweight(v2,n)
                if w2 < w: v, w = v2, w2; improved = True
        if best is None or w < best: best, bestv = w, v
    ns, ext = support_geometry(bestv, n, L, cell)
    print(f"  {name:22s} lowest logical found: weight {best:4d}   support sites {ns:4d}   "
          f"bounding box {ext[0]}x{ext[1]}x{ext[2]}")
    return best, ext

print("SHAPE OF THE WRITER (lowest-weight logical operator found; weights are UPPER BOUNDS)")
print("A STRING has bounding box L x 1 x 1.  A FRACTAL / MEMBRANE does not.\n")
for L in (3,4):
    cell3 = lambda i,L=L: ((i//3)//(L*L), ((i//3)//L)%L, (i//3)%L)
    cell2 = lambda i,L=L: ((i//2)//(L*L), ((i//2)//L)%L, (i//2)%L)
    cell1 = lambda i,L=L: (i//(L*L), (i//L)%L, i%L)
    print(f"L = {L}")
    probe("3D toric (control)", *toric3d(L), L, cell3, trials=1200)
    probe("X-cube", *xcube(L), L, cell3, trials=1200)
    probe("Haah CC1", *haah(L), L, cell2, trials=1200)
    if L % 2 == 0:
        probe("checkerboard", *checkerboard(L), L, cell1, trials=1200)
    print()

print("""CONTROL: the 3D toric code's lowest logical MUST be a string (bounding box L x 1 x 1),
because H_1(T^3) is generated by the three straight non-contractible loops.  If the probe
returns a string there and a non-string for Haah, the shape difference is real and is not
an artefact of the search.""")
