#!/usr/bin/env python3
"""THE CLAIMS GRID — the program's headline claims, their stage, and their anchors' LIVE statuses.

  ./ledger/claims.py                  render (and rewrite THE_CLAIMS_V001.md)
  ./ledger/claims.py set G-D STAGE    change one claim's stage
  ./ledger/claims.py anchors G-D "C-77;C-90"   change a claim's anchor rows
  ./ledger/claims.py next G-D "T-51;T-49"      change the live next-task list
  ./ledger/claims.py urm G-D "GEOMETRY layer"  change the URM-location cell

Commissioned by the principal, 2026-08-21: a grid of the MAIN claims beside the model — the final
deliverable being the URM with the ability to prove each of these. House discipline throughout:
ledger/claims.tsv is the source of truth, this grid is GENERATED, rows append and never renumber.
Anchor statuses are pulled LIVE from ledger/status_ledger.tsv at render time, so the claims grid can
never silently go stale against the record — a stale anchor shows itself on every render.

THE REFUSAL: a claim may not carry stage PROVED-AT-BAR unless EVERY anchor row is PROVED in the
ledger. The bar is the principal's (any physicist, their own data) and the tool holds it here
exactly as status.py holds it row-level. Stages are a closed vocabulary (below)."""
import csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CLAIMS = os.path.join(HERE, "claims.tsv")
LEDGER = os.path.join(HERE, "status_ledger.tsv")
PLAN = os.path.join(HERE, "plan.tsv")
OUT = os.path.join(ROOT, "THE_CLAIMS_V001.md")

STAGES = ["IDENTIFIED", "FORMAL-PARTIAL", "FORMAL-COMPLETE", "GROUNDED-NOT-EARNED",
          "STATED-ON-TWO-CARRIERS", "MEMBER-LEVEL-MATCH", "WORLD-CONTACT-PARTIAL",
          "IN-CONSTRUCTION", "PROVED-AT-BAR"]

STAGE_MEANING = {
 "IDENTIFIED": "the claim is posed and instrumented; no scored computation yet",
 "FORMAL-PARTIAL": "established in part about the program's own definition; gaps named",
 "FORMAL-COMPLETE": "the formal account is complete on the model's objects; no real-data contact",
 "GROUNDED-NOT-EARNED": "the world passes the definition, but why-THIS-definition is open (H-3)",
 "STATED-ON-TWO-CARRIERS": "the statement stands with every load-bearing clause on marked rows",
 "MEMBER-LEVEL-MATCH": "a computed member matches a known form; occupancy/enforcement/norm unearned",
 "WORLD-CONTACT-PARTIAL": "at least one constituent row meets the PROOF bar; the rest do not",
 "IN-CONSTRUCTION": "the deliverable is being built; its own gates say what is missing",
 "PROVED-AT-BAR": "every anchor row is PROVED: a physicist anywhere can run it on their own data",
}

def load(path):
    with open(path, newline="") as f:
        rows = list(csv.reader(f, delimiter="\t", quoting=csv.QUOTE_NONE))
    return rows[0], [r for r in rows[1:] if r and r[0].strip()]

def statuses():
    _, rows = load(LEDGER)
    return {r[0]: r[3] for r in rows if len(r) > 3}

def plan_status():
    _, rows = load(PLAN)
    return {r[0]: r[3] for r in rows if len(r) > 3}

def render():
    hdr, rows = load(CLAIMS)
    st, pl = statuses(), plan_status()
    for r in rows:
        if r[3] not in STAGES:
            sys.exit("stage outside the closed vocabulary: %s (%s)" % (r[3], r[0]))
        if r[3] == "PROVED-AT-BAR":
            bad = [a for a in r[4].split(";") if st.get(a.strip()) != "PROVED"]
            if bad:
                sys.exit("REFUSED: %s claims PROVED-AT-BAR but these anchors are not PROVED: %s"
                         % (r[0], ", ".join(bad)))
    L = ["# THE CLAIMS — WHERE ATOMS COME FROM — V001", "",
         "**Generated by `./ledger/claims.py` from `ledger/claims.tsv` — never hand-edited. Anchor",
         "statuses are read LIVE from the status ledger at render time. A claim may not carry",
         "`PROVED-AT-BAR` unless every anchor row is `PROVED`; the tool refuses otherwise.**", "",
         "> **The deliverable (the principal, 2026-08-21): the URM — the world model, the framework",
         "> new observations enter — with the ability to prove each claim below.**", ""]
    L.append("| # | claim | stage | anchors (live status) | next | where in the URM |")
    L.append("|---|---|---|---|---|---|")
    for r in rows:
        anchors = " · ".join("`%s` %s" % (a.strip(), st.get(a.strip(), "?")) for a in r[4].split(";"))
        nxt = " ".join("`%s`(%s)" % (t.strip(), pl.get(t.strip(), "?")) for t in r[5].split(";"))
        L.append("| **%s** | **%s** — %s | **%s** | %s | %s | %s |" % (r[0], r[1], r[2], r[3], anchors, nxt, r[6]))
    L += ["", "## THE STAGE VOCABULARY (closed)", "", "| stage | meaning |", "|---|---|"]
    for s in STAGES:
        L.append("| `%s` | %s |" % (s, STAGE_MEANING[s]))
    L += ["", "> Stages move by registrar act with a register entry; anchors and NEXT move with the",
          "> record. The grid is a VIEW of the ledger and the plan, never a second source of truth."]
    open(OUT, "w").write("\n".join(L) + "\n")
    return "\n".join(L) + "\n"

def main():
    a = sys.argv[1:]
    hdr, rows = load(CLAIMS)
    if not a or a[0] == "render":
        sys.stdout.write(render()); return
    if a[0] == "set":
        rid, stage = a[1], a[2]
        if stage not in STAGES: sys.exit("stage outside the closed vocabulary: %s" % stage)
        hit = [r for r in rows if r[0] == rid]
        if not hit: sys.exit("no such claim: %s" % rid)
        old = hit[0][3]; hit[0][3] = stage
    elif a[0] == "anchors":
        hit = [r for r in rows if r[0] == a[1]]
        if not hit: sys.exit("no such claim: %s" % a[1])
        old = hit[0][4]; hit[0][4] = a[2]
    elif a[0] == "next":
        hit = [r for r in rows if r[0] == a[1]]
        if not hit: sys.exit("no such claim: %s" % a[1])
        old = hit[0][5]; hit[0][5] = a[2]
    elif a[0] == "urm":
        hit = [r for r in rows if r[0] == a[1]]
        if not hit: sys.exit("no such claim: %s" % a[1])
        old = hit[0][6]; hit[0][6] = a[2]
    else:
        sys.exit(__doc__)
    with open(CLAIMS, "w", newline="") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n", quoting=csv.QUOTE_NONE)
        w.writerow(hdr); w.writerows(rows)
    render(); print("%s: %s -> %s" % (a[1], old, a[2]))

if __name__ == "__main__":
    main()
