#!/usr/bin/env python3
"""THE STATUS RECORD — retrieve and update, never retype.

  ./ledger/status.py                      render the grid (and rewrite STATUS_LEDGER_V001.md)
  ./ledger/status.py set C-1 PROVED        change one status cell
  ./ledger/status.py set C-1 PROVED "Thm E"   change status and evidence
  ./ledger/status.py text A-GR "new wording"     reword an item (claim unchanged)\n  ./ledger/status.py add ROLE X-7 "item text" OPEN   append a new row
  ./ledger/status.py blocked C-1 "T-50"          name what a PARTIAL row waits on

Row ORDER IS FILE ORDER and is never sorted, so IDs never renumber and the rendered
grid is byte-stable unless a cell actually changed. Rows are appended, never deleted:
a row that stops being true becomes WITHDRAWN or FAILED, it does not disappear.
"""
import re, sys, os, csv, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LEDGER = os.path.join(HERE, 'status_ledger.tsv')
VOCAB  = os.path.join(HERE, 'STATUS_VOCAB.tsv')
OUT    = os.path.join(ROOT, 'STATUS_LEDGER_V001.md')

AREAS = [('HARD',        'H. THE HARD PROBLEMS — what stands between here and the goal'),
         ('PROOF',       'P. THE ROAD TO A FULL PROOF — the controlled plan'),
         ('DOCTRINE',    'O. STANDING DOCTRINE — checked before any lane is commissioned'),
         ('ROLE',        'A. THE THREE ROLES — the charter\'s question'),
         ('CLAIM',       'B. THE CLAIM, STATEMENT BY STATEMENT'),
         ('GRAVITY',     'C. GRAVITY AT THE RECORD LEVEL'),
         ('OBSTRUCTION', 'D. OBSTRUCTIONS — solvable here'),
         ('OUT OF REACH','E. OUT OF REACH HERE — named, not deferred'),
         ('TARGET',      'F. THE TARGET\'S UNADDRESSED ITEMS')]

# fixed display order; unlisted statuses sort last, alphabetically
RANK = ['PROVED','DERIVED','MEASURED','PARTIAL','CANDIDATE','DEFINED',
        'OPEN','BLOCKED','FAILED','WITHDRAWN','RECLASSIFIED','NOT OURS']

def load(path):
    with open(path, newline='') as f:
        r = list(csv.reader(f, delimiter='\t'))
    return r[0], r[1:]

def save(hdr, rows):
    with open(LEDGER, 'w', newline='') as f:
        w = csv.writer(f, delimiter='\t', lineterminator='\n')
        w.writerow(hdr); w.writerows(rows)

def esc(s):
    return s.replace('|', '\\|')

def render():
    hdr, rows = load(LEDGER)
    _, vocab = load(VOCAB)
    valid = {v[0] for v in vocab}
    bad = [(r[0], r[3]) for r in rows if r[3] not in valid]
    if bad:
        sys.exit('STATUS NOT IN THE CLOSED VOCABULARY: %s' % bad)
    ids = [r[0] for r in rows]
    if len(ids) != len(set(ids)):
        sys.exit('DUPLICATE ROW IDs: %s' % [i for i in ids if ids.count(i) > 1])

    L = ['# STATUS LEDGER — WHERE ATOMS COME FROM', '',
         '**THIS IS THE RECORD. It is not re-derived at each status; it is retrieved and updated.**',
         '`ledger/status_ledger.tsv` is the source of truth; this file is generated by `ledger/status.py`.',
         'Rows are **appended, never renumbered or deleted** — a row that stops holding becomes',
         '`WITHDRAWN` or `FAILED` in place. Only the STATUS cell normally moves.', '',
         'Anchor `CORE_FRAMEWORK_V001.md` · standing corrections `STANDING_CORRECTIONS_V001.md` ·',
         'proofs `PROOF_V001.md` · withdrawn claims `THE_ROAD_V001.md` · narrative `STATUS_V001.md`', '']

    tally = {}
    for r in rows:
        tally[r[3]] = tally.get(r[3], 0) + 1
    order = sorted(tally, key=lambda s: (RANK.index(s) if s in RANK else 99, s))
    L += ['## THE COUNT', '',
          '| ' + ' | '.join(order) + ' |',
          '|' + '---|' * len(order),
          '| ' + ' | '.join(str(tally[s]) for s in order) + ' |', '',
          '**%d rows.**' % len(rows), '', '---', '']

    for key, title in AREAS:
        sel = [r for r in rows if r[1] == key]
        if not sel:
            continue
        L += ['## ' + title, '',
              '| ID | ITEM | STATUS | EVIDENCE | BLOCKED BY | WOULD BE REFUTED BY |',
              '|---|---|:---:|---|---|---|']
        for r in sel:
            i, _, item, st, ev, bl, rf = (r + [''] * 7)[:7]
            L.append('| **%s** | %s | **%s** | %s | %s | %s |' %
                     (i, esc(item), st, esc(ev or '—'), esc(bl or '—'), esc(rf or '—')))
        L += ['']

    L += ['---', '', '## THE CLOSED VOCABULARY — a status outside this list is an error', '',
          '| STATUS | MEANING |', '|---|---|']
    for v in vocab:
        L.append('| `%s` | %s |' % (v[0], v[1]))
    L += ['', '---', '',
          '> **A record is a bit the world cannot lose locally. EM provides the carrier, alpha sets',
          '> what it costs, and the topology of space is what makes the bit exist, writable, and safe.**', '']

    txt = '\n'.join(L)
    with open(OUT, 'w') as f:
        f.write(txt)
    return txt


def grounded(row):
    """A row is GROUNDED when it names a test ANY PHYSICIST ANYWHERE can run against THEIR OWN
       real-world data, on ANY RECORD SURFACE, and confirm works as asserted.

       STRENGTHENED 2026-08-20. The principal: "PROOF means that someone anywhere in the world can
       prove that our calculation agrees with ANY RECORD SURFACE." One named record is not enough --
       that is an instance, not a proof. The grounding must carry a line

           RECORDS VERIFIED: <name>; <name>; ...

       listing at least TWO STRUCTURALLY DIFFERENT real record surfaces on which the calculation was
       checked. Different mechanism, not different parameters: a magnetic grain and a floating gate
       count; two grain sizes do not.

       The principal, 2026-08-20: "The PROOF must be something that any physicist anywhere in the
       world can run against their real world data and confirm that it works as asserted. That is a
       proof. Otherwise we're not proving anything other than that we can construct equations."

       Naming a real record is NOT enough -- that was the registrar's weaker first attempt. The row
       must name the MEASURABLE QUANTITY, the PREDICTED VALUE, and WHAT WOULD FALSIFY IT."""
    g = row[7] if len(row) > 7 else ''
    if not g.strip() or g.strip().upper().startswith('UNGROUNDED'):
        return False
    m = re.search(r'RECORDS VERIFIED:(.*)', g, re.I)
    if not m:
        return False
    # DEDUPED: 'RECORDS VERIFIED: a; a' fooled the parser (solidity review, guard probe).
    names = {x.strip().lower() for x in m.group(1).split(';') if x.strip()}
    return len(names) >= 2


def ungrounded_msg(rid):
    return ('REFUSED: %s cannot be PROVED.\n'
            '\n'
            '  PROVED means: a test ANY PHYSICIST ANYWHERE can run against THEIR OWN real-world\n'
            '  data, ON ANY RECORD SURFACE, and confirm works as asserted. The row must name:\n'
            '     1. the MEASURABLE QUANTITY, in units;\n'
            '     2. the PREDICTED VALUE or relation;\n'
            '     3. WHAT WOULD FALSIFY IT;\n'
            '     4. a line reading  RECORDS VERIFIED: <name>; <name>  listing at least TWO\n'
            '        STRUCTURALLY DIFFERENT real record surfaces it was checked on. Different\n'
            '        MECHANISM, not different parameters. One record is an instance, not a proof.\n'
            '\n'
            '  Set it:   ./ledger/status.py ground %s "<quantity, prediction, falsifier>"\n'
            '\n'
            '  If the row is about the program\'s STIPULATED definition rather than the world, it\n'
            '  is not PROVED. Use FORMAL — real mathematics, no contact with a real record.\n'
            '\n'
            '  The principal, 2026-08-20: "The PROOF must be something that any physicist anywhere\n'
            '  in the world can run against their real world data and confirm that it works as\n'
            '  asserted. That is a proof. Otherwise we\'re not proving anything other than that we\n'
            '  can construct equations."'
            % (rid, rid))


def main():
    a = sys.argv[1:]
    if not a or a[0] == 'render':
        sys.stdout.write(render()); return
    hdr, rows = load(LEDGER)
    if a[0] == 'set':
        rid, st = a[1], a[2]
        _, vocab = load(VOCAB)
        if st not in {v[0] for v in vocab}:
            sys.exit('not in the closed vocabulary: %s' % st)
        hit = [r for r in rows if r[0] == rid]
        if not hit:
            sys.exit('no such row: %s' % rid)
        # THE GROUNDING REQUIREMENT (H-3, the principal 2026-08-20). A row cannot be PROVED unless it
        # names the REAL RECORD it was tested against. This is a REFUSAL, not a reminder: the program
        # spent two days proving things about a stipulation because every previous guard was a doctrine
        # row or a hand-checked box, which looked handled and changed nothing.
        if st == 'PROVED' and not grounded(hit[0]):
            sys.exit(ungrounded_msg(rid))
        old = hit[0][3]; hit[0][3] = st
        if len(a) > 3: hit[0][4] = a[3]
        save(hdr, rows); render()
        print('%s: %s -> %s' % (rid, old, st))
    elif a[0] == 'text':
        rid = a[1]
        hit = [r for r in rows if r[0] == rid]
        if not hit:
            sys.exit('no such row: %s' % rid)
        old = hit[0][2]; hit[0][2] = a[2]
        save(hdr, rows); render()
        print('%s text updated\n  was: %s\n  now: %s' % (rid, old, a[2]))
    elif a[0] == 'add':
        area, rid, item, st = a[1], a[2], a[3], a[4]
        if any(r[0] == rid for r in rows):
            sys.exit('id already used: %s' % rid)
        row = [rid, area, item, st] + (list(a[5:9]) + [''] * 4)[:4]
        if st == 'PROVED' and not grounded(row):
            sys.exit(ungrounded_msg(rid))
        rows.append(row)
        save(hdr, rows); render()
        print('appended %s' % rid)
    elif a[0] == 'ground':
        rid = a[1]
        hit = [r for r in rows if r[0] == rid]
        if not hit:
            sys.exit('no such row: %s' % rid)
        while len(hit[0]) < 8: hit[0].append('')
        old = hit[0][7]; hit[0][7] = a[2]
        save(hdr, rows); render()
        print('%s grounded\n  was: %s\n  now: %s' % (rid, old or '(nothing)', a[2]))
    elif a[0] == 'blocked':
        # PARTIAL's own definition is "one direction proved, the other open -- NAMED IN BLOCKED_BY".
        # Until now no command could write that column, so the naming lived in prose and the closed
        # vocabulary's promise was unkeepable through the tool. It is keepable now.
        rid = a[1]
        hit = [r for r in rows if r[0] == rid]
        if not hit:
            sys.exit('no such row: %s' % rid)
        while len(hit[0]) < 8: hit[0].append('')
        old = hit[0][5]; hit[0][5] = a[2]
        save(hdr, rows); render()
        print('%s blocked_by\n  was: %s\n  now: %s' % (rid, old or '(nothing)', a[2]))
    elif a[0] == 'ungrounded':
        bad = [r for r in rows if r[3] == 'PROVED' and not grounded(r)]
        pr = [r for r in rows if r[3] == 'PROVED']
        print('%d of %d PROVED rows are UNGROUNDED — no test a physicist could run against their own data' % (len(bad), len(pr)))
        for r in bad: print('  %-8s %s' % (r[0], r[2][:88]))
    else:
        sys.exit(__doc__)

main()
