#!/usr/bin/env python3
"""THE STATUS RECORD — retrieve and update, never retype.

  ./ledger/status.py                      render the grid (and rewrite STATUS_LEDGER_V001.md)
  ./ledger/status.py set C-1 PROVED        change one status cell
  ./ledger/status.py set C-1 PROVED "Thm E"   change status and evidence
  ./ledger/status.py add ROLE X-7 "item text" OPEN   append a new row

Row ORDER IS FILE ORDER and is never sorted, so IDs never renumber and the rendered
grid is byte-stable unless a cell actually changed. Rows are appended, never deleted:
a row that stops being true becomes WITHDRAWN or FAILED, it does not disappear.
"""
import sys, os, csv, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LEDGER = os.path.join(HERE, 'status_ledger.tsv')
VOCAB  = os.path.join(HERE, 'STATUS_VOCAB.tsv')
OUT    = os.path.join(ROOT, 'STATUS_LEDGER_V001.md')

AREAS = [('ROLE',        'A. THE THREE ROLES — the charter\'s question'),
         ('CLAIM',       'B. THE CLAIM, STATEMENT BY STATEMENT'),
         ('GRAVITY',     'C. GRAVITY AT THE RECORD LEVEL'),
         ('OBSTRUCTION', 'D. OBSTRUCTIONS — solvable here'),
         ('OUT OF REACH','E. OUT OF REACH HERE — named, not deferred'),
         ('TARGET',      'F. THE TARGET\'S UNADDRESSED ITEMS')]

# fixed display order; unlisted statuses sort last, alphabetically
RANK = ['PROVED','DERIVED','MEASURED','PARTIAL','CANDIDATE','DEFINED',
        'OPEN','BLOCKED','FAILED','WITHDRAWN','RECLASSIFIED','NOT OURS']

def load(path):
    with open(path, newline='') as f:
        r = list(csv.reader(f, delimiter='\t'))
    return r[0], r[1:]

def save(hdr, rows):
    with open(LEDGER, 'w', newline='') as f:
        w = csv.writer(f, delimiter='\t', lineterminator='\n')
        w.writerow(hdr); w.writerows(rows)

def esc(s):
    return s.replace('|', '\\|')

def render():
    hdr, rows = load(LEDGER)
    _, vocab = load(VOCAB)
    valid = {v[0] for v in vocab}
    bad = [(r[0], r[3]) for r in rows if r[3] not in valid]
    if bad:
        sys.exit('STATUS NOT IN THE CLOSED VOCABULARY: %s' % bad)
    ids = [r[0] for r in rows]
    if len(ids) != len(set(ids)):
        sys.exit('DUPLICATE ROW IDs: %s' % [i for i in ids if ids.count(i) > 1])

    L = ['# STATUS LEDGER — WHERE ATOMS COME FROM', '',
         '**THIS IS THE RECORD. It is not re-derived at each status; it is retrieved and updated.**',
         '`ledger/status_ledger.tsv` is the source of truth; this file is generated by `ledger/status.py`.',
         'Rows are **appended, never renumbered or deleted** — a row that stops holding becomes',
         '`WITHDRAWN` or `FAILED` in place. Only the STATUS cell normally moves.', '',
         'Anchor `CORE_FRAMEWORK_V001.md` · standing corrections `STANDING_CORRECTIONS_V001.md` ·',
         'proofs `PROOF_V001.md` · withdrawn claims `THE_ROAD_V001.md` · narrative `STATUS_V001.md`', '']

    tally = {}
    for r in rows:
        tally[r[3]] = tally.get(r[3], 0) + 1
    order = sorted(tally, key=lambda s: (RANK.index(s) if s in RANK else 99, s))
    L += ['## THE COUNT', '',
          '| ' + ' | '.join(order) + ' |',
          '|' + '---|' * len(order),
          '| ' + ' | '.join(str(tally[s]) for s in order) + ' |', '',
          '**%d rows.**' % len(rows), '', '---', '']

    for key, title in AREAS:
        sel = [r for r in rows if r[1] == key]
        if not sel:
            continue
        L += ['## ' + title, '',
              '| ID | ITEM | STATUS | EVIDENCE | BLOCKED BY | WOULD BE REFUTED BY |',
              '|---|---|:---:|---|---|---|']
        for r in sel:
            i, _, item, st, ev, bl, rf = (r + [''] * 7)[:7]
            L.append('| **%s** | %s | **%s** | %s | %s | %s |' %
                     (i, esc(item), st, esc(ev or '—'), esc(bl or '—'), esc(rf or '—')))
        L += ['']

    L += ['---', '', '## THE CLOSED VOCABULARY — a status outside this list is an error', '',
          '| STATUS | MEANING |', '|---|---|']
    for v in vocab:
        L.append('| `%s` | %s |' % (v[0], v[1]))
    L += ['', '---', '',
          '> **A record is a bit the world cannot lose locally. EM provides the carrier, alpha sets',
          '> what it costs, and the topology of space is what makes the bit exist, writable, and safe.**', '']

    txt = '\n'.join(L)
    with open(OUT, 'w') as f:
        f.write(txt)
    return txt

def main():
    a = sys.argv[1:]
    if not a or a[0] == 'render':
        sys.stdout.write(render()); return
    hdr, rows = load(LEDGER)
    if a[0] == 'set':
        rid, st = a[1], a[2]
        _, vocab = load(VOCAB)
        if st not in {v[0] for v in vocab}:
            sys.exit('not in the closed vocabulary: %s' % st)
        hit = [r for r in rows if r[0] == rid]
        if not hit:
            sys.exit('no such row: %s' % rid)
        old = hit[0][3]; hit[0][3] = st
        if len(a) > 3: hit[0][4] = a[3]
        save(hdr, rows); render()
        print('%s: %s -> %s' % (rid, old, st))
    elif a[0] == 'add':
        area, rid, item, st = a[1], a[2], a[3], a[4]
        if any(r[0] == rid for r in rows):
            sys.exit('id already used: %s' % rid)
        rows.append([rid, area, item, st] + (a[5:8] + ['', '', ''])[:3])
        save(hdr, rows); render()
        print('appended %s' % rid)
    else:
        sys.exit(__doc__)

main()
