#!/usr/bin/env python3
"""
LANE R-GROUP REFUTER — part 4. The two-cell exhibit that decides the claim.

The claim's wall:  "hold at d = 1, fail at d >= 2, WHETHER OR NOT THE GROUP IS
ABELIAN."  Four boxes:

                     |  holonomy pair CENTRAL   |  holonomy pair NON-CENTRAL
   group ABELIAN     |        (i)               |        (ii)
   group NON-ABELIAN |        (iii)             |        (iv)

The claim predicts every d>=2 box fails. Boxes (i) and (iii) HOLD EXACTLY.
"""
import numpy as np

NV = 5
A = np.array([1, 1, 1, 0, 0])
B = np.array([1, 0, 0, 1, 1])
p_S3 = np.array([0.4, 0.15, 0.15, 0.15, 0.15])
f0, c0 = 2.0, 1.1


def Zk(WF, WC, S, ks):
    d = S.shape[1]
    out = np.empty(len(ks), complex)
    for i, k in enumerate(ks):
        FF = np.linalg.matrix_power(WF, int(k))
        CC = np.linalg.matrix_power(WC, int(k))
        t = 0j
        for v in range(NV):
            L = FF @ S[v] if A[v] else S[v]
            R = CC @ S[v] if B[v] else S[v]
            t += np.vdot(L, R)
        out[i] = t
    return out


def Zk_d1(u, v, p, ks):
    return np.array([sum(p[w] * u ** (k * A[w]) * v ** (k * B[w]) for w in range(NV))
                     for k in ks], dtype=complex)


ks = np.arange(0, 401)
rng = np.random.default_rng(1414213)              # SEED PUBLISHED

# --- Q8 in its 2-dimensional irreducible representation
I2 = np.eye(2, dtype=complex)
i_ = np.array([[1j, 0], [0, -1j]])
j_ = np.array([[0, 1], [-1, 0]], dtype=complex)
k_ = i_ @ j_
Q8 = {"1": I2, "-1": -I2, "i": i_, "-i": -i_, "j": j_, "-j": -j_, "k": k_, "-k": -k_}
print("Q8 (2-dim irrep) non-abelian?  ||[i,j]|| = %.6f" % np.linalg.norm(i_ @ j_ - j_ @ i_))
print("Q8 centre = {1, -1}\n")


def report(name, WF, WC, u_scalar, v_scalar):
    S = rng.normal(size=(NV, 2)) + 1j * rng.normal(size=(NV, 2))
    for v in range(NV):
        S[v] *= np.sqrt(p_S3[v]) / np.linalg.norm(S[v])
    Zg = Zk(WF, WC, S, ks)
    dev_state = []
    for _ in range(8):
        T = rng.normal(size=(NV, 2)) + 1j * rng.normal(size=(NV, 2))
        for v in range(NV):
            T[v] *= np.sqrt(p_S3[v]) / np.linalg.norm(T[v])
        dev_state.append(abs(Zk(WF, WC, T, [1])[0]))
    dev_state = np.array(dev_state)
    com = np.linalg.norm(WF @ WC - WC @ WF)
    cen = max(np.linalg.norm(WF - (np.trace(WF) / 2) * np.eye(2)),
              np.linalg.norm(WC - (np.trace(WC) / 2) * np.eye(2)))
    line = "  %-46s ||[.,.]||=%.3f  dist(centre)=%.3f" % (name, com, cen)
    print(line)
    if u_scalar is not None:
        d1 = Zk_d1(u_scalar, v_scalar, p_S3, ks)
        print("     max |Z_k(d=2) - Z_k(d=1 with same class weights)|, k<=400 = %.3e"
              % np.max(np.abs(Zg - d1)))
    print("     |Z_1| spread over 8 states with IDENTICAL class weights   = %.3e"
          % (dev_state.max() - dev_state.min()))


print("(i)   ABELIAN GROUP, CENTRAL PAIR, d = 2")
report("U(1) acting as e^{i.} I_2", np.exp(1j * f0) * I2, np.exp(1j * c0) * I2,
       np.exp(-1j * f0), np.exp(1j * c0))

print("\n(iii) NON-ABELIAN GROUP Q8, CENTRAL PAIR, d = 2")
report("W_F = -1, W_C = -1  (both in the centre of Q8)", -I2, -I2, -1.0 + 0j, -1.0 + 0j)
report("W_F = -1, W_C = +1  (both in the centre of Q8)", -I2, I2, -1.0 + 0j, 1.0 + 0j)

print("\n(ii)  ABELIAN GROUP, NON-CENTRAL PAIR, d = 2")
report("diag charges (1,2) of U(1)",
       np.diag([np.exp(1j * f0), np.exp(2j * f0)]),
       np.diag([np.exp(1j * c0), np.exp(2j * c0)]), None, None)

print("\n(iv)  NON-ABELIAN GROUP Q8, NON-CENTRAL PAIR, d = 2")
report("W_F = i, W_C = j", i_, j_, None, None)

print("""
VERDICT ON THE FOUR BOXES
  (i)   abelian,     central     : HOLDS  (identical to d=1, ~1e-14)
  (iii) NON-abelian, central     : HOLDS  (identical to d=1, ~1e-14)
  (ii)  abelian,     non-central : FAILS
  (iv)  NON-abelian, non-central : FAILS

The dividing line runs HORIZONTALLY through this table in the CENTRAL /
NON-CENTRAL direction, not vertically through ABELIAN / NON-ABELIAN, and not
at all through d. Box (iii) alone refutes the claim as written: fibre
dimension two, group NON-ABELIAN, and every S4 result holds to 1e-14.

FORMATION STILL FIRES IN BOX (iii): W_F = -1, W_C = +1 gives u = -1, v = 1,
characters chi_0 = -1, chi_F = -1, chi_C = 1, so G = <-1> != {1}. This is not
a degenerate no-formation corner.
""")

# the S2/W-02 criterion, evaluated in box (iii), to show it is not vacuous
for nm, (WF, WC) in [("W_F=-1,W_C=-1", (-I2, -I2)), ("W_F=-1,W_C=+1", (-I2, I2))]:
    u, v = complex(np.trace(WF.conj().T) / 2), complex(np.trace(WC) / 2)
    chi = {"chi_0": u * v, "chi_F": u, "chi_C": v}
    ratios = set()
    for a in chi.values():
        for b in chi.values():
            ratios.add(complex(np.round(a / b, 12)))
    print("  %s : chi_0=%s chi_F=%s chi_C=%s  ->  G generated by %s  -> formation %s"
          % (nm, chi["chi_0"], chi["chi_F"], chi["chi_C"], sorted(ratios, key=abs),
             "OCCURS" if ratios != {1 + 0j} else "does NOT occur"))
