#!/usr/bin/env python3
"""
LANE_R_GROUP_REFUTER -- rg_lib.py
Written from scratch for the group-axis REFUTATION.  No corpus code reused.

PUBLISHED CONVENTIONS (this file is the only source of truth for this lane)
==========================================================================

CARRIER K1 (S1_CARRIER_K1_V001.md sections 1-2), vertices indexed 0..4 = v0..v4,
edges indexed 0..5 = e1..e6.

  e1: v0->v1   e2: v1->v2   e3: v2->v0   e4: v0->v3   e5: v3->v4   e6: v4->v0
  F attached along e1+e2+e3.

d1 = boundary C_1 -> C_0, ROWS = vertices v0..v4, COLS = edges e1..e6,
     d1[v,e] = +1 if v = target(e), -1 if v = source(e), 0 else.

        e1  e2  e3  e4  e5  e6
   v0 [ -1   0  +1  -1   0  +1 ]
   v1 [ +1  -1   0   0   0   0 ]
   v2 [  0  +1  -1   0   0   0 ]
   v3 [  0   0   0  +1  -1   0 ]
   v4 [  0   0   0   0  +1  -1 ]

d2 = boundary C_2 -> C_1, ROWS = edges e1..e6, COLS = faces (F only).
   d2 = [1,1,1,0,0,0]^T.   d1 @ d2 = 0 is CHECKED, not asserted.

LOOPS.  gamma_F = e1.e2.e3 (vertices {v0,v1,v2});  gamma_C = e4.e5.e6 ({v0,v3,v4}).
CLASS MAP.  a_v = 1 iff v on gamma_F, b_v = 1 iff v on gamma_C.
   v0 -> (1,1);  v1,v2 -> (1,0);  v3,v4 -> (0,1).  NO class-(0,0) vertex on K1.

THE FORMATION FUNCTIONAL (W-01 / W-02 as restated in the lane brief).
Loop operator (M_gamma s)(v) = rho(W(gamma)) s(v) for v on gamma, s(v) otherwise.
The stage-k datum is the overlap of the two separately transported sections:

    Z_k = < M_F^k s , M_C^k s >
        = SUM_v  < s_v ,  rho(W_F)^{-k a_v} rho(W_C)^{+k b_v} s_v >          (*)
    lambda = lim_N (1/N) SUM_{k=1..N} log |Z_k|

(*) is the ONLY dynamical definition used in this lane.  At rank one and unit
charge it collapses to  Z_k = SUM_v p_v (u^{a_v} v^{b_v})^k,  u = conj(W_F),
v = W_C, p_v = |s_v|^2 -- exactly the corpus's chi_0 = uv, chi_F = u, chi_C = v.
It is validated against the corpus's own published K1 rates in rg_0_validate.py.

THE CLOSURE H, AND WHY THE CHARACTER SUPPORT IS EXACT AND NOT AN FFT ESTIMATE.
Z_k depends on k only through (rho(W_F)^{-k}, rho(W_C)^{k}), which runs in the
closure H of the cyclic group generated by (rho(W_F)^{-1}, rho(W_C)).  For a
rank-one structure group each coordinate lies in ONE one-parameter subgroup, so
H is a subtorus of T_F x T_C = T^2.  With

    A(x) = the primitive one-parameter subgroup with A(theta_F) = rho(W_F)^{-1}
    B(y) = the primitive one-parameter subgroup with B(theta_C) = rho(W_C)
    z(x,y) = SUM_v < s_v, A(x)^{a_v} B(y)^{b_v} s_v >,     Z_k = z(k theta_F, k theta_C)

z is a trigonometric polynomial on T^2 whose Fourier coefficients I compute IN
CLOSED FORM by simultaneous eigendecomposition:

    A(x) = V_A diag(e^{i wA x}) V_A^{-1},   B(y) = V_B diag(e^{i wB y}) V_B^{-1}
    class (1,1):  coeff at (wA_j, wB_l) = (s* V_A)_j (V_A^{-1} V_B)_{jl} (V_B^{-1} s)_l
    class (1,0):  coeff at (wA_j, 0)    = (s* V_A)_j (V_A^{-1} s)_j
    class (0,1):  coeff at (0, wB_l)    = (s* V_B)_l (V_B^{-1} s)_l
    class (0,0):  coeff at (0,0)        = |s|^2

    supp(z) = the modes with non-zero coefficient.
    G := subgroup of Z^2 generated by the DIFFERENCES of supp(z).

|z| is invariant under translation by the annihilator of G, so rank G is the
number of independent directions of T^2 that lambda can see.  THIS is the object
THEOREM S4-1 computes and the object the CLAIM proposes to replace.  Note that
the coefficient at a mode can VANISH -- which is exactly why the CLAIM's
"contained in" is not the same statement as its "generates rank 2".

NORMALISATION -- DECLARED, BECAUSE IT IS LOAD-BEARING FOR THE CLAIM.
A(x) must be PRIMITIVE (2-pi-periodic, not a proper power).  For U(1) with
integer fibre weight set Lambda = {w_1..w_d}, A(x) = diag(e^{-i w_j x}) is
primitive iff gcd(w_j) = 1.  For SU(2) fundamental, A(x) = V diag(e^{-ix},e^{ix})
V^{-1}, weights (-1,+1), under the parameterisation W = exp(i theta n.sigma).
Under the other standard parameterisation W = exp(i theta n.sigma / 2) the
weights are (-1/2,+1/2) and the CLAIM's "3x3 grid in Z^2" becomes a grid in
(1/2)Z^2, which is not a subgroup of Hom(T^2,U(1)) = Z^2 at all.  Every result
in this lane is a statement about RANK and is therefore scale-invariant; the
normalisation is declared only because the CLAIM's headline depends on it.
"""

import numpy as np
import math, itertools

# ----------------------------------------------------------------- carrier K1

D1 = np.array([
    [-1,  0, +1, -1,  0, +1],
    [+1, -1,  0,  0,  0,  0],
    [ 0, +1, -1,  0,  0,  0],
    [ 0,  0,  0, +1, -1,  0],
    [ 0,  0,  0,  0, +1, -1],
], dtype=int)

D2 = np.array([[1], [1], [1], [0], [0], [0]], dtype=int)

LOOP_F_VERTS = (0, 1, 2)
LOOP_C_VERTS = (0, 3, 4)

def k1_classes():
    return [(1 if v in LOOP_F_VERTS else 0,
             1 if v in LOOP_C_VERTS else 0) for v in range(5)]

# ------------------------------------------------------------- SU(2) helpers

PX = np.array([[0, 1], [1, 0]], dtype=complex)
PY = np.array([[0, -1j], [1j, 0]], dtype=complex)
PZ = np.array([[1, 0], [0, -1]], dtype=complex)

def su2(axis, theta):
    """exp(i theta n.sigma).  Eigenvalues exp(+- i theta)."""
    n = np.asarray(axis, dtype=float); n = n / np.linalg.norm(n)
    N = n[0] * PX + n[1] * PY + n[2] * PZ
    return math.cos(theta) * np.eye(2, dtype=complex) + 1j * math.sin(theta) * N

# ------------------------------------------- one-parameter subgroups as (V,w)

class OneParam:
    """A(x) = V diag(exp(i w x)) V^{-1}.  `w` INTEGER weights (primitive)."""
    def __init__(self, V, w):
        self.V = np.asarray(V, dtype=complex)
        self.w = np.asarray(w, dtype=int)
        self.Vi = np.linalg.inv(self.V)
        self.d = self.V.shape[0]
    def at(self, x):
        return self.V @ np.diag(np.exp(1j * self.w * x)) @ self.Vi

def op_u1(weights, sign=+1):
    """U(1) structure group, fibre C^d diagonal with integer weights."""
    w = sign * np.asarray(weights, dtype=int)
    return OneParam(np.eye(len(w), dtype=complex), w)

def op_su2(axis, sign=+1):
    """SU(2) fundamental, one-parameter subgroup with the given axis."""
    n = np.asarray(axis, dtype=float); n = n / np.linalg.norm(n)
    N = n[0] * PX + n[1] * PY + n[2] * PZ
    ev, V = np.linalg.eigh(N)          # eigenvalues +-1
    order = np.argsort(-ev)            # (+1, -1)
    V = V[:, order]
    w = sign * np.array([1, -1], dtype=int)
    return OneParam(V, w)

# --------------------------------------------- EXACT character decomposition

def modes(classes, sections, A: OneParam, B: OneParam, tol=1e-12):
    """
    Exact Fourier modes of z(x,y) = SUM_v <s_v, A(x)^{a_v} B(y)^{b_v} s_v>.
    Returns dict {(nx,ny): complex coeff} with |coeff| > tol.
    """
    acc = {}
    def add(key, val):
        acc[key] = acc.get(key, 0j) + val
    VAi_VB = A.Vi @ B.V
    for (a, b), s in zip(classes, sections):
        s = np.asarray(s, dtype=complex)
        if a and b:
            l = s.conj() @ A.V                    # row
            r = B.Vi @ s                          # col
            for j in range(A.d):
                for m in range(B.d):
                    add((int(A.w[j]), int(B.w[m])), l[j] * VAi_VB[j, m] * r[m])
        elif a:
            l = s.conj() @ A.V
            r = A.Vi @ s
            for j in range(A.d):
                add((int(A.w[j]), 0), l[j] * r[j])
        elif b:
            l = s.conj() @ B.V
            r = B.Vi @ s
            for m in range(B.d):
                add((0, int(B.w[m])), l[m] * r[m])
        else:
            add((0, 0), complex(np.vdot(s, s)))
    return {k: v for k, v in acc.items() if abs(v) > tol}

def modes_general(classes, sections, ops, tol=1e-12):
    """
    As `modes`, but with a PER-VERTEX pair ops[v] = (A_v, B_v) of OneParam
    objects.  This is what per-vertex charge requires: the fibre at v carries
    its own representation of the structure group, so there is no single Lambda.
    """
    acc = {}
    def add(key, val):
        acc[key] = acc.get(key, 0j) + val
    for (a, b), s, (A, B) in zip(classes, sections, ops):
        s = np.asarray(s, dtype=complex)
        if a and b:
            Mx = A.Vi @ B.V
            l = s.conj() @ A.V
            r = B.Vi @ s
            for j in range(A.d):
                for m in range(B.d):
                    add((int(A.w[j]), int(B.w[m])), l[j] * Mx[j, m] * r[m])
        elif a:
            l = s.conj() @ A.V; r = A.Vi @ s
            for j in range(A.d):
                add((int(A.w[j]), 0), l[j] * r[j])
        elif b:
            l = s.conj() @ B.V; r = B.Vi @ s
            for m in range(B.d):
                add((0, int(B.w[m])), l[m] * r[m])
        else:
            add((0, 0), complex(np.vdot(s, s)))
    return {k: v for k, v in acc.items() if abs(v) > tol}


def z_from_modes(md):
    """Vectorised evaluator z(X,Y) on numpy arrays."""
    keys = np.array(list(md.keys()), dtype=float)
    vals = np.array(list(md.values()), dtype=complex)
    def z(X, Y):
        X = np.asarray(X, dtype=float); Y = np.asarray(Y, dtype=float)
        out = np.zeros(np.broadcast(X, Y).shape, dtype=complex)
        for (nx, ny), c in zip(keys, vals):
            out = out + c * np.exp(1j * (nx * X + ny * Y))
        return out
    return z

def lattice_rank(points):
    """Rank of the subgroup of Z^2 generated by the DIFFERENCES of `points`."""
    pts = [np.array(p, dtype=float) for p in points]
    if len(pts) < 2:
        return 0
    diffs = np.array([p - pts[0] for p in pts[1:]])
    if not np.any(np.abs(diffs) > 1e-12):
        return 0
    return int(np.linalg.matrix_rank(diffs, tol=1e-8))

# ----------------------------------------------------------------- the rates

def lam_haar(md, M=2048):
    """Haar average of log|z| over the FULL torus T^2, midpoint rule, vectorised.
       Correct when (theta_F,theta_C) are generic so that the closure H = T^2."""
    g = (np.arange(M) + 0.5) * 2.0 * math.pi / M
    X, Y = np.meshgrid(g, g, indexing='ij')
    Z = z_from_modes(md)(X, Y)
    return float(np.mean(np.log(np.maximum(np.abs(Z), 1e-300))))

def lam_direct(md, thF, thC, N=400000):
    """Direct schedule average (1/N) SUM_{k=1..N} log|z(k thF, k thC)|.
       Assumes NOTHING about equidistribution."""
    k = np.arange(1, N + 1, dtype=float)
    Z = z_from_modes(md)(k * thF, k * thC)
    return float(np.mean(np.log(np.maximum(np.abs(Z), 1e-300))))

def support_fft(md, M=64, tol=1e-9):
    """Independent FFT re-derivation of supp(z), to cross-check `modes`."""
    g = np.arange(M) * 2.0 * math.pi / M
    X, Y = np.meshgrid(g, g, indexing='ij')
    arr = z_from_modes(md)(X, Y)
    Fc = np.fft.fft2(arr) / (M * M)
    out = []
    for i in range(M):
        for j in range(M):
            if abs(Fc[i, j]) > tol:
                nx = i if i <= M // 2 else i - M
                ny = j if j <= M // 2 else j - M
                out.append(((nx, ny), Fc[i, j]))
    return sorted(out)

# ------------------------------------------------------- Mahler cross-checks

_BERN = {0: 1.0, 1: -0.5, 2: 1/6, 4: -1/30, 6: 1/42, 8: -1/30, 10: 5/66,
         12: -691/2730, 14: 7/6, 16: -3617/510, 18: 43867/798, 20: -174611/330,
         22: 854513/138}

def _li2_series(z):
    """Li_2 by the Bernoulli series in u = -log(1-z).  Valid for |u| < 2 pi."""
    z = complex(z)
    u = -np.log(1.0 - z)
    s = 0j
    fact = 1.0
    for k in range(0, 23):
        fact = math.factorial(k + 1)
        b = _BERN.get(k, 0.0)
        if b:
            s += b * u ** (k + 1) / fact
    return s

def _li2(z):
    """Li_2(z), principal branch, via inversion + reflection + Bernoulli series.
       Recursion depth is bounded by 2 by construction."""
    z = complex(z)
    if abs(z) > 1.0:                      # inversion -> |1/z| < 1
        return -_li2_inner(1.0 / z) - math.pi ** 2 / 6 - 0.5 * np.log(-z) ** 2
    return _li2_inner(z)

def _li2_inner(z):
    z = complex(z)
    if abs(1.0 - z) < 0.5:                # z near 1: reflect, 1-z is then small
        return math.pi ** 2 / 6 - _li2_series(1.0 - z) - np.log(z) * np.log(1.0 - z)
    return _li2_series(z)

def bloch_wigner(zc):
    zc = complex(zc)
    if abs(zc) < 1e-300:
        return 0.0
    return _li2(zc).imag + math.atan2((1 - zc).imag, (1 - zc).real) * math.log(abs(zc))

def cassaigne_maillot(a, b, c):
    """m(a + b x + c y) for positive reals."""
    a, b, c = float(a), float(b), float(c)
    if a > b + c or b > a + c or c > a + b:
        return math.log(max(a, b, c))
    alpha = math.acos(max(-1.0, min(1.0, (b*b + c*c - a*a) / (2*b*c))))
    beta  = math.acos(max(-1.0, min(1.0, (a*a + c*c - b*b) / (2*a*c))))
    gamma = math.pi - alpha - beta
    zc = (a / b) * complex(math.cos(gamma), math.sin(gamma))
    return (bloch_wigner(zc) + alpha*math.log(a) + beta*math.log(b) + gamma*math.log(c)) / math.pi

# ------------------------------------------------------------ section makers

def sections_from_class_weights(pv, d=1, direction=None, rng=None):
    """
    Ready state: weight pv[class] spread uniformly over the vertices of that
    class; fibre direction `direction` (default (1..1)/sqrt(d)) at every vertex,
    or independent Haar-random directions if rng is given.
    """
    cls = k1_classes()
    counts = {}
    for c in cls:
        counts[c] = counts.get(c, 0) + 1
    out = []
    for c in cls:
        if rng is not None:
            v = rng.normal(size=d) + 1j * rng.normal(size=d)
            v = v / np.linalg.norm(v)
        elif direction is not None:
            v = np.asarray(direction, dtype=complex); v = v / np.linalg.norm(v)
        else:
            v = np.ones(d, dtype=complex) / math.sqrt(d)
        out.append(math.sqrt(pv.get(c, 0.0) / counts[c]) * v)
    n = math.sqrt(sum(float(np.vdot(x, x).real) for x in out))
    return [x / n for x in out]
