#!/usr/bin/env python3
"""
LANE W-10 / C — REFUTER 2 — STEP 4.
(A) A CENSUS OF EVERY CONNECTION THE CORPUS HAS PUBLISHED, WITH ITS RELATION LATTICE COMPUTED
    RATHER THAN NAMED.  Lane C's C-4/C3 assert "lambda = m(P) is FALSE at every connection this
    corpus has ever published"; the headline says "at both connections this corpus has ever
    published".  This step enumerates them from S3/S4 by line number and types each one.
(B) SPOT-CHECKS, OUTSIDE THE LENS BUT CHEAP, of the m(P) values lane C publishes for the two
    ready states whose Jensen integrand has a KINK (branch crossing) and where a plain
    trapezoid is only O(n^-2): K1 SENSE U and B0b*.

TYPING RULE, PROVED ONCE AND APPLIED TO EVERY ROW.  alpha = -f/(2 pi), beta = c/(2 pi).
   m alpha + n beta in Z  <=>  -m f + n c = 2 pi j  for some j in Z.
   If f and c are both RATIONAL the left side is rational, so j = 0 and the relation lattice is
   the rank-one lattice generated by the primitive (m,n) with m/n = c/f.  THEREFORE EVERY
   CONNECTION WITH BOTH f AND c RATIONAL IS EXACTLY RESONANT -- there are no generic rational
   connections at all.  Genericity requires f or c to be transcendental over the other and
   over pi.
Precision: exact integer arithmetic on the rationals; mpmath 50 dps for the quadratures.
"""
import mpmath as mp
from fractions import Fraction as Fr
import math

mp.mp.dps = 50

# (label, where published, f, c) with f, c as EXACT Fractions where rational, else a tag
PUBLISHED = [
    ("S1 sec6 worked instance  W_F=-1, W_C=-i", "S1:114-115 / S3:78",
     ("pi_mult", Fr(1, 1)), ("pi_mult", Fr(3, 2))),     # f = pi, c = 3pi/2
    ("S3 headline               f=2.0,  c=1.1", "S3:88, S3:310, S4:891",
     ("rat", Fr(2)), ("rat", Fr(11, 10))),
    ("S3 sec6(f)                f=pi,   c=pi/2", "S3:700, S4:956",
     ("pi_mult", Fr(1)), ("pi_mult", Fr(1, 2))),
    ("S3 sec6(f)                f=pi,   c=3pi/2", "S3:701, S4:957",
     ("pi_mult", Fr(1)), ("pi_mult", Fr(3, 2))),
    ("S3 sec6(f)                f=c=2.0", "S4:955",
     ("rat", Fr(2)), ("rat", Fr(2))),
    ("S3 audit                  f=3.14159, c=1.57080", "S3:698, S4:960",
     ("rat", Fr(314159, 100000)), ("rat", Fr(157080, 100000))),
    ("S3 audit                  f=3.14159, c=4.71239", "S3:699",
     ("rat", Fr(314159, 100000)), ("rat", Fr(471239, 100000))),
    ("S4 sec3                   f=1.0, c=0.3", "S4:330",
     ("rat", Fr(1)), ("rat", Fr(3, 10))),
    ("S4 sec3                   f=1.0, c=3.0", "S4:330",
     ("rat", Fr(1)), ("rat", Fr(3))),
    ("S4 sec3                   f=1.0, c=2.1", "S4:342",
     ("rat", Fr(1)), ("rat", Fr(21, 10))),
    ("S4 sec7 detune            f=2.0, c=1.1+1e-5", "S4:924",
     ("rat", Fr(2)), ("rat", Fr(110001, 100000))),
    ("S4 VERIFICATION           f=1.0, c=sqrt(2)", "S4:603, S4:1054",
     ("rat", Fr(1)), ("sqrt2", Fr(1))),
]


def type_connection(f, c):
    """Return (kind, primitive relation (m,n) or None, order or None)."""
    fk, fv = f; ck, cv = c
    if fk == "rat" and ck == "rat":
        # relation lattice = <(m,n)> primitive with -m f + n c = 0, i.e. m/n = c/f
        r = cv / fv                     # = m/n
        m, n = r.numerator, r.denominator
        g = math.gcd(abs(m), abs(n)); m //= g; n //= g
        return "RESONANT (rank 1)", (m, n), None
    if fk == "pi_mult" and ck == "pi_mult":
        # f = a pi, c = b pi  ->  alpha = -a/2, beta = b/2, both rational: FINITE ORDER
        a = fv; b = cv
        al = Fr(-a, 2) % 1; be = Fr(b, 2) % 1
        den = math.lcm(al.denominator, be.denominator)
        return "FINITE ORDER", None, den
    if fk == "rat" and ck == "sqrt2":
        # -m f + n c = 2 pi j with f rational, c = sqrt2 * rational: LHS algebraic, RHS
        # transcendental unless j = 0; then n sqrt2 = m f forces m = n = 0.
        return "GENERIC (L = {0})", None, None
    return "?", None, None


if __name__ == "__main__":
    print("=" * 108)
    print("R2_04 (A) — CENSUS OF THE CORPUS'S PUBLISHED CONNECTIONS, TYPED BY COMPUTATION")
    print("=" * 108)
    print(f"  {'connection':44s} {'where':22s} {'type':22s} relation / order")
    generic = []
    for lab, where, f, c in PUBLISHED:
        kind, rel, order = type_connection(f, c)
        extra = (f"primitive (m,n) = {rel}" if rel else
                 (f"ord(rho) = {order}" if order else "L = {0}"))
        print(f"  {lab:44s} {where:22s} {kind:22s} {extra}")
        if kind.startswith("GENERIC"):
            generic.append(lab)
    print("\n  EVERY CONNECTION WITH BOTH f AND c RATIONAL IS EXACTLY RESONANT.  That covers")
    print("  every row above except the pi-multiples (finite order) and the ONE row with an")
    print("  irrational ratio.  THE CORPUS HAS PUBLISHED EXACTLY ONE GENERIC CONNECTION:")
    for g in generic:
        print(f"     {g}")
    print("  and it is the connection S4 used to VERIFY the very lambda column lane C audits")
    print("  (S4:603 'Closed forms verified against direct schedule-B simulation at f = 1.0,")
    print("  c = sqrt(2), N = 2e6'; S4:1054 repeats it in the verification table).")
    print("  R2_03 section 3 runs it at K = 2e8 on both four-class carriers and on K1:")
    print("  the average converges to m(P) with errors 5.7e-10, 1.2e-09 and 2.7e-08.")
    print("  ==> 'lambda = m(P) is FALSE at every connection this corpus has ever published'")
    print("      IS REFUTED BY THE CORPUS'S OWN VERIFICATION CONNECTION, and lane C's own")
    print("      C_04 output prints that connection's agreement ten lines below the claim.")
    print("\n  NOTE, CUTTING AGAINST THE SAME CLAIM FROM THE OTHER SIDE: S4:960's resolution of")
    print("  f = 3.14159, c = 1.57080 calls those truncated decimals 'generic'.  They are NOT:")
    print("  both are rational, so the connection is resonant with primitive relation")
    print("  (157080, 314159).  S4's CONCLUSION is right to any attainable precision (Boyd-")
    print("  Lawton makes the subtorus measure agree with m(P) far beyond float64), but its")
    print("  TYPING is wrong -- the corpus's third mislabelling of a connection, and neither")
    print("  W-08, W-09 nor lane C has caught it.")

    # ------------------------------------------------------------------ (B) spot-checks
    print("\n" + "=" * 108)
    print("R2_04 (B) — KINK-SPLIT m(P) FOR THE TWO ROWS WHERE THE JENSEN INTEGRAND HAS A CORNER")
    print("=" * 108)

    def m_kinksplit(p, name):
        """m(P) = (1/pi) INT_0^pi log max(|A|,|B|) dt, split EXACTLY at the branch crossing."""
        p00, p10, p01, p11 = [mp.mpf(q) for q in p]
        def A2(t): return p00**2 + p10**2 + 2*p00*p10*mp.cos(t)
        def B2(t): return p01**2 + p11**2 + 2*p01*p11*mp.cos(t)
        # A2 - B2 is affine in cos t: (a0 - b0) + (a1 - b1) cos t
        a0 = p00**2 + p10**2; a1 = 2*p00*p10
        b0 = p01**2 + p11**2; b1 = 2*p01*p11
        num = b0 - a0; den = a1 - b1
        cross = None
        if den != 0:
            cc = num / den
            if -1 < cc < 1:
                cross = mp.acos(cc)
        if cross is None:
            val = mp.quad(lambda t: mp.log(mp.sqrt(max(A2(t), B2(t)))), [0, mp.pi]) / mp.pi
            return val, None
        i1 = mp.quad(lambda t: mp.log(mp.sqrt(max(A2(t), B2(t)))), [0, cross]) / mp.pi
        i2 = mp.quad(lambda t: mp.log(mp.sqrt(max(A2(t), B2(t)))), [cross, mp.pi]) / mp.pi
        return i1 + i2, cross

    for name, p, lanec in (
            ("K1   SENSE U (0,2,2,1)/5", [0, mp.mpf(2)/5, mp.mpf(2)/5, mp.mpf(1)/5],
             "-0.756573585640  (S4:597 Cassaigne-Maillot; lane C C_04 prints -0.756573585640)"),
            ("B0b* SENSE U (2,1,3,3)/9", [mp.mpf(2)/9, mp.mpf(1)/9, mp.mpf(3)/9, mp.mpf(3)/9],
             "-0.987918288038  (lane C C-5)"),
            ("B0b  SENSE U (4,2,1,2)/9", [mp.mpf(4)/9, mp.mpf(2)/9, mp.mpf(1)/9, mp.mpf(2)/9],
             "-0.810930216216  = log(4/9)"),
            ("B4   SENSE U (1,1,1,3)/6", [mp.mpf(1)/6, mp.mpf(1)/6, mp.mpf(1)/6, mp.mpf(3)/6],
             "-0.693147180560  = -log 2"),
    ):
        v, cr = m_kinksplit(p, name)
        print(f"\n  {name}")
        print(f"     kink-split adaptive quadrature = {mp.nstr(v, 18)}"
              f"   {'crossing at cos t = ' + mp.nstr(mp.cos(cr), 8) if cr is not None else 'NO crossing (single branch dominates)'}")
        print(f"     lane C / corpus value          = {lanec}")

    print("\n  READ: a plain (unsplit) trapezoid on the Jensen integrand is O(n^-2) at a")
    print("  crossing.  This refuter's own R2_02 used an unsplit 2^16 trapezoid and was")
    print("  therefore wrong by ~8e-11 (K1) and ~1.7e-10 (B0b*) -- recorded as defect R-2.")
    print("  Lane C's kink-split values are the accurate ones and are CONFIRMED here.")
    print("\nDONE.")
