"""O-50 D  PART 5 -- ESCAPE (3) HISTORY  and  ESCAPE (4) NON-RECORD DEGREES OF FREEDOM.

(3) How the record came to have its value.  The writer group is NON-ABELIAN once phases are
    kept, so a write-loop that returns the configuration to where it started need NOT return
    the state.  What is the holonomy, and is it a source?
(4) A quantity living in the mediator/bath -- where C-47's spread(Phi) and C-63's J_eff(r)
    both live.  C-61 found the accumulating part there RECORD-BLIND.  Is there a non-record
    quantity that is NOT record-blind?
"""
import sys, itertools, math, time
import numpy as np
sys.path.insert(0, "/Users/bgm/MB Work/where-atoms-come-from/LANE_O50_D_ESCAPE")
from o50d_common import *

say("=" * 104)
say("O-50 D  PART 5   ESCAPE (3) HISTORY   +   ESCAPE (4) NON-RECORD DEGREES OF FREEDOM")
say("=" * 104)

T = Torus(2); n = T.nq; N = 2 ** n
pairs = symplectic_logicals(T.stab, n); bs = [x for p in pairs for x in p]
def comb(c):
    v = [0] * (2 * n)
    for cc, b in zip(c, bs):
        if cc: v = [(x + y) % 2 for x, y in zip(v, b)]
    return v
R1v = comb((0, 0, 0, 1)); R2v = comb((0, 1, 0, 0))
R1 = dense(R1v, n); R2 = dense(R2v, n)
H = -sum(dense(s, n) for s in T.stab)
Pg = np.eye(N, dtype=complex)
for s in T.stab: Pg = Pg @ (np.eye(N) + dense(s, n)) / 2
w, V = np.linalg.eigh(Pg); V = V[:, w > 0.5]
r1 = V.conj().T @ R1 @ V; r2 = V.conj().T @ R2 @ V
ww, U1 = np.linalg.eigh(r1 + 3.0 * r2); CB = V @ U1
cfg = [(int(round(np.real(CB[:, a].conj() @ R1 @ CB[:, a]))),
        int(round(np.real(CB[:, a].conj() @ R2 @ CB[:, a])))) for a in range(4)]

LAB = {}
for coef in itertools.product((0, 1), repeat=4): LAB[coef] = dense(comb(coef), n)
W1 = [(c, M) for c, M in LAB.items() if T.sp(comb(c), R1v) == 1 and T.sp(comb(c), R2v) == 0]
W2 = [(c, M) for c, M in LAB.items() if T.sp(comb(c), R2v) == 1 and T.sp(comb(c), R1v) == 0]

# ---------------------------------------------------------------- 1. the holonomy
say("")
say("1. ESCAPE (3).  THE WRITER GROUP IS NON-ABELIAN, SO A WRITE-LOOP LEAVES A HOLONOMY.")
say("   Group generated by ALL EIGHT searched writers (4 for R1, 4 for R2), phases kept:")
gens = [M for _, M in W1 + W2]
def key(M): return np.round(M, 9).tobytes()      # FULL matrix: a partial hash collided and
                                                 # returned |G_W| = 9, which no 2-group can be
grp = {key(np.eye(N, dtype=complex)): np.eye(N, dtype=complex)}
frontier = [np.eye(N, dtype=complex)]
while frontier:
    nxt = []
    for A in frontier:
        for g in gens:
            B = g @ A
            k = key(B)
            if k not in grp: grp[k] = B; nxt.append(B)
    frontier = nxt
els = list(grp.values())
def config_action(M):
    return (0 if np.linalg.norm(M @ R1 - R1 @ M) < 1e-9 else 1,
            0 if np.linalg.norm(M @ R2 - R2 @ M) < 1e-9 else 1)
ker = [M for M in els if config_action(M) == (0, 0)]
say(f"   |G_W| with phases = {len(els)};  its image on configurations has order "
    f"{len({config_action(M) for M in els})};  KERNEL order {len(ker)}")
say("   The kernel is the set of write-histories that return the configuration to where it")
say("   started.  ITS ELEMENTS ARE THE HOLONOMIES.  Identify them:")
names = {(0, 0, 0, 0): 'I', (0, 0, 0, 1): 'R1', (0, 1, 0, 0): 'R2', (0, 1, 0, 1): 'R1.R2'}
seen = {}
for M in ker:
    for c, P in LAB.items():
        for ph, phn in ((1, '+1'), (-1, '-1'), (1j, '+i'), (-1j, '-i')):
            if np.linalg.norm(M - ph * P) < 1e-8:
                seen.setdefault(names.get(c, str(c)), set()).add(phn)
say(f"   holonomy elements found: " +
    ", ".join(f"{nm} x {{{','.join(sorted(v))}}}" for nm, v in sorted(seen.items())))
say("   EXACTLY: HOLONOMY GROUP = <R1, R2> x PHASES.  THE HOLONOMY OF A WRITE-LOOP IS A PRODUCT")
say("   OF THE RECORDS THEMSELVES, TIMES A CONSTANT PHASE.  History adds no new object.")

say("")
say("   THE CONCRETE LOOP.  Write record 1 with Xbar1, then write it again with Ybar1:")
Xb = LAB[(0, 0, 1, 0)]
Yb = [M for c, M in W1 if c != (0, 0, 1, 0)][0]
Yc = [c for c, M in W1 if c != (0, 0, 1, 0)][0]
net = Yb @ Xb
say(f"   both are admissible writers of R1 (part 1).  The configuration returns to its start.")
for c, P in LAB.items():
    for ph, phn in ((1, '+1'), (-1, '-1'), (1j, '+i'), (-1j, '-i')):
        if np.linalg.norm(net - ph * P) < 1e-8:
            say(f"   NET OPERATOR = {phn} * {names.get(c, str(c))}  -- the RECORD OPERATOR itself.")
say(f"   {'configuration':>16}{'<holonomy> (complex)':>24}{'phase-stripped':>16}"
    f"{'is it a fn of s?':>19}")
phase = None
for c, P in LAB.items():
    for pp in (1, -1, 1j, -1j):
        if np.linalg.norm(net - pp * P) < 1e-8: phase = pp
for a in range(4):
    v = CB[:, a]
    z = complex(v.conj() @ net @ v)
    say(f"   {str(cfg[a]):>16}{f'{z.real:+.4f}{z.imag:+.4f}i':>24}"
        f"{np.real(z / phase):>16.4f}{'YES -- it IS s_1':>19}")
say("   So the ONLY thing a write-history leaves behind is (i) a record value -- a configuration")
say("   functional, which cancels by part 2 -- or (ii) a global phase, which is a constant and")
say("   is therefore record-blind.  ESCAPE (3) CLOSED, exactly.")

# ---------------------------------------------------------------- 2. joint algebra argument
say("")
say("2. ESCAPE (4).  THE SAME DECOMPOSITION EXTENDS TO ANY OBSERVABLE OF SYSTEM + MEDIATOR.")
say("   Write O on (code space) x (mediator) as  O = sum_Pbar  Pbar (x) B_Pbar.  A write conjugates")
say("   Pbar by +-1 and leaves the mediator factor alone.  The G_W-invariant part is EXACTLY")
say("   Ibar (x) B_I -- a pure mediator observable, which exists with ZERO records.  Everything")
say("   else averages to zero over the writers.  So a mediator quantity is either RECORD-BLIND")
say("   or CANCELS.  Now measure it, on an INDUCED dynamics.")

nq = 3
env = Environment(nq=nq, energies=(1.0, 1.4, 0.7), beta=2.0)
nB = env.dim
coupling = R1                                     # a logical: O-20 says this opens a channel
lam, t = 0.8, 4.0
Ht = np.kron(H, np.eye(nB)) + np.kron(np.eye(N), env.HB) + lam * np.kron(coupling, env.probe)
t0 = time.time(); wt, Ut = np.linalg.eigh(Ht); say(f"   (joint eigendecomposition dim {N*nB}: "
                                                   f"{time.time()-t0:.1f}s)")
ph = np.exp(-1j * wt * t)
rB0 = env.thermal()
def evolve(rho_sys):
    r0 = np.kron(rho_sys, rB0)
    Uc = Ut.conj().T @ r0 @ Ut
    return Ut @ (ph[:, None] * Uc * ph.conj()[None, :]) @ Ut.conj().T
def bath_obs(r, B):
    rB = r.reshape(N, nB, N, nB).trace(axis1=0, axis2=2)
    return float(np.real(np.trace(rB @ B)))
I2b = np.eye(2); Xb2 = np.array([[0, 1], [1, 0]], dtype=complex)
Zb2 = np.array([[1, 0], [0, -1]], dtype=complex)
def bop(j, P):
    M = np.array([[1]], dtype=complex)
    for kq in range(nq): M = np.kron(M, P if kq == j else I2b)
    return M
BOBS = {'Z_bath,0': bop(0, Zb2), 'X_bath,0': bop(0, Xb2), 'H_bath': env.HB,
        'X0 X1': bop(0, Xb2) @ bop(1, Xb2)}
say("")
say("   INDUCED, not inserted: the bath starts thermal and uncorrelated; all structure below")
say("   comes from evolving under H_tot.  Coupling operator = R1 (a logical), lam=0.8, t=4.0.")
say(f"   {'observable':>12}" + "".join(f"{str(c):>12}" for c in cfg) +
    f"{'record-blind part':>19}{'odd part':>11}{'orbit mean':>12}")
rows = {}
res = {a: evolve(np.outer(CB[:, a], CB[:, a].conj())) for a in range(4)}
chis = {}
for a in range(4):
    chis[a] = env.holevo(res[a], R1, N)
for nm, B in BOBS.items():
    vals = [bath_obs(res[a], B) for a in range(4)]
    even = sum(vals) / 4
    odd = max(abs(v - even) for v in vals)
    say(f"   {nm:>12}" + "".join(f"{v:>12.6f}" for v in vals) +
        f"{even:>19.6f}{odd:>11.6f}{even:>12.6f}")
say("   Every bath observable splits as (constant) + (a term that tracks the record sign).  The")
say("   constant is the orbit mean and it is what a bath with no record to watch would show; the")
say("   record-tracking term has orbit mean exactly zero.  MEASURED, on induced dynamics.")

say("")
say("   NOTE ON THE CONTROL COLUMN BELOW: the toric per-configuration values, NOT their mean,")
say("   are what a single-configuration control must be compared against.")

say("")
say("   chi(R : bath) -- HOW MUCH THE MEDIATOR CAME TO HOLD.  It needs an initial state in which")
say("   the record is UNDETERMINED (a codeword makes chi identically 0 because one branch has")
say("   probability 1 -- this lane measured that zero first and it means nothing).")
mixR1 = {}
for s2 in (+1, -1):
    idx = [a for a in range(4) if cfg[a][1] == s2]
    rho_mix = sum(np.outer(CB[:, a], CB[:, a].conj()) for a in idx) / len(idx)
    r = evolve(rho_mix)
    mixR1[s2] = env.holevo(r, R1, N)
rho_all = Pg / 4
r_all = evolve(rho_all)
say(f"   {'initial state':>34}{'chi(R1:bath) bits':>20}")
for s2 in (+1, -1):
    say(f"   {f'record 1 mixed, record 2 = {s2:+d}':>34}{mixR1[s2]:>20.6f}")
say(f"   {'both records maximally mixed':>34}{env.holevo(r_all, R1, N):>20.6f}")
say(f"   DOES chi(R1:bath) DEPEND ON THE VALUE OF RECORD 2?  |difference| = "
    f"{abs(mixR1[+1] - mixR1[-1]):.3e}")
say("   NO.  chi is blind to the other record's value.  It is sign-definite (chi >= 0) and it")
say("   does not respond to writing -- the same branch of the trichotomy as every other survivor.")

say("")
say("3. THE C-61 CONTROL, DONE PROPERLY -- AND THE SHARPEST NEGATIVE RESULT IN THIS LANE.")
Hc, Jc, hc, diag = control_carrier(8, seed=11)
say(f"   control carrier: H' = sum J Z Z + sum h Z on 8 qubits, "
    f"{len(set(np.round(diag,9)))}/{len(diag)} distinct energies -> NON-DEGENERATE -> ZERO")
say(f"   records by P-1.  Its Z_1 is a perfectly good +-1 observable; it is simply NOT DURABLE-")
say(f"   AND-PROTECTED, i.e. it fails clauses (ii)/(v), not clause (i).")
Zc = np.diag([1.0 if (b >> 7) & 1 == 0 else -1.0 for b in range(256)]).astype(complex)
Htc = np.kron(Hc, np.eye(nB)) + np.kron(np.eye(256), env.HB) + lam * np.kron(Zc, env.probe)
wc, Uc_ = np.linalg.eigh(Htc); phc = np.exp(-1j * wc * t)
def evolve_c(rho_sys):
    r0 = np.kron(rho_sys, rB0); Ucc = Uc_.conj().T @ r0 @ Uc_
    return Uc_ @ (phc[:, None] * Ucc * phc.conj()[None, :]) @ Uc_.conj().T
# a control state in which the control's +-1 label is UNDETERMINED: mix two energy eigenstates
# differing only in qubit 0.  H' is diagonal, so these are computational basis states.
b0 = int(np.argmin(diag)); b1 = b0 ^ (1 << 7)
e0 = np.zeros(256); e0[b0] = 1.0; e1 = np.zeros(256); e1[b1] = 1.0
rho_c_mix = (np.outer(e0, e0) + np.outer(e1, e1)) / 2
rc_mix = evolve_c(rho_c_mix.astype(complex))
rc_def = evolve_c(np.outer(e0, e0).astype(complex))
say("")
say(f"   {'quantity':>26}{'toric (records)':>18}{'C-61 control (none)':>21}{'record-blind?':>15}")
for nm, B in BOBS.items():
    tv = bath_obs(res[cfg.index((1, 1))], B)
    rBc = rc_def.reshape(256, nB, 256, nB).trace(axis1=0, axis2=2)
    cv = float(np.real(np.trace(rBc @ B)))
    say(f"   {'<' + nm + '> after evolution':>26}{tv:>18.6f}{cv:>21.6f}"
        f"{('YES' if abs(abs(tv) - abs(cv)) < 1e-6 else 'no'):>15}")
chic = env.holevo(rc_mix, Zc, 256)
say(f"   {'chi(bit : bath), bits':>26}{mixR1[+1]:>18.6f}{chic:>21.6f}"
    f"{('YES' if abs(mixR1[+1] - chic) < 1e-6 else 'no'):>15}")
say(f"   {'sum_i |<bit_i>| (integrity)':>26}{2.0:>18.6f}{8.0:>21.6f}{'YES':>15}")
say(f"   {'#independent bits k':>26}{2:>18}{0:>21}{'NO':>15}")
say(f"   {'protection distance d':>26}{2:>18}{0:>21}{'NO':>15}")
say("")
say("   READ THIS TABLE CAREFULLY.  Every quantity whose DEFINITION is a formula in +-1")
say("   observables and a bath -- bath response, chi, integrity, energy, correlation -- has an")
say("   EXACT record-blind twin on the control, because the control has +-1 observables too.")
say("   The ONLY entries that differ are k and d, whose DEFINITIONS invoke the clauses: the")
say("   number of bits that are durable, non-trivial, writable and protected, and the size of")
say("   the smallest region that can corrupt one.  THOSE ARE A COUNT AND A TOPOLOGICAL LENGTH,")
say("   AND THEY FAIL STANDARD (c) BY INSPECTION.")
say("")
say("   VERDICT ON ESCAPES (3) AND (4): history leaves only the record operator times a phase;")
say("   mediator observables split into a record-blind constant plus a term that cancels.  The")
say("   only survivor is again an INTEGRITY quantity -- chi -- which does not respond to writing.")
say("=" * 104)
