"""PROBE 6.  Is the lane's FINITE-G missing step ('d_R = 1 always for a finite on-site 0-form
symmetry') merely OPEN, or is the literal statement FALSE?
Candidate: the Steane code has a TRANSVERSAL (on-site) logical X = X^(x)7.  G = Z2 = {I, X^(x)7}
is then a genuine finite ON-SITE 0-form symmetry of H0 = -sum(stabilisers), and it acts NON-SCALARLY
on the ground multiplet -- exactly the hypothesis the connected-G proof uses.  Does a single-site
operator split the multiplet at first order?"""
import itertools, numpy as np
I2=np.eye(2,dtype=complex); SX=np.array([[0,1],[1,0]],dtype=complex)
SY=np.array([[0,-1j],[1j,0]],dtype=complex); SZ=np.array([[1,0],[0,-1]],dtype=complex)
P={'I':I2,'X':SX,'Y':SY,'Z':SZ}
def pm(s):
    M=np.array([[1.0+0j]])
    for c in s: M=np.kron(M,P[c])
    return M
def sy(a,b):
    c=0
    for x,y in zip(a,b):
        if x!='I' and y!='I' and x!=y: c^=1
    return c
def pmul(a,b):
    o=[]
    for x,y in zip(a,b):
        if x=='I': o.append(y)
        elif y=='I': o.append(x)
        elif x==y: o.append('I')
        else: o.append({'XY':'Z','YX':'Z','XZ':'Y','ZX':'Y','YZ':'X','ZY':'X'}[x+y])
    return ''.join(o)
def stabgrp(g,n):
    S={'I'*n}; fr=['I'*n]
    while fr:
        nx=[]
        for a in fr:
            for x in g:
                b=pmul(a,x)
                if b not in S: S.add(b); nx.append(b)
        fr=nx
    return S
def codespace(gens,n):
    N=2**n; H=np.zeros((N,N),complex)
    for g in gens: H-=pm(g)
    H=(H+H.conj().T)/2
    ev,U=np.linalg.eigh(H)
    sel=np.abs(ev-ev[0])<1e-8*max(1.0,abs(ev).max())
    return H,U[:,sel]
def phi(V,Q):
    B=Q.conj().T@V@Q; m=B.shape[0]
    return B-np.trace(B)/m*np.eye(m)
def paulis_w(n,w):
    out=[]
    for sup in itertools.combinations(range(n),w):
        for L in itertools.product('XYZ',repeat=w):
            s=['I']*n
            for k,c in zip(sup,L): s[k]=c
            out.append(''.join(s))
    return out

gens=["IIIXXXX","IXXIIXX","XIXIXIX","IIIZZZZ","IZZIIZZ","ZIZIZIZ"]
n=7; S=stabgrp(gens,n); H0,Q=codespace(gens,n)
G="XXXXXXX"
print("STEANE [[7,1,3]].  G = Z2 generated by the ON-SITE operator u(g)=X applied to every site.")
print(f"  ground-space dim = {Q.shape[1]}")
print(f"  X^(x)7 commutes with every stabiliser: {all(sy(G,g)==0 for g in gens)}")
print(f"  X^(x)7 in the stabiliser group (would act as identity): {G in S}")
UG=pm(G)
print(f"  ||[H0, X^(x)7]|| = {np.linalg.norm(H0@UG-UG@H0):.2e}   (genuine symmetry of H0)")
print(f"  (u(g))^2 = I on each site: {np.allclose(SX@SX,I2)}  -> a faithful on-site Z2 action")
B=Q.conj().T@UG@Q; B=(B+B.conj().T)/2
print(f"  eigenvalues of the symmetry ON THE GROUND MULTIPLET = {np.round(np.linalg.eigvalsh(B),8)}")
print(f"  ||Phi(X^(x)7)|| on E0 = {np.linalg.norm(phi(UG,Q)):.4f}"
      "   -> the symmetry acts NON-SCALARLY: E0 carries BOTH Z2 characters,")
print("     which is the exact finite-group analogue of 'drho(X^a) non-scalar' in the connected proof.")
D1=max(float(np.linalg.norm(phi(pm(s),Q))) for s in paulis_w(n,1))
print(f"  D1 = max over all single-site Paulis of ||Phi(V)|| = {D1:.3e}")
w2=max(float(np.linalg.norm(phi(pm(s),Q))) for s in paulis_w(n,2))
w3=max(float(np.linalg.norm(phi(pm(s),Q))) for s in paulis_w(n,3))
print(f"  POSITIVE CONTROL, same code path at higher weight: w=2 -> {w2:.3e},  w=3 -> {w3:.3e}")
# d_R for the record R = the symmetry charge itself (Xbar), and for Zbar
def dR(gens,n,S,Rstr,wmax=4):
    for w in range(1,wmax+1):
        for s in paulis_w(n,w):
            if all(sy(s,g)==0 for g in gens) and s not in S and sy(s,Rstr)==1: return w,s
    return None,None
for Rs,lab in [("XXXXXXX","R = Xbar = the Z2 charge"),("ZZZZZZZ","R = Zbar")]:
    w,wit=dR(gens,n,S,Rs)
    print(f"  {lab}: d_R = {w}  (witness {wit})")
print()
print("VERDICT ON THE MISSING STEP:")
print("  A FINITE on-site 0-form symmetry (Z2) here has a ground multiplet on which it acts")
print("  non-scalarly, NO single-site operator splits that multiplet at first order (D1 = 0 to")
print("  machine precision, controlled by w=3 in the same code path), and d_R = 3, not 1.")
print("  So the statement the lane nominates as 'the ONLY step' -- 'a finite on-site 0-form symmetry")
print("  cannot produce a ground multiplet with no local order parameter, i.e. d_R = 1 always' --")
print("  is FALSE as written under the direct finite-group translation of its own connected-G")
print("  hypothesis.  Closing C-2 needs an EXTRA hypothesis that excludes transversal-logical cases,")
print("  and that hypothesis is not stated anywhere in the lane.")
