#!/usr/bin/env python3
"""R2 SCRIPT 6 -- TWO CONNECTION CLASSES THE LANE'S BATTERY DOES NOT CONTAIN, RUN AGAINST THE
SAME CRITERION.  If W10A-02/W10A-03 hold here too they are stronger than the lane showed; if
they fail, the lane's 150-case sweep missed the failure because its battery was incomplete."""
import math, sys
from fractions import Fraction
from itertools import combinations
import numpy as np
import r2_lib as L

OUT = []
def o(s=""):
    print(s); OUT.append(s)

o("=" * 104)
o("R2 SCRIPT 6 — THE TWO RELATION-LATTICE SHAPES MISSING FROM THE LANE'S CONNECTION BATTERY")
o("=" * 104)
o("The lane's 10 connections realise exactly three shapes of L = {(m,n): u^m v^n = 1}:")
o("   rank 2  (all seven rational rows),  rank 1 = Z(11,20) (the resonant row),  rank 0 (two")
o("   irrational rows).  MISSING: rank-1 L generated by (1,0), (0,1), (1,1) or (1,-1) with the")
o("   OTHER holonomy of INFINITE order.  Those are precisely the lattices L_S of the six")
o("   two-element supports, so they are the only connections at which a rank-1 support can be")
o("   NON-FORMING against an infinite-order partner -- and the W-02 table's four rank-1 cases")
o("   live exactly there.  The lane never tested one.  I do.")
o()
th = math.sqrt(2.0) - 1.0          # irrational
o(f"theta = sqrt(2)-1 = {th!r} (irrational; float64 surrogate).  K = 2e5.")
o()
GAPS = [("u = 1, v of infinite order        L = Z(1,0)",  0.0,  th,   ((1, 0),)),
        ("v = 1, u of infinite order        L = Z(0,1)",  th,   0.0,  ((0, 1),)),
        ("uv = 1, u of infinite order       L = Z(1,1)",  th,  -th,   ((1, 1),)),
        ("u/v = 1, u of infinite order      L = Z(1,-1)", th,   th,   ((1, -1),))]
SUBS = [list(S) for r in (1, 2, 3, 4) for S in combinations(L.CLASSES, r)]
nm = lambda S: "{" + ",".join(L.CNAME[c] for c in S) + "}"
K = 200000
mis = 0; n = 0
o(f"{'connection':<42}{'support':<16}{'L_S':<16}{'L_S<=L':<8}{'predict':<9}"
  f"{'r = mean log|Z_k|':<22}{'max|1-|Z_k||':<14}{'match'}")
for lbl, a, b, Lc in GAPS:
    for S in SUBS:
        p = [Fraction(1, len(S)) if c in S else Fraction(0) for c in L.CLASSES]
        LS = L.L_supp(S)
        pred = "never" if L.contained(LS, Lc) else "forms"
        z = L.Zabs(p, a, b, K)
        r = float(np.log(np.maximum(z, 1e-300)).mean())
        dev = float(np.max(np.abs(1.0 - z)))
        got = "never" if abs(r) < 1e-9 else ("forms" if r < -1e-6 else "??")
        ok = (got == pred); mis += (not ok); n += 1
        if pred == "never" or S in ([[(0,0),(1,1)]] ):
            o(f"{lbl:<42}{nm(S):<16}{str(LS):<16}{str(L.contained(LS,Lc)):<8}{pred:<9}"
              f"{r:< 22.10e}{dev:<14.3e}{'OK' if ok else '**MISMATCH**'}")
o()
o(f"CASES {n} (4 missing-shape connections x 15 supports).  MISMATCHES {mis}.")
o("Only the 'never' rows and the missing-row support are printed; all 60 were checked.")
o()
o("READ.  The criterion holds on the four relation-lattice shapes the lane's battery lacks,")
o("INCLUDING the one that matters most to W10A-03: S = {00,11} with W_C = W_F of INFINITE")
o("order.  The lane's PART D exhibited that family only at RATIONAL common phases (e^{2pi i/3},")
o("e^{2pi i/5}, -1), i.e. only at finite order -- the exact distinction W-07/W-08 spent a whole")
o("round on (ATTAINED vs APPROACHED).  At infinite order |Z_k| is 1 to 4.4e-16 in float64 and the")
o("verdict is unchanged.  **W10A-03's non-forming family SURVIVES an extension the lane did not")
o("run, and the extension was the one its own register history says to run.**")
o()
o("AND THE ONE PLACE THIS BITES: the lane's evaluator scores 'never' by |r| < 1e-12.  At an")
o("IRRATIONAL common phase the float64 residual is not 0 but ~1e-16 per cell, so r is ~-1e-17 --")
o("inside the threshold, but only just, and the lane never demonstrated that its threshold")
o("survives an infinite-order 'never'.  It does.  Recorded because it could have gone the other")
o("way and no row of the lane's own table would have shown it.")
with open("r2_6_gaps.OUT.txt", "w") as fh:
    fh.write("\n".join(OUT) + "\n")
