"""KERNEL GATE. The first version used H_S with NEGATIVE eigenvalues while H_C is
non-negative, so the constraint n*omega = E_s had only the n=0 solution: the kernel was a
STATIC EIGENSTATE, not a history, and conditioning on it looked unitary for trivial reasons
while lambda had no effect at all. H_S now shares the clock ladder so the kernel contains
genuine superpositions over clock readings. The gate below checks that.
"""
"""W-58b.  A CLOCK WHOSE RATE DEPENDS ON WHAT IS THERE.

w58 established the timeless construction: constraint satisfied to 2.7e-16, and conditioning on the
clock reproduces unitary evolution to 2.6e-15 with NO external time anywhere. For an IDEAL clock the
timeless picture is exactly equivalent to the ordinary one -- so removing background time, by itself,
changes nothing. A2 is not an obstruction at that level.

THE CASE THAT IS NOT EQUIVALENT, AND IS THE GRAVITY-RELEVANT ONE. Gravitational time dilation means
THE CLOCK RATE DEPENDS ON WHAT IS THERE. In the timeless language that is an interaction inside the
constraint:
        [ H_C (x) (I + lambda A)  -  I (x) H_S ] |Psi> = 0
so the clock advances at a rate set by the system observable A. There is still no external time; what
changes is that time is no longer UNIVERSAL -- different system configurations wind the clock
differently.

THE QUESTION: with a non-universal time, is there still a record -- an observable whose conditional
value is constant across clock readings? And is it the SAME observable as before?

lambda = 0 must reproduce w58 exactly. That is the control.
"""
import numpy as np
rng=np.random.default_rng(9)
def expm(A):
    nr=np.linalg.norm(A,np.inf)
    k=max(0,int(np.ceil(np.log2(nr)))+1) if nr>0 else 0
    B=A/(2.0**k); X=np.eye(A.shape[0],dtype=complex); T=X.copy()
    for m in range(1,60):
        T=T@B/m; X=X+T
        if np.linalg.norm(T,np.inf)<1e-18*max(1.0,np.linalg.norm(X,np.inf)): break
    for _ in range(k): X=X@X
    return X
dC=12; dS=4
wC=2*np.pi/dC
HC=np.diag(wC*np.arange(dC)).astype(complex)
F=np.array([[np.exp(-2j*np.pi*n*k/dC)/np.sqrt(dC) for n in range(dC)] for k in range(dC)])
tstates=[F[k].conj() for k in range(dC)]
U0,_=np.linalg.qr(rng.normal(size=(dS,dS))+1j*rng.normal(size=(dS,dS)))
HS=U0@np.diag(+wC*np.array([0,1,2,3]))@U0.conj().T; HS=(HS+HS.conj().T)/2
# THE OBSERVABLE THE CLOCK RATE RESPONDS TO. It must NOT commute with H_S: if it does, the coupling
# merely rescales time within each energy sector and evolution stays generated by H_S. The first
# version built A diagonal in H_S's own basis, so [A,H_S]=0 and lambda changed nothing measurable.
_r=rng.normal(size=(dS,dS)); A=(_r+_r.T)/2; A=A/np.linalg.norm(A)*1.5
A=A.astype(complex)
IS=np.eye(dS); IC=np.eye(dC)

def build(lam):
    Htot=np.kron(HC,IS+lam*A)-np.kron(IC,HS)
    Htot=(Htot+Htot.conj().T)/2
    ev,evec=np.linalg.eigh(Htot)
    ker=[evec[:,i] for i in range(len(ev)) if abs(ev[i])<1e-8]
    return Htot,ker
def conditionals(Psi):
    out=[]
    for k in range(dC):
        proj=np.kron(np.outer(tstates[k],tstates[k].conj()),IS)
        v=(proj@Psi).reshape(dC,dS)
        c=v[np.argmax(np.linalg.norm(v,axis=1))]
        n=np.linalg.norm(c)
        out.append(c/n if n>1e-12 else c)
    return out

print("W-58b  A CLOCK WHOSE RATE DEPENDS ON THE SYSTEM. No external time anywhere.")
print(f"  GATE: the rate observable must not commute with H_S -- ||[A,H_S]|| = "
      f"{np.linalg.norm(A@HS-HS@A):.3f}")
print(f"  {'lambda':>8s} {'ker dim':>8s} {'||H|Psi>||':>12s}   what stays constant across clock readings")
print("  "+"-"*88)
for lam in (0.0,0.15,0.4,0.8):
    Htot,ker=build(lam)
    if not ker:
        print(f"  {lam:8.2f} {0:8d}   EMPTY KERNEL -- no timeless state exists at this coupling"); continue
    c=rng.normal(size=len(ker))+1j*rng.normal(size=len(ker))
    Psi=sum(c[i]*ker[i] for i in range(len(ker))); Psi/=np.linalg.norm(Psi)
    cond=conditionals(Psi)
    # search the SYSTEM operator space for observables whose conditional value is constant in k
    basis=[]
    for i in range(dS):
        for j in range(dS):
            M=np.zeros((dS,dS),complex); M[i,j]=1
            basis.append((M+M.conj().T)/2 if i!=j else M)
    vals=np.array([[np.real(np.vdot(c_,B@c_)) for B in basis] for c_ in cond])   # dC x len(basis)
    vals=vals-vals.mean(axis=0)
    U,sv,Vh=np.linalg.svd(vals)
    nconst=int((sv<1e-8*max(1.0,sv[0])).sum())
    print(f"  {lam:8.2f} {len(ker):8d} {np.linalg.norm(Htot@Psi):12.2e}   "
          f"{nconst} of {len(basis)} directions are exactly constant"
          f"   (largest variation {sv[0]:.3f})")
print()
print("  CONTROL -- lambda = 0 must reproduce w58: unitary conditional evolution.")
Htot,ker=build(0.0)
Psi=ker[0]; cond=conditionals(Psi); worst=0.0
for k in range(dC):
    t=2*np.pi*k/(dC*wC)
    tgt=expm(-1j*HS*t)@cond[0]; tgt/=np.linalg.norm(tgt)
    ph=np.vdot(tgt,cond[k]); ph=ph/abs(ph) if abs(ph)>1e-12 else 1.0
    worst=max(worst,np.linalg.norm(cond[k]/ph-tgt))
print(f"    worst deviation from unitary evolution at lambda=0: {worst:.3e}")
print()
print("  AND THE POINT: at lambda > 0 is the conditional evolution still unitary with a FIXED H_S?")
for lam in (0.15,0.4,0.8):
    Htot,ker=build(lam)
    if not ker: continue
    Psi=ker[0]; cond=conditionals(Psi); worst=0.0
    for k in range(dC):
        t=2*np.pi*k/(dC*wC)
        tgt=expm(-1j*HS*t)@cond[0]; tgt/=np.linalg.norm(tgt)
        ph=np.vdot(tgt,cond[k]); ph=ph/abs(ph) if abs(ph)>1e-12 else 1.0
        worst=max(worst,np.linalg.norm(cond[k]/ph-tgt))
    print(f"    lambda={lam:4.2f}: worst deviation = {worst:.3e}   "
          f"{'still the same evolution' if worst<1e-8 else 'NO -- time is no longer universal'}")

print()
print("  KERNEL GATE -- the timeless state must be a HISTORY, i.e. spread over clock readings,")
print("  not a static eigenstate. Measured as the spread of |<t_k|Psi>|^2 over k.")
for lam in (0.0,0.15,0.4,0.8):
    Htot,ker=build(lam)
    if not ker: print(f"    lambda={lam:4.2f}: EMPTY KERNEL"); continue
    c=rng.normal(size=len(ker))+1j*rng.normal(size=len(ker))
    Psi=sum(c[i]*ker[i] for i in range(len(ker))); Psi/=np.linalg.norm(Psi)
    w=[]
    for k in range(dC):
        proj=np.kron(np.outer(tstates[k],tstates[k].conj()),IS)
        w.append(float(np.real(np.vdot(proj@Psi,proj@Psi))))
    w=np.array(w); w/=w.sum()
    part=1.0/np.sum(w**2)
    print(f"    lambda={lam:4.2f}  ker dim {len(ker)}  clock readings occupied (participation) = "
          f"{part:.2f} of {dC}   {'HISTORY' if part>1.5 else 'STATIC -- void'}")
