"""VERIFY check 2 (independent): record venue on toric L=2 built from scratch.
N(S) = all 2^16 Paulis commuting with all stabilizers (brute force), S = span of stabilizers
(brute force closure), classes = cosets N(S)/S (no logicals, no labels needed).
J = min local-anticommutation count over all rep pairs.  Check: J(a,a)=0; J symmetric;
J mod 2 constant per class pair and == sp; indiscernibles fail; triangle fails among
classes with a NONZERO-ONLY witness; channel graph (sp=1) on nonzero classes connected,
BFS metric passes all axioms, spectrum {1,2}."""
L=2; n=2*L*L
def h(i,j): return (i%L)*L+(j%L)
def v(i,j): return L*L+(i%L)*L+(j%L)
stars=[]; plaqs=[]
for i in range(L):
    for j in range(L):
        s=0
        for e in (h(i,j),h(i,j-1),v(i,j),v(i-1,j)): s|=1<<e
        stars.append(s)
        p=0
        for e in (h(i,j),h(i+1,j),v(i,j),v(i,j+1)): p|=1<<e
        plaqs.append(p)
# Pauli = (x,z) masks; stabilizers: (star,0) and (0,plaq)
stabs=[(s,0) for s in stars]+[(0,p) for p in plaqs]
def sp(a,b):
    return (bin(a[0]&b[1]).count("1")+bin(a[1]&b[0]).count("1"))%2
def cross(a,b):
    return bin((a[0]&b[1])^(a[1]&b[0])).count("1")
NS=[]
for x in range(1<<n):
    for z in range(1<<n):
        u=(x,z)
        if all(sp(u,g)==0 for g in stabs):
            NS.append(u)
# S = group generated by stabs
S={(0,0)}
frontier=[(0,0)]
while frontier:
    nxt=[]
    for a in frontier:
        for g in stabs:
            b=(a[0]^g[0],a[1]^g[1])
            if b not in S:
                S.add(b); nxt.append(b)
    frontier=nxt
assert len(NS)==1024 and len(S)==64, (len(NS),len(S))
# cosets
canon={}
cosets={}
for u in NS:
    c=min((u[0]^g[0],u[1]^g[1]) for g in S)
    cosets.setdefault(c,[]).append(u)
classes=sorted(cosets)
assert len(classes)==16
ok=True
def gate(lbl,b,detail=""):
    global ok
    print(("PASS " if b else "FAIL "),lbl,detail); ok&=b
J={}
SPc={}
for a in classes:
    for b in classes:
        m=min(cross(u,vv) for u in cosets[a] for vv in cosets[b])
        J[(a,b)]=m
        sps={sp(u,vv) for u in cosets[a] for vv in cosets[b]}
        SPc[(a,b)]=sps
gate("sp is class-constant on every pair", all(len(s)==1 for s in SPc.values()))
gate("J(a,a)=0 all classes", all(J[(a,a)]==0 for a in classes))
gate("J symmetric", all(J[(a,b)]==J[(b,a)] for a in classes for b in classes))
gate("J mod 2 == sp every pair", all(J[(a,b)]%2==next(iter(SPc[(a,b)])) for a in classes for b in classes))
ident=(0,0)
nonzero=[c for c in classes if c!=ident]
ind_fail=any(J[(a,b)]==0 for a in classes for b in classes if a!=b)
gate("J fails indiscernibles", ind_fail)
nz=[(a,b,c) for a in nonzero for b in nonzero for c in nonzero
    if J[(a,c)]>J[(a,b)]+J[(b,c)]]
gate("J fails triangle among NONZERO classes", len(nz)>0, "witnesses %d, e.g. %s"%(len(nz),nz[:1]))
# channel graph on nonzero classes
import collections
adj={a:[b for b in nonzero if b!=a and next(iter(SPc[(a,b)]))==1] for a in nonzero}
d={}
conn=True
for s in nonzero:
    seen={s:0}; q=collections.deque([s])
    while q:
        u=q.popleft()
        for w in adj[u]:
            if w not in seen:
                seen[w]=seen[u]+1; q.append(w)
    if len(seen)!=len(nonzero): conn=False
    for w,dd in seen.items(): d[(s,w)]=dd
gate("channel graph connected on 15 nonzero classes", conn)
if conn:
    a1=all(d[(p,p)]==0 for p in nonzero)
    a2=all(d[(p,q)]==d[(q,p)] for p in nonzero for q in nonzero)
    a3=all(d[(p,q)]>0 for p in nonzero for q in nonzero if p!=q)
    a4=all(d[(p,r)]<=d[(p,q)]+d[(q,r)] for p in nonzero for q in nonzero for r in nonzero)
    gate("channel metric all four axioms", a1 and a2 and a3 and a4)
    spec=sorted(set(v for k,v in d.items() if v>0))
    gate("channel spectrum {1,2} diameter 2", spec==[1,2])
print("V2 OVERALL:", "PASS" if ok else "FAIL")
