# T1 — THE NULL OPTION, run PROSPECTIVELY on a proposed new program's founding question,
# before anything is built. This is W-17's lesson applied forward instead of backward.
#
# PROPOSED QUESTION: does a record criterion (quantum Darwinism's R_delta, Korbicz's SBS
# condition) SELECT among the classified boundary-algebra choices in a gauge theory?
# PROPOSED FIRST CARRIER (handoff, "THE SEPARATE QUESTION"): Z_2 pure gauge theory on a
# three-link theta graph with a genuine Gauss law and a real cut.
#
# T1 asks whether EITHER branch obtains: (a) is there a choice to select AMONG, and
# (b) is there a record to select FOR. Either answer "no" kills the construction before it is built.
import numpy as np, itertools
I2=np.eye(2); X=np.array([[0,1],[1,0]],dtype=complex); Z=np.diag([1,-1]).astype(complex)
def op(*ps):
    M=np.array([[1]],dtype=complex)
    for p in ps: M=np.kron(M,p)
    return M
L=3                                                    # three links, each a Z_2 qubit
def on(i,P): return op(*[P if j==i else I2 for j in range(L)])
X1,X2,X3=[on(i,X) for i in range(L)]; Z1,Z2,Z3=[on(i,Z) for i in range(L)]

print("== SETUP: Z_2 pure gauge theory on the theta graph ==")
print("  2 vertices, 3 links all oriented u->v; each link carries Z_2, so H = C^8.")
G=X1@X2@X3                                             # Gauss operator (both vertices give this)
print(f"  Gauss law G = X1 X2 X3.  G^2 = I : {np.allclose(G@G,np.eye(8))}")
P=(np.eye(8)+G)/2                                      # projector onto the physical sector
print(f"  physical sector dim = {int(round(np.trace(P).real))} of 8")
W12,W23=Z1@Z2,Z2@Z3                                    # Wilson loops on the two independent cycles
for nm,O in [("X1",X1),("X2",X2),("X3",X3),("W12=Z1Z2",W12),("W23=Z2Z3",W23),("Z1 alone",Z1)]:
    print(f"    [{nm:<10}, G] = 0 ?  {np.allclose(O@G,G@O)}")
print("  -> Z1 alone is NOT gauge invariant: a single link holonomy is unobservable when both")
print("     endpoints are gauged. THAT is the non-factorization the whole question is about.\n")

print("== T1(a)  IS THERE A CHOICE TO SELECT AMONG? ==")
# gauge-invariant operators supported on the SYSTEM = link 1 alone
cand={"I":np.eye(8),"X1":X1,"Z1":Z1,"Y1":1j*(Z1@X1)}
inv1=[nm for nm,O in cand.items() if np.allclose(O@G,G@O)]
print(f"  gauge-invariant operators supported on link 1 alone: {inv1}")
print("  -> the region algebra A_1 is generated by X1 only. It is ABELIAN, hence EQUAL to its own")
print("     centre: the algebra of the region does not factorize off. Premise CONFIRMED.")
# how many distinct algebras sit between A_1 and its commutant in the physical algebra?
gens={"X1":X1,"X2":X2,"X3":X3,"W12":W12,"W23":W23}
def close(sel):
    """generate the *-algebra on the physical sector, return its dimension"""
    basis=[P]
    frontier=[P@gens[s]@P for s in sel]
    pool=basis+frontier
    for _ in range(6):
        new=[]
        for A in pool:
            for s in sel:
                C=P@(A@gens[s])@P
                M=np.array([m.ravel() for m in pool+new])
                if np.linalg.matrix_rank(np.vstack([M,C.ravel()]),tol=1e-9)>np.linalg.matrix_rank(M,tol=1e-9):
                    new.append(C)
        if not new: break
        pool+=new
    return np.linalg.matrix_rank(np.array([m.ravel() for m in pool]),tol=1e-9)
seen={}
for r in range(1,len(gens)+1):
    for sel in itertools.combinations(gens,r):
        if "X1" not in sel: continue                   # must contain the region algebra
        seen.setdefault(close(sel),[]).append(sel)
print(f"  algebras containing X1, generated from the gauge-invariant generators:")
for d in sorted(seen): print(f"    dim {d:>2}  reached by {len(seen[d])} generator sets, e.g. {seen[d][0]}")
print(f"  -> {len(seen)} DISTINCT algebra dimensions are reachable. There IS a choice to make.\n")

print("== T1(b)  IS THERE A RECORD TO SELECT FOR? ==")
print("  R_delta and the SBS condition are REDUNDANCY criteria: they ask how many DISJOINT")
print("  environment fragments independently carry the system's information.")
nsys=1; nenv=L-nsys
frags=[f for r in range(1,nenv+1) for f in itertools.combinations(range(nsys,L),r)]
print(f"  system = link 1.  environment = links 2,3.  DISJOINT fragment count available: {nenv}")
print(f"  all fragments (incl. overlapping): {len(frags)}  ->  {[list(f) for f in frags]}")
print()
print("  quantum Darwinism's signature is a PLATEAU in mutual information versus fragment size,")
print("  and R_delta counts how many independent fragments reach (1-delta) of the system entropy.")
print("  With TWO environment links the fragment-size axis has exactly TWO points.")
print("  A plateau cannot be exhibited on two points, and R_delta cannot exceed 2.")
print()
# and measure it, rather than only counting
def mutinf(rho,A,B,n=L):
    def red(r,keep):
        d=[2]*n; r=r.reshape(d+d)
        tr=[i for i in range(n) if i not in keep]
        for k,i in enumerate(sorted(tr,reverse=True)): r=np.trace(r,axis1=i,axis2=i+n-k)
        m=2**len(keep); return r.reshape(m,m)
    S=lambda r:(lambda w:-sum(x*np.log2(x) for x in w if x>1e-12))(np.linalg.eigvalsh(r))
    return S(red(rho,A))+S(red(rho,B))-S(red(rho,sorted(A+B)))
lam=0.7
H=-lam*(X1+X2+X3)-(W12+W23)
Hp=P@H@P
w,v=np.linalg.eigh(Hp)
psi=v[:,np.argmax(np.abs(w)*0+ (np.abs(np.diag(P@np.eye(8)@P))*0) + 0)] if False else None
idx=[i for i in range(8) if abs(w[i])>1e-12 or True]
# ground state within the physical sector
ev,evec=np.linalg.eigh(Hp + 1e6*(np.eye(8)-P))
psi=evec[:,0]; psi=psi/np.linalg.norm(psi)
rho=np.outer(psi,psi.conj())
print("  MEASURED on the ground state of H = -0.7*sum X_i - (W12 + W23), physical sector:")
for f in [[1],[2],[1,2]]:
    print(f"    I(link 1 : links {[x+1 for x in f]})  =  {mutinf(rho,[0],f):.6f} bits")
print("    system entropy S(link 1) is the plateau height the criterion needs.")

