"""LANE O-2/O-3, PART 2.  WHY THE FIRST-ORDER MATRIX ELEMENT VANISHES TO ORDER d-1.

Part 1 established the exact criterion for first-order splitting:
        E0 splits at first order under V  <=>  Phi(V) := PVP - (tr PVP/n) P  !=  0,
and that for a 0-form symmetry there is always a SINGLE-SITE V with Phi(V) != 0, because a 0-form
charge is a SUM OF LOCAL DENSITIES and some density must be non-scalar on the multiplet.

This part does the other half of the contrast.  The claim to be proved and measured:

  THEOREM (topological vanishing).  Let E0 be the code space of a stabiliser code of distance d, with
  H0 = -sum_j S_j so that E0 is the ground eigenspace with gap 2.  Let V_w = the real span of Pauli
  operators of weight <= w.  Then
        rank Phi restricted to V_w  =  0   for all  w < d,
  so NO perturbation of weight < d splits E0 at first order, generic or not; and the splitting obeys
        Delta(eps)  ~  eps^(ceil(d/w)),   in particular  Delta ~ eps^d  for single-site noise.

  PROOF OF THE VANISHING (this is the whole mechanism, in three lines).
    Let O be a Pauli of weight |O| < d.
      - if O ANTICOMMUTES with some stabiliser S_j, then P O P = P O P and S_j P = P, so
        P O P = P S_j O S_j P = - P O P = 0.  Scalar (namely 0).
      - if O COMMUTES with every stabiliser and lies IN the stabiliser group, P O P = +- P.  Scalar.
      - if O commutes with every stabiliser and is NOT in the stabiliser group, O is by definition an
        undetectable non-trivial logical operator, so |O| >= d.  EXCLUDED by |O| < d.
    Hence every Pauli of weight < d has P O P in C.P, so Phi = 0 on all of V_w for w < d.  QED
    THIS IS EXACTLY THE KNILL-LAFLAMME CONDITION.  "Distance d" and "no first-order splitting below
    weight d" are THE SAME STATEMENT, not two facts that happen to agree.

  WHY THE 0-FORM CASE CANNOT DO THIS.  The non-scalar operators on E0 are the logical operators.  In
  the topological case they are non-contractible LOOPS -- there is no local density whose sum they
  are.  In the 0-form case the non-scalar operator Q^a = sum_x q^a_x IS a sum of local densities, so
  one density is already non-scalar.  d = 1.  That single sentence is the whole contrast.

MEASURED HERE
  SELF-CHECK  brute-force the distance d of every code from its definition (minimum weight of an
              undetectable non-trivial Pauli) and check it against the code's known d.
  MEASURED 1  the first-order rank of Phi on V_w for w = 1..d, for each code.  Must be 0 below d.
  MEASURED 2  the splitting exponent under single-site noise.  Prediction: slope = d.
  POSITIVE CONTROL  a d = 1 code ([[3,1,1]] with a weight-1 logical) run through the identical
              pipeline.  It must give rank Phi > 0 at w = 1 and slope 1.  Without it, every zero
              below would be uncontrolled.
"""
import itertools
import numpy as np

rng = np.random.default_rng(4242)
I2 = np.eye(2, dtype=complex)
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
PAULI = {'I': I2, 'X': SX, 'Y': SY, 'Z': SZ}


def pauli_mat(s):
    M = np.array([[1.0 + 0j]])
    for ch in s:
        M = np.kron(M, PAULI[ch])
    return M


def weight(s):
    return sum(1 for ch in s if ch != 'I')


def symp(a, b):
    """0 if the two Pauli strings commute, 1 if they anticommute."""
    c = 0
    for x, y in zip(a, b):
        if x != 'I' and y != 'I' and x != y:
            c ^= 1
    return c


def pauli_group_elems(n):
    return [''.join(p) for p in itertools.product('IXYZ', repeat=n)]


def stab_group(gens, n):
    """the abelian group generated by gens, as a set of Pauli strings ignoring phase."""
    mul = {}
    def m(a, b):
        out = []
        for x, y in zip(a, b):
            if x == 'I':
                out.append(y)
            elif y == 'I':
                out.append(x)
            elif x == y:
                out.append('I')
            else:
                out.append({'XY': 'Z', 'YX': 'Z', 'XZ': 'Y', 'ZX': 'Y', 'YZ': 'X', 'ZY': 'X'}[x + y])
        return ''.join(out)
    S = {'I' * n}
    frontier = ['I' * n]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = m(a, g)
                if b not in S:
                    S.add(b); nxt.append(b)
        frontier = nxt
    return S


def brute_distance(gens, n):
    """min weight of a Pauli that commutes with every generator but is NOT in the stabiliser group."""
    S = stab_group(gens, n)
    best = None
    witness = None
    for p in pauli_group_elems(n):
        if p == 'I' * n:
            continue
        if all(symp(p, g) == 0 for g in gens) and p not in S:
            w = weight(p)
            if best is None or w < best:
                best, witness = w, p
    return best, witness, len(S)


CODES = {
    "[[3,1,1]] POSITIVE CONTROL (weight-1 logical)": (["ZZI", "IZZ"], 1),
    "[[4,2,2]]": (["XXXX", "ZZZZ"], 2),
    "toric code 2x2 torus = [[8,2,2]]": (None, 2),        # filled in below
    "[[5,1,3]] perfect code": (["XZZXI", "IXZZX", "XIXZZ", "ZXIXZ"], 3),
    "[[7,1,3]] Steane code": (["IIIXXXX", "IXXIIXX", "XIXIXIX",
                               "IIIZZZZ", "IZZIIZZ", "ZIZIZIZ"], 3),
}


def toric_2x2_generators():
    """8 qubits on the links of a 2x2 periodic square lattice.
    link index: h(i,j) = j*2+i  (0..3),  v(i,j) = 4 + j*2+i  (4..7)."""
    h = lambda i, j: (j % 2) * 2 + (i % 2)
    v = lambda i, j: 4 + (j % 2) * 2 + (i % 2)
    gens = []
    for j in range(2):
        for i in range(2):
            # vertex operator: X on the four links touching vertex (i,j)
            links = [h(i, j), h(i - 1, j), v(i, j), v(i, j - 1)]
            s = ['I'] * 8
            for L in links:
                s[L] = 'X' if s[L] == 'I' else 'I'    # a link touched twice cancels (2x2 lattice)
            gens.append(''.join(s))
            # plaquette operator: Z on the four links around plaquette (i,j)
            links = [h(i, j), v(i + 1, j), h(i, j + 1), v(i, j)]
            s = ['I'] * 8
            for L in links:
                s[L] = 'Z' if s[L] == 'I' else 'I'
            gens.append(''.join(s))
    # keep an independent generating set
    return gens


gens_t = toric_2x2_generators()
CODES["toric code 2x2 torus = [[8,2,2]]"] = (gens_t, 2)


def independent(gens, n):
    """reduce to an independent generating set over F2 in symplectic representation."""
    rows = []
    keep = []
    for g in gens:
        vec = 0
        for k, ch in enumerate(g):
            if ch in 'XY':
                vec |= 1 << (2 * k)
            if ch in 'ZY':
                vec |= 1 << (2 * k + 1)
        cur = vec
        for r in rows:
            p = r.bit_length() - 1
            if cur >> p & 1:
                cur ^= r
        if cur:
            rows.append(cur); rows.sort(reverse=True); keep.append(g)
    return keep


def code_space(gens, n):
    N = 2 ** n
    H = np.zeros((N, N), complex)
    for g in gens:
        H -= pauli_mat(g)
    H = (H + H.conj().T) / 2
    ev, U = np.linalg.eigh(H)
    tol = 1e-8 * max(1.0, abs(ev).max())
    sel = np.abs(ev - ev[0]) < tol
    Q = U[:, sel]
    return H, Q, Q @ Q.conj().T, ev


def phi(V, Q):
    B = Q.conj().T @ V @ Q
    m = B.shape[0]
    return B - np.trace(B) / m * np.eye(m)


def first_order_rank(ops, Q, tol=1e-9):
    rows = []
    m = Q.shape[1]
    for V in ops:
        A = phi(V, Q)
        v = []
        for a in range(m):
            for b in range(a, m):
                if a == b:
                    v.append(A[a, a].real)
                else:
                    v.append(A[a, b].real); v.append(A[a, b].imag)
        rows.append(v)
    M = np.array(rows)
    s = np.linalg.svd(M, compute_uv=False)
    smax = s.max() if s.size else 0.0
    return int(np.sum(s > tol * max(1.0, smax))), float(smax)


def paulis_of_weight(n, w):
    out = []
    for supp in itertools.combinations(range(n), w):
        for letters in itertools.product('XYZ', repeat=w):
            s = ['I'] * n
            for k, ch in zip(supp, letters):
                s[k] = ch
            out.append(''.join(s))
    return out


def splitting(H, P0, m):
    ev, U = np.linalg.eigh(H)
    ov = np.einsum('ij,jk,ki->i', U.conj().T, P0, U).real
    idx = np.argsort(-ov)[:m]
    e = np.sort(ev[idx])
    return e[-1] - e[0]


def slope_fit(H0, V, P0, m, eps_list):
    xs, ys = [], []
    for eps in eps_list:
        s = splitting(H0 + eps * V, P0, m)
        if s > 1e-12:
            xs.append(np.log(eps)); ys.append(np.log(s))
    if len(xs) < 2:
        return float('nan'), 0.0, []
    A = np.polyfit(xs, ys, 1)
    res = float(np.max(np.abs(np.polyval(A, xs) - ys)))
    return A[0], res, list(zip(np.exp(xs), np.exp(ys)))


print("=" * 104)
print("LANE O-2 PART 2.  THE TOPOLOGICAL SIDE: WHY THE MATRIX ELEMENT VANISHES TO ORDER d-1")
print("=" * 104)

print("\nSELF-CHECK -- brute-force the distance of every code from the definition and compare to its")
print("known value.  (min weight of a Pauli commuting with all stabilisers but outside the group.)")
info = {}
for name, (gens, d_known) in CODES.items():
    n = len(gens[0])
    gi = independent(gens, n)
    d_meas, wit, nS = brute_distance(gi, n)
    k = n - len(gi)
    print(f"    {name:<46s} n={n} k={k}  |S|={nS:4d}  measured d = {d_meas}  known d = {d_known}  "
          f"witness = {wit}   {'PASS' if d_meas == d_known else 'FAIL'}")
    info[name] = (gi, n, k, d_meas)

print("\n" + "-" * 104)
print("MEASURED 1.  rank of Phi on V_w = span{Pauli of weight exactly w}.  Theory: 0 for every w < d.")
print("-" * 104)
for name, (gi, n, k, d) in info.items():
    H, Q, P, ev = code_space(gi, n)
    m = Q.shape[1]
    print(f"    {name}   (ground degeneracy {m} = 2^{k}, gap {ev[2**k] - ev[0]:.3f})")
    for w in range(1, min(d + 1, n) + 1):
        ops = [pauli_mat(s) for s in paulis_of_weight(n, w)]
        r, smax = first_order_rank(ops, Q)
        # also the largest single-Pauli defect at this weight
        best = max(float(np.linalg.norm(phi(V, Q))) for V in ops)
        flag = "  <-- FIRST WEIGHT THAT SPLITS" if r > 0 and w == d else ""
        print(f"        w = {w}:  #Paulis = {len(ops):5d}   rank Phi = {r:3d}   "
              f"max ||Phi(single Pauli)|| = {best:.3e}{flag}")
    print()

print("-" * 104)
print("MEASURED 2.  splitting exponent under a random SINGLE-SITE (weight-1) perturbation.")
print("             Theory: Delta ~ eps^d.  slope must equal d.")
print("-" * 104)
results = []
for name, (gi, n, k, d) in info.items():
    H, Q, P, ev = code_space(gi, n)
    m = Q.shape[1]
    V = sum(rng.normal() * pauli_mat(s) for s in paulis_of_weight(n, 1))
    V = (V + V.conj().T) / 2
    V = V / np.linalg.norm(V) * np.linalg.norm(H)
    # choose an eps window where the leading power dominates but the splitting is well above 1e-13
    if d == 1:
        eps_l = np.array([1e-6, 1e-5, 1e-4, 1e-3])
    elif d == 2:
        eps_l = np.array([1e-4, 3e-4, 1e-3, 3e-3])
    else:
        eps_l = np.array([3e-3, 5e-3, 1e-2, 2e-2])
    sl, res, pts = slope_fit(H, V, P, m, eps_l)
    results.append((name, d, sl, res))
    print(f"    {name:<46s} d = {d}   measured slope = {sl:.4f}   max log-log residual = {res:.1e}")
    for e, s in pts:
        print(f"          eps = {e:.1e}   splitting = {s:.6e}")
print()
ok = all(abs(sl - d) < 0.05 for _, d, sl, _ in results)
print(f"    SLOPE LAW  'splitting exponent = code distance':  "
      f"{'CONFIRMED on all ' + str(len(results)) + ' codes' if ok else 'NOT CONFIRMED'}")
print("    the d=1 row is the POSITIVE CONTROL: identical pipeline, and it registers slope 1.")

print("\n" + "-" * 104)
print("MEASURED 3.  the mechanism, term by term, on the [[5,1,3]] code: classify every weight-1 and")
print("             weight-2 Pauli into the three cases of the proof, and show the count is exhaustive.")
print("-" * 104)
gi, n, k, d = info["[[5,1,3]] perfect code"]
S = stab_group(gi, n)
H, Q, P, ev = code_space(gi, n)
for w in (1, 2, 3):
    anti = incl = logi = 0
    maxdev = 0.0
    for s in paulis_of_weight(n, w):
        commutes = all(symp(s, g) == 0 for g in gi)
        if not commutes:
            anti += 1
        elif s in S:
            incl += 1
        else:
            logi += 1
        M = pauli_mat(s)
        maxdev = max(maxdev, float(np.linalg.norm(phi(M, Q))))
    tot = len(paulis_of_weight(n, w))
    print(f"    weight {w}: anticommutes with a stabiliser = {anti:4d}   in the stabiliser group = {incl:3d}"
          f"   non-trivial logical = {logi:3d}   total {tot:4d}  "
          f"({'exhaustive' if anti + incl + logi == tot else 'NOT EXHAUSTIVE'})")
    print(f"              max ||Phi|| over all weight-{w} Paulis = {maxdev:.3e}   "
          f"{'-> every one is SCALAR on the code space' if maxdev < 1e-10 else '-> some are NON-SCALAR'}")

print("\n" + "=" * 104)
print("WHAT PART 2 ESTABLISHES")
print("=" * 104)
print("""  The vanishing of the first-order matrix element in the topological case is NOT a genericity
  statement and NOT an accident of the perturbation chosen.  It is the Knill-Laflamme condition:
  every Pauli of weight below the distance either anticommutes with a stabiliser (then PVP = 0) or
  lies in the stabiliser group (then PVP = +-P).  Both are SCALAR, so Phi vanishes IDENTICALLY on the
  whole space of sub-distance perturbations -- rank Phi = 0, not 'rank Phi generically small'.

  THE ONE-SENTENCE CONTRAST WITH THE 0-FORM CASE:
     a 0-form charge is a SUM OF LOCAL DENSITIES, so some density is already non-scalar on the
     multiplet and rank Phi >= 1 at weight 1;
     a 1-form charge is carried by NON-CONTRACTIBLE LOOPS, which are not sums of local densities, so
     rank Phi = 0 until the weight reaches the length of the shortest such loop, which is d.
  The exponent d in Delta ~ eps^d is the LENGTH OF THE SHORTEST NON-SCALAR OPERATOR.  For a 0-form
  symmetry that length is 1.""")
