#!/usr/bin/env python3
"""
LANE O-1 -- THE CONVERSE, REPAIRED AND STATED WITH ITS HYPOTHESES.

O-1 as registered:  "the converse of P-2: degeneracy gives (i)-(iii), not (ii)
compatibility with {L_k} nor (iv) flippability."

VERDICT DELIVERED BY THIS LANE: the converse is FALSE as registered, and the two missing
hypotheses are exactly these.

  THEOREM O1-C.  Let H be a Hamiltonian on a finite-dimensional Hilbert space of dimension
  D, {L_k} the jump operators, A = alg{I, H, L_k, L_k^dag} the *-algebra they generate and
  A' its commutant.  Then an R satisfying clauses (i),(ii),(iii),(iv) exists

      <=>  there is a PROJECTION Q in A' with

           (H1)  P_lam Q P_lam is neither 0 nor P_lam, for some eigenprojector P_lam of H
                 -- equivalently, the compression P_lam A P_lam is a PROPER subalgebra of
                 B(E_lam), i.e. the dynamics is REDUCIBLE on that degenerate eigenspace;

           (H2)  2 Tr Q = D  -- the record is TRACE-BALANCED.

  and then R = I - 2Q works, with a writer U built as the swap of the two eigenspaces of R.
  ("admissible" is read at its most permissive: any unitary.  Any narrower reading only
  removes writers, so (H1)+(H2) remain necessary; and by Theorem O1-B3 the narrow reading
  'generated by the theory's own operators' removes ALL of them.)

  DEGENERACY ALONE IMPLIES NEITHER HYPOTHESIS.  Degeneracy is a property of H; (H1) is a
  property of the pair (H,{L_k}); (H2) is a property of the noise's block structure.

  NOT COVERED: clause (v).  Protection quantifies over "operations on a contractible
  region", and (H, {L_k}) carries no locality structure at all, so (v) cannot even be
  stated in this setting.  O-1 as registered names only (ii) and (iv); the (v) half is a
  separate hypothesis and is flagged here, not closed.

This file verifies Theorem O1-C by EXHAUSTIVE ENUMERATION on a family of systems in which
every involution in A' can be listed, comparing the criterion against direct testing of
clauses (i)-(iv) on explicit matrices.
"""

import numpy as np
from itertools import combinations
from o1_core import (hermitian_commutant, generated_algebra, eigenspaces, clause_report,
                     span_dim, selfchecks)

np.set_printoptions(precision=6, suppress=True, linewidth=170)


def show(t):
    print("\n" + "=" * 98)
    print(t)
    print("=" * 98)


def build_system(sizes, energies, rng):
    """H is constant on each noise block (value = energies[i]); L is block-diagonal with
    generic, mutually inequivalent blocks of the given sizes."""
    D = sum(sizes)
    H = np.zeros((D, D), dtype=complex)
    L = np.zeros((D, D), dtype=complex)
    projs, o = [], 0
    for i, s in enumerate(sizes):
        H[o:o + s, o:o + s] = energies[i] * np.eye(s)
        B = rng.normal(size=(s, s)) + 1j * rng.normal(size=(s, s))
        L[o:o + s, o:o + s] = B + (7.0 * (i + 1)) * np.eye(s)   # inequivalent blocks
        P = np.zeros((D, D), dtype=complex)
        P[o:o + s, o:o + s] = np.eye(s)
        projs.append(P)
        o += s
    return H, L, projs


def predict(sizes, energies):
    """(H1)+(H2) evaluated combinatorially on the block data."""
    D = sum(sizes)
    nb = len(sizes)
    for k in range(1, nb):
        for S in combinations(range(nb), k):
            if 2 * sum(sizes[i] for i in S) != D:
                continue                                   # (H2)
            for lam in set(energies):                      # (H1)
                blocks = [i for i in range(nb) if energies[i] == lam]
                inS = [i for i in blocks if i in S]
                if inS and len(inS) < len(blocks):
                    return True
    return False


def brute(H, L, projs, rng):
    """Enumerate every involution R = I - 2Q with Q a sum of block projections, and test
    clauses (i)-(iv) directly on the matrices.  Returns (found, R, U)."""
    D = H.shape[0]
    nb = len(projs)
    for k in range(1, nb):
        for S in combinations(range(nb), k):
            Q = sum(projs[i] for i in S)
            R = np.eye(D) - 2 * Q
            if np.linalg.norm(R - R.conj().T) > 1e-9 or np.linalg.norm(R @ R - np.eye(D)) > 1e-9:
                continue                                                    # (i)
            if np.linalg.norm(H @ R - R @ H) > 1e-9:
                continue                                                    # (ii) a
            if np.linalg.norm(L @ R - R @ L) > 1e-9:
                continue                                                    # (ii) b
            nontriv = False
            for lam, cols in eigenspaces(H):
                m = cols.shape[1]
                if m < 2:
                    continue
                Rl = cols.conj().T @ R @ cols
                if np.linalg.norm(Rl - np.trace(Rl) / m * np.eye(m)) > 1e-9:
                    nontriv = True
            if not nontriv:
                continue                                                    # (iii)
            w, v = np.linalg.eigh(R)
            pl, mn = v[:, w > 0], v[:, w < 0]
            if pl.shape[1] != mn.shape[1]:
                continue                                                    # (iv)
            U = pl @ mn.conj().T + mn @ pl.conj().T
            if np.linalg.norm(U.conj().T @ R @ U + R) > 1e-9:
                continue
            return True, R, U
    return False, None, None


def main():
    print("O-1 -- THE CONVERSE, REPAIRED (THEOREM O1-C)")
    print("machinery self-checks first:\n")
    if not selfchecks():
        raise SystemExit("self-checks failed")
    rng = np.random.default_rng(90210)

    # ------------------------------------------------------------------------------
    show("PART 1 -- EXHAUSTIVE VERIFICATION OF THEOREM O1-C.")
    print("  Family: D in {4,6,8}; every unordered block structure of the noise; every")
    print("  assignment of block energies drawn from {0,1,2} (so eigenspaces of H are unions")
    print("  of noise blocks).  For each system: the combinatorial criterion (H1)+(H2) is")
    print("  compared against direct testing of clauses (i)-(iv) on explicit matrices.\n")

    def partitions(n, maxp=None):
        if maxp is None:
            maxp = n
        if n == 0:
            yield []
            return
        for k in range(min(n, maxp), 0, -1):
            for rest in partitions(n - k, k):
                yield [k] + rest

    total = agree = 0
    disagreements = []
    yes_cases = no_cases = 0
    for D in (4, 6, 8):
        for sizes in partitions(D):
            if len(sizes) < 2:
                continue
            nb = len(sizes)
            for trial in range(6):
                energies = [int(rng.integers(0, 3)) for _ in range(nb)]
                H, L, projs = build_system(sizes, energies, rng)
                p = predict(sizes, energies)
                b, R, U = brute(H, L, projs, rng)
                total += 1
                if p == b:
                    agree += 1
                else:
                    disagreements.append((D, tuple(sizes), tuple(energies), p, b))
                yes_cases += int(b)
                no_cases += int(not b)
    print(f"  systems tested                         : {total}")
    print(f"  criterion agrees with direct testing   : {agree}/{total}")
    print(f"  systems where a full record EXISTS     : {yes_cases}")
    print(f"  systems where NO full record exists    : {no_cases}   <- the converse's failures")
    print(f"  disagreements                          : {len(disagreements)}")
    for d in disagreements[:5]:
        print("    ", d)
    print(f"\n  THEOREM O1-C: {'PASS' if agree == total else 'FAIL'}")
    print("  Both outcomes occur in quantity, so this is not a one-sided test.")

    # ------------------------------------------------------------------------------
    show("PART 2 -- THE FOUR CORNERS.  (H1) and (H2) fail independently.")
    print("  D = 6 throughout.  Only the block sizes and their energies change.\n")
    corners = [
        ("(H1) yes, (H2) yes", [3, 3], [0, 0]),
        ("(H1) yes, (H2) NO ", [2, 4], [0, 0]),
        ("(H1) NO , (H2) yes", [3, 3], [0, 1]),
        ("(H1) NO , (H2) NO ", [2, 4], [0, 1]),
    ]
    print(f"  {'corner':20s} {'sizes':10s} {'energies':10s} {'predict':>8} {'brute':>7}   clause values")
    for name, sizes, energies in corners:
        H, L, projs = build_system(sizes, energies, rng)
        p = predict(sizes, energies)
        b, R, U = brute(H, L, projs, rng)
        print(f"  {name:20s} {str(sizes):10s} {str(energies):10s} "
              f"{str(p):>8} {str(b):>7}", end="")
        if b:
            D = H.shape[0]
            c2 = max(np.linalg.norm(H @ R - R @ H), np.linalg.norm(L @ R - R @ L))
            c4 = np.linalg.norm(U.conj().T @ R @ U + R)
            print(f"   (ii) {c2:.1e}  (iv) {c4:.1e}  Tr R = {np.real(np.trace(R)):+.1f}")
        else:
            print("   -- no R passes all four clauses")
    print("\n  '(H1) NO, (H2) yes' is the instructive corner: the noise DOES leave a record")
    print("  and it IS trace-balanced, but H separates the two blocks into different")
    print("  eigenvalues, so R is a function of H and clause (iii) dies.  The three ways of")
    print("  failing are genuinely different failures.")

    # ------------------------------------------------------------------------------
    show("PART 3 -- THE CONSTRUCTIVE DIRECTION, END TO END.")
    print("  A system satisfying (H1) and (H2); R and the writer U are built and every")
    print("  clause the abstract setting can express is evaluated.\n")
    H, L, projs = build_system([3, 3], [0, 0], rng)
    b, R, U = brute(H, L, projs, rng)
    D = H.shape[0]
    print(f"  H = 0 on C^6 (6-fold degenerate);  L = L_3 (+) L_3, one jump operator")
    print(f"  dim A = {len(generated_algebra([H, L], D))}   "
          f"dim A' = {len(hermitian_commutant([H, L], D))}")
    clause_report(H, [L], R, "constructed record R")
    print(f"  (iv) ||U^dag R U + R||               = {np.linalg.norm(U.conj().T @ R @ U + R):.3e}")
    print(f"       U is unitary: ||U^dag U - I||   = {np.linalg.norm(U.conj().T @ U - np.eye(D)):.3e}")
    print(f"       the writer does NOT commute with H: ||[U,H]|| = "
          f"{np.linalg.norm(U @ H - H @ U):.3e}  (H = 0 here, so this is 0 by triviality)")
    print(f"       the writer does NOT commute with L: ||[U,L]|| = "
          f"{np.linalg.norm(U @ L - L @ U):.3e}  <- P-2, measured")
    print("\n  (v) PROTECTION IS NOT EVALUATED.  (H,{L_k}) carries no notion of a contractible")
    print("  region, so clause (v) has no referent in this setting.  Stated, not closed.")

    # ------------------------------------------------------------------------------
    show("PART 4 -- A CASE WITH MULTIPLICITY, where A' is NON-commutative.")
    print("  L = B (+) B with the SAME block twice: A is M_3 with multiplicity 2, so")
    print("  A' = M_2 (x) I_3, dimension 4 -- the commutant is non-commutative and the")
    print("  records form a 2-sphere rather than a finite set.\n")
    B = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
    Lm = np.zeros((6, 6), dtype=complex)
    Lm[:3, :3] = B
    Lm[3:, 3:] = B
    Hm = np.zeros((6, 6), dtype=complex)
    hbm = hermitian_commutant([Hm, Lm], 6)
    Am = generated_algebra([Hm, Lm], 6)
    print(f"  dim A = {len(Am)} (expected 9),  dim A' = {len(hbm)} (expected 4),  "
          f"A' commutative: "
          f"{all(np.linalg.norm(a@b - b@a) < 1e-8 for a in hbm for b in hbm)}")
    theta = 0.7
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    Rm = np.kron(np.cos(theta) * sz + np.sin(theta) * sx, np.eye(3))
    clause_report(Hm, [Lm], Rm, "a record at angle theta = 0.7")
    w, v = np.linalg.eigh(Rm)
    Um = v[:, w > 0] @ v[:, w < 0].conj().T + v[:, w < 0] @ v[:, w > 0].conj().T
    print(f"  (iv) ||U^dag R U + R|| = {np.linalg.norm(Um.conj().T @ Rm @ Um + Rm):.3e}")
    print("  Here (H2) holds automatically because the multiplicity space is even-")
    print("  dimensional.  Multiplicity is one structural way to guarantee the trace")
    print("  balance that Theorem O1-B demands -- a candidate hypothesis for a future")
    print("  sufficient condition, NOT a proof that the converse holds.")


if __name__ == "__main__":
    main()
