#!/usr/bin/env python3
"""
LANE O-1 -- THE CONVERSE OF P-2.

P-2 as written in CORE_FRAMEWORK_V001.md:
  "P-2.  (ii)+(iv) => the writer is built from neither H nor {L_k}.  W anticommutes with R
   while H and every L_k commute with it."

The O-1 row as registered:
  "the converse of P-2: degeneracy gives (i)-(iii), not (ii) compatibility with {L_k}
   nor (iv) flippability"

This file is MACHINERY ONLY.  It builds and self-tests the commutant solver used by
o1_gap_a_compatibility.py, o1_gap_b_flippability.py and o1_toric_pauli.py.

Every self-check below has an answer known independently of this code.
"""

import numpy as np

np.set_printoptions(precision=6, suppress=True, linewidth=160)


# ----------------------------------------------------------------------------------
# LEMMA 0 (used everywhere below).  For R Hermitian, [L,R]=0  <=>  [L^dag,R]=0.
#   ([L,R])^dag = R^dag L^dag - L^dag R^dag = R L^dag - L^dag R = [R, L^dag].
# So clause (ii) forces R into the commutant of the *-ALGEBRA generated by
# {I, H, L_k, L_k^dag}, not merely of the set {H, L_k}.  This is the whole of gap (a).
# ----------------------------------------------------------------------------------


def commutant_basis(ops, d, tol=1e-9):
    """Orthonormal (Hilbert-Schmidt) basis of {X in C^{dxd} : [X,O]=0 for all O in ops}.

    Returns (basis_list, dim).  dim is the COMPLEX dimension.
    Because we always pass a *-closed set of ops, the commutant is *-closed and the
    Hermitian elements form a REAL vector space of the same dimension.
    """
    I = np.eye(d)
    rows = []
    for O in ops:
        # row-major vec: vec(A X B) = (A (x) B^T) vec(X)
        M = np.kron(I, O.T) - np.kron(O, I)
        rows.append(M)
    if not rows:
        A = np.zeros((1, d * d), dtype=complex)
    else:
        A = np.vstack(rows)
    # null space via SVD
    _, s, vh = np.linalg.svd(A)
    s_full = np.zeros(d * d)
    s_full[: len(s)] = s
    null = vh[s_full <= tol * max(1.0, s_full.max() if s_full.size else 1.0)]
    basis = [v.reshape(d, d) for v in null.conj()]
    return basis, len(basis)


def star_closure(ops):
    out = []
    for O in ops:
        out.append(O)
        out.append(O.conj().T)
    return out


def hermitian_commutant(ops, d, tol=1e-9):
    """Real-orthonormal basis of the HERMITIAN elements of the commutant."""
    b, k = commutant_basis(star_closure(ops), d, tol)
    herm = []
    for X in b:
        herm.append((X + X.conj().T) / 2.0)
        herm.append((X - X.conj().T) / (2.0j))
    # real-orthonormalise under <A,B> = Re Tr(A^dag B)
    out = []
    for X in herm:
        for Y in out:
            X = X - np.real(np.trace(Y.conj().T @ X)) * Y
        n = np.sqrt(np.real(np.trace(X.conj().T @ X)))
        if n > 1e-8:
            out.append(X / n)
    return out


def generated_algebra(ops, d, tol=1e-9, maxit=40):
    """HS-orthonormal basis of the *-algebra generated by {I} u ops u ops^dag."""
    seeds = [np.eye(d, dtype=complex)] + list(star_closure(ops))

    def add(basis, X):
        for Y in basis:
            X = X - np.trace(Y.conj().T @ X) * Y
        n = np.sqrt(abs(np.trace(X.conj().T @ X)))
        if n > 1e-7:
            basis.append(X / n)
            return True
        return False

    basis = []
    for X in seeds:
        add(basis, X)
    for _ in range(maxit):
        grew = False
        cur = list(basis)
        for A in cur:
            for B in cur:
                if add(basis, A @ B):
                    grew = True
        if not grew:
            break
    return basis


def compress(basis, P_cols):
    """Compress a list of operators to the subspace spanned by the columns of P_cols."""
    return [P_cols.conj().T @ X @ P_cols for X in basis]


def span_dim(mats, tol=1e-8):
    if not mats:
        return 0
    V = np.array([m.ravel() for m in mats])
    return int(np.linalg.matrix_rank(V, tol=tol))


def eigenspaces(H, tol=1e-8):
    """[(eigenvalue, columns spanning the eigenspace)] for Hermitian H."""
    w, v = np.linalg.eigh(H)
    out = []
    i = 0
    while i < len(w):
        j = i
        while j + 1 < len(w) and abs(w[j + 1] - w[i]) < tol:
            j += 1
        out.append((float(w[i]), v[:, i : j + 1]))
        i = j + 1
    return out


def record_search(H, Ls, tol=1e-8, seed=0):
    """Search for R satisfying (i) bit, (ii) durable, (iii) non-trivial.

    Returns dict with the Hermitian-commutant dimension, and an explicit R if found.
    Strategy: R must lie in the commutant A' of the *-algebra A = alg{I,H,L_k,L_k^dag}.
    Take a random Hermitian element of A', cluster its spectrum, and form the spectral
    projections -- these lie in A' too.  Any non-trivial one gives R = I - 2Q.
    """
    d = H.shape[0]
    ops = [H] + list(Ls)
    hb = hermitian_commutant(ops, d, tol)
    res = {"herm_commutant_dim": len(hb), "R": None, "lambda": None}
    if len(hb) <= 1:
        return res
    rng = np.random.default_rng(seed)
    for attempt in range(20):
        c = rng.normal(size=len(hb))
        X = sum(ci * Bi for ci, Bi in zip(c, hb))
        X = (X + X.conj().T) / 2
        w, v = np.linalg.eigh(X)
        # cluster
        groups, cur = [], [0]
        for i in range(1, d):
            if abs(w[i] - w[i - 1]) < 1e-7:
                cur.append(i)
            else:
                groups.append(cur)
                cur = [i]
        groups.append(cur)
        if len(groups) < 2:
            continue
        for split in range(1, len(groups)):
            idx = [i for g in groups[:split] for i in g]
            Q = v[:, idx] @ v[:, idx].conj().T
            R = np.eye(d) - 2 * Q
            # verify (i),(ii)
            if np.linalg.norm(R @ R - np.eye(d)) > 1e-8:
                continue
            if np.linalg.norm(R - R.conj().T) > 1e-8:
                continue
            if np.linalg.norm(H @ R - R @ H) > 1e-7:
                continue
            if any(np.linalg.norm(L @ R - R @ L) > 1e-7 for L in Ls):
                continue
            # (iii): non-constant on SOME eigenspace of H
            for lam, cols in eigenspaces(H):
                if cols.shape[1] < 2:
                    continue
                Rl = cols.conj().T @ R @ cols
                if np.linalg.norm(Rl - np.trace(Rl) / cols.shape[1] * np.eye(cols.shape[1])) > 1e-7:
                    res["R"] = R
                    res["lambda"] = lam
                    return res
    return res


def record_search_on(H, Ls, lam_index, tol=1e-8, seed=0):
    """Same as record_search but the record must be non-constant on the CHOSEN eigenspace."""
    d = H.shape[0]
    hb = hermitian_commutant([H] + list(Ls), d, tol)
    es = eigenspaces(H)
    lam, cols = es[lam_index]
    m = cols.shape[1]
    out = {"herm_commutant_dim": len(hb), "R": None, "lambda": lam, "m": m}
    if len(hb) <= 1 or m < 2:
        return out
    rng = np.random.default_rng(seed)
    for _ in range(30):
        c = rng.normal(size=len(hb))
        X = sum(ci * Bi for ci, Bi in zip(c, hb))
        X = (X + X.conj().T) / 2
        w, v = np.linalg.eigh(X)
        groups, cur = [], [0]
        for i in range(1, d):
            if abs(w[i] - w[i - 1]) < 1e-7:
                cur.append(i)
            else:
                groups.append(cur)
                cur = [i]
        groups.append(cur)
        for split in range(1, len(groups)):
            idx = [i for g in groups[:split] for i in g]
            Q = v[:, idx] @ v[:, idx].conj().T
            R = np.eye(d) - 2 * Q
            if np.linalg.norm(R @ R - np.eye(d)) > 1e-8:
                continue
            if np.linalg.norm(H @ R - R @ H) > 1e-7:
                continue
            if any(np.linalg.norm(L @ R - R @ L) > 1e-7 for L in Ls):
                continue
            Rl = cols.conj().T @ R @ cols
            if np.linalg.norm(Rl - np.trace(Rl) / m * np.eye(m)) > 1e-7:
                out["R"] = R
                return out
    return out


def clause_report(H, Ls, R, name=""):
    """Numerical values of clauses (i)-(iv).  (v) needs a locality structure; see note."""
    d = H.shape[0]
    c1a = np.linalg.norm(R - R.conj().T)
    c1b = np.linalg.norm(R @ R - np.eye(d))
    c2 = max([np.linalg.norm(H @ R - R @ H)] + [np.linalg.norm(L @ R - R @ L) for L in Ls])
    c3 = 0.0
    for lam, cols in eigenspaces(H):
        m = cols.shape[1]
        if m < 2:
            continue
        Rl = cols.conj().T @ R @ cols
        c3 = max(c3, float(np.linalg.norm(Rl - np.trace(Rl) / m * np.eye(m))))
    tr = float(np.real(np.trace(R)))
    print(f"  {name:38s} (i) {c1a:.2e}/{c1b:.2e}  (ii) {c2:.2e}  (iii) {c3:.4f}  Tr R = {tr:+.4f}")
    return dict(i=max(c1a, c1b), ii=c2, iii=c3, trace=tr)


# ==================================================================================
#  SELF-CHECKS -- every expected value is known independently of this code.
# ==================================================================================

def selfchecks():
    ok = True

    def chk(label, got, want):
        nonlocal ok
        good = (got == want)
        ok = ok and good
        print(f"  [{'PASS' if good else 'FAIL'}] {label:62s} got {got:6d}  want {want:6d}")

    print("SELF-CHECKS (commutant dimensions; all expected values known independently)")

    # 1. no constraints at all -> full matrix algebra
    chk("commutant of {I} on d=5 is all of M_5", commutant_basis([np.eye(5)], 5)[1], 25)

    # 2. one Hermitian with distinct eigenvalues -> the diagonal algebra, dim d
    rng = np.random.default_rng(1)
    A = rng.normal(size=(6, 6)) + 1j * rng.normal(size=(6, 6))
    A = A + A.conj().T
    chk("commutant of a generic Hermitian on d=6 is the diagonal, dim 6",
        commutant_basis([A], 6)[1], 6)

    # 3. Pauli: commutant of alg{XX, ZZ} on 2 qubits = span{II,XX,YY,ZZ}, dim 4
    X = np.array([[0, 1], [1, 0]], dtype=complex)
    Y = np.array([[0, -1j], [1j, 0]])
    Z = np.array([[1, 0], [0, -1]], dtype=complex)
    XX, ZZ = np.kron(X, X), np.kron(Z, Z)
    chk("commutant of alg{XX,ZZ} on 2 qubits = span{II,XX,YY,ZZ}",
        commutant_basis([XX, ZZ], 4)[1], 4)

    # 4. SU(2) on 2 spin-1/2: 0 (x) 1, multiplicities 1,1 -> dim A' = 1^2+1^2 = 2
    def spin_ops(n):
        sx, sy, sz = X / 2, Y / 2, Z / 2
        J = [np.zeros((2 ** n, 2 ** n), dtype=complex) for _ in range(3)]
        for i in range(n):
            for a, s in enumerate((sx, sy, sz)):
                op = np.eye(1, dtype=complex)
                for j in range(n):
                    op = np.kron(op, s if j == i else np.eye(2))
                J[a] += op
        return J

    chk("commutant of SU(2) on 2 spins = 1^2+1^2 = 2", commutant_basis(spin_ops(2), 4)[1], 2)

    # 5. SU(2) on 3 spin-1/2: 3/2 (x1) + 1/2 (x2) -> dim A' = 1^2 + 2^2 = 5
    chk("commutant of SU(2) on 3 spins = 1^2+2^2 = 5", commutant_basis(spin_ops(3), 8)[1], 5)

    # 6. A = I_3 (x) M_2  ->  A' = M_3 (x) I_2, dim 9
    B1 = rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2))
    B2 = rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2))
    ops6 = [np.kron(np.eye(3), B1), np.kron(np.eye(3), B2)]
    chk("commutant of I_3 (x) M_2 is M_3 (x) I_2, dim 9",
        commutant_basis(star_closure(ops6), 6)[1], 9)

    # 7. Hermitian commutant has the SAME dimension over R as the commutant over C
    hb = hermitian_commutant(spin_ops(3), 8)
    chk("dim_R(Hermitian part of A') = dim_C(A') for SU(2) on 3 spins", len(hb), 5)

    # 8. generated algebra: alg{XX,ZZ} = span{II,XX,YY,ZZ}, dim 4
    chk("dim alg{XX,ZZ} = 4", len(generated_algebra([XX, ZZ], 4)), 4)

    # 9. generated algebra of a generic pair on d=4 is all of M_4
    G1 = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
    chk("dim alg{generic G, G^dag} on d=4 = 16", len(generated_algebra([G1], 4)), 16)

    # 10. LEMMA 0 numerically: [L,R]=0 => [L^dag,R]=0 for Hermitian R
    R = np.diag([1, 1, -1, -1]).astype(complex)
    L = np.kron(np.eye(2), rng.normal(size=(2, 2)) + 1j * rng.normal(size=(2, 2)))
    lem = np.linalg.norm(L @ R - R @ L) < 1e-12 and np.linalg.norm(L.conj().T @ R - R @ L.conj().T) < 1e-12
    print(f"  [{'PASS' if lem else 'FAIL'}] LEMMA 0: [L,R]=0 and [L^dag,R]=0 together"
          f"{'':22s}")
    ok = ok and lem

    print(f"\nSELF-CHECKS: {'ALL PASS' if ok else 'SOME FAILED -- STOP'}")
    return ok


if __name__ == "__main__":
    good = selfchecks()
    raise SystemExit(0 if good else 1)
