#!/usr/bin/env python3
"""
LANE O-1, GAP (a): COMPATIBILITY WITH {L_k}.

QUESTION AS REGISTERED: given an exactly degenerate eigenspace of H, why should any R on
that subspace commute with every Lindblad operator L_k?

ANSWER DELIVERED HERE: it should not, and generically it does not.  The converse fails at
clause (ii).  Degeneracy is a property of H ALONE; clause (ii) is a property of the PAIR
(H, {L_k}); nothing carries one to the other.

  LEMMA 0.  For R Hermitian, [L,R]=0 <=> [L^dag,R]=0.  So clause (ii) puts R in the
            commutant A' of the *-ALGEBRA A = alg{I, H, L_k, L_k^dag}.

  THEOREM O1-A.  Fix an eigenvalue lam of H, eigenprojector P, m = dim E_lam >= 2.  Then
            some R satisfies (i),(ii) and is non-constant on E_lam
              <=>  the compression P A P, acting on E_lam, is a PROPER subalgebra of
                   B(E_lam), i.e. the compressed dynamics is REDUCIBLE on E_lam.
            Proof sketch.  R in A' commutes with P (P is a polynomial in H), so pi(R) =
            R|_E is defined; pi : A' -> B(E) is a *-homomorphism whose image is the
            commutant of PAP in B(E) (standard for P in A); projections lift along
            surjections of finite-dimensional C*-algebras, and a non-scalar projection
            exists in the image iff PAP is not all of B(E).  Then R = I - 2Q.

  COROLLARY.  Generic {L_k} => A = B(Hilb) => A' = C.I => NO RECORD, at any degeneracy.

  THE TRAP (Experiment 4).  PAP is the compression of the ALGEBRA, not the algebra
            generated by the compressions.  Jump operators whose compressions to EVERY
            eigenspace of H vanish identically can still leave no record anywhere.

Machinery + self-checks: o1_core.py.  Every null below is paired with a positive control.
"""

import numpy as np
from o1_core import (hermitian_commutant, commutant_basis, generated_algebra, eigenspaces,
                     record_search, record_search_on, clause_report, span_dim, selfchecks)

np.set_printoptions(precision=6, suppress=True, linewidth=160)


def compression_dim(H, Ls, lam_index=0):
    d = H.shape[0]
    A = generated_algebra([H] + list(Ls), d)
    lam, cols = eigenspaces(H)[lam_index]
    m = cols.shape[1]
    comp = [cols.conj().T @ X @ cols for X in A]
    return lam, m, span_dim(comp), m * m


def show(title):
    print("\n" + "=" * 96)
    print(title)
    print("=" * 96)


def main():
    print("O-1 GAP (a) -- COMPATIBILITY WITH THE JUMP OPERATORS")
    print("machinery self-checks first:\n")
    if not selfchecks():
        raise SystemExit("self-checks failed -- no headline number may be read")

    rng = np.random.default_rng(20260818)

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 1 -- THE NULL.  Degenerate H, one generic jump operator, no record.")
    H = np.diag([0.0, 0.0, 1.0, 1.0]).astype(complex)
    R_naive = np.diag([1.0, -1.0, 1.0, -1.0]).astype(complex)
    print("  H = diag(0,0,1,1).  With NO jump operators, R = diag(1,-1,1,-1) is a record:")
    clause_report(H, [], R_naive, "R, {L_k} empty")

    trivial, N = 0, 400
    for _ in range(N):
        L = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
        if len(hermitian_commutant([H, L], 4)) == 1:
            trivial += 1
    print(f"\n  {N} independent generic jump operators L, same H:")
    print(f"    Hermitian commutant is the scalars ONLY : {trivial}/{N}")
    print(f"    a record of any kind exists             : {N - trivial}/{N}")

    good = 0
    for t in range(N):
        L = np.diag(rng.normal(size=4) + 1j * rng.normal(size=4))
        if record_search(H, [L], seed=t)["R"] is not None:
            good += 1
    print(f"\n  POSITIVE CONTROL -- same H, {N} DIAGONAL jump operators (dephasing in the")
    print(f"  energy eigenbasis).  A record satisfying (i),(ii),(iii) is found: {good}/{N}")
    L = np.diag([0.3, 0.3, -1.2, 2.0]).astype(complex)
    res = record_search_on(H, [L], 0, seed=0)
    print("  explicit R on the ground eigenspace, eigenvalues =",
          np.round(np.linalg.eigvalsh(res["R"]), 12))
    clause_report(H, [L], res["R"], "positive-control record")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 2 -- HOW BIG IS THE SET OF COMPATIBLE {L_k}?  Sweep dimension.")
    print("  H = 0 (MAXIMAL degeneracy: the whole space is one eigenspace).  If degeneracy")
    print("  alone gave a record this is the most favourable case that exists.\n")
    print(f"  {'d':>3} {'#L':>3}  {'dim A':>7} {'d^2':>7}  {'dim A_herm':>10}  record?")
    for d in (2, 3, 4, 6, 8):
        for nL in (1, 2):
            H0 = np.zeros((d, d), dtype=complex)
            Ls = [rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d)) for _ in range(nL)]
            A = generated_algebra([H0] + Ls, d)
            hb = hermitian_commutant([H0] + Ls, d)
            r = record_search(H0, Ls, seed=d)
            print(f"  {d:3d} {nL:3d}  {len(A):7d} {d*d:7d}  {len(hb):10d}  "
                  f"{'YES' if r['R'] is not None else 'no'}")
    print("\n  A single generic jump operator generates the FULL matrix algebra, so the")
    print("  commutant is the scalars and NO record exists at ANY degeneracy.")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 3 -- THEOREM O1-A, the exact criterion, checked against brute force.")
    print("  Claim: a record non-constant on E_lam exists  <=>  dim(P A P) < m^2 on E_lam.")
    print(f"\n  {'case':40s} {'m':>3} {'dimPAP':>7} {'m^2':>5}  {'predict':>7} {'brute':>7}  ok")

    H1 = np.diag([0, 0, 0, 0, 3.0, 3.0]).astype(complex)
    Lblk = np.zeros((6, 6), dtype=complex)
    Lblk[:2, :2] = rng.normal(size=(2, 2))
    Lblk[2:4, 2:4] = rng.normal(size=(2, 2))
    Lblk[4:, 4:] = rng.normal(size=(2, 2))
    Lgen = rng.normal(size=(6, 6)) + 1j * rng.normal(size=(6, 6))
    Z2 = np.diag([1, 1, -1, -1, 1, -1]).astype(complex)
    Lsym = rng.normal(size=(6, 6)) + 1j * rng.normal(size=(6, 6))
    Lsym = (Lsym + Z2 @ Lsym @ Z2) / 2
    Ldiag = np.diag(rng.normal(size=6)).astype(complex)

    Htrap = np.diag([0.0, 0.0, 1.0, 1.0]).astype(complex)
    T1 = np.zeros((4, 4), dtype=complex); T1[2, 0] = 1; T1[1, 2] = 1
    T2 = np.zeros((4, 4), dtype=complex); T2[3, 1] = 1; T2[0, 3] = 1
    C1 = np.zeros((4, 4), dtype=complex); C1[2, 0] = 1
    C2 = np.zeros((4, 4), dtype=complex); C2[3, 1] = 1

    cases = [("block-diagonal jump (2+2 on E)", H1, [Lblk]),
             ("generic jump", H1, [Lgen]),
             ("Z_2-symmetric jump", H1, [Lsym]),
             ("diagonal jump", H1, [Ldiag]),
             ("EXCURSION pair (the trap)", Htrap, [T1, T2]),
             ("one-leg pair (the control)", Htrap, [C1, C2])]

    allok = True
    for name, Hc, Lc in cases:
        lam, m, dpap, m2 = compression_dim(Hc, Lc, 0)
        predict = "record" if dpap < m2 else "none"
        brute = "record" if record_search_on(Hc, Lc, 0, seed=7)["R"] is not None else "none"
        ok = (predict == brute)
        allok = allok and ok
        print(f"  {name:40s} {m:3d} {dpap:7d} {m2:5d}  {predict:>7} {brute:>7}  "
              f"{'PASS' if ok else 'FAIL'}")
    print(f"\n  THEOREM O1-A agrees with brute-force search on every case: "
          f"{'PASS' if allok else 'FAIL'}")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 4 -- THE TRAP.  Jump operators that VANISH on every eigenspace of H\n"
         "                and still leave no record anywhere in the system.")
    P0 = np.diag([1, 1, 0, 0]).astype(complex)
    P1 = np.diag([0, 0, 1, 1]).astype(complex)
    print("  H  = diag(0,0,1,1)")
    print("  L1 = |e2><e0| + |e1><e2|     L2 = |e3><e1| + |e0><e3|")
    for label, Ls in (("TRAP   ", [T1, T2]), ("CONTROL", [C1, C2])):
        blk = max(max(np.linalg.norm(P0 @ L @ P0), np.linalg.norm(P1 @ L @ P1)) for L in Ls)
        _, m, dpap, m2 = compression_dim(H, Ls, 0)
        hb = hermitian_commutant([H] + Ls, 4)
        r0 = record_search_on(H, Ls, 0, seed=1)
        r1 = record_search_on(H, Ls, 1, seed=1)
        print(f"\n  {label}  max_k max_lam ||P_lam L_k P_lam|| = {blk:.3e}   "
              f"(the noise is INVISIBLE inside every eigenspace)")
        print(f"           dim(P A P) on E_0 = {dpap} of m^2 = {m2}   "
              f"-> {'IRREDUCIBLE' if dpap == m2 else 'reducible'}")
        print(f"           dim of the Hermitian commutant of the whole *-algebra = {len(hb)}")
        print(f"           record on E_0: {'YES' if r0['R'] is not None else 'NO'}    "
              f"record on E_1: {'YES' if r1['R'] is not None else 'NO'}")
        if r0["R"] is not None:
            clause_report(H, Ls, r0["R"], "control record")
    print("\n  CONTROL differs from TRAP only by deleting the RETURN leg of each jump.")
    print("  READING: 'the jump operators act trivially inside the degenerate subspace' is")
    print("  NOT sufficient for clause (ii).  Second-order excursions out of the eigenspace")
    print("  and back enter A and make the compression irreducible.  Any attempt to prove")
    print("  the converse by inspecting P L_k P alone is answered by this counterexample.")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 5 -- HOW LARGE IS THE COMPATIBLE SET?  An exact codimension.")
    print("  For a FIXED record R with eigenvalue multiplicities (p,q), p+q = d, the set of")
    print("  jump operators satisfying [L,R] = 0 is a LINEAR SUBSPACE of C^{dxd} of complex")
    print("  dimension p^2 + q^2, i.e. of complex codimension 2pq.  Measured against theory:\n")
    print(f"  {'d':>3} {'p':>3} {'q':>3}  {'dim{L:[L,R]=0}':>16} {'p^2+q^2':>9}  {'codim':>6}  ok")
    okall = True
    for d, p in ((4, 2), (4, 1), (6, 3), (6, 2), (8, 4), (8, 3)):
        q = d - p
        Rp = np.diag([1.0] * p + [-1.0] * q).astype(complex)
        got = commutant_basis([Rp], d)[1]
        want = p * p + q * q
        okall = okall and (got == want)
        print(f"  {d:3d} {p:3d} {q:3d}  {got:16d} {want:9d}  {2*p*q:6d}  "
              f"{'PASS' if got == want else 'FAIL'}")
    print(f"\n  codimension law verified: {'PASS' if okall else 'FAIL'}")
    print("  The compatible set has measure ZERO in the space of jump operators, for every")
    print("  d >= 2 and every splitting.  Degeneracy of H places no constraint on L at all.")

    show("EXPERIMENT 6 -- THE FAILURE OF CLAUSE (ii) IS FIRST ORDER IN THE PERTURBATION.")
    print("  L(eps) = diag(0.3,0.3,-1.2,2.0) + eps * (generic complex matrix);")
    print("  R = diag(1,-1,1,-1) is an exact record at eps = 0.\n")
    Rg = np.diag([1.0, -1.0, 1.0, -1.0]).astype(complex)
    Lg = np.diag([0.3, 0.3, -1.2, 2.0]).astype(complex)
    V = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
    print(f"  {'eps':>10}  {'||[L(eps),R]||':>16}  {'defect/eps':>12}")
    for eps in (1e-8, 1e-6, 1e-4, 1e-2, 1e-1):
        Lp = Lg + eps * V
        defect = np.linalg.norm(Lp @ Rg - Rg @ Lp)
        print(f"  {eps:10.0e}  {defect:16.6e}  {defect/eps:12.4f}")
    print("\n  Slope 1 across six decades: clause (ii) is violated at FIRST order.")
    print("  Now the exact question -- does ANY record survive a finite perturbation?\n")
    print(f"  {'eps':>8}  {'trials':>6}  {'records found':>14}")
    for eps in (1e-4, 1e-3, 1e-2, 1e-1):
        found = 0
        NT = 200
        for t in range(NT):
            Vt = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
            if record_search(H, [Lg + eps * Vt], seed=t)["R"] is not None:
                found += 1
        print(f"  {eps:8.0e}  {NT:6d}  {found:14d}")
    print("\n  STATED LIMITATION: below eps ~ 1e-5 the surviving commutant directions are")
    print("  distinguished from float noise only by second-order singular values (eps^2 vs")
    print("  1e-16), so this sweep is reported only where it is unambiguous.  The exact")
    print("  statement is the codimension law of Experiment 5, which needs no tolerance.")
    print("\n  READING: the converse cannot be rescued by a 'small enough noise' hypothesis.")
    print("  Clause (ii) as written is exact and its violation is linear.  That is O-5")
    print("  (exactness) seen from inside O-1.")


if __name__ == "__main__":
    main()
