#!/usr/bin/env python3
"""
LANE O-1, GAP (b): FLIPPABILITY -- clause (iv), "some admissible U has U^dag R U = -R".

THE LANE BRIEF CONJECTURED: "on a degenerate subspace of dimension m >= 2, a Hermitian
involution R with both eigenvalues present always admits a unitary conjugating R to -R
within that subspace (any permutation swapping the two eigenspaces).  So flippability may
be FREE, and the whole content of clause (iv) may sit in the word ADMISSIBLE."

THAT IS FALSE AS STATED, and this file says exactly where.  A permutation swaps the two
eigenspaces of R only if they have the SAME DIMENSION.  The correct statement is:

  THEOREM O1-B (flippability is exactly a trace condition).
    Let R = R^dag, R^2 = I on a finite-dimensional Hilbert space of dimension d, with
    eigenvalue multiplicities (p, q), p + q = d.  Then
        there exists a unitary U with U^dag R U = -R   <=>   p = q   <=>   Tr R = 0.
    Proof.  (=>) unitary conjugation preserves the spectrum with multiplicity, and the
    spectrum of -R is that of R with p and q exchanged; also Tr(U^dag R U) = Tr R = -Tr R
    forces Tr R = 0.  (<=) if p = q pick orthonormal bases {u_i} of the (+1)-eigenspace
    and {v_i} of the (-1)-eigenspace and let U be the swap u_i <-> v_i.  Then
    U^dag R U = -R.  QED

  COROLLARY O1-B1 (a parity obstruction).  If dim Hilbert space is ODD, then Tr R is odd
    for every Hermitian involution R, so Tr R != 0 and NO record is writable.  Ever.
    Clause (iv) fails for parity reasons alone, no matter what "admissible" means.

  COROLLARY O1-B2 (energy-conserving writers).  If the writer is required to commute with
    H -- i.e. writing must not change the energy -- then U preserves every eigenspace and
    the condition sharpens to  tr(R|_{E_lam}) = 0 for EVERY eigenvalue lam of H.
    A record can be globally balanced and still not writable without an energy transition.

  THEOREM O1-B3 (the collision with O-4).  Let A = alg{I, H, L_k, L_k^dag}.  Clause (ii)
    puts R in A'.  If "admissible" is read as O-4's first branch -- "generated by the
    theory's own operators" -- then U is in A, so U^dag R U = R.U^dag U = R, and clause
    (iv) is UNSATISFIABLE for every R that satisfies clause (ii).  Under that reading the
    definition is inconsistent and no record exists in any system whatsoever.
    THIS IS EXACTLY P-2 SHARPENED FROM "the writer is built from neither H nor {L_k}" TO
    "the writer is outside the algebra they generate, so O-4 must take its SECOND branch."

  SO O-1 AND O-4 ARE ENTANGLED -- but not in the direction conjectured.  Flippability is
  not free-and-therefore-vacuous; it carries a genuine trace/parity obstruction that
  survives the MOST PERMISSIVE reading of "admissible", and it becomes IMPOSSIBLE under
  one of the two readings O-4 proposes.
"""

import numpy as np
from itertools import combinations
from o1_core import (hermitian_commutant, generated_algebra, eigenspaces, record_search,
                     record_search_on, clause_report, selfchecks)

np.set_printoptions(precision=6, suppress=True, linewidth=160)


def show(title):
    print("\n" + "=" * 96)
    print(title)
    print("=" * 96)


def build_flipper(R, tol=1e-9):
    """If Tr R = 0, return U with U^dag R U = -R; else None."""
    d = R.shape[0]
    w, v = np.linalg.eigh(R)
    plus = v[:, w > 0]
    minus = v[:, w < 0]
    if plus.shape[1] != minus.shape[1]:
        return None
    U = plus @ minus.conj().T + minus @ plus.conj().T
    return U


def commutative_minimal_projections(hb, tol=1e-7):
    """Minimal projections of a COMMUTATIVE Hermitian commutant basis hb.  Returns ranks."""
    d = hb[0].shape[0]
    rng = np.random.default_rng(0)
    X = sum(c * B for c, B in zip(rng.normal(size=len(hb)), hb))
    X = (X + X.conj().T) / 2
    w, v = np.linalg.eigh(X)
    ranks, cur = [], 1
    for i in range(1, d):
        if abs(w[i] - w[i - 1]) < 1e-7:
            cur += 1
        else:
            ranks.append(cur)
            cur = 1
    ranks.append(cur)
    return ranks


def block_L(sizes, rng):
    """Block-diagonal jump operator with the given block sizes, generic within each block."""
    d = sum(sizes)
    L = np.zeros((d, d), dtype=complex)
    o = 0
    for s in sizes:
        B = rng.normal(size=(s, s)) + 1j * rng.normal(size=(s, s))
        # shift the spectrum so different blocks carry inequivalent irreps
        B = B + (o + 1) * 3.0 * np.eye(s)
        L[o:o + s, o:o + s] = B
        o += s
    return L


def subset_sums(sizes):
    out = set()
    for k in range(len(sizes) + 1):
        for c in combinations(range(len(sizes)), k):
            out.add(sum(sizes[i] for i in c))
    return out


def main():
    print("O-1 GAP (b) -- FLIPPABILITY (clause iv)")
    print("machinery self-checks first:\n")
    if not selfchecks():
        raise SystemExit("self-checks failed -- no headline number may be read")
    rng = np.random.default_rng(4242)

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 1 -- THEOREM O1-B.  Flippability holds exactly when Tr R = 0.")
    print(f"  {'d':>3} {'p':>3} {'q':>3} {'Tr R':>6}  {'flipper built?':>15}  "
          f"{'||U^dag R U + R||':>18}  {'best over 4000 random U':>24}")
    allok = True
    for d, p in ((2, 1), (3, 1), (3, 2), (4, 2), (4, 1), (5, 2), (6, 3), (6, 2), (8, 4), (8, 3)):
        q = d - p
        R = np.diag([1.0] * p + [-1.0] * q).astype(complex)
        # scramble into a generic basis so nothing depends on the diagonal form
        Q, _ = np.linalg.qr(rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d)))
        R = Q @ R @ Q.conj().T
        U = build_flipper(R)
        res = np.linalg.norm(U.conj().T @ R @ U + R) if U is not None else float('nan')
        best = np.inf
        for _ in range(4000):
            M = rng.normal(size=(d, d)) + 1j * rng.normal(size=(d, d))
            V, _ = np.linalg.qr(M)
            best = min(best, np.linalg.norm(V.conj().T @ R @ V + R))
        want = (p == q)
        got = (U is not None) and res < 1e-9
        ok = (want == got) and (want or best > 1e-6)
        allok = allok and ok
        print(f"  {d:3d} {p:3d} {q:3d} {p-q:+6d}  {str(U is not None):>15}  "
              f"{res:18.3e}  {best:24.6f}   {'PASS' if ok else 'FAIL'}")
    print(f"\n  THEOREM O1-B: {'ALL PASS' if allok else 'FAILED'}")
    print("  The random-unitary column is the POSITIVE CONTROL for the nulls: where a")
    print("  flipper exists the search finds one, where none exists the best of 4000 draws")
    print("  stays O(1).  The brief's claim 'flippability is free' is false whenever the")
    print("  two eigenvalue multiplicities differ.")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 2 -- COUNTEREXAMPLE F1.  A system with an exactly degenerate H, a\n"
         "                record satisfying (i),(ii),(iii), and NO writer of any kind.")
    d = 6
    H = np.zeros((d, d), dtype=complex)          # maximal degeneracy
    L = block_L([2, 4], rng)                      # one jump operator, blocks 2 (+) 4
    hb = hermitian_commutant([H, L], d)
    A = generated_algebra([H, L], d)
    print("  H = 0 on C^6 (a single 6-fold degenerate eigenvalue -- degeneracy is maximal)")
    print("  L = L_2 (+) L_4, one jump operator, generic and inequivalent within each block")
    print(f"  dim A = {len(A)}  (expected 2^2 + 4^2 = {4 + 16})")
    print(f"  dim of the Hermitian commutant A' = {len(hb)}  (expected 2)")
    ranks = commutative_minimal_projections(hb)
    print(f"  minimal projections of A' have ranks {ranks}  (expected [2, 4])")
    print("\n  Every Hermitian involution in A' is  a.P_2 + b.P_4  with a,b in {+1,-1}:")
    print(f"  {'R':22s} {'Tr R':>6}  {'(iii) non-constant?':>20}  {'(iv) writer exists?':>20}")
    found_any = False
    for a in (1, -1):
        for b in (1, -1):
            P2 = None
            # rebuild the two minimal projections explicitly
            X = sum(c * B for c, B in zip(np.random.default_rng(0).normal(size=len(hb)), hb))
            X = (X + X.conj().T) / 2
            w, v = np.linalg.eigh(X)
            g1 = [i for i in range(d) if abs(w[i] - w[0]) < 1e-7]
            g2 = [i for i in range(d) if i not in g1]
            Pa = v[:, g1] @ v[:, g1].conj().T
            Pb = v[:, g2] @ v[:, g2].conj().T
            R = a * Pa + b * Pb
            tr = float(np.real(np.trace(R)))
            nonconst = np.linalg.norm(R - np.trace(R) / d * np.eye(d)) > 1e-7
            flip = build_flipper(R) is not None
            found_any = found_any or (nonconst and flip)
            label = f"{a:+d}.P_{len(g1)} {b:+d}.P_{len(g2)}"
            print(f"  {label:22s} {tr:+6.1f}  {str(nonconst):>20}  {str(flip):>20}")
    print(f"\n  A record satisfying (i),(ii),(iii) AND (iv) exists: {found_any}")
    R = record_search(H, [L], seed=1)["R"]
    clause_report(H, [L], R, "the unique record (up to sign)")
    print("  Its trace is +/-2, so no unitary on C^6 -- admissible or not, local or not,")
    print("  physical or not -- conjugates it to minus itself.  CLAUSE (iv) FAILS while")
    print("  (i),(ii),(iii) all hold.  THE CONVERSE IS FALSE AT CLAUSE (iv) TOO.")

    print("\n  POSITIVE CONTROL -- identical construction with blocks 3 (+) 3:")
    L3 = block_L([3, 3], rng)
    hb3 = hermitian_commutant([H, L3], d)
    R3 = record_search(H, [L3], seed=1)["R"]
    print(f"  dim A' = {len(hb3)}, minimal projection ranks {commutative_minimal_projections(hb3)}")
    clause_report(H, [L3], R3, "record with balanced blocks")
    U3 = build_flipper(R3)
    print(f"  writer built explicitly: ||U^dag R U + R|| = "
          f"{np.linalg.norm(U3.conj().T @ R3 @ U3 + R3):.3e}   -> clause (iv) PASSES")
    print("  The two systems differ ONLY in how the 6 dimensions are split by the noise.")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 3 -- HOW OFTEN DOES (iv) FAIL ONCE (i),(ii),(iii) HOLD?")
    print("  For a jump operator with inequivalent blocks of sizes s_1..s_k, A' is")
    print("  commutative with minimal projections of those ranks, and a writable record")
    print("  exists iff some SUBSET of the sizes sums to d/2.  Counted over all block")
    print("  structures (unordered partitions of d into >= 2 parts):\n")
    print(f"  {'d':>3}  {'partitions':>11}  {'writable':>9}  {'NOT writable':>13}  {'fail rate':>10}")

    def partitions(n, maxp=None):
        if maxp is None:
            maxp = n
        if n == 0:
            yield []
            return
        for k in range(min(n, maxp), 0, -1):
            for rest in partitions(n - k, k):
                yield [k] + rest

    for dd in (4, 6, 8, 10, 12, 14):
        tot = w_ok = 0
        for part in partitions(dd):
            if len(part) < 2:
                continue
            tot += 1
            if dd / 2 in subset_sums(part):
                w_ok += 1
        print(f"  {dd:3d}  {tot:11d}  {w_ok:9d}  {tot-w_ok:13d}  {(tot-w_ok)/tot:10.3f}")

    print("\n  SPOT-CHECK of the counting against explicit matrices (d = 6):")
    print(f"  {'sizes':12s} {'dim A_herm':>10} {'ranks':>12} {'record?':>8} {'writable?':>10}  ok")
    ok3 = True
    for sizes in ([2, 4], [3, 3], [1, 5], [2, 2, 2], [1, 2, 3], [1, 1, 4]):
        Lb = block_L(sizes, rng)
        hbb = hermitian_commutant([H, Lb], d)
        rr = record_search(H, [Lb], seed=2)["R"]
        writable = False
        if rr is not None:
            # search all involutions in the commutative commutant
            X = sum(c * B for c, B in zip(rng.normal(size=len(hbb)), hbb))
            X = (X + X.conj().T) / 2
            wv, vv = np.linalg.eigh(X)
            groups, cur = [], [0]
            for i in range(1, d):
                if abs(wv[i] - wv[i - 1]) < 1e-7:
                    cur.append(i)
                else:
                    groups.append(cur); cur = [i]
            groups.append(cur)
            for k in range(1, len(groups)):
                for c in combinations(range(len(groups)), k):
                    idx = [i for j in c for i in groups[j]]
                    Qp = vv[:, idx] @ vv[:, idx].conj().T
                    Rc = np.eye(d) - 2 * Qp
                    if abs(np.trace(Rc)) < 1e-8 and np.linalg.norm(Rc - np.trace(Rc)/d*np.eye(d)) > 1e-7:
                        writable = True
            pred = (d / 2 in subset_sums(sizes))
            ok = (writable == pred)
        else:
            pred, ok = False, True
        ok3 = ok3 and ok
        print(f"  {str(sizes):12s} {len(hbb):10d} {str(commutative_minimal_projections(hbb)):>12} "
              f"{str(rr is not None):>8} {str(writable):>10}  {'PASS' if ok else 'FAIL'}")
    print(f"\n  counting agrees with explicit construction: {'PASS' if ok3 else 'FAIL'}")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 4 -- COROLLARY O1-B2.  Energy-conserving writers need a stronger\n"
         "                condition: balance on EVERY eigenspace, not just globally.")
    Hs = np.diag([0.0, 0.0, 0.0, 1.0]).astype(complex)
    Rs = np.diag([1.0, -1.0, -1.0, 1.0]).astype(complex)
    print("  H = diag(0,0,0,1),  R = diag(1,-1,-1,1)")
    print(f"  Tr R = {np.real(np.trace(Rs)):+.1f}  -> SOME unitary flips it:")
    Us = build_flipper(Rs)
    print(f"     ||U^dag R U + R||   = {np.linalg.norm(Us.conj().T @ Rs @ Us + Rs):.3e}")
    print(f"     ||[U,H]||           = {np.linalg.norm(Us @ Hs - Hs @ Us):.3e}   <- it MOVES ENERGY")
    for lam, cols in eigenspaces(Hs):
        tr = float(np.real(np.trace(cols.conj().T @ Rs @ cols)))
        print(f"     tr(R restricted to eigenvalue {lam:+.1f}) = {tr:+.1f}")
    print("  Because tr(R|_{E_0}) = -1 != 0, NO unitary commuting with H flips R.  Verified:")
    best = np.inf
    for _ in range(20000):
        # random unitary block-diagonal w.r.t. the eigenspaces of H  ==  [U,H]=0
        M = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
        V3, _ = np.linalg.qr(M)
        ph = np.exp(2j * np.pi * rng.random())
        V = np.zeros((4, 4), dtype=complex)
        V[:3, :3] = V3
        V[3, 3] = ph
        best = min(best, np.linalg.norm(V.conj().T @ Rs @ V + Rs))
    print(f"     best over 20000 energy-conserving unitaries: {best:.6f}   (a true zero would be ~1e-15)")
    Rb = np.diag([1.0, -1.0, 1.0, -1.0]).astype(complex)
    Hb = np.diag([0.0, 0.0, 1.0, 1.0]).astype(complex)
    Ub = build_flipper(Rb)
    print("\n  POSITIVE CONTROL -- H = diag(0,0,1,1), R = diag(1,-1,1,-1), balanced on EACH")
    print(f"  eigenspace:  ||U^dag R U + R|| = {np.linalg.norm(Ub.conj().T @ Rb @ Ub + Rb):.3e}, "
          f"||[U,H]|| = {np.linalg.norm(Ub @ Hb - Hb @ Ub):.3e}")

    # ------------------------------------------------------------------------------
    show("EXPERIMENT 5 -- THEOREM O1-B3.  The collision with O-4: if 'admissible' means\n"
         "                'generated by the theory's own operators', clause (iv) is\n"
         "                UNSATISFIABLE for every R that satisfies clause (ii).")
    Lc = block_L([3, 3], rng)
    Rc = record_search(H, [Lc], seed=1)["R"]
    Aalg = generated_algebra([H, Lc], 6)
    print("  System: H = 0 on C^6, L = L_3 (+) L_3.  R is the record found above, and a")
    print("  writer DOES exist among general unitaries.  Now restrict U to the unitary")
    print("  group of A = alg{I, H, L, L^dag}:  U = exp(i X), X Hermitian, X in A.\n")
    print(f"  {'draw':>5}  {'||U^dag R U - R||':>18}  {'||U^dag R U + R||':>18}")
    worst_same, best_flip = 0.0, np.inf
    for t in range(2000):
        c = rng.normal(size=len(Aalg))
        X = sum(ci * Bi for ci, Bi in zip(c, Aalg))
        X = (X + X.conj().T) / 2
        wv, vv = np.linalg.eigh(X)
        U = vv @ np.diag(np.exp(1j * wv * rng.normal() * 3)) @ vv.conj().T
        same = np.linalg.norm(U.conj().T @ Rc @ U - Rc)
        flip = np.linalg.norm(U.conj().T @ Rc @ U + Rc)
        worst_same = max(worst_same, same)
        best_flip = min(best_flip, flip)
        if t < 3:
            print(f"  {t:5d}  {same:18.3e}  {flip:18.3e}")
    print(f"  ...")
    print(f"  worst ||U^dag R U - R|| over 2000 draws from A : {worst_same:.3e}   (must be 0)")
    print(f"  best  ||U^dag R U + R|| over 2000 draws from A : {best_flip:.6f}    (must be > 0)")
    print("\n  POSITIVE CONTROL -- the same R with an unrestricted unitary:")
    Uc = build_flipper(Rc)
    print(f"  ||U^dag R U + R|| = {np.linalg.norm(Uc.conj().T @ Rc @ Uc + Rc):.3e}  and")
    print(f"  U lies OUTSIDE A: distance from U to A = "
          f"{np.linalg.norm(Uc - sum(np.trace(B.conj().T @ Uc) * B for B in Aalg)):.6f}")
    print("\n  READING: O-4 must NOT be resolved as 'generated by the theory's own")
    print("  operators'.  That reading makes clause (iv) contradict clause (ii) in EVERY")
    print("  system, which would make the record definition empty.  O-4's second branch")
    print("  ('a physical channel') is the only survivor, and it must be a channel built")
    print("  from operators OUTSIDE alg{I,H,L_k,L_k^dag}.  That is P-2, sharpened.")


if __name__ == "__main__":
    main()
