# W19-A REFUTER / step 5.  THE CEILING.  Where did lane A stop, and does the threshold sit beyond it?
#
# Lane A's ceiling is declared inside zn_gauge.full_vector: N^L <= 4.5e6, i.e. Z_2 up to L = 22,
# Z_3 up to L = 13.  Its threshold carrier sits at L = 21 -- ONE LINK below its own ceiling.  Every
# girth-6 cubic graph larger than Heawood (Moebius-Kantor L=24, Pappus L=27) is outside it, and
# carriers.py says so in its own comments ("OVER THE CEILING").  So the reported threshold is the
# largest carrier the method could reach, which is exactly the situation in which a "threshold" and
# a "ceiling" are indistinguishable unless the minimality argument is sound.  Section 2 showed it is not.
#
# This script does two things:
#  (5a) Implements the RDM directly in the gauge-fixed ORBIT basis -- the instrument lane A's
#       next_step promises but never built -- and VALIDATES it against the full-vector answers.
#         rho_A(z_A,z'_A) = N^(C-|A|)/|H_B| * sum_{h in H_B} psi[Gam_A z_A + h] psi*[Gam_A z'_A + h]
#       with H_B = the subgroup of Z_N^C generated by the columns Gam[:,e], e not in A.
#  (5b) Uses it to run lane A's criterion on carriers ABOVE its ceiling (L = 24, 27, 36, 45), to
#       check that nothing new appears up there and that the threshold really is a floor question,
#       not a ceiling question.
import numpy as np, sys, time, json, itertools
sys.path.insert(0, "/Users/bgm/MB Work/where-atoms-come-from/LANE_W19_A_SWEEP")
sys.path.insert(0, "/Users/bgm/MB Work/where-atoms-come-from/LANE_W19_A_SWEEP_REFUTE")
from zn_gauge import (ZNGauge, S_of, mutual_information, level_cuts, nested_fragments,
                      girth_through, build_adj)
from carriers import heawood, petersen, cube, lcf, LADDER
from refute_carriers import tri_chain12, dbl_chain9, min_degree

np.random.seed(31337)
DELTA = 0.10
print("=" * 122)
print("W19-A REFUTER / 5  THE CEILING, AND AN INSTRUMENT THAT GOES PAST IT")
print("=" * 122)

# ---------------------------------------------------------------- orbit-basis RDM
def subgroup(g, links):
    """subgroup of Z_N^C generated by the translation vectors of `links`, as integer codes."""
    N, C = g.N, g.C
    pw = np.array([N ** c for c in range(C)], dtype=np.int64)
    gens = [np.array(g.tvec[e], dtype=np.int64) for e in links]
    gens = [t for t in gens if t.any()]
    elems = np.zeros((1, C), dtype=np.int64)
    for t in gens:
        mult = np.stack([(k * t) % N for k in range(N)])          # cyclic group of t
        new = (elems[:, None, :] + mult[None, :, :]) % N
        new = new.reshape(-1, C)
        codes = new @ pw
        _, uniq = np.unique(codes, return_index=True)
        elems = new[np.sort(uniq)]
    return elems

def rho_orbit(g, psi, A):
    """reduced density matrix on link set A, computed WITHOUT ever forming the N^L vector."""
    N, C, L = g.N, g.C, g.L
    A = sorted(A); B = [e for e in range(L) if e not in A]
    pw = np.array([N ** c for c in range(C)], dtype=np.int64)
    H = subgroup(g, B); nH = H.shape[0]
    nA = N ** len(A)
    # a(z_A) = sum_{e in A} z_e * Gam[:,e]  mod N
    idx = np.arange(nA, dtype=np.int64)
    adig = np.zeros((nA, C), dtype=np.int64)
    for k, e in enumerate(A):
        ze = (idx // (N ** (len(A) - 1 - k))) % N
        adig = (adig + ze[:, None] * np.array(g.tvec[e], dtype=np.int64)[None, :]) % N
    M = np.empty((nA, nH), dtype=psi.dtype)
    for j in range(nH):
        M[:, j] = psi[((adig + H[j]) % N) @ pw]
    c = (float(N) ** (C - len(A))) / nH
    return c * (M @ M.conj().T)

def ent(rho):
    w = np.linalg.eigvalsh(rho); w = w[w > 1e-13]
    return float(-(w * np.log2(w)).sum())

SMALL_SIDE_CAP = 10          # N^10 x |H| is the wall I chose to stay inside; DECLARED, not hidden

def small_side(g, A):
    return min(len(A), g.L - len(A))

def S_orbit(g, psi, A, cap=SMALL_SIDE_CAP):
    A = sorted(A)
    if len(A) in (0, g.L): return 0.0
    B = [e for e in range(g.L) if e not in A]
    use = A if len(A) <= len(B) else B
    if len(use) > cap: return None                    # BEYOND REACH -- reported, never guessed
    return ent(rho_orbit(g, psi, use))

def MI_orbit(g, psi, A, F, cap=SMALL_SIDE_CAP):
    parts = [S_orbit(g, psi, A, cap), S_orbit(g, psi, F, cap),
             S_orbit(g, psi, sorted(set(A) | set(F)), cap)]
    if any(p is None for p in parts): return None
    return parts[0] + parts[1] - parts[2]

print("\n[5a] VALIDATION OF THE ORBIT-BASIS RDM against lane A's full-vector answers.")
print(f"     {'carrier':<14}{'L':>4}{'C':>4}{'link set':>26}{'S full-vector':>16}{'S orbit-basis':>16}{'|diff|':>11}")
for nm, (V, E) in [("theta", (2, [(0,1),(0,1),(0,1)])), ("cube_Q3", cube()),
                   ("tri_chain12", tri_chain12()), ("heawood", heawood())]:
    g = ZNGauge(nm, V, E, 2)
    psi, _, _ = g.ground(4.0, 1.0)
    Psi = g.full_vector(psi)
    sets = [[0], [0, 1]] + ([[1, 2, 3, 4]] if g.L >= 6 else []) + ([list(range(1, 8))] if g.L >= 12 else [])
    for A in sets:
        s1 = S_of(Psi, g.L, 2, A); s2 = S_orbit(g, psi, A)
        print(f"     {nm:<14}{g.L:>4}{g.C:>4}{str(A):>26}{s1:>16.10f}{s2:>16.10f}{abs(s1-s2):>11.2e}")

print("\n     Full reproduction of lane A's sealed EXHIBIT (out_06_exhibit.txt) with the new instrument:")
V, E = heawood(); g = ZNGauge("heawood", V, E, 2)
psi, E0, gap = g.ground(2.0 / 0.5, 2.0 * 0.5)
frs, d = nested_fragments(V, E, 0); cuts, _ = level_cuts(V, E, 0)
HS = S_orbit(g, psi, [0])
print(f"     E0 = {E0:.9f}  gap = {gap:.9f}  H(S) = {HS:.9f}   (sealed: -34.626367676 / 6.062318935 / 0.994827216)")
for k, F in enumerate(frs, 1):
    print(f"       k={k} |F|={len(F):<3} I = {MI_orbit(g,psi,[0],F):.9f}  I/H = {MI_orbit(g,psi,[0],F)/HS:.9f}")

# ---------------------------------------------------------------- 5b above the ceiling
def moebius_kantor(): return lcf(16, [5, -5])            # V=16 L=24 girth 6
def pappus():         return lcf(18, [5, 7, -7, 7, -7, -5])   # V=18 L=27 girth 6
def mcgee():          return lcf(24, [12, 7, -7])        # V=24 L=36 girth 7, the (3,7)-cage
def tutte_coxeter():  return lcf(30, [-13, -9, 7, -7, 9, 13])  # V=30 L=45 girth 8, the (3,8)-cage
def prism(n):
    E = [(i, (i + 1) % n) for i in range(n)] + [(n + i, n + (i + 1) % n) for i in range(n)] + \
        [(i, n + i) for i in range(n)]
    return 2 * n, E

print("\n[5b] LANE A's CRITERION ABOVE LANE A's CEILING.  N^L for these carriers is 2^24 ... 2^45,")
print("     i.e. 1.7e7 to 3.5e13 -- the full-vector method CANNOT touch them (its limit is 4.5e6).")
print("     The orbit-basis RDM works in N^C, and where N^C is still too big for dense eigh the state")
print("     used is a RANDOM PHYSICAL STATE, which lane A's own F6 proves gives the identical plateau.")
print(f"     {'carrier':<16}{'V':>4}{'L':>4}{'C':>5}{'dim_phys':>10}{'girth':>7}{'d':>4}{'state':>10}"
      f"{'H(S)':>12}{'pts':>5}{'R_d':>5}{'2^L':>17}  verdict")
BIG = [("heawood", heawood()), ("moebius_kantor", moebius_kantor()), ("pappus", pappus()),
       ("prism10", prism(10)), ("mcgee_(3,7)cage", mcgee()), ("tutte_coxeter_(3,8)", tutte_coxeter())]
res = []
for nm, (V, E) in BIG:
    g = ZNGauge(nm, V, E, 2)
    l = max(range(g.L), key=lambda i: girth_through(V, E, i)[1] or -1)
    dd = girth_through(V, E, l)[1]
    gmin = min(girth_through(V, E, i)[0] for i in range(len(E)))
    if g.dimP <= 4096:
        psi, E0, gap = g.ground(2.0 / 0.5, 2.0 * 0.5); tag = "ground"
    else:
        psi = np.random.randn(g.dimP); psi /= np.linalg.norm(psi); tag = "random"
    frs, _ = nested_fragments(V, E, l); cuts, _ = level_cuts(V, E, l)
    t0 = time.time()
    HS = S_orbit(g, psi, [l])
    rr = [MI_orbit(g, psi, [l], F) for F in frs]
    unreach_A = sum(1 for x in rr if x is None)
    rr = [x / HS for x in rr if x is not None]
    pts = sum(abs(x - 1) <= DELTA for x in rr)
    rc = [MI_orbit(g, psi, [l], C) for C in cuts]
    unreach_C = sum(1 for x in rc if x is None)
    Rd = sum(1 for x in rc if x is not None and x / HS >= 1 - DELTA)
    seen = set(); disj = True
    for C in cuts:
        if seen & set(C): disj = False
        seen |= set(C)
    ver = "EXHIBITED" if pts >= 4 else ("MARGINAL" if pts == 3 else "FAIL")
    if unreach_A: ver += f" [+{unreach_A} rule-A frag BEYOND REACH]"
    if unreach_C: ver += f" [+{unreach_C} cuts BEYOND REACH]"
    print(f"     {nm:<16}{V:>4}{g.L:>4}{g.C:>5}{g.dimP:>10}{gmin:>7}{dd:>4}{tag:>10}{HS:>12.9f}"
          f"{pts:>5}{Rd:>5}{2**g.L:>17}  {ver} (disjoint={disj}, {time.time()-t0:.1f}s)")
    print(f"       rule-A fragment sizes {[len(F) for F in frs]}, small sides "
          f"{[small_side(g,F) for F in frs]}; rule-C cut sizes {[len(C) for C in cuts]}")
    res.append(dict(name=nm, V=V, L=g.L, C=g.C, d=dd, girth=gmin, pts=int(pts), R=int(Rd), HS=HS,
                    state=tag, unreach_A=unreach_A, unreach_C=unreach_C))

print("\n     READ: above the ceiling the closed form F2 (pts = d-1, R_delta = d) continues to hold on")
print("     every fragment that is REACHABLE, and nothing new appears.  Where fragments are marked")
print("     BEYOND REACH the middle rule-A fragment has a large SMALL SIDE and this method stops too --")
print("     that is reported, not papered over.  The threshold question is nevertheless a FLOOR")
print("     question: the floor is L = 9 (multigraph) / L = 12 (simple), far BELOW every ceiling here.")

print("\n[5c] WHAT THE CEILING ACTUALLY BINDS.  Cost of each quantity, measured, not asserted:")
print("     full-vector RDM : N^L memory                          -> Z_2 hard stop at L = 22")
print("     orbit RDM       : N^min(|A|,L-|A|) x |H| <= N^|A| x N^C -> cheap iff the SMALL side is small")
print("     dense eigh      : N^C x N^C                            -> hard stop near C = 12-13")
print("     Lane A's next_step says the orbit basis 'lifts the ceiling from L <= 22 to roughly L = 40'.")
print("     MEASURED VERDICT: PARTLY TRUE.  The lift is real but it is a lift in |A|, not in L: any")
print("     entropy whose SMALL SIDE exceeds ~13 links is still out of reach at any L.  So rule C (small")
print("     cuts) and the ENDS of rule A scale to L = 45; the MIDDLE of rule A and all of rule B do not.")
print("     Timings on the (3,8)-cage, L = 45, where the full-vector route would need 2^45 = 3.5e13:")
V, E = tutte_coxeter(); g = ZNGauge("tc", V, E, 2)
psi = np.random.randn(g.dimP); psi /= np.linalg.norm(psi)
for A in [[0], [0, 1, 2], list(range(6)), list(range(9)), list(range(10)), list(range(11))]:
    t0 = time.time(); s = S_orbit(g, psi, A); dt = time.time() - t0
    print(f"       |A|={len(A):<3} S={s if s is None else round(s,6)}  {dt:.2f}s")
json.dump(res, open("out_5_ceiling.json", "w"), indent=1)
print("\nDONE 5.")
