"""
r1 -- IS THE BOUNDARY-ALGEBRA ENUMERATION COMPLETE, OR MERELY CONVENIENT?

The target lane (finding B-7, and its next_step (i)) asserts that the boundary-algebra choice is a
FIVE-fold list {C1_EXT, C2_ELEC, C3_FULL, C5_MAG, C6_DRESS} which, after its own collapse theorem
B-9, becomes "a THREE-fold choice, not five-fold".  This file checks that arithmetic three ways.

  PART 1  TYPE AUDIT.  A region algebra for R must at minimum be (i) a *-subalgebra, (ii) SUPPORTED
          IN R, and -- if it is to be called gauge-invariant -- (iii) inside the commutant of the
          Gauss law.  Two of the five fail (ii) or (iii).  Printed per choice, per carrier.
  PART 2  CENTRE AUDIT.  The published choices are NAMED BY THEIR CENTRES (electric centre /
          magnetic centre).  I compute the actual centre of each generator list.
  PART 3  COMPLETE ENUMERATION.  Every Pauli *-subalgebra on the region, counted exactly against
          the Galois numbers, with the five named choices located inside the lattice.
  PART 4  THE ENUMERATION USED AS A TEST.  All gauge-invariant choices on the b3 PART B cut, and
          all of them on the b3 PART C cut, evaluated on the SAME state through the SAME code.

ISOLATION LEDGER.  Held fixed: carrier, state, system region, fragment list, delta, and the
entropy function (lib_b.algebra_entropy, imported unmodified from the target lane).
Moved: THE ALGEBRA, and nothing else.  Every algebra is printed as its generator list.
"""
import itertools
import numpy as np
from rlib import *

np.set_printoptions(precision=6, suppress=True)
DELTA = 0.1

hr("r1  THE BOUNDARY-ALGEBRA ENUMERATION")
print("target: /Users/bgm/MB Work/where-atoms-come-from/LANE_W19_B_CRITERION/b3_gauge_choices.py")
print("all entropies below are lib_b.algebra_entropy, imported unmodified from that directory.")

# =====================================================================================
hr("PART 1  --  TYPE AUDIT OF THE FIVE NAMED CHOICES")
print("""
  A 'region algebra for R' must be a *-subalgebra of B(H) whose elements are SUPPORTED IN R.
  A 'gauge-invariant region algebra' must in addition lie in the commutant of every Gauss operator.
  Below, for the exact regions used in b3 PART B (theta_8, S = [0], fragments = [1]..[6],
  dressing reference link 7), I print the SUPPORT of each generator list and its invariance.""")
car = theta(8); L = 8
import lib_b as LB
rows = []
for R, tag in [([0], "system S"), ([1], "fragment F_1"), ([2], "fragment F_2")]:
    for ch, g in [("C1_EXT", gens_EXT(car, R)), ("C5_MAG", gens_MAG(car, R)),
                  ("C3_FULL", gens_FULL(car, R)), ("C2_ELEC", gens_ELEC(car, R)),
                  ("C6_DRESS", gens_DRESS(car, R, 7))]:
        sup = support_links(g, L)
        rows.append((tag, R, ch, sup, sup == sorted(R), is_gauge_invariant(car, g),
                     [sp_str(a, L) for a in g]))
print(f"  {'region':<20}{'choice':<10}{'support':<14}{'in R?':<7}{'gauge-inv?':<12}generators")
print("-" * 104)
for tag, R, ch, sup, inR, gi, gs in rows:
    print(f"  {tag+' '+str(R):<20}{ch:<10}{str(sup):<14}{str(inR):<7}{str(gi):<12}{gs}")
print("""
  READING.  Of the five, exactly TWO are gauge-invariant region algebras (C2_ELEC, C3_FULL) and
  on a single-link region those two are THE SAME ALGEBRA.  C1_EXT and C5_MAG are not gauge
  invariant (they contain Z_l, which anticommutes with G = prod_l X_l).  C6_DRESS is not supported
  in R at all -- its second generator carries link 7.""")

print("\n  CONSEQUENCE FOR THE DISJOINT-FRAGMENT PREMISE OF R_delta.  Under C6_DRESS the six")
print("  'disjoint' fragments of b3 PART B all contain the reference link 7:")
sups = {}
for e in range(1, 7):
    sups[e] = support_links(gens_DRESS(car, [e], 7), L)
print("     " + "   ".join(f"F_{e}->{sups[e]}" for e in range(1, 7)))
common = set.intersection(*[set(v) for v in sups.values()])
print(f"     pairwise-common links across all six fragment algebras = {sorted(common)}")
print(f"     and the SYSTEM algebra's support is {support_links(gens_DRESS(car,[0],7), L)},")
print("     which also contains link 7.  R_delta counts DISJOINT fragments; under C6 they are not")
print("     disjoint and do not even exclude the system.  The C6 row of b3 PART B is not weightless")
print("     (as the target marks it) -- it is ILL-TYPED for a redundancy criterion.")

# =====================================================================================
hr("PART 2  --  CENTRE AUDIT.  THE CHOICES ARE NAMED BY THEIR CENTRES.  WHAT ARE THEY?")
print("""
  In the algebraic classification, region algebras are labelled by their CENTRE: the 'electric
  centre' choice has a centre generated by electric-field operators, the 'magnetic centre' choice
  by magnetic fluxes (Wilson loops).  I compute the centre of each generator list directly.""")
print(f"  {'carrier':<10}{'region':<10}{'choice':<10}{'centre kind':<18}{'dim':<5}centre generators")
print("-" * 104)
for car, R in [(theta(8), [0]), (theta(8), [1, 2]), (fan(4), [1, 2]), (fan(4), [3, 4]),
               (wheel(4), [0, 4]), (theta(10), [0, 1])]:
    Lc = car["L"]
    for ch, g in [("C1_EXT", gens_EXT(car, R)), ("C5_MAG", gens_MAG(car, R)),
                  ("C3_FULL", gens_FULL(car, R)), ("C2_ELEC", gens_ELEC(car, R))]:
        kind, dim = center_kind(car, g)
        pairs, cen = algebra_structure(g)
        print(f"  {car['name']:<10}{str(R):<10}{ch:<10}{kind:<18}{dim:<5}"
              f"{[sp_str(a, Lc) for a in cen]}")
print("""
  READING.  The choice the target lane calls 'C5 MAG  magnetic centre (Casini-Huerta-Rosabal)' has,
  wherever its centre is non-trivial at all, an ELECTRIC centre -- generated by the interior Gauss
  operators, which are products of X.  PROOF: X_l is in A for every l in R, so a central element
  P_{x,z} must have z = 0; and P_{x,0} must commute with every Z^z in A, i.e. x must be orthogonal
  to the nullspace of the interior-Gauss rows, i.e. x lies in the span of the interior Gauss
  strings themselves.  Hence centre(C5) = <interior Gauss operators>, pure X, ELECTRIC.
  The list therefore contains NO magnetic-centre algebra, and the name is a mislabel of the
  mathematics, not only of the attribution the lane self-flagged.""")

# =====================================================================================
hr("PART 3  --  COMPLETE ENUMERATION OF PAULI *-SUBALGEBRAS ON A REGION")
print("""
  Pauli *-subalgebras supported on n links are in bijection with GF(2)-subspaces of F_2^{2n}
  (the Pauli group modulo phases).  Their number is the Galois number G_{2n}.  I enumerate them
  exhaustively and check the count against G_{2n}, so this is a COMPLETE enumeration and not a
  sample.  Then I count how many are GAUGE-INVARIANT (z-part in the cycle space of R -- the
  target's own theorem B-8, which I confirm).""")
print(f"  {'region':<28}{'n links':<9}{'all subalgebras':<18}{'G_2n':<8}"
      f"{'gauge-invariant':<18}{'G_(n+cyc)':<10}")
print("-" * 104)
for car, R in [(theta(8), [0]), (theta(10), [0, 1]), (fan(4), [1, 2]), (wheel(4), [0, 4, 1])]:
    n = len(R)
    subs = all_subspaces(2 * n)
    gi_vecs = gauge_invariant_mask(car, R)
    giset = set(gi_vecs)
    gi_subs = [s for s in subs if s <= giset]
    cyc = cyclomatic(car, R)
    print(f"  {car['name']+' R='+str(R):<28}{n:<9}{len(subs):<18}{GALOIS[2*n]:<8}"
          f"{len(gi_subs):<18}{GALOIS.get(n+cyc,'?'):<10}")
    assert len(subs) == GALOIS[2 * n], "enumeration incomplete"
    assert len(gi_subs) == GALOIS[n + cyc], "gauge-invariant count != G_(n+cyc)"
print("""
  ALL COUNTS MATCH THE GALOIS NUMBERS, so the enumeration is exhaustive.
  A SINGLE LINK carries exactly 5 Pauli subalgebras, of which exactly 2 are gauge-invariant:
  the unit algebra C.1 and alg{X_0}.  A PLAQUETTE on theta carries 67, of which 16 are
  gauge-invariant.  The target lane names 5 objects and, of those, 2 are gauge-invariant region
  algebras -- 2 of 16 on a plaquette, and on a single link its C2 and C3 are literally the same
  algebra, so 1 of 2.  THE LIST IS NOT A CLASSIFICATION; IT IS A SAMPLE.""")

# =====================================================================================
hr("PART 4  --  THE ENUMERATION USED AS A TEST, ON THE TARGET'S OWN CUTS")
print("""
  4a. theta_8, S = [0], magnetic GHZ (the g^2->0 ground state) -- the cut of b3 PART B and the
      state on which finding B-7 declares the verdict 'INVERTED'.  There are exactly TWO
      gauge-invariant algebras on a single link.  Both are evaluated.  This turns B-7's five-arm
      survey into an EXHAUSTION -- and it also shows the survey was 5 rows for 2 objects.""")
car = theta(8); L = 8
psi = sym_basis_state(car, 0)
E = pauli_table(psi, L)
S = [0]; ENVF = [[e] for e in range(1, 7)]
n = 1
subs = [s for s in all_subspaces(2 * n) if set(s) <= set(gauge_invariant_mask(car, S))]
print(f"  {'A_S generators':<26}{'H_A(S)':>9}   I(S:F) for |F|=1..6{'':>16}{'Rdelta':>8}")
print("-" * 104)
for s in subs:
    g = [vec_to_sp(v, S, n) for v in sorted(s) if v]
    HS = algebra_entropy(E, g)[0] if g else 0.0
    cur, sing = [], []
    for m in range(1, 7):
        F = sum(ENVF[:m], [])
        cur.append(mutual_information(E, g, gens_FULL(car, F))[0] if g else 0.0)
    for f in ENVF:
        sing.append(mutual_information(E, g, gens_FULL(car, f))[0] if g else 0.0)
    R = rdelta_count(sing, HS, DELTA)
    lab = str([sp_str(a, L) for a in g]) if g else "[] (unit algebra C.1)"
    print(f"  {lab:<26}{HS:9.5f}   {' '.join('%8.5f' % v for v in cur)}{R:8d}")
print("""      => EXHAUSTIVE: on a single-link system region there is no gauge-invariant algebra
      choice that could have produced a plateau, because the only non-trivial one is alg{X_0}
      and <X_0 (x) anything> = 0 on the magnetic GHZ.  B-7's gauge-invariant column is therefore
      a THEOREM, not a survey -- but it is also a theorem about the SYSTEM REGION, not about the
      criterion: it is B-8's own corollary (|S| >= girth) restated.""")

print("""
  4b. theta_10, S = the plaquette [0,1], Wilson-loop GHZ -- the cut of b3 PART C, where the target
      reports 'R_delta = 0 on a state that plainly has a record' (B-10) and proposes a POINTER
      SUBALGEBRA as a REPAIR OF THE CRITERION.  ALL 16 gauge-invariant algebras on that region are
      swept.  Fragments held fixed at C3_FULL plaquettes; delta = 0.1; only A_S moves.""")
car = theta(10); L = 10
a = sym_basis_state(car, 0)
b = sym_basis_state(car, sum(1 << i for i in range(1, L, 2)))
psiW = project_physical((a + b) / np.linalg.norm(a + b), car)
E = pauli_table(psiW, L, "direct")
S = [0, 1]; FR = [[2, 3], [4, 5], [6, 7], [8, 9]]
n = 2
gi = set(gauge_invariant_mask(car, S))
subs = [s for s in all_subspaces(2 * n) if set(s) <= gi]
print(f"  {'#':<4}{'A_S generators':<44}{'H_A(S)':>9}{'  I(S:F) 1..4 fragments':<38}{'Rdelta':>7}")
print("-" * 104)
verdicts = {}
for i, s in enumerate(subs):
    g = [vec_to_sp(v, S, n) for v in sorted(s) if v]
    HS = algebra_entropy(E, g)[0] if g else 0.0
    cur = [mutual_information(E, g, sum([gens_FULL(car, f) for f in FR[:m]], []))[0] if g else 0.0
           for m in range(1, 5)]
    sing = [mutual_information(E, g, gens_FULL(car, f))[0] if g else 0.0 for f in FR]
    R = rdelta_count(sing, HS, DELTA)
    lab = str([sp_str(x, L) for x in g]) if g else "[] (unit algebra)"
    print(f"  {i:<4}{lab:<44}{HS:9.5f}  {' '.join('%8.5f' % v for v in cur):<38}{R:>7}")
    verdicts[(round(HS, 6), tuple(round(v, 6) for v in cur), R)] = lab
print(f"""
      DISTINCT VERDICTS (H_A(S), curve, R_delta) among the 16: {len(verdicts)}.
      The target reports TWO of these rows (C2_ELEC and C3_FULL) plus its 'pointer subalgebra
      repair' alg{{W_01}} = ['+ZZIIIIIIII'], which is ROW-FOR-ROW ONE OF THE 16 GAUGE-INVARIANT
      REGION ALGEBRAS ENUMERATED HERE.  The 'declared pointer subalgebra' of finding B-10 is
      therefore NOT a second, independent convention alongside the boundary-algebra choice
      (next_step items (i) and (ii)): IT IS AN INSTANCE OF THE FIRST.  Fixing the boundary algebra
      fixes the pointer.  There are three conventions to fix, not four -- and the first of them
      ranges over 16 values on this region, not 3.""")
