#!/usr/bin/env python3
"""
L2 — THE STRUCTURAL LINK THE REGISTER ASSERTS, TESTED WHERE IT IS ACTUALLY TRUE.

REGISTER W-05 N1: "The identification is new; it INHERITS THE ENTROPY THEORY OF ALGEBRAIC
Z^d-ACTIONS WHOLESALE."   (REGISTER_V001.md, N1)

That sentence is too strong and this leg says exactly how much of it survives.

  Lind-Schmidt-Ward (Invent. Math. 101 (1990) 593-629) and Schmidt's book define the algebraic
  Z^d-action on R_d = Z[u_1^{+-1},...,u_d^{+-1}] — INTEGER Laurent polynomials.  There is no
  algebraic Z^d-action attached to a polynomial with irrational coefficients, so nothing is
  inherited on the general simplex.  What IS inherited, and only when pi is RATIONAL with
  common denominator D:  D*P has integer coefficients, and

        m(P) = m(D*P) - log D = h(alpha_{D*P}) - log D,

  an entropy MINUS A NORMALISATION.  This leg checks the sharper statement that goes with it:

  CLAIM L2.  Let pi be rational with common denominator D, let f = D*P in Z[u^{+-1},v^{+-1}],
  and let (u,v) = (w^a, w^b), w = e^{2 pi i/q}, have finite order q in T^2.  Write
  g(z) = f(z^a, z^b) mod (z^q - 1), an integer vector of length q, and C its circulant.  Then

        PROD_{k=1}^{q} |Z_k|  =  |det C| / D^q ,

  so D^q PROD_{k=1}^{q} |Z_k| IS A NON-NEGATIVE INTEGER; and by Lind-Schmidt-Verbitskiy
  Lemma 2.1 that integer is  P_Gamma(alpha_f) = |Fix_Gamma(alpha_f)/Fix^0_Gamma(alpha_f)|,
  the number of Gamma-periodic COMPONENTS of the algebraic Z^2-action defined by f, for
  Gamma the annihilator of the cyclic group generated by (u,v).

    LSV Lemma 2.1 (quoted): "P_Gamma(alpha) = PROD_{omega in Omega_Gamma \\ U(f)} |f(omega)|."

  So at every FINITE-ORDER connection the corpus's own |Omega_q| is a periodic-point count of
  an algebraic Z^2-action, exactly, and the integrality is a non-trivial check on the corpus's
  arithmetic that nothing in the corpus has ever run.

  det C is computed by the BAREISS fraction-free algorithm in Python integers: EXACT, no float.
"""
from fractions import Fraction as F
import math
import cmath

print("=" * 78)
print("L2 — FINITE-ORDER CONNECTIONS AS PERIODIC-POINT COUNTS.  EXACT INTEGER ARITHMETIC.")
print("=" * 78)


def bareiss_det(M):
    """Exact integer determinant, fraction-free Bareiss.  M is a list of lists of ints."""
    n = len(M)
    A = [row[:] for row in M]
    sign = 1
    prev = 1
    for k in range(n - 1):
        if A[k][k] == 0:
            piv = next((i for i in range(k + 1, n) if A[i][k] != 0), None)
            if piv is None:
                return 0
            A[k], A[piv] = A[piv], A[k]
            sign = -sign
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                A[i][j] = (A[i][j] * A[k][k] - A[i][k] * A[k][j]) // prev
            A[i][k] = 0
        prev = A[k][k]
    return sign * A[n - 1][n - 1]


def circulant_det(vec):
    q = len(vec)
    M = [[vec[(j - i) % q] for j in range(q)] for i in range(q)]
    return bareiss_det(M)


def leg(pi_frac, D, a, b, q, label):
    """pi_frac = (p00,p10,p01,p11) Fractions; f = D*P; (u,v) = (w^a, w^b), w = exp(2 pi i/q)."""
    coef = [int(D * x) for x in pi_frac]          # f coefficients for 1, u, v, uv
    exps = [0, a, b, (a + b)]                     # exponent of z for each monomial
    vec = [0] * q
    for c, e in zip(coef, exps):
        vec[e % q] += c
    dc = circulant_det(vec)                       # EXACT integer
    # float64 cross-check: the same product computed the corpus's own way
    prod = 1.0
    logs = 0.0
    for k in range(1, q + 1):
        u = cmath.exp(2j * math.pi * (a * k % q) / q)
        v = cmath.exp(2j * math.pi * (b * k % q) / q)
        Zk = complex(float(pi_frac[0]) + float(pi_frac[1]) * u
                     + float(pi_frac[2]) * v + float(pi_frac[3]) * u * v)
        prod *= abs(Zk)
    pred = abs(dc) / (D ** q)
    dev = abs(prod - pred)
    lam = (math.log(pred) / q) if pred > 0 else float("-inf")
    print("  %-34s q=%3d  |det C| = %-22d  pred %.12e" % (label, q, abs(dc), pred))
    print("  %-34s        float64 PROD|Z_k| = %.12e   |diff| = %.2e   lambda_q = %+.12f"
          % ("", prod, dev, lam))
    return abs(dc), dev


print("\nROW 1 IS S1's OWN PUBLISHED CONNECTION.  W_F = -1, W_C = -i, so u = conj(W_F) = -1,")
print("v = W_C = -i, and (u,v) = (w^2, w^3) with w = exp(2 pi i/4).  Order 4.\n")

pi = (F(0), F(3, 10), F(3, 10), F(2, 5))
D = 10
rows = [
    (2, 3, 4,   "S1 PUBLISHED (order 4)"),
    (1, 0, 4,   "order 4, v trivial"),
    (1, 1, 3,   "order 3 diagonal"),
    (1, 2, 5,   "order 5"),
    (1, 3, 7,   "order 7"),
    (2, 3, 12,  "order 12"),
    (5, 7, 24,  "order 24"),
    (7, 11, 40, "order 40"),
]
worst = 0.0
ints = []
for a, b, q, lab in rows:
    dc, dev = leg(pi, D, a, b, q, lab)
    ints.append(dc)
    worst = max(worst, dev)

print("\n  EVERY |det C| ABOVE IS A NON-NEGATIVE INTEGER BY CONSTRUCTION (Bareiss over Z).")
print("  Worst float64 deviation of PROD|Z_k| from |det C|/D^q over %d rows: %.2e" % (len(rows), worst))

print("""
--------------------------------------------------------------------------------
THE ONE ROW THAT MATTERS, SPELLED OUT.
""")
dc, _ = leg(pi, D, 2, 3, 4, "S1 PUBLISHED (order 4) [repeat]")
print("  |det C| = %d,  D^q = 10^4 = 10000,  so PROD_{k=1}^{4}|Z_k| = %d/10000 = %s" %
      (dc, dc, F(dc, 10 ** 4)))
print("  and lambda_4 = (1/4) log(%s) = %.15f" % (F(dc, 10 ** 4), math.log(dc / 1e4) / 4))
print("  R1_08(B) (sealed, LANE_W08_M1_IDENTIFICATION_REFUTE_1) computes the same product in")
print("  exact Gaussian rationals and gets 1/25, i.e. -(1/2) log 5 = %.15f." % (-0.5 * math.log(5)))
print("  1/25 = %s  ->  AGREE EXACTLY." % (F(dc, 10 ** 4) == F(1, 25)))
print("""
  SO: at S1's published connection the corpus's product is 400/10^4, and 400 is the number of
  Gamma-periodic components of the algebraic Z^2-action defined by f = 3u + 3v + 4uv, by
  LSV Lemma 2.1.  The register's N1 sentence is right in KIND on the rational locus and wrong
  in SCOPE: nothing is inherited when pi is irrational, and the constant -log D is not optional.

  AND THE CAVEAT THAT MATTERS MORE.  This link exists only at FINITE-ORDER connections, which
  are exactly the connections at which N1 IS FALSE (M1_08 T2(e): the order-4 value is
  -(1/2) log 5 = -0.804719 against m(P) = -0.767508).  The entropy theory of algebraic
  Z^d-actions attaches to the corpus's object precisely where the corpus's headline identity
  does not hold.  Where the identity holds — generic (u,v) — there is no finite subgroup, no
  periodic-point count, and no algebraic Z^2-action in play at all: only Weyl plus a
  Diophantine hypothesis.
""")
print("DONE L2")
