# LANE W-08 / M2 REFUTER 2 — leg B: WHAT IS THE ATTAINED/APPROACHED DISTINCTION ACTUALLY WORTH?
# The lane's headline: "the ATTAINED/APPROACHED distinction is worth 4.8% in lambda at |H|=4".
# 4.8% is the gap between ONE attained point (S1's) and ONE approached point (rank 2).  This leg
# computes the WHOLE attained spectrum and the WHOLE approached spectrum and asks whether the
# distinction partitions lambda at all.
# ISOLATION LEDGER (this leg): HELD - carrier K1, ready state RS-G (p11,p10,p01)=(0.4,0.3,0.3),
# the functional lambda = lim (1/N) log|Omega_N| evaluated as the exact H-average (no finite-K
# window, so no window artefact in the sense of COR-E).  MOVES - the connection only, over the
# COMPLETE set of finite orbit closures up to order NMAX, and over rank-1 closures by direction.
# Double precision for the sweep; every extreme re-evaluated at 40 dps in mpmath and printed.
import numpy as np, mpmath as mp
from math import gcd
mp.mp.dps = 40
W11,W10,W01 = 0.4,0.3,0.3
LAM_T2 = mp.mpf('-0.76750788035777587165')          # verified independently in leg A3
NMAX = 120

def lam_finite(a,b,n):
    """exact H-average of log|Z| over the cyclic orbit generated by (e^{2pi i a/n}, e^{2pi i b/n})"""
    s = mp.mpf(0)
    for k in range(1,n+1):
        z = (mp.mpf('0.4')*mp.expjpi(mp.mpf(2*((k*(a+b))%n))/n)
             + mp.mpf('0.3')*mp.expjpi(mp.mpf(2*((k*a)%n))/n)
             + mp.mpf('0.3')*mp.expjpi(mp.mpf(2*((k*b)%n))/n))
        s += mp.log(abs(z))
    return s/n

print("== B1  THE COMPLETE ATTAINED SPECTRUM (every finite orbit closure of order <= %d) ==" % NMAX)
print("   lambda_H = (1/|H|) SUM_{k<=|H|} log|Z_k|, computed on the orbit itself (exact average).")
print("   Generic (rank-2, approached) value for comparison: %s" % mp.nstr(LAM_T2,12))
best=[]; worst=[]; rows={}
tot=0; slower=0; over5=0
for n in range(2,NMAX+1):
    k = np.arange(1,n+1)
    ph = np.exp(2j*np.pi*np.outer(k,np.arange(n))/n)     # ph[k-1,r] = e^{2 pi i k r / n}
    A = np.arange(n)
    for a in range(n):
        ka = ph[:,a][:,None]
        kb = ph[:,A][:, :]                                # k x b
        kab = ph[:, (a+A)%n]
        Z = W11*kab + W10*ka + W01*kb
        lam = np.mean(np.log(np.abs(Z)),axis=0)           # per b
        for b in range(n):
            g = gcd(gcd(a,b),n); order = n//g
            if order != n:  continue                      # count each subgroup at its true order
            tot += 1
            v = lam[b]
            if v > float(LAM_T2): slower += 1
            if abs(v-float(LAM_T2))/abs(float(LAM_T2)) > 0.048: over5 += 1
            rows.setdefault(order,[]).append((v,a,b,n))
print(f"   points enumerated (pairs of roots of unity of exact order <= {NMAX}): {tot}")
allv = [r for lst in rows.values() for r in lst]
allv.sort()
print("   DEEPEST 6 (record decays FASTEST):")
for v,a,b,n in allv[:6]:
    e = lam_finite(a,b,n)
    print(f"      |H|={n:>4}  (a,b)=({a},{b})/{n}  lambda = {mp.nstr(e,12):>16}  "
          f"deviation vs generic {float((e-LAM_T2)/abs(LAM_T2))*100:+8.2f}%")
print("   SHALLOWEST 6 (record decays SLOWEST):")
for v,a,b,n in allv[-6:][::-1]:
    e = lam_finite(a,b,n)
    print(f"      |H|={n:>4}  (a,b)=({a},{b})/{n}  lambda = {mp.nstr(e,12):>16}  "
          f"deviation vs generic {float((e-LAM_T2)/abs(LAM_T2))*100:+8.2f}%")
print(f"   FRACTION OF ATTAINED POINTS WHOSE RECORD DECAYS **SLOWER** THAN GENERIC: "
      f"{slower}/{tot} = {slower/tot:.3f}")
print(f"   FRACTION DEVIATING BY MORE THAN THE HEADLINE'S 4.8%: {over5}/{tot} = {over5/tot:.3f}\n")

print("== B2  THE SMALL ORDERS, ONE ROW EACH — the lane's own leg D2 stopped short of these ==")
print(f"   {'|H|':>4} {'min lambda over H of this order':>32} {'dev':>9}   "
      f"{'max lambda over H of this order':>32} {'dev':>9}")
for m in [2,3,4,5,6,7,8,12,16,64,120]:
    if m not in rows: continue
    lst = sorted(rows[m])
    (v0,a0,b0,n0),(v1,a1,b1,n1) = lst[0], lst[-1]
    e0 = lam_finite(a0,b0,n0); e1 = lam_finite(a1,b1,n1)
    print(f"   {m:>4} {mp.nstr(e0,12):>32} {float((e0-LAM_T2)/abs(LAM_T2))*100:>+8.2f}%   "
          f"{mp.nstr(e1,12):>32} {float((e1-LAM_T2)/abs(LAM_T2))*100:>+8.2f}%")
print("   S1's published point for reference: (a,b)=(1,3)/4 in the lane's convention,")
print(f"      lambda = {mp.nstr(lam_finite(2,3,4),12)}  (the lane's -0.804718956217, |H|=4),")
print(f"      deviation {float((lam_finite(2,3,4)-LAM_T2)/abs(LAM_T2))*100:+.2f}%  <- THE HEADLINE'S 4.8%\n")

print("== B3  THE APPROACHED SPECTRUM: how far apart are two APPROACHED connections? ==")
print("   Rank-1 closures H = {(t^p, t^q)} (coprime p,q; realised by (x,y)=(e^{2pi i p theta},")
print("   e^{2pi i q theta}) with theta irrational -- sup|Z_k| = 1 APPROACHED, never attained,")
print("   and G != {1} so formation occurs).  lambda = m(0.4 z^{p+q} + 0.3 z^p + 0.3 z^q).")
def m_1var(exps, N=1<<20):
    t = 2*np.pi*np.arange(N)/N
    val = 0.4*np.exp(1j*exps[0]*t) + 0.3*np.exp(1j*exps[1]*t) + 0.3*np.exp(1j*exps[2]*t)
    return float(np.mean(np.log(np.abs(val))))
res=[]
for p in range(-8,9):
    for q in range(-8,9):
        if (p,q)==(0,0): continue
        if gcd(abs(p),abs(q))!=1: continue
        res.append((m_1var((p+q,p,q)),p,q))
res.sort()
print(f"   {'p':>3} {'q':>3} {'lambda (rank-1)':>18} {'deviation vs generic':>22}")
for v,p,q in res[:3]+res[-3:]:
    print(f"   {p:>3} {q:>3} {v:>18.9f} {(v-float(LAM_T2))/abs(float(LAM_T2))*100:>+21.2f}%")
lo,hi = res[0][0], res[-1][0]
print(f"   RANGE OVER APPROACHED, FORMING CONNECTIONS: [{lo:.6f}, {hi:.6f}]")
print(f"   = a spread of {abs(hi-lo)/abs(float(LAM_T2))*100:.1f}% of |lambda_generic|, against the")
print(f"     headline's 4.8% BETWEEN the attained and approached classes.")
print(f"   exact endpoints: xy=1 circle -> log(0.3) = {float(mp.log(mp.mpf('0.3'))):.9f};"
      f"  y=1 circle -> log(0.7) = {float(mp.log(mp.mpf('0.7'))):.9f}")
