"""W-56.  ROAD ITEM 25.  IS THE BOUNDARY DERIVED FROM THE ALGEBRA?

The tensor product is a postulate about COMPOSITE systems: it presupposes the parts. Used where
parts must be derived, it assumes the answer. The framework that does not presuppose parts is
algebraic -- a subsystem is a SUBALGEBRA, its environment the COMMUTANT, no factorisation anywhere.

NO PARTIAL TRACE IS TAKEN IN THIS LANE. Nothing here needs the Hilbert space to factorise.

THE QUESTION. For a set S of links, let A(S) be the algebra of operators supported on S. Its CENTER
Z(S) -- the elements commuting with all of A(S) -- is NOT a choice: it is determined by A(S) alone.

    IF THE CENTER IS GENERATED BY THE BOUNDARY OF S, THEN THE BOUNDARY IS DERIVED, NOT SUPPLIED,
    and Gap 2 was an artifact of insisting on tensor factors.

That is the Donnelly-Wall / Casini-Huerta-Rosabal structure, but here it is COMPUTED on this
program's own carrier rather than cited, and compared against the boundary this program has been
using all along.

FORCED-OR-NOT, FIRST. A center is nontrivial for trivial reasons if A(S) is abelian (then Z=A). So
report dim A(S) and whether A(S) is abelian BEFORE reading any center, and treat abelian cases
separately.
"""
import itertools, numpy as np

V2=[(i,j) for j in range(3) for i in range(3)]; vid={v:k for k,v in enumerate(V2)}
E=[]
for j in range(3):
    for i in range(2): E.append((vid[(i,j)],vid[(i+1,j)]))
for j in range(2):
    for i in range(3): E.append((vid[(i,j)],vid[(i,j+1)]))
L=len(E)
hid=lambda i,j:j*2+i; vx=lambda i,j:6+j*3+i
PLQ=[[(hid(i,j),+1),(vx(i+1,j),+1),(hid(i,j+1),-1),(vx(i,j),-1)] for j in range(2) for i in range(2)]
st=[s for s in itertools.product(range(2),repeat=L)
    if all((sum(s[k] for k,(a,b) in enumerate(E) if a==v)
           -sum(s[k] for k,(a,b) in enumerate(E) if b==v))%2==0 for v in range(9))]
idx={s:i for i,s in enumerate(st)}; D=len(st)
def Zop(links): return np.diag([(-1.0)**(sum(s[k] for k in links)%2) for s in st]).astype(complex)
def Move(mv):
    M=np.zeros((D,D),complex)
    for j,s in enumerate(st):
        t=list(s)
        for k,sg in mv: t[k]=(t[k]+sg)%2
        t=tuple(t)
        if t in idx: M[idx[t],j]=1.0
    return M
PSUP=[set(k for k,_ in p) for p in PLQ]
print(f"W-56  physical dim {D}, links {L}, plaquettes {len(PLQ)}.  NO PARTIAL TRACE IS TAKEN.")

def vec(M): return M.reshape(-1)
def span_basis(mats,tol=1e-9):
    if not mats: return []
    A=np.array([vec(m) for m in mats])
    U,sv,Vh=np.linalg.svd(A,full_matrices=False)
    r=int((sv>tol*max(1.0,sv[0])).sum())
    return [Vh[i].reshape(D,D) for i in range(r)]
def close_algebra(gens,tol=1e-9,maxit=12):
    """closure of the *-algebra generated by gens (with identity), as a linear basis"""
    B=span_basis([np.eye(D,dtype=complex)]+list(gens)+[g.conj().T for g in gens],tol)
    for _ in range(maxit):
        prods=[a@b for a in B for b in B]
        NB=span_basis(B+prods,tol)
        if len(NB)==len(B): return NB
        B=NB
    return B
def center(B,tol=1e-8):
    """elements of span(B) commuting with all of B -- solved as a linear system, no factorisation"""
    n=len(B)
    rows=[]
    for g in B:
        M=np.zeros((D*D,n),complex)
        for k,b in enumerate(B): M[:,k]=vec(g@b-b@g)
        rows.append(M)
    A=np.vstack(rows)
    U,sv,Vh=np.linalg.svd(A)
    ns=[Vh[i].conj() for i in range(len(Vh)) if (i>=len(sv) or sv[i]<tol*max(1.0,sv[0]))]
    return [sum(c[k]*B[k] for k in range(n)) for c in ns]

def region_algebra(S):
    gens=[Zop([k]) for k in S]
    for p,sup in enumerate(PSUP):
        if sup <= set(S): gens.append(Move(PLQ[p]))
    return close_algebra(gens)

def boundary_of(S):
    """links of S lying on exactly one plaquette that is inside S, i.e. the topological boundary"""
    inside=[p for p,sup in enumerate(PSUP) if sup<=set(S)]
    c={}
    for p in inside:
        for lk in PSUP[p]: c[lk]=c.get(lk,0)+1
    return set(lk for lk,v in c.items() if v%2)

def describe(name,S):
    B=region_algebra(S)
    ab = max(np.linalg.norm(a@b-b@a) for a in B for b in B) < 1e-8
    Zc=center(B)
    bd=boundary_of(S)
    Wb=Move([(k,1) for k in sorted(bd)]) if bd else None
    inZ = None
    if Wb is not None and Zc:
        Zb=span_basis(Zc)
        c=np.array([np.vdot(vec(z),vec(Wb)) for z in Zb])
        proj=sum(c[i]*vec(Zb[i]) for i in range(len(Zb)))
        resid=np.linalg.norm(vec(Wb)-proj)/np.linalg.norm(vec(Wb))
        inZ=resid
    print(f"  {name:>26s} |S|={len(S):2d}  dim A={len(B):3d}  abelian={str(ab):5s}  "
          f"dim Z={len(Zc):3d}  boundary links={sorted(bd)}"
          + (f"  ||W_bdy - proj_Z|| = {inZ:.2e}" if inZ is not None else "  (no interior plaquette)"))
    return len(B),ab,len(Zc),inZ

print()
print("  FORCED-OR-NOT: an abelian A(S) has Z=A trivially. Reported before any center is read.")
print()
CENTER=vid[(1,1)]; CUT=[k for k,(a,b) in enumerate(E) if a==CENTER or b==CENTER]
PERIM=[k for k in range(L) if k not in CUT]
cases=[("one plaquette p0", sorted(PSUP[0])),
       ("two plaquettes p0,p1", sorted(PSUP[0]|PSUP[1])),
       ("two diagonal p0,p3", sorted(PSUP[0]|PSUP[3])),
       ("all four (whole patch)", list(range(L))),
       ("the CUT only", CUT),
       ("the PERIMETER only", PERIM)]
for nm,S in cases: describe(nm,S)
