"""W-56b.  IS THE BOUNDARY DERIVED FROM THE ALGEBRA?  (exact, over GF(2))

NO PARTIAL TRACE IS TAKEN ANYWHERE IN THIS LANE. Nothing here needs the Hilbert space to factorise.
That is the point: the tensor product presupposes the parts, so it is not used.

The physical space of the 3x3 patch is 2^4 (cycle rank 4) and every operator in play is a Pauli
string on those 4 effective qubits, so the whole question is exact F_2 linear algebra rather than
numerics.

  a plaquette shift W_p  ->  X on effective qubit p                     (X-vector e_p)
  an electric Z on link L ->  product of Z_i over the cycles containing L (Z-vector: which plaquette
                              boundaries contain L -- i.e. the incidence column of L)

For a link set S, A(S) is generated by { Z_L : L in S } and { W_p : plaquette p entirely inside S }.
Its span V lives in F_2^8. The CENTER is V intersect V^perp under the symplectic form
        <(a,b),(a',b')> = a.b' + a'.b
and it is DETERMINED BY A(S) -- it is not a choice. The question is what it turns out to be.

FORCED-OR-NOT: if A(S) is abelian then V is symplectically self-orthogonal and Z = A trivially.
Reported for every region before any center is interpreted.
"""
import itertools, numpy as np

V2=[(i,j) for j in range(3) for i in range(3)]; vid={v:k for k,v in enumerate(V2)}
E=[]
for j in range(3):
    for i in range(2): E.append((vid[(i,j)],vid[(i+1,j)]))
for j in range(2):
    for i in range(3): E.append((vid[(i,j)],vid[(i,j+1)]))
L=len(E)
hid=lambda i,j:j*2+i; vx=lambda i,j:6+j*3+i
PSUP=[set([hid(i,j),vx(i+1,j),hid(i,j+1),vx(i,j)]) for j in range(2) for i in range(2)]
m=len(PSUP)
CENTREV=vid[(1,1)]; CUT=[k for k,(a,b) in enumerate(E) if a==CENTREV or b==CENTREV]
PERIM=[k for k in range(L) if k not in CUT]

def zvec(lk):  return tuple(1 if lk in PSUP[p] else 0 for p in range(m))   # incidence column
def xvec(p):   return tuple(1 if q==p else 0 for q in range(m))
def pack(a,b): return tuple(a)+tuple(b)
def sympl(u,v):
    a,b=u[:m],u[m:]; c,d=v[:m],v[m:]
    return (sum(x*y for x,y in zip(a,d))+sum(x*y for x,y in zip(c,b)))%2
def span(vs):
    basis=[]
    for v in vs:
        cur=list(v)
        for b in basis:
            piv=next((i for i,x in enumerate(b) if x),None)
            if piv is not None and cur[piv]: cur=[(x+y)%2 for x,y in zip(cur,b)]
        if any(cur): basis.append(cur)
    return basis
def elements(basis):
    out=[]
    for coef in itertools.product([0,1],repeat=len(basis)):
        v=[0]*(2*m)
        for c,b in zip(coef,basis):
            if c: v=[(x+y)%2 for x,y in zip(v,b)]
        out.append(tuple(v))
    return out

def analyse(name,S):
    gens=[pack([0]*m,zvec(lk)) for lk in S]
    inside=[p for p in range(m) if PSUP[p]<=set(S)]
    gens+= [pack(xvec(p),[0]*m) for p in inside]
    B=span(gens); V=elements(B)
    abelian=all(sympl(u,v)==0 for u in V for v in V)
    Zc=[v for v in V if all(sympl(v,u)==0 for u in V)]
    # the boundary of S: links on an ODD number of the plaquettes inside S
    cnt={}
    for p in inside:
        for lk in PSUP[p]: cnt[lk]=cnt.get(lk,0)+1
    bd=sorted(lk for lk,v in cnt.items() if v%2)
    # candidate centre elements this program has used: the MAGNETIC loop of the region,
    # and the ELECTRIC flux on its boundary
    magn=pack([1 if p in inside else 0 for p in range(m)],[0]*m)
    elec=[0]*m
    for lk in bd: elec=[(x+y)%2 for x,y in zip(elec,zvec(lk))]
    elecv=pack([0]*m,elec)
    print(f"  {name:>24s} |S|={len(S):2d} in={len(inside)}  dimA={len(B)}  abelian={str(abelian):5s} "
          f" dimZ={int(np.log2(len(Zc))) if Zc else 0}  bd={bd}")
    print(f"  {'':>24s}    magnetic loop of region in centre? {magn in Zc}"
          f"    electric flux on boundary in centre? {elecv in Zc}")
    return len(B),abelian,len(Zc),(magn in Zc),(elecv in Zc)

print("W-56b  CENTRES OF REGION SUBALGEBRAS -- exact over GF(2), no partial trace, no factorisation.")
print(f"  physical dim 2^{m}; operators are Pauli strings on {m} effective qubits\n")
for nm,S in [("one plaquette p0",sorted(PSUP[0])),
             ("two adjacent p0,p1",sorted(PSUP[0]|PSUP[1])),
             ("two diagonal p0,p3",sorted(PSUP[0]|PSUP[3])),
             ("three p0,p1,p2",sorted(PSUP[0]|PSUP[1]|PSUP[2])),
             ("all four (whole patch)",list(range(L))),
             ("the CUT only",CUT),
             ("the PERIMETER only",PERIM)]:
    analyse(nm,S)
print()
print("  READING: the centre is computed from A(S) alone. If it contains the region's own boundary")
print("  operator, that boundary is DERIVED by the algebra rather than supplied by the modeller.")

print()
print("="*78)
print("  WHAT THE CENTRES ACTUALLY ARE (reported, not guessed)")
print("  notation: X_p = plaquette shift on p ; Z_p = the dual electric charge of cycle p")
def name_elt(v):
    a,b=v[:m],v[m:]
    xs="".join(f"X{p}" for p in range(m) if a[p])
    zs="".join(f"Z{p}" for p in range(m) if b[p])
    return (xs+zs) if (xs or zs) else "1"
def centre_of(S):
    gens=[pack([0]*m,zvec(lk)) for lk in S]
    inside=[p for p in range(m) if PSUP[p]<=set(S)]
    gens+=[pack(xvec(p),[0]*m) for p in inside]
    B=span(gens); V=elements(B)
    Zc=[v for v in V if all(sympl(v,u)==0 for u in V)]
    return inside,B,Zc
for nm,S in [("one plaquette p0",sorted(PSUP[0])),
             ("two adjacent p0,p1",sorted(PSUP[0]|PSUP[1])),
             ("two diagonal p0,p3",sorted(PSUP[0]|PSUP[3])),
             ("three p0,p1,p2",sorted(PSUP[0]|PSUP[1]|PSUP[2])),
             ("all four (whole patch)",list(range(L)))]:
    inside,B,Zc=centre_of(S)
    gen=[z for z in span([list(z) for z in Zc]) ]
    print(f"\n  {nm}   inside plaquettes {inside}")
    print(f"    centre generators: {[name_elt(tuple(g)) for g in gen] or ['1 only']}")
    print(f"    |centre| = {len(Zc)}   dim A(S) = {len(B)}")
print()
print("  THE PATTERN TO READ: for each region, is the centre generated by operators supported on")
print("  the region's COMPLEMENT (the outside), on its BOUNDARY, or on neither?")
for nm,S in [("one plaquette p0",sorted(PSUP[0])),
             ("two adjacent p0,p1",sorted(PSUP[0]|PSUP[1])),
             ("three p0,p1,p2",sorted(PSUP[0]|PSUP[1]|PSUP[2]))]:
    inside,B,Zc=centre_of(S)
    outside=[p for p in range(m) if p not in inside]
    gen=span([list(z) for z in Zc])
    onlyout=all(all(g[p]==0 and g[m+p]==0 for p in inside) for g in gen) if gen else True
    print(f"    {nm:>22s}: centre lives only on the OUTSIDE cycles {outside}?  {onlyout}")
