# LANE W-08 / M2 leg F — THE FLOOR LAW, ITS OPERATIVE VARIABLE, AND A CORRECTION TO W-07.
# F1  F(K) ~ K^{-2/d_eff}: fitted, not eyeballed.
# F2  N(eps) ~ K eps^{d_eff/2}: fitted.  Same exponent, same cause.
# F3  the competitor ruled out: Diophantine QUALITY moves the constant, d_eff moves the exponent.
# F4  THE CORRECTION: W-07's row labelled "GENERIC (badly approximable)" is not generic.
import numpy as np, pickle, mpmath as mp
mp.mp.dps=40
# SEED DEFECT, RECORDED NOT SILENTLY FIXED: the first run of this script used a hard-coded
# pair (0.63696..., 0.26979...) labelled D_RAND1 that is NOT the seeded stream leg B used.
# Any rank-2 irrational pair supports the same conclusion, but the LABEL was wrong and the
# number was unreproducible from the published seed -- the exact defect this program treats
# as absent data.  The pairs are now drawn from the master seed here exactly as in leg B.
RNG_ = __import__('numpy').random.default_rng(20260816)
RND_ = [(RNG_.random(), RNG_.random()) for _ in range(3)]

res={(rt,cn.strip()):d for (rt,cn),d in pickle.load(open("m2_b_sweep.pkl","rb")).items()}
KS=[10**3,10**4,10**5,10**6,10**7]; EPS=[10.0**-e for e in range(1,15)]

# re-measure F(K) at the checkpoints (the pickle stored only the final min)
def floors(al,be,W):
    w11,w10,w01=W; out=[]; run=np.inf
    lo=0
    for K in KS:
        k=np.arange(lo+1,K+1,dtype=np.float64)
        u=(k*al)%1.0; v=(k*be)%1.0
        du=u-np.round(u); dv=v-np.round(v); duv=u+v; duv-=np.round(duv)
        S=np.minimum(4*(w11*w10*np.sin(np.pi*dv)**2+w11*w01*np.sin(np.pi*du)**2
                        +w10*w01*np.sin(np.pi*duv)**2),1.0)
        g=S/(1.0+np.sqrt(np.maximum(0.0,1.0-S)))
        run=min(run,float(g.min())); out.append(run); lo=K
    return out
phi=(1+5**0.5)/2; t7=2*np.cos(2*np.pi/7)
CONN=[("B_S3RES  f=2.0,c=11/10",1/np.pi,11/(20*np.pi),1),
      ("E_W07GEN 2pi.phi,2pi.phi^2",np.mod(phi,1),np.mod(phi**2,1),1),
      ("C_BADAPP cubic pair",np.mod(t7,1),np.mod(t7**2,1),2),
      ("D_RAND1",RND_[0][0],RND_[0][1],2),
      ("D_RAND2",RND_[1][0],RND_[1][1],2),
      ("D_RAND3",RND_[2][0],RND_[2][1],2)]

print("== F1  THE FLOOR LAW.  F(K) = min_{k<=K}(1-|Z_k|).  Fitted exponent, both ready states. ==")
print("   d_eff = dim of the closed subgroup generated by the character RATIOS that carry weight.")
print("   RS-G (all three weights live): d_eff = dim H.   RS-P (p10 = 0, K1's PUBLISHED state):")
print("   only chi_0/chi_C = conj(W_F) survives, so d_eff = 1 FOR EVERY CONNECTION.")
print(f"   {'connection':<28} {'ready':<6} {'d_eff':>5} " + "".join(f"{f'F(1e{e})':>13}" for e in range(3,8))
      + f" {'fitted exponent':>16} {'theory -2/d_eff':>16}")
for lab,al,be,dim in CONN:
    for rt,W,deff in [("RS-G",(0.4,0.3,0.3),dim),("RS-P",(0.5,0.0,0.5),1)]:
        f=floors(al,be,W)
        sl=np.polyfit(np.log10(KS),np.log10(f),1)[0]
        print(f"   {lab:<28} {rt:<6} {deff:>5} " + "".join(f"{x:>13.3e}" for x in f)
              + f" {sl:>16.3f} {-2.0/deff:>16.1f}")
print("   -> exponent -1 when d_eff = 2, exponent -2 when d_eff = 1.  Dirichlet's box principle in")
print("      d dimensions gives min_{k<=K} max_j ||k gamma_j|| ~ K^{-1/d}, and 1-|Z| is QUADRATIC in")
print("      those residues (leg A3), so F(K) ~ K^{-2/d}.  Nothing else is needed to predict it.\n")

print("== F2  THE DISTRIBUTION, WHICH IS THE SAME FACT.  N(eps) = #{k<=1e7 : 1-|Z_k| < eps}. ==")
print(f"   {'ready':<6} {'connection':<9} {'d_eff':>5} " + "".join(f"{f'{e:.0e}':>9}" for e in EPS[:8])
      + f" {'fitted d log N/d log eps':>25} {'theory d_eff/2':>15}")
for (rt,cn),d in sorted(res.items()):
    c=np.array(d["counts"],dtype=float)
    deff = d['dim'] if rt=="RS-G" else min(1,d['dim'])
    if deff==0:
        print(f"   {rt:<6} {cn:<9} {deff:>5} " + "".join(f"{int(x):>9d}" for x in c[:8])
              + f" {'N(eps) is CONSTANT = K/|H|':>25} {'(atom at 0)':>15}"); continue
    m=(c[2:9]>20)
    sl=np.polyfit(np.log10(np.array(EPS[2:9])[m]),np.log10(c[2:9][m]),1)[0] if m.sum()>2 else np.nan
    print(f"   {rt:<6} {cn:<9} {deff:>5} " + "".join(f"{int(x):>9d}" for x in c[:8])
          + f" {sl:>25.3f} {deff/2:>15.2f}")
print("   -> N(eps) ~ K eps for d_eff = 2 and ~ K sqrt(eps) for d_eff = 1; for d_eff = 0 the")
print("      distribution has an ATOM of mass 1/|H| at exactly zero and N(eps) does not move.")
print("      THE ATOM IS THE WHOLE OF 'ATTAINED'.  Everything else about the floor is continuous.\n")

print("== F3  THE COMPETITOR RULED OUT: Diophantine quality sets the CONSTANT, d_eff the EXPONENT ==")
print("   Same d_eff = 2, same ready state RS-G, only the arithmetic quality of the pair moves:")
print(f"   {'pair':<34} {'F(1e6)':>13} {'F(1e7)':>13} {'ratio':>9}  {'comment':<38}")
qual=[("cubic field (badly approximable)",np.mod(t7,1),np.mod(t7**2,1),"exponent -1, constant O(1)"),
      ("uniform random, stream 1",RND_[0][0],RND_[0][1],"exponent -1, constant O(1)"),
      ("uniform random, stream 2",RND_[1][0],RND_[1][1],"exponent -1, constant O(1)"),
      ("VERY well approximable, Q=2999999",1234567/2999999,765431/2999999,"EXPONENT BROKEN downward")]
for lab,al,be,cm in qual:
    f=floors(al,be,(0.4,0.3,0.3))
    r = (f"{f[3]/f[4]:>9.1f}" if f[4]>0 else f"{'inf':>9}")
    print(f"   {lab:<34} {f[3]:>13.3e} {f[4]:>13.3e} {r}  {cm:<38}")
print("   (the VWA row reads F(1e7) = 0 EXACTLY here: at k = 2999999 the DOUBLE value of alpha")
print("    rounds k*alpha to an integer.  That is a precision artefact of this table, not the")
print("    object — leg B carries the same pair at 60 digits and gets 3.609e-23.  Recorded.)")
print("   (the VWA row's true floor at K=1e7 is 3.61e-23, from leg B where the pair is carried at")
print("    60 digits; the double-precision alpha above cannot even represent it — recorded as a")
print("    precision caveat, not smoothed over.)")
print("   -> badly-approximable and random agree to a factor of ~3.  A very-well-approximable pair")
print("      drives the floor 15 orders deeper AND CHANGES NOTHING ABOUT THE SUM (leg B: SUM/K =")
print("      0.469215 against the generic 0.469189).  Floor depth and durability are DECOUPLED.\n")

print("== F4  CORRECTION TO W-07 (this lane's own predecessor, same model lineage) ==")
print("""   W-07's leg D table has a row labelled  "GENERIC (badly approximable)"  with
   aF = 2*pi*phi, aC = 2*pi*phi^2, and the register's W-07 row builds on its figure:
     "Generically |Z_k| still returns to within 1.4e-12 of complete indistinguishability by
      k = 10^6, which may erase a record as thoroughly as exact recurrence."
   THAT CONNECTION IS NOT GENERIC.  phi^2 - phi = 1 exactly, so aC - aF = 2*pi exactly, so""")
print(f"     W_C = exp(i*2*pi*phi^2) = exp(i*2*pi*phi) = W_F   -- checked: |W_C - W_F| = "
      f"{float(abs(mp.expj(2*mp.pi*((1+mp.sqrt(5))/2)**2)-mp.expj(2*mp.pi*(1+mp.sqrt(5))/2))):.3e}")
print("""   and therefore chi_0 = conj(W_F) W_C = 1 IDENTICALLY: the root vertex's character is trivial
   for every k.  H is the anti-diagonal CIRCLE, dim H = 1, not T^2.  The pair (phi, phi^2) is
   badly approximable ONE NUMBER AT A TIME and rationally DEPENDENT as a pair, which is the only
   property that matters here.""")
print("   REPRODUCTION FIRST, so this is not a different calculation:")
for rt,W,tag in [("RS-P",(0.5,0.0,0.5),"W-07 leg D table 1 (published ready state)"),
                 ("RS-G",(0.4,0.3,0.3),"W-07 leg D table 2 (generic ready state)")]:
    w11,w10,w01=W
    for lab,al,be in [("W07 'GENERIC' = 2pi.phi, 2pi.phi^2",np.mod(phi,1),np.mod(phi**2,1)),
                      ("S3/S4 headline f=2.0,c=1.1",1/np.pi,11/(20*np.pi)),
                      ("S1 published f=pi,c=3pi/2",0.5,0.75)]:
        k=np.arange(1,10**6+1,dtype=np.float64)
        u=(k*al)%1.0; v=(k*be)%1.0
        du=u-np.round(u); dv=v-np.round(v); duv=u+v; duv-=np.round(duv)
        S=np.minimum(4*(w11*w10*np.sin(np.pi*dv)**2+w11*w01*np.sin(np.pi*du)**2
                        +w10*w01*np.sin(np.pi*duv)**2),1.0)
        g=S/(1.0+np.sqrt(np.maximum(0.0,1.0-S)))
        print(f"      {tag[:34]:<34} {lab:<34} max|Z_k| = {1-g.min():.15f}")
    break
w11,w10,w01=(0.4,0.3,0.3)
for lab,al,be in [("W07 'GENERIC' 2pi.phi,2pi.phi^2 (dim H=1)",np.mod(phi,1),np.mod(phi**2,1)),
                  ("S3/S4 headline f=2.0,c=1.1      (dim H=1)",1/np.pi,11/(20*np.pi)),
                  ("A GENUINELY GENERIC PAIR        (dim H=2)",RND_[0][0],RND_[0][1]),
                  ("cubic badly-approximable pair   (dim H=2)",np.mod(t7,1),np.mod(t7**2,1))]:
    k=np.arange(1,10**6+1,dtype=np.float64)
    u=(k*al)%1.0; v=(k*be)%1.0
    du=u-np.round(u); dv=v-np.round(v); duv=u+v; duv-=np.round(duv)
    S=np.minimum(4*(w11*w10*np.sin(np.pi*dv)**2+w11*w01*np.sin(np.pi*du)**2
                    +w10*w01*np.sin(np.pi*duv)**2),1.0)
    g=S/(1.0+np.sqrt(np.maximum(0.0,1.0-S)))
    print(f"      RS-G, K=1e6:  {lab:<42} max|Z_k| = {1-g.min():.15f}   1-max = {g.min():.3e}")
print("""   THE CORRECTION.  The deepest generic near-return by k = 1e6 is 1.3e-6, not 1.4e-12: the
   register's figure is SIX ORDERS OF MAGNITUDE too deep because it was measured on a rank-1
   connection (and, in table 1, also on the p10 = 0 ready state, which forces d_eff = 1 by
   itself).  W-07's own ruling is UNAFFECTED -- ord(rho) = 4 versus infinite is exactly right and
   is reproduced here -- but the sentence in "WHAT THIS DOES NOT ESTABLISH" that leans on 1.4e-12
   is not supported, and it leans the wrong way: generic near-returns are far SHALLOWER than the
   register believes, which strengthens rather than weakens the durability side.""")
